"use client";

import { useEffect, useRef, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { useRouter } from "@/i18n/navigation";
import Image from "next/image";
import { Check, CreditCard, Globe2, Loader2, LockKeyhole, PackageCheck, ShieldCheck } from "lucide-react";
import { Container } from "@/components/ui/container";
import { Button } from "@/components/ui/button";
import { useCart } from "@/lib/cart-context";
import { formatPrice } from "@/lib/utils";
import { pickLocalized } from "@/lib/i18n-content";

const pick=(locale:string,fa:string,en:string,tr:string,ar:string)=>locale==="fa"?fa:locale==="tr"?tr:locale==="ar"?ar:en;
const createRequestToken=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;

export default function CheckoutPage(){
 const t=useTranslations("checkout"); const cartT=useTranslations("cart"); const c=useTranslations("common"); const locale=useLocale(); const router=useRouter(); const {lines,subtotal,hydrated}=useCart();
 const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null); const requestTokenRef=useRef<string>("");
 const labels={
  province:pick(locale,"استان","Province / Region","İl / Bölge","المحافظة / المنطقة"),country:pick(locale,"کشور","Country","Ülke","الدولة"),summary:pick(locale,"خلاصه سفارش","Order summary","Sipariş özeti","ملخص الطلب"),payment:pick(locale,"روش پرداخت","Payment method","Ödeme yöntemi","طريقة الدفع"),gateway:pick(locale,"پرداخت اینترنتی","Online payment","Online ödeme","الدفع عبر الإنترنت"),gatewaySub:pick(locale,"پس از ثبت سفارش به درگاه پرداخت منتقل می‌شوید.","You will be redirected to the payment gateway after the order is created.","Sipariş oluşturulduktan sonra ödeme ağ geçidine yönlendirileceksiniz.","سيتم تحويلك إلى بوابة الدفع بعد إنشاء الطلب."),verified:pick(locale,"موجودی، تعداد و مبلغ سفارش پیش از ایجاد پرداخت در سرور دوباره بررسی می‌شود.","Stock, quantities and the order total are revalidated on the server before payment is created.","Stok, adet ve sipariş toplamı ödeme oluşturulmadan önce sunucuda yeniden doğrulanır.","تتم إعادة التحقق من المخزون والكميات وإجمالي الطلب على الخادم قبل إنشاء الدفع."),items:pick(locale,"کالا","items","ürün","عنصر"),serverTotal:pick(locale,"مبلغ نهایی پس از بررسی سفارش در سرور تعیین می‌شود.","The final payable amount is determined after server-side order validation.","Nihai ödeme tutarı sunucu tarafındaki sipariş doğrulamasından sonra belirlenir.","يتم تحديد المبلغ النهائي بعد التحقق من الطلب على الخادم."),cartStep:pick(locale,"سبد خرید","Cart","Sepet","السلة"),deliveryStep:pick(locale,"اطلاعات ارسال","Delivery details","Teslimat bilgileri","معلومات الشحن"),paymentStep:pick(locale,"پرداخت","Payment","Ödeme","الدفع"),genericError:pick(locale,"ثبت سفارش انجام نشد. لطفاً دوباره تلاش کنید.","Checkout failed. Please try again.","Sipariş tamamlanamadı. Lütfen tekrar deneyin.","تعذر إكمال الطلب. يرجى المحاولة مرة أخرى.")
 };
 async function handleSubmit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault(); if(submitting)return; setError(null); setSubmitting(true); const form=new FormData(event.currentTarget);
  if(!requestTokenRef.current)requestTokenRef.current=createRequestToken();
  try{
   const response=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({locale,requestToken:requestTokenRef.current,customerName:form.get("customerName"),phone:form.get("phone"),email:form.get("email")||undefined,address:form.get("address"),province:form.get("province")||undefined,city:form.get("city"),country:form.get("country")||undefined,postalCode:form.get("postalCode")||undefined,notes:form.get("notes")||undefined,lines:lines.map(line=>({type:line.type,id:line.id,quantity:line.quantity,preferredDate:line.preferredDate}))})});
   const data:unknown=await response.json().catch(()=>null); const redirectUrl=data&&typeof data==="object"&&"redirectUrl" in data?(data as {redirectUrl?:unknown}).redirectUrl:null;
   if(!response.ok||typeof redirectUrl!=="string"||!redirectUrl){throw new Error("checkout_failed");}
   window.location.assign(redirectUrl);
  }catch{setError(labels.genericError);setSubmitting(false);}
 }
 useEffect(()=>{if(hydrated&&lines.length===0)router.replace("/cart")},[hydrated,lines.length,router]);
 if(!hydrated||lines.length===0)return null;
 return <main className="flex-1 bg-[#f4f7fb] py-6 sm:py-10"><Container className="max-w-[1440px]">
  <section className="mb-8 hidden sm:block" aria-label={pick(locale,"مراحل ثبت سفارش","Checkout steps","Sipariş adımları","خطوات إتمام الطلب")}><div className="relative grid grid-cols-3 items-start"><div aria-hidden="true" className="absolute left-[16.5%] right-[16.5%] top-5 h-0.5 bg-[#001736]"/>{[[Check,labels.cartStep],[Check,labels.deliveryStep],[CreditCard,labels.paymentStep]].map(([IconValue,label],index)=>{const Icon=IconValue as typeof Check;return <div key={String(label)} className="relative z-10 flex flex-col items-center text-center"><span className={`flex h-10 w-10 items-center justify-center rounded-full border-2 ${index<2?"border-[#001736] bg-[#001736] text-white":"border-[#001736] bg-[#eef3f9] text-[#001736]"}`}><Icon aria-hidden="true" className="h-5 w-5"/></span><span className="mt-2 text-xs font-black text-[#001736]">{String(label)}</span></div>})}</div></section>
  <form onSubmit={handleSubmit} className="grid gap-7 lg:grid-cols-[360px_minmax(0,1fr)] lg:items-start xl:grid-cols-[390px_minmax(0,1fr)]">
   <aside className="order-2 lg:order-1 lg:sticky lg:top-28"><div className="rounded-3xl border border-[#dfe4ea] bg-white p-6 shadow-[0_18px_50px_rgba(0,23,54,.055)]"><div className="flex items-center justify-between gap-3 border-b border-[#e0e3e6] pb-5"><h2 className="text-lg font-black text-[#001736]">{labels.summary}</h2><span className="rounded-lg bg-[#eef1f4] px-3 py-1.5 text-xs font-bold text-[#43474f]">{new Intl.NumberFormat(locale).format(lines.reduce((sum,line)=>sum+line.quantity,0))} {labels.items}</span></div><ul className="mt-5 space-y-4">{lines.map(line=>{const name=pickLocalized(locale,{fa:line.nameFa,tr:line.nameTr,en:line.nameEn,ar:line.nameAr});return <li key={line.key} className="flex gap-3 rounded-2xl border border-[#e0e3e6] p-3"><div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-xl bg-[#edf1f5]">{line.image?<Image src={line.image} alt={name} fill className="object-contain p-1.5" sizes="64px"/>:null}</div><div className="min-w-0 flex-1"><p className="line-clamp-2 text-xs font-bold leading-5 text-[#001736]">{name}</p><div className="mt-2 flex justify-between gap-2 text-xs"><span className="text-[#747780]">× {new Intl.NumberFormat(locale).format(line.quantity)}</span><strong className="tabular-nums text-[#ba0036]">{formatPrice(line.price*line.quantity,locale)} {c("currency")}</strong></div></div></li>})}</ul><dl className="mt-6 border-t border-[#e0e3e6] pt-5 text-sm"><div className="flex justify-between gap-3"><dt className="text-[#43474f]">{cartT("subtotal")}</dt><dd className="font-bold tabular-nums text-[#001736]">{formatPrice(subtotal,locale)} {c("currency")}</dd></div></dl><p className="mt-4 rounded-xl bg-[#f4f7fb] p-3 text-[11px] leading-5 text-[#747780]">{labels.serverTotal}</p><Button type="submit" disabled={submitting} aria-disabled={submitting} className="mt-5 min-h-14 w-full justify-center rounded-xl bg-[#ba0036] font-black text-white shadow-[0_12px_28px_rgba(186,0,54,.18)] hover:bg-[#e80346]">{submitting?<Loader2 aria-hidden="true" className="h-4 w-4 animate-spin"/>:<LockKeyhole aria-hidden="true" className="h-4 w-4"/>}{t("submit")}</Button></div></aside>
   <div className="order-1 space-y-5 lg:order-2">
    <section className="rounded-3xl border border-[#dfe4ea] bg-white p-5 shadow-[0_16px_44px_rgba(0,23,54,.045)] sm:p-7"><div className="mb-5 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#001736] text-white"><PackageCheck aria-hidden="true" className="h-5 w-5"/></span><h1 className="text-xl font-black text-[#001736] sm:text-2xl">{t("customerInfo")}</h1></div><div className="grid gap-4 sm:grid-cols-2"><Field label={t("fullName")} name="customerName" required/><Field label={t("phone")} name="phone" type="tel" dir="ltr" required/><Field label={t("email")} name="email" type="email" dir="ltr"/><Field label={labels.country} name="country"/><Field label={labels.province} name="province"/><Field label={t("city")} name="city" required/><Field label={t("postalCode")} name="postalCode" dir="ltr"/></div><div className="mt-4 space-y-4"><Field label={t("address")} name="address" required as="textarea"/><Field label={t("notes")} name="notes" as="textarea"/></div></section>
    <section className="rounded-3xl border border-[#dfe4ea] bg-white p-5 shadow-[0_16px_44px_rgba(0,23,54,.045)] sm:p-7"><div className="mb-5 flex items-center gap-2"><CreditCard aria-hidden="true" className="h-5 w-5 text-[#ba0036]"/><h2 className="text-lg font-black text-[#001736]">{labels.payment}</h2></div><div className="rounded-2xl border-2 border-[#001736] bg-[#001f48] p-5 text-white shadow-[0_12px_30px_rgba(0,31,72,.15)]"><Globe2 aria-hidden="true" className="h-9 w-9"/><strong className="mt-4 block text-sm">{labels.gateway}</strong><span className="mt-2 block text-xs leading-5 text-[#d6e3ff]">{labels.gatewaySub}</span></div></section>
    <section className="rounded-2xl border border-[#a9bfd8] bg-[#edf4fb] p-4 text-xs leading-6 text-[#43474f]"><div className="flex items-start gap-3"><ShieldCheck aria-hidden="true" className="mt-0.5 h-5 w-5 shrink-0 text-[#001736]"/><span>{labels.verified}</span></div></section>
    {error?<div role="alert" aria-live="assertive" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>:null}
   </div>
  </form>
 </Container></main>;
}

const fieldConfig:Record<string,{maxLength:number;autoComplete?:string;inputMode?:"text"|"tel"|"email"|"numeric"}>={customerName:{maxLength:120,autoComplete:"name"},phone:{maxLength:24,autoComplete:"tel",inputMode:"tel"},email:{maxLength:254,autoComplete:"email",inputMode:"email"},country:{maxLength:120,autoComplete:"country-name"},province:{maxLength:120,autoComplete:"address-level1"},city:{maxLength:120,autoComplete:"address-level2"},postalCode:{maxLength:20,autoComplete:"postal-code"},address:{maxLength:500,autoComplete:"street-address"},notes:{maxLength:1000}};
function Field({label,name,type="text",required,dir,as="input"}:{label:string;name:string;type?:string;required?:boolean;dir?:"ltr"|"rtl";as?:"input"|"textarea"}){const shared="vitalis-focus w-full rounded-xl border border-[#c4c6d0] bg-[#fbfcfe] px-3.5 text-sm text-[#181c1e] placeholder:text-[#747780]";const cfg=fieldConfig[name]??{maxLength:500};return <label className="flex flex-col gap-1.5"><span className="text-xs font-bold text-[#43474f]">{label}{required?<span aria-hidden="true"> *</span>:null}</span>{as==="textarea"?<textarea name={name} required={required} dir={dir} rows={4} maxLength={cfg.maxLength} autoComplete={cfg.autoComplete} className={shared}/>:<input name={name} type={type} required={required} dir={dir} maxLength={cfg.maxLength} autoComplete={cfg.autoComplete} inputMode={cfg.inputMode} className={`h-12 ${shared}`}/>}</label>}
