import Link from "next/link";
import { Pencil, Plus, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { DeleteButton } from "@/components/admin/delete-button";
import { deletePage } from "./actions";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminNumber, adminStatusText, type AdminLocale } from "@/lib/admin-i18n";

type PageRow={id:string;slug:string;titleFa:string;titleTr:string;titleEn:string;titleAr:string;isPublished:boolean;showInNav:boolean;navOrder:number;template:string};
const c:Record<AdminLocale,Record<string,string>>={
 fa:{eyebrow:"مدیریت محتوا",title:"صفحات سایت",new:"صفحه جدید",name:"عنوان",path:"مسیر",template:"قالب",nav:"منو",status:"وضعیت",yes:"بله",no:"خیر",all:"همه",search:"جستجو",searchPlaceholder:"عنوان، مسیر یا قالب...",published:"منتشرشده",draft:"پیش‌نویس",default:"پیش‌فرض",landing:"لندینگ",legal:"حقوقی",full:"تمام عرض",empty:"هنوز صفحه‌ای ثبت نشده است.",noMatch:"صفحه‌ای مطابق این فیلترها پیدا نشد."},
 ar:{eyebrow:"إدارة المحتوى",title:"صفحات الموقع",new:"صفحة جديدة",name:"العنوان",path:"المسار",template:"القالب",nav:"القائمة",status:"الحالة",yes:"نعم",no:"لا",all:"الكل",search:"بحث",searchPlaceholder:"العنوان أو المسار أو القالب...",published:"منشور",draft:"مسودة",default:"افتراضي",landing:"صفحة هبوط",legal:"قانوني",full:"عرض كامل",empty:"لا توجد صفحات مسجلة بعد.",noMatch:"لم يتم العثور على صفحة مطابقة لهذه المرشحات."},
 en:{eyebrow:"Content Management",title:"Site pages",new:"New page",name:"Title",path:"Path",template:"Template",nav:"Navigation",status:"Status",yes:"Yes",no:"No",all:"All",search:"Search",searchPlaceholder:"Title, path or template...",published:"Published",draft:"Draft",default:"Default",landing:"Landing",legal:"Legal",full:"Full width",empty:"No page has been registered yet.",noMatch:"No page matched these filters."},
 tr:{eyebrow:"İçerik Yönetimi",title:"Site sayfaları",new:"Yeni sayfa",name:"Başlık",path:"Yol",template:"Şablon",nav:"Menü",status:"Durum",yes:"Evet",no:"Hayır",all:"Tümü",search:"Ara",searchPlaceholder:"Başlık, yol veya şablon...",published:"Yayında",draft:"Taslak",default:"Varsayılan",landing:"Açılış sayfası",legal:"Yasal",full:"Tam genişlik",empty:"Henüz sayfa kaydedilmedi.",noMatch:"Bu filtrelerle eşleşen sayfa bulunamadı."}
};
const localizedTitle=(p:PageRow,l:AdminLocale)=>{const ordered=l==="fa"?[p.titleFa,p.titleAr,p.titleEn,p.titleTr]:l==="ar"?[p.titleAr,p.titleFa,p.titleEn,p.titleTr]:l==="tr"?[p.titleTr,p.titleEn,p.titleFa,p.titleAr]:[p.titleEn,p.titleTr,p.titleFa,p.titleAr];return ordered.find(Boolean)||p.slug;};
const templateLabel=(v:string,t:Record<string,string>)=>({default:t.default,landing:t.landing,legal:t.legal,"full-width":t.full}[v]||v);

export default async function AdminPagesPage({searchParams}:{searchParams:Promise<{q?:string;status?:string;nav?:string}>}) {
 const {q="",status="",nav=""}=await searchParams;
 const [pages,l]=await Promise.all([adminRpc<PageRow[]>("admin_pages_search",{p_search:q,p_status:status,p_nav:nav}),currentAdminLocale()]);
 const t=c[l],filtered=Boolean(q||status||nav);
 return <div className="space-y-6">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-muted">{t.eyebrow}</p><h1 className="mt-2 text-2xl font-black text-foreground">{t.title}</h1></div><Link href="/admin/pages/new" className="flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-black text-white hover:bg-primary/90"><Plus className="h-4 w-4"/>{t.new}</Link></div>
  <form className="grid gap-3 rounded-2xl border border-border bg-card p-4 md:grid-cols-[1fr_180px_180px_auto]"><label className="relative"><Search className="pointer-events-none absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted"/><input name="q" defaultValue={q} placeholder={t.searchPlaceholder} className="h-11 w-full rounded-xl border border-border bg-background ps-10 pe-3 text-sm outline-none focus:border-primary"/></label><select name="status" defaultValue={status} className="h-11 rounded-xl border border-border bg-background px-3 text-sm"><option value="">{t.all} · {t.status}</option><option value="PUBLISHED">{t.published}</option><option value="DRAFT">{t.draft}</option></select><select name="nav" defaultValue={nav} className="h-11 rounded-xl border border-border bg-background px-3 text-sm"><option value="">{t.all} · {t.nav}</option><option value="YES">{t.yes}</option><option value="NO">{t.no}</option></select><button className="h-11 rounded-xl bg-foreground px-5 text-xs font-black text-background">{t.search}</button></form>
  <div className="overflow-x-auto rounded-2xl border border-border bg-card"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-border text-xs text-muted"><th className="px-4 py-3 text-start">{t.name}</th><th className="px-4 py-3 text-start">{t.path}</th><th className="px-4 py-3 text-start">{t.template}</th><th className="px-4 py-3 text-start">{t.nav}</th><th className="px-4 py-3 text-start">{t.status}</th><th className="px-4 py-3"/></tr></thead><tbody>{pages.map(p=><tr key={p.id} className="border-b border-border last:border-0"><td className="px-4 py-3"><div className="font-bold text-foreground">{localizedTitle(p,l)}</div></td><td className="px-4 py-3 text-muted" dir="ltr">/{p.slug}</td><td className="px-4 py-3 text-muted">{templateLabel(p.template,t)}</td><td className="px-4 py-3 text-muted">{p.showInNav?`${t.yes} · ${adminNumber(p.navOrder,l)}`:t.no}</td><td className="px-4 py-3"><Badge variant={p.isPublished?"success":"muted"}>{adminStatusText(p.isPublished?"PUBLISHED":"DRAFT",l)}</Badge></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Link href={`/admin/pages/${p.id}`} className="flex h-9 w-9 items-center justify-center rounded-lg text-muted hover:bg-muted-bg"><Pencil className="h-4 w-4"/></Link><DeleteButton action={deletePage.bind(null,p.id)}/></div></td></tr>)}{pages.length===0?<tr><td colSpan={6} className="px-4 py-12 text-center text-muted">{filtered?t.noMatch:t.empty}</td></tr>:null}</tbody></table></div>
 </div>;
}
