import Link from "next/link";
import { Pencil, Plus, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { DeleteButton } from "@/components/admin/delete-button";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminCurrency, adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { verticalLabel, verticalOptions } from "@/lib/verticals";
import { deleteService } from "./actions";

type ServiceRow={id:string;vertical:string;slug:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;price?:number|null;priceIsFrom:boolean;durationMinutes?:number|null;requiresBooking:boolean;isPublished:boolean;bookingCount:number};
const c:Record<AdminLocale,Record<string,string>>={
 fa:{eyebrow:"خدمات تخصصی",title:"خدمات",new:"خدمت جدید",service:"خدمت",vertical:"حوزه",price:"قیمت",duration:"مدت",minute:"دقیقه",bookings:"رزروها",bookingMode:"رزرو",required:"الزامی",optional:"اختیاری",status:"وضعیت",from:"از",quote:"نیاز به استعلام",published:"منتشرشده",draft:"پیش‌نویس",all:"همه",search:"جستجو",searchPlaceholder:"نام خدمت یا slug...",empty:"هنوز خدمتی ثبت نشده است.",noMatch:"خدمتی مطابق این فیلترها پیدا نشد."},
 ar:{eyebrow:"الخدمات التخصصية",title:"الخدمات",new:"خدمة جديدة",service:"الخدمة",vertical:"المجال",price:"السعر",duration:"المدة",minute:"دقيقة",bookings:"الحجوزات",bookingMode:"الحجز",required:"مطلوب",optional:"اختياري",status:"الحالة",from:"ابتداءً من",quote:"يتطلب عرض سعر",published:"منشور",draft:"مسودة",all:"الكل",search:"بحث",searchPlaceholder:"اسم الخدمة أو slug...",empty:"لا توجد خدمات بعد.",noMatch:"لم يتم العثور على خدمة مطابقة لهذه المرشحات."},
 en:{eyebrow:"Clinical services",title:"Services",new:"New service",service:"Service",vertical:"Vertical",price:"Price",duration:"Duration",minute:"min",bookings:"Bookings",bookingMode:"Booking",required:"Required",optional:"Optional",status:"Status",from:"From",quote:"Contact for quote",published:"Published",draft:"Draft",all:"All",search:"Search",searchPlaceholder:"Service name or slug...",empty:"No services have been added yet.",noMatch:"No service matched these filters."},
 tr:{eyebrow:"Uzman hizmetler",title:"Hizmetler",new:"Yeni hizmet",service:"Hizmet",vertical:"Alan",price:"Fiyat",duration:"Süre",minute:"dk",bookings:"Rezervasyonlar",bookingMode:"Rezervasyon",required:"Zorunlu",optional:"İsteğe bağlı",status:"Durum",from:"Başlangıç",quote:"Fiyat için iletişime geçin",published:"Yayında",draft:"Taslak",all:"Tümü",search:"Ara",searchPlaceholder:"Hizmet adı veya slug...",empty:"Henüz hizmet eklenmedi.",noMatch:"Bu filtrelerle eşleşen hizmet bulunamadı."}
};
const localizedName=(x:ServiceRow,l:AdminLocale)=>{const ordered=l==="fa"?[x.nameFa,x.nameAr,x.nameEn,x.nameTr]:l==="ar"?[x.nameAr,x.nameFa,x.nameEn,x.nameTr]:l==="tr"?[x.nameTr,x.nameEn,x.nameFa,x.nameAr]:[x.nameEn,x.nameTr,x.nameFa,x.nameAr];return ordered.find(Boolean)||x.slug;};

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;status?:string;vertical?:string}>}){
 const {q="",status="",vertical=""}=await searchParams;
 const [services,l]=await Promise.all([adminRpc<ServiceRow[]>("admin_services_search",{p_search:q,p_status:status,p_vertical:vertical}),currentAdminLocale()]);
 const t=c[l],verticals=verticalOptions(l),filtered=Boolean(q||status||vertical);
 return <div className="space-y-6">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-muted">{t.eyebrow}</p><h1 className="mt-2 text-2xl font-black">{t.title}</h1></div><Link href="/admin/services/new" className="flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-black text-white"><Plus className="h-4 w-4"/>{t.new}</Link></div>
  <form className="grid gap-3 rounded-2xl border bg-card p-4 md:grid-cols-[1fr_180px_220px_auto]"><label className="relative"><Search className="pointer-events-none absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted"/><input name="q" defaultValue={q} placeholder={t.searchPlaceholder} className="h-11 w-full rounded-xl border bg-background ps-10 pe-3 text-sm outline-none focus:border-primary"/></label><select name="status" defaultValue={status} className="h-11 rounded-xl border bg-background px-3 text-sm"><option value="">{t.all} · {t.status}</option><option value="PUBLISHED">{t.published}</option><option value="DRAFT">{t.draft}</option></select><select name="vertical" defaultValue={vertical} className="h-11 rounded-xl border bg-background px-3 text-sm"><option value="">{t.all} · {t.vertical}</option>{verticals.map(v=><option key={v.value} value={v.value}>{v.label}</option>)}</select><button className="h-11 rounded-xl bg-foreground px-5 text-xs font-black text-background">{t.search}</button></form>
  <div className="overflow-x-auto rounded-2xl border bg-card"><table className="w-full min-w-[1050px] text-sm"><thead><tr className="border-b text-xs text-muted">{[t.service,t.vertical,t.price,t.duration,t.bookingMode,t.bookings,t.status,""].map((x,i)=><th key={i} className="px-4 py-3 text-start">{x}</th>)}</tr></thead><tbody>{services.map(s=><tr key={s.id} className="border-b last:border-0"><td className="px-4 py-3"><b>{localizedName(s,l)}</b><div className="mt-1 text-xs text-muted" dir="ltr">/{s.slug}</div></td><td className="px-4 py-3">{verticalLabel(s.vertical,l)}</td><td className="px-4 py-3">{s.price!==null&&s.price!==undefined?`${s.priceIsFrom?t.from+" ":""}${adminNumber(s.price,l)} ${adminCurrency[l]}`:t.quote}</td><td className="px-4 py-3">{s.durationMinutes!==null&&s.durationMinutes!==undefined?`${adminNumber(s.durationMinutes,l)} ${t.minute}`:"—"}</td><td className="px-4 py-3">{s.requiresBooking?t.required:t.optional}</td><td className="px-4 py-3">{adminNumber(s.bookingCount,l)}</td><td className="px-4 py-3"><Badge variant={s.isPublished?"success":"muted"}>{s.isPublished?t.published:t.draft}</Badge></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Link href={`/admin/services/${s.id}`} className="flex h-9 w-9 items-center justify-center rounded-lg hover:bg-muted-bg"><Pencil className="h-4 w-4"/></Link><DeleteButton action={deleteService.bind(null,s.id)}/></div></td></tr>)}{!services.length?<tr><td colSpan={8} className="px-4 py-12 text-center text-muted">{filtered?t.noMatch:t.empty}</td></tr>:null}</tbody></table></div>
 </div>;
}
