import Link from "next/link";
import { KeyRound, ShieldCheck } from "lucide-react";
import { resetPasswordAction } from "../actions";

const copy={
 fa:{title:"تعیین رمز عبور جدید",body:"رمز جدید باید حداقل ۸ کاراکتر باشد. بعد از تغییر رمز، همه نشست‌های قبلی حساب بسته می‌شوند.",mismatch:"رمز و تکرار آن یکسان نیست.",invalid:"لینک بازیابی نامعتبر یا منقضی شده است.",missing:"لینک بازیابی معتبر در دسترس نیست. یک درخواست جدید ثبت کنید.",password:"رمز جدید",confirm:"تکرار رمز جدید",submit:"ثبت رمز جدید",newLink:"درخواست لینک جدید"},
 tr:{title:"Yeni şifre belirleyin",body:"Yeni şifre en az 8 karakter olmalıdır. Şifre değiştirildikten sonra hesabın önceki tüm oturumları kapatılır.",mismatch:"Şifreler eşleşmiyor.",invalid:"Kurtarma bağlantısı geçersiz veya süresi dolmuş.",missing:"Geçerli bir kurtarma bağlantısı yok. Yeni bir istek oluşturun.",password:"Yeni şifre",confirm:"Yeni şifre tekrar",submit:"Yeni şifreyi kaydet",newLink:"Yeni bağlantı iste"},
 en:{title:"Set a new password",body:"Your new password must be at least 8 characters. After the password is changed, all previous account sessions will be closed.",mismatch:"Passwords do not match.",invalid:"The recovery link is invalid or has expired.",missing:"No valid recovery link is available. Submit a new request.",password:"New password",confirm:"Confirm new password",submit:"Save new password",newLink:"Request a new link"},
 ar:{title:"تعيين كلمة مرور جديدة",body:"يجب ألا تقل كلمة المرور الجديدة عن 8 أحرف. بعد تغييرها سيتم إغلاق جميع جلسات الحساب السابقة.",mismatch:"كلمتا المرور غير متطابقتين.",invalid:"رابط الاستعادة غير صالح أو منتهي الصلاحية.",missing:"لا يتوفر رابط استعادة صالح. أرسل طلبًا جديدًا.",password:"كلمة المرور الجديدة",confirm:"تأكيد كلمة المرور الجديدة",submit:"حفظ كلمة المرور الجديدة",newLink:"طلب رابط جديد"}
} as const;

export default async function ResetPasswordPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{token?:string;error?:string}>}){
  const {locale}=await params; const q=await searchParams; const token=q.token??""; const action=resetPasswordAction.bind(null,locale); const t=copy[locale as keyof typeof copy]??copy.fa;
  return <main className="py-16"><div className="mx-auto max-w-xl px-4"><section className="vitalis-glass rounded-[2rem] border border-white/70 p-7 shadow-xl sm:p-10"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 text-primary"><KeyRound className="h-7 w-7"/></div><h1 className="mt-6 text-2xl font-black text-foreground">{t.title}</h1><p className="mt-2 text-sm leading-7 text-muted">{t.body}</p>{q.error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{q.error==="mismatch"?t.mismatch:t.invalid}</div>:null}{!token?<div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{t.missing}</div>:<form action={action} className="mt-6 space-y-4"><input type="hidden" name="token" value={token}/><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{t.password}</span><input name="password" type="password" minLength={8} required autoComplete="new-password" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{t.confirm}</span><input name="confirmPassword" type="password" minLength={8} required autoComplete="new-password" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label><button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-black text-white"><ShieldCheck className="h-4 w-4"/>{t.submit}</button></form>}<div className="mt-6 text-center"><Link href={`/${locale}/account/forgot-password`} className="text-xs font-bold text-primary">{t.newLink}</Link></div></section></div></main>;
}
