import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { CommerceImportPanel } from "@/components/admin/commerce-import-panel";

type Branch={id:string;code:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;currency:string};
type Warehouse={id:string;code:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;isActive:boolean};
type Bundle={branch:Branch|null;branches:Branch[];warehouses:Warehouse[]};
function name(row:Branch,l:string){return (l==="fa"?row.nameFa:l==="tr"?row.nameTr:l==="ar"?row.nameAr:row.nameEn)||row.nameEn||row.nameFa}
export default async function Page({searchParams}:{searchParams:Promise<{branch?:string}>}){const{branch=""}=await searchParams;const locale=await currentAdminLocale();const data=await adminRpc<Bundle>("admin_commerce_control_center",{p_branch_id:branch||null,p_search:null});if(!data.branch)return <div className="rounded-2xl border bg-white p-8">No published commerce branch is available.</div>;return <div className="mx-auto max-w-6xl space-y-6"><header><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">Production commerce</p><h1 className="mt-2 text-3xl font-black">Current commerce data import</h1><p className="mt-2 text-sm text-muted">Branch price and real warehouse stock are written only after preflight and explicit confirmation. The source is retained as evidence.</p></header><form className="rounded-2xl border bg-white p-4"><label className="text-xs font-bold">Branch<select name="branch" defaultValue={data.branch.id} className="mt-2 h-11 w-full rounded-xl border px-3" onChange={undefined}>{data.branches.map(b=><option key={b.id} value={b.id}>{name(b,locale)} · {b.code} · {b.currency}</option>)}</select></label><button className="mt-3 min-h-10 rounded-xl bg-[#001736] px-4 text-xs font-black text-white">Load branch</button></form><CommerceImportPanel locale={locale} branchId={data.branch.id} warehouses={data.warehouses.filter(w=>w.isActive)}/></div>}
