import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getLocale } from "next-intl/server";
import { Container } from "@/components/ui/container";
import { ShopProductCard } from "@/components/site/shop-product-card";
import { getPublicCollectionBySlug } from "@/lib/catalog-extensions";

function pick(x:any,l:string,key:string){const s=l==="fa"?"Fa":l==="tr"?"Tr":l==="ar"?"Ar":"En";return x[`${key}${s}`]||x[`${key}En`]||x[`${key}Fa`]||""}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params,l=await getLocale(),r=await getPublicCollectionBySlug(slug);if(!r)return{};return{title:pick(r.collection,l,"seoTitle")||pick(r.collection,l,"title"),description:pick(r.collection,l,"seoDescription")||pick(r.collection,l,"description")||undefined};}
export default async function CollectionPage({params}:{params:Promise<{slug:string}>}){const{slug}=await params,l=await getLocale(),r=await getPublicCollectionBySlug(slug);if(!r)notFound();const c=r.collection,title=pick(c,l,"title"),desc=pick(c,l,"description");return <main className="flex-1 bg-[#f7fafd]"><section className="relative overflow-hidden border-b bg-[#001736] text-white">{c.heroImageUrl?<div className="absolute inset-0 bg-cover bg-center opacity-25" style={{backgroundImage:`url(${c.heroImageUrl})`}}/>:null}<Container><div className="relative py-16 sm:py-20 lg:py-24"><p className="text-xs font-black uppercase tracking-[.2em] text-[#63d6ff]">HYPER DOCTOR COLLECTION</p><h1 className="mt-4 max-w-4xl text-4xl font-black leading-tight sm:text-5xl">{title}</h1>{desc?<p className="mt-5 max-w-3xl whitespace-pre-line text-sm leading-8 text-white/80 sm:text-base">{desc}</p>:null}</div></Container></section><Container><section className="py-10 sm:py-14"><div className="mb-6 flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black text-[#001736]">{l==="fa"?"محصولات این کالکشن":l==="tr"?"Koleksiyon ürünleri":l==="ar"?"منتجات المجموعة":"Collection products"}</h2><p className="mt-1 text-xs text-[#747780]">{r.products.length} {l==="fa"?"محصول":l==="tr"?"ürün":l==="ar"?"منتج":"products"}</p></div></div>{r.products.length?<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{r.products.map((p:any)=><ShopProductCard key={p.id} product={p}/>)}</div>:<div className="rounded-3xl border border-dashed bg-white p-12 text-center text-sm text-[#8b9098]">{l==="fa"?"هنوز محصولی به این کالکشن اضافه نشده است.":l==="tr"?"Bu koleksiyona henüz ürün eklenmedi.":l==="ar"?"لم تتم إضافة منتجات إلى هذه المجموعة بعد.":"No products have been added to this collection yet."}</div>}</section></Container></main>}
