import Link from "next/link";
import { AlertTriangle, BadgeCheck, Boxes, ImageOff, Languages, PackageSearch, Tags } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminNumber, type AdminLocale } from "@/lib/admin-i18n";

type Summary={products:number;published:number;missingBrand:number;missingTaxonomy:number;missingImages:number;missingTranslations:number;outOfStock:number;duplicateSku:number};
type Issue={id:string;sku:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;stock:number;issues:string[]};
type Payload={summary:Summary;issues:Issue[]};
const copy:Record<AdminLocale,any>={fa:{eyebrow:"کنترل کیفیت کاتالوگ",title:"سلامت کاتالوگ",desc:"کنترل خودکار داده‌های واقعی محصولات منتشرشده و مواردی که قبل از فروش باید تکمیل شوند.",total:"کل محصولات",published:"منتشرشده",brand:"بدون برند مرجع",taxonomy:"بدون Taxonomy",image:"بدون تصویر",translation:"ترجمه ناقص",stock:"ناموجود",duplicate:"SKU تکراری",clean:"هیچ ایراد عملیاتی در محصولات منتشرشده پیدا نشد.",issues:"موارد نیازمند اصلاح",edit:"اصلاح محصول",labels:{MISSING_BRAND:"برند مرجع ندارد",MISSING_TAXONOMY:"طبقه‌بندی چندبعدی ندارد",MISSING_IMAGE:"تصویر ندارد",MISSING_TRANSLATION:"ترجمه ناقص است",OUT_OF_STOCK:"موجودی صفر است"}},en:{eyebrow:"Catalog quality control",title:"Catalog health",desc:"Automatic checks against real published product data before it reaches customers.",total:"All products",published:"Published",brand:"Missing brand",taxonomy:"Missing taxonomy",image:"Missing image",translation:"Missing translation",stock:"Out of stock",duplicate:"Duplicate SKU",clean:"No operational issues were found in published products.",issues:"Items requiring attention",edit:"Fix product",labels:{MISSING_BRAND:"Missing canonical brand",MISSING_TAXONOMY:"Missing multi-taxonomy",MISSING_IMAGE:"Missing image",MISSING_TRANSLATION:"Missing translation",OUT_OF_STOCK:"Out of stock"}},tr:{eyebrow:"Katalog kalite kontrolü",title:"Katalog sağlığı",desc:"Yayınlanan gerçek ürün verilerini müşteriye ulaşmadan önce otomatik olarak kontrol eder.",total:"Tüm ürünler",published:"Yayında",brand:"Marka eksik",taxonomy:"Taksonomi eksik",image:"Görsel eksik",translation:"Çeviri eksik",stock:"Stokta yok",duplicate:"Tekrarlanan SKU",clean:"Yayınlanan ürünlerde operasyonel sorun bulunamadı.",issues:"Düzeltilmesi gerekenler",edit:"Ürünü düzelt",labels:{MISSING_BRAND:"Resmi marka eksik",MISSING_TAXONOMY:"Çoklu taksonomi eksik",MISSING_IMAGE:"Görsel eksik",MISSING_TRANSLATION:"Çeviri eksik",OUT_OF_STOCK:"Stokta yok"}},ar:{eyebrow:"مراقبة جودة الكتالوج",title:"سلامة الكتالوج",desc:"فحص تلقائي لبيانات المنتجات المنشورة الفعلية قبل وصولها إلى العملاء.",total:"كل المنتجات",published:"منشور",brand:"علامة مفقودة",taxonomy:"تصنيف مفقود",image:"صورة مفقودة",translation:"ترجمة ناقصة",stock:"نفد المخزون",duplicate:"SKU مكرر",clean:"لم يتم العثور على مشاكل تشغيلية في المنتجات المنشورة.",issues:"عناصر تحتاج إلى تصحيح",edit:"تصحيح المنتج",labels:{MISSING_BRAND:"العلامة المرجعية مفقودة",MISSING_TAXONOMY:"التصنيف المتعدد مفقود",MISSING_IMAGE:"الصورة مفقودة",MISSING_TRANSLATION:"الترجمة ناقصة",OUT_OF_STOCK:"نفد المخزون"}}};
const productName=(x:Issue,l:AdminLocale)=>({fa:x.nameFa,tr:x.nameTr,en:x.nameEn,ar:x.nameAr}[l]||x.nameEn||x.nameFa||x.sku);
export default async function Page(){const[data,locale]=await Promise.all([adminRpc<Payload>("admin_catalog_integrity"),currentAdminLocale()]);const t=copy[locale],s=data.summary;const cards=[[t.total,s.products,Boxes],[t.published,s.published,BadgeCheck],[t.brand,s.missingBrand,Tags],[t.taxonomy,s.missingTaxonomy,PackageSearch],[t.image,s.missingImages,ImageOff],[t.translation,s.missingTranslations,Languages],[t.stock,s.outOfStock,AlertTriangle],[t.duplicate,s.duplicateSku,AlertTriangle]] as const;return <div className="mx-auto max-w-[1450px] space-y-6"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-[#747780]">{t.desc}</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,Icon])=><div key={label} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#747780]">{label}</span><Icon className="h-4 w-4 text-[#009dd8]"/></div><strong className="mt-3 block text-2xl font-black text-[#001736]">{adminNumber(value,locale)}</strong></div>)}</div><section className="rounded-[1.6rem] border bg-white p-5 shadow-sm"><h2 className="text-base font-black text-[#001736]">{t.issues}</h2>{data.issues.length?<div className="mt-4 divide-y">{data.issues.map(x=><div key={x.id} className="flex flex-col gap-3 py-4 md:flex-row md:items-center md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><b className="text-sm text-[#001736]">{productName(x,locale)}</b><span dir="ltr" className="rounded-lg bg-[#f1f4f7] px-2 py-1 text-[10px] font-bold">{x.sku}</span></div><div className="mt-2 flex flex-wrap gap-1.5">{x.issues.map(i=><span key={i} className="rounded-full bg-[#fff2cc] px-2.5 py-1 text-[10px] font-black text-[#765700]">{t.labels[i]??i}</span>)}</div></div><Link href={`/admin/products/${x.id}`} className="inline-flex min-h-10 items-center justify-center rounded-xl bg-[#001736] px-4 text-xs font-black text-white">{t.edit}</Link></div>)}</div>:<div className="mt-5 rounded-2xl bg-[#e8f6ed] p-5 text-sm font-bold text-[#187143]">{t.clean}</div>}</section></div>}
