import { formatLocalizedDate, formatLocalizedDateTime } from "@/lib/calendar";

export type AdminLocale = "fa" | "ar" | "en" | "tr";
export const adminLocales: AdminLocale[]=["fa","ar","en","tr"];
export function getAdminLocale(value?:string|null):AdminLocale{return value==="ar"||value==="en"||value==="tr"?value:"fa"}
export const adminDir=(l:AdminLocale)=>l==="fa"||l==="ar"?"rtl":"ltr";
export const adminIntlLocale:Record<AdminLocale,string>={fa:"fa-IR-u-nu-arabext",ar:"ar-u-nu-arab",en:"en-US",tr:"tr-TR"};
export const adminCurrency:Record<AdminLocale,string>={fa:"تومان",ar:"تومان",en:"Toman",tr:"Toman"};
const currencyLabels:Record<string,Record<AdminLocale,string>>={IRR:{fa:"ریال",ar:"ريال إيراني",en:"IRR",tr:"İran Riyali"},IRT:{fa:"تومان",ar:"تومان",en:"Toman",tr:"Toman"},TOMAN:{fa:"تومان",ar:"تومان",en:"Toman",tr:"Toman"},TRY:{fa:"لیر ترکیه",ar:"ليرة تركية",en:"TRY",tr:"Türk Lirası"},USD:{fa:"دلار آمریکا",ar:"دولار أمريكي",en:"USD",tr:"ABD Doları"},EUR:{fa:"یورو",ar:"يورو",en:"EUR",tr:"Euro"}};
const gatewayLabels:Record<string,Record<AdminLocale,string>>={ZARINPAL:{fa:"زرین‌پال",ar:"زرين بال",en:"Zarinpal",tr:"Zarinpal"},MANUAL:{fa:"پرداخت دستی",ar:"دفع يدوي",en:"Manual payment",tr:"Manuel ödeme"},CARD_TO_CARD:{fa:"کارت‌به‌کارت",ar:"تحويل بطاقة",en:"Card-to-card",tr:"Karttan karta"},CRYPTO:{fa:"رمزارز",ar:"عملة رقمية",en:"Crypto",tr:"Kripto"},CASH:{fa:"نقدی",ar:"نقدي",en:"Cash",tr:"Nakit"}};
export function adminCurrencyText(value:string|undefined|null,l:AdminLocale){const key=String(value||"IRT").trim().toUpperCase();return currencyLabels[key]?.[l]||key}
export function adminGatewayText(value:string|undefined|null,l:AdminLocale){const key=String(value||"").trim().toUpperCase();return gatewayLabels[key]?.[l]||String(value||"—").replaceAll("_"," ")}
export const adminStatus:Record<AdminLocale,Record<string,string>>={fa:{PENDING_PAYMENT:"در انتظار پرداخت",PAYMENT_REVIEW:"پرداخت تأیید؛ نیازمند بررسی",PAID:"پرداخت‌شده",PROCESSING:"در حال پردازش",SHIPPED:"ارسال‌شده",COMPLETED:"تکمیل‌شده",CANCELLED:"لغوشده",FAILED:"ناموفق",REFUNDED:"بازپرداخت‌شده",OPEN:"باز",IN_PROGRESS:"در حال پیگیری",WAITING_CUSTOMER:"در انتظار مشتری",RESOLVED:"حل‌شده",CLOSED:"بسته",PENDING:"در انتظار",ACTIVE:"فعال",EXPIRED:"منقضی‌شده",SUSPENDED:"تعلیق‌شده",REPLACED:"تعویض‌شده",INACTIVE:"غیرفعال",APPROVED:"تأییدشده",REJECTED:"ردشده",DRAFT:"پیش‌نویس",PUBLISHED:"منتشرشده",LOW:"کم",NORMAL:"عادی",HIGH:"زیاد",URGENT:"فوری"},ar:{PENDING_PAYMENT:"بانتظار الدفع",PAYMENT_REVIEW:"تم الدفع؛ يحتاج إلى مراجعة",PAID:"مدفوع",PROCESSING:"قيد المعالجة",SHIPPED:"تم الشحن",COMPLETED:"مكتمل",CANCELLED:"ملغي",FAILED:"فشل",REFUNDED:"تم رد المبلغ",OPEN:"مفتوح",IN_PROGRESS:"قيد المتابعة",WAITING_CUSTOMER:"بانتظار العميل",RESOLVED:"تم الحل",CLOSED:"مغلق",PENDING:"قيد الانتظار",ACTIVE:"نشط",EXPIRED:"منتهي الصلاحية",SUSPENDED:"معلّق",REPLACED:"تم الاستبدال",INACTIVE:"غير نشط",APPROVED:"معتمد",REJECTED:"مرفوض",DRAFT:"مسودة",PUBLISHED:"منشور",LOW:"منخفض",NORMAL:"عادي",HIGH:"مرتفع",URGENT:"عاجل"},en:{PENDING_PAYMENT:"Pending payment",PAYMENT_REVIEW:"Payment confirmed; review required",PAID:"Paid",PROCESSING:"Processing",SHIPPED:"Shipped",COMPLETED:"Completed",CANCELLED:"Cancelled",FAILED:"Failed",REFUNDED:"Refunded",OPEN:"Open",IN_PROGRESS:"In progress",WAITING_CUSTOMER:"Waiting for customer",RESOLVED:"Resolved",CLOSED:"Closed",PENDING:"Pending",ACTIVE:"Active",EXPIRED:"Expired",SUSPENDED:"Suspended",REPLACED:"Replaced",INACTIVE:"Inactive",APPROVED:"Approved",REJECTED:"Rejected",DRAFT:"Draft",PUBLISHED:"Published",LOW:"Low",NORMAL:"Normal",HIGH:"High",URGENT:"Urgent"},tr:{PENDING_PAYMENT:"Ödeme bekliyor",PAYMENT_REVIEW:"Ödeme onaylandı; inceleme gerekli",PAID:"Ödendi",PROCESSING:"İşleniyor",SHIPPED:"Gönderildi",COMPLETED:"Tamamlandı",CANCELLED:"İptal edildi",FAILED:"Başarısız",REFUNDED:"İade edildi",OPEN:"Açık",IN_PROGRESS:"İşlemde",WAITING_CUSTOMER:"Müşteri bekleniyor",RESOLVED:"Çözüldü",CLOSED:"Kapalı",PENDING:"Bekliyor",ACTIVE:"Aktif",EXPIRED:"Süresi doldu",SUSPENDED:"Askıya alındı",REPLACED:"Değiştirildi",INACTIVE:"Pasif",APPROVED:"Onaylandı",REJECTED:"Reddedildi",DRAFT:"Taslak",PUBLISHED:"Yayında",LOW:"Düşük",NORMAL:"Normal",HIGH:"Yüksek",URGENT:"Acil"}};
export function adminNumber(v:number,l:AdminLocale){return new Intl.NumberFormat(adminIntlLocale[l]).format(v)}
export function adminDate(v:string|number|Date,l:AdminLocale){return formatLocalizedDate(v,l,{year:"numeric",month:"short",day:"numeric"})}
export function adminDateTime(v:string|number|Date,l:AdminLocale){return formatLocalizedDateTime(v,l)}
export function adminStatusText(v:string,l:AdminLocale){return adminStatus[l][v]||v.replaceAll("_"," ")}
