"use client";
import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from "react";
export type CartLine={key:string;type:"product"|"service";id:string;nameFa:string;nameTr?:string;nameEn:string;nameAr?:string;price:number;image?:string|null;quantity:number;preferredDate?:string;minQuantity?:number;maxQuantity?:number|null};
type CartContextValue={lines:CartLine[];hydrated:boolean;add:(line:Omit<CartLine,"key">)=>void;updateQuantity:(key:string,quantity:number)=>void;remove:(key:string)=>void;clear:()=>void;subtotal:number;count:number};
const CartContext=createContext<CartContextValue|null>(null);const STORAGE_KEY="hyperdoctor.cart.v3";const LEGACY_STORAGE_KEYS=["hyperdoctor.cart.v2","hyperdoctor.cart.v1"];const MAX_CART_LINES=100;const MAX_LINE_QTY=50;
const cleanText=(v:unknown,max:number)=>typeof v==="string"?v.trim().slice(0,max):"";
function normalizeMin(type:CartLine["type"],value:unknown):number{if(type==="service")return 1;const n=Number(value);if(!Number.isFinite(n)||n<=0)return 1;return Math.max(1,Math.min(MAX_LINE_QTY,Math.floor(n)));}
function normalizeMax(type:CartLine["type"],value:unknown,min:number):number|null{if(type==="service")return 1;if(value===null||value===undefined||value==="")return null;const n=Number(value);if(!Number.isFinite(n))return null;return Math.max(min,Math.min(MAX_LINE_QTY,Math.floor(n)));}
function strictestMin(a:number|undefined,b:number|undefined){return Math.max(a??1,b??1);}
function strictestMax(a:number|null|undefined,b:number|null|undefined,min:number):number|null{const left=a??null,right=b??null;const value=left===null?right:right===null?left:Math.min(left,right);return value===null?null:Math.max(min,value);}
function safeQty(value:unknown,type:CartLine["type"],min:number,max:number|null){const floor=type==="service"?1:min;const cap=type==="service"?1:Math.min(MAX_LINE_QTY,max??MAX_LINE_QTY);const n=Number(value);if(!Number.isFinite(n)||n<=0)return floor;return Math.min(Math.max(floor,Math.floor(n)),cap);}
function normalizeStoredLines(raw:unknown):CartLine[]{if(!Array.isArray(raw))return[];const byKey=new Map<string,CartLine>();for(const item of raw){if(!item||typeof item!=="object")continue;const line=item as Partial<CartLine>;if(line.type!=="product"&&line.type!=="service")continue;const id=cleanText(line.id,160),nameFa=cleanText(line.nameFa,240),nameEn=cleanText(line.nameEn,240);if(!id||!nameFa||!nameEn)continue;const price=Number(line.price);if(!Number.isFinite(price)||price<0)continue;const preferredDate=line.type==="service"?(cleanText(line.preferredDate,80)||undefined):undefined;const minQuantity=normalizeMin(line.type,line.minQuantity),maxQuantity=normalizeMax(line.type,line.maxQuantity,minQuantity),quantity=safeQty(line.quantity,line.type,minQuantity,maxQuantity);const key=`${line.type}:${id}:${preferredDate??""}`;const normalized:CartLine={key,type:line.type,id,nameFa,nameTr:cleanText(line.nameTr,240)||undefined,nameEn,nameAr:cleanText(line.nameAr,240)||undefined,price,image:typeof line.image==="string"&&line.image.length<=2048?line.image:null,quantity,preferredDate,minQuantity,maxQuantity};const existing=byKey.get(key);if(existing){const strictMin=strictestMin(existing.minQuantity,minQuantity),strictMax=strictestMax(existing.maxQuantity,maxQuantity,strictMin);byKey.set(key,{...existing,minQuantity:strictMin,maxQuantity:strictMax,quantity:safeQty(existing.quantity+quantity,line.type,strictMin,strictMax)});}else if(byKey.size<MAX_CART_LINES)byKey.set(key,normalized);}return[...byKey.values()];}
export function CartProvider({children}:{children:ReactNode}){const[lines,setLines]=useState<CartLine[]>([]);const[hydrated,setHydrated]=useState(false);
 useEffect(()=>{try{let raw=localStorage.getItem(STORAGE_KEY);if(!raw)for(const key of LEGACY_STORAGE_KEYS){raw=localStorage.getItem(key);if(raw)break;}if(raw){const parsed=normalizeStoredLines(JSON.parse(raw));setLines(parsed);localStorage.setItem(STORAGE_KEY,JSON.stringify(parsed));}for(const key of LEGACY_STORAGE_KEYS)localStorage.removeItem(key);}catch{localStorage.removeItem(STORAGE_KEY);for(const key of LEGACY_STORAGE_KEYS)localStorage.removeItem(key);}setHydrated(true);},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(lines));}catch{}},[lines,hydrated]);
 const value=useMemo<CartContextValue>(()=>{const add:CartContextValue["add"]=(line)=>{if(line.type!=="product"&&line.type!=="service")return;const id=cleanText(line.id,160),nameFa=cleanText(line.nameFa,240),nameEn=cleanText(line.nameEn,240),price=Number(line.price);if(!id||!nameFa||!nameEn||!Number.isFinite(price)||price<0)return;const preferredDate=line.type==="service"?(cleanText(line.preferredDate,80)||undefined):undefined;const key=`${line.type}:${id}:${preferredDate??""}`,minQuantity=normalizeMin(line.type,line.minQuantity),maxQuantity=normalizeMax(line.type,line.maxQuantity,minQuantity),incoming=safeQty(line.quantity,line.type,minQuantity,maxQuantity);setLines(prev=>{const existing=prev.find(l=>l.key===key);if(existing){const strictMin=strictestMin(existing.minQuantity,minQuantity),strictMax=strictestMax(existing.maxQuantity,maxQuantity,strictMin);return prev.map(l=>l.key===key?{...l,minQuantity:strictMin,maxQuantity:strictMax,quantity:safeQty(l.quantity+incoming,l.type,strictMin,strictMax)}:l)}if(prev.length>=MAX_CART_LINES)return prev;return[...prev,{key,type:line.type,id,nameFa,nameTr:cleanText(line.nameTr,240)||undefined,nameEn,nameAr:cleanText(line.nameAr,240)||undefined,price,image:typeof line.image==="string"&&line.image.length<=2048?line.image:null,quantity:incoming,preferredDate,minQuantity,maxQuantity}];});};
 const updateQuantity=(key:string,quantity:number)=>setLines(prev=>{const target=prev.find(l=>l.key===key);if(!target)return prev;const min=normalizeMin(target.type,target.minQuantity),max=normalizeMax(target.type,target.maxQuantity,min);if(!Number.isFinite(quantity))return prev;if(quantity<min)return prev;const next=safeQty(quantity,target.type,min,max);return prev.map(l=>l.key===key?{...l,minQuantity:min,maxQuantity:max,quantity:next}:l)});const remove=(key:string)=>setLines(prev=>prev.filter(l=>l.key!==key));const clear=()=>setLines([]);const subtotal=lines.reduce((sum,l)=>{const value=l.price*l.quantity;return Number.isFinite(value)&&value>=0?sum+value:sum;},0);const count=lines.reduce((sum,l)=>sum+l.quantity,0);return{lines,hydrated,add,updateQuantity,remove,clear,subtotal,count};},[lines,hydrated]);return <CartContext.Provider value={value}>{children}</CartContext.Provider>;}
export function useCart(){const ctx=useContext(CartContext);if(!ctx)throw new Error("useCart must be used within CartProvider");return ctx;}
