"use client";
import {createContext,useContext,useEffect,useMemo,useState,type ReactNode} from "react";
export type CartLine={key:string;type:"product"|"service";id:string;nameFa:string;nameTr?:string;nameEn:string;nameAr?:string;price:number;image?:string|null;quantity:number;preferredDate?:string;maxQuantity?:number|null};
type CartContextValue={lines:CartLine[];hydrated:boolean;add:(line:Omit<CartLine,"key">)=>void;updateQuantity:(key:string,quantity:number)=>void;remove:(key:string)=>void;clear:()=>void;subtotal:number;count:number};
const CartContext=createContext<CartContextValue|null>(null);const STORAGE_KEY="hyperdoctor.cart.v2";const LEGACY_STORAGE_KEY="hyperdoctor.cart.v1";const MAX_CART_LINES=100;const MAX_LINE_QTY=50;
const cleanText=(v:unknown,max:number)=>typeof v==="string"?v.trim().slice(0,max):"";
function normalizeMax(type:CartLine["type"],value:unknown):number|null{if(type==="service")return 1;if(value===null||value===undefined||value==="")return null;const n=Number(value);if(!Number.isFinite(n))return null;return Math.max(0,Math.min(MAX_LINE_QTY,Math.floor(n)));}
function strictestMax(a:number|null|undefined,b:number|null|undefined):number|null{const left=a??null,right=b??null;if(left===null)return right;if(right===null)return left;return Math.min(left,right);}
function safeQty(value:unknown,type:CartLine["type"],max:number|null){if(max===0)return 0;const n=Number(value);const cap=type==="service"?1:Math.min(MAX_LINE_QTY,max??MAX_LINE_QTY);if(!Number.isFinite(n)||n<=0)return 1;return Math.min(Math.max(1,Math.floor(n)),cap);}
function normalizeStoredLines(raw:unknown):CartLine[]{if(!Array.isArray(raw))return[];const byKey=new Map<string,CartLine>();for(const item of raw){if(!item||typeof item!=="object")continue;const line=item as Partial<CartLine>;if(line.type!=="product"&&line.type!=="service")continue;const id=cleanText(line.id,160),nameFa=cleanText(line.nameFa,240),nameEn=cleanText(line.nameEn,240);if(!id||!nameFa||!nameEn)continue;const price=Number(line.price);if(!Number.isFinite(price)||price<0)continue;const preferredDate=line.type==="service"?(cleanText(line.preferredDate,80)||undefined):undefined;const maxQuantity=normalizeMax(line.type,line.maxQuantity);const quantity=safeQty(line.quantity,line.type,maxQuantity);if(quantity<=0)continue;const key=`${line.type}:${id}:${preferredDate??""}`;const normalized:CartLine={key,type:line.type,id,nameFa,nameTr:cleanText(line.nameTr,240)||undefined,nameEn,nameAr:cleanText(line.nameAr,240)||undefined,price,image:typeof line.image==="string"&&line.image.length<=2048?line.image:null,quantity,preferredDate,maxQuantity};const existing=byKey.get(key);if(existing){const strictMax=strictestMax(existing.maxQuantity,maxQuantity);byKey.set(key,{...existing,maxQuantity:strictMax,quantity:safeQty(existing.quantity+quantity,line.type,strictMax)});}else if(byKey.size<MAX_CART_LINES)byKey.set(key,normalized);}return[...byKey.values()];}
export function CartProvider({children}:{children:ReactNode}){const[lines,setLines]=useState<CartLine[]>([]);const[hydrated,setHydrated]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY)??localStorage.getItem(LEGACY_STORAGE_KEY);if(raw){const parsed=normalizeStoredLines(JSON.parse(raw));setLines(parsed);localStorage.setItem(STORAGE_KEY,JSON.stringify(parsed));localStorage.removeItem(LEGACY_STORAGE_KEY);}}catch{localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(LEGACY_STORAGE_KEY);}setHydrated(true);},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(lines));}catch{}},[lines,hydrated]);
 const value=useMemo<CartContextValue>(()=>{const add:CartContextValue["add"]=(line)=>{if(line.type!=="product"&&line.type!=="service")return;const id=cleanText(line.id,160),nameFa=cleanText(line.nameFa,240),nameEn=cleanText(line.nameEn,240),price=Number(line.price);if(!id||!nameFa||!nameEn||!Number.isFinite(price)||price<0)return;const preferredDate=line.type==="service"?(cleanText(line.preferredDate,80)||undefined):undefined;const key=`${line.type}:${id}:${preferredDate??""}`,maxQuantity=normalizeMax(line.type,line.maxQuantity),incoming=safeQty(line.quantity,line.type,maxQuantity);if(incoming<=0)return;setLines(prev=>{const existing=prev.find(l=>l.key===key);if(existing){const strictMax=strictestMax(existing.maxQuantity,maxQuantity);if(strictMax===0)return prev.filter(l=>l.key!==key);return prev.map(l=>l.key===key?{...l,maxQuantity:strictMax,quantity:safeQty(l.quantity+incoming,l.type,strictMax)}:l)}if(prev.length>=MAX_CART_LINES)return prev;return[...prev,{key,type:line.type,id,nameFa,nameTr:cleanText(line.nameTr,240)||undefined,nameEn,nameAr:cleanText(line.nameAr,240)||undefined,price,image:typeof line.image==="string"&&line.image.length<=2048?line.image:null,quantity:incoming,preferredDate,maxQuantity}];});};
 const updateQuantity=(key:string,quantity:number)=>setLines(prev=>{const target=prev.find(l=>l.key===key);if(!target)return prev;if(!Number.isFinite(quantity)||quantity<=0)return prev.filter(l=>l.key!==key);const next=safeQty(quantity,target.type,target.maxQuantity??null);return next<=0?prev.filter(l=>l.key!==key):prev.map(l=>l.key===key?{...l,quantity:next}:l)});const remove=(key:string)=>setLines(prev=>prev.filter(l=>l.key!==key));const clear=()=>setLines([]);const subtotal=lines.reduce((sum,l)=>{const value=l.price*l.quantity;return Number.isFinite(value)&&value>=0?sum+value:sum;},0);const count=lines.reduce((sum,l)=>sum+l.quantity,0);return{lines,hydrated,add,updateQuantity,remove,clear,subtotal,count};},[lines,hydrated]);return <CartContext.Provider value={value}>{children}</CartContext.Provider>;}
export function useCart(){const ctx=useContext(CartContext);if(!ctx)throw new Error("useCart must be used within CartProvider");return ctx;}
