import { cookies } from "next/headers";
import { inFilter, supabaseSelect } from "@/lib/supabase-rest";

async function hydrateProducts(products:any[]){if(!products.length)return[];const productIds=products.map(p=>p.id),categoryIds=[...new Set(products.map(p=>p.categoryId).filter(Boolean))],brandIds=[...new Set(products.map(p=>p.brandId).filter(Boolean))];const[images,categories,brands]=await Promise.all([supabaseSelect<any>("Media",{select:"*",productId:inFilter(productIds),order:"sortOrder.asc"}),categoryIds.length?supabaseSelect<any>("Category",{select:"*",id:inFilter(categoryIds)}):Promise.resolve([]),brandIds.length?supabaseSelect<any>("Brand",{select:"*",id:inFilter(brandIds)}):Promise.resolve([])]);const categoriesById=new Map(categories.map(c=>[c.id,c])),brandsById=new Map(brands.map(b=>[b.id,b])),imagesByProductId=new Map<string,any[]>();for(const image of images){const list=imagesByProductId.get(image.productId)??[];list.push(image);imagesByProductId.set(image.productId,list)}return products.map(product=>({...product,images:imagesByProductId.get(product.id)??[],category:categoriesById.get(product.categoryId)??null,brandEntity:product.brandId?brandsById.get(product.brandId)??null:null}))}

export async function getCategories(){try{const[categories,products,secondary]=await Promise.all([supabaseSelect<any>("Category",{select:"*",isPublished:"eq.true",order:"order.asc,createdAt.asc"}),supabaseSelect<any>("Product",{select:"id,categoryId",isPublished:"eq.true"}),supabaseSelect<any>("ProductSecondaryCategory",{select:"productId,categoryId"})]);const memberships=new Map<string,Set<string>>();for(const product of products){const set=memberships.get(product.categoryId)??new Set<string>();set.add(product.id);memberships.set(product.categoryId,set)}for(const row of secondary){const set=memberships.get(row.categoryId)??new Set<string>();set.add(row.productId);memberships.set(row.categoryId,set)}return categories.map(category=>({...category,_count:{products:memberships.get(category.id)?.size??0}}))}catch(error){console.error("[queries] categories Data API read failed",error);return[]}}
export async function getCategoryBySlug(slug:string){try{const rows=await supabaseSelect<any>("Category",{select:"*",slug:`eq.${slug}`,isPublished:"eq.true",limit:"1"});return rows[0]??null}catch(error){console.error("[queries] category Data API read failed",error);return null}}
export async function getCatalogFacets(){try{const[brands,terms]=await Promise.all([supabaseSelect<any>("Brand",{select:"id,name,slug",isPublished:"eq.true",order:"name.asc"}),supabaseSelect<any>("TaxonomyTerm",{select:"id,dimension,slug,nameFa,nameTr,nameEn,nameAr",isPublished:"eq.true",order:"dimension.asc,sortOrder.asc"})]);return{brands,terms}}catch(error){console.error("[queries] catalog facets read failed",error);return{brands:[],terms:[]}}}
export async function getShopFilterState(){const c=await cookies();return{brandId:c.get("hd_shop_brand")?.value||"",termIds:(c.get("hd_shop_taxonomy")?.value||"").split(",").filter(Boolean).slice(0,12)}}
export type ProductSort="newest"|"price-asc"|"price-desc";
export async function getProducts(opts:{categorySlug?:string;sort?:ProductSort;search?:string;ignoreCatalogFilters?:boolean}={}){const{categorySlug,sort="newest",search,ignoreCatalogFilters=false}=opts,q=search?.trim().toLocaleLowerCase();try{let categoryId:string|undefined;if(categorySlug){const category=await getCategoryBySlug(categorySlug);if(!category)return[];categoryId=category.id}let products=await supabaseSelect<any>("Product",{select:"*",isPublished:"eq.true"});if(categoryId){const secondary=await supabaseSelect<any>("ProductSecondaryCategory",{select:"productId",categoryId:`eq.${categoryId}`});const secondaryIds=new Set(secondary.map(r=>r.productId));products=products.filter(p=>p.categoryId===categoryId||secondaryIds.has(p.id))}if(!ignoreCatalogFilters){const filters=await getShopFilterState();if(filters.brandId)products=products.filter(p=>p.brandId===filters.brandId);if(filters.termIds.length){const links=await supabaseSelect<any>("ProductTaxonomy",{select:"productId,termId",termId:inFilter(filters.termIds)}),byProduct=new Map<string,Set<string>>();for(const link of links){const set=byProduct.get(link.productId)??new Set<string>();set.add(link.termId);byProduct.set(link.productId,set)}products=products.filter(p=>filters.termIds.every(id=>byProduct.get(p.id)?.has(id)))}}const hydrated=await hydrateProducts(products);products=q?hydrated.filter(product=>[product.nameFa,product.nameTr,product.nameEn,product.nameAr,product.brandEntity?.name,product.modelNumber,product.sku].some(value=>String(value??"").toLocaleLowerCase().includes(q))):hydrated;products.sort((a,b)=>sort==="price-asc"?a.price-b.price:sort==="price-desc"?b.price-a.price:new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());return products}catch(error){console.error("[queries] products Data API read failed",error);return[]}}
export async function getFeaturedProducts(take=8){try{const products=await supabaseSelect<any>("Product",{select:"*",isPublished:"eq.true",isFeatured:"eq.true"});products.sort((a,b)=>a.isNewArrival!==b.isNewArrival?(a.isNewArrival?-1:1):new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());return await hydrateProducts(products.slice(0,take))}catch(error){console.error("[queries] featured products Data API read failed",error);return[]}}
export async function getProductBySlug(slug:string){try{const rows=await supabaseSelect<any>("Product",{select:"*",slug:`eq.${slug}`,isPublished:"eq.true",limit:"1"}),product=rows[0];if(!product)return null;const[hydrated]=await hydrateProducts([product]);const[variants,reviews,taxonomy]=await Promise.all([supabaseSelect<any>("ProductVariant",{select:"*",productId:`eq.${product.id}`,isPublished:"eq.true",order:"createdAt.asc"}),supabaseSelect<any>("Review",{select:"*",productId:`eq.${product.id}`,status:"eq.APPROVED",order:"createdAt.desc",limit:"12"}),supabaseSelect<any>("ProductTaxonomy",{select:"termId",productId:`eq.${product.id}`})]);let taxonomyTerms:any[]=[];const termIds=taxonomy.map(x=>x.termId);if(termIds.length)taxonomyTerms=await supabaseSelect<any>("TaxonomyTerm",{select:"*",id:inFilter(termIds),isPublished:"eq.true",order:"sortOrder.asc"});return{...hydrated,variants,reviews,taxonomyTerms}}catch(error){console.error("[queries] product Data API read failed",error);return null}}
export async function getRelatedProducts(categoryId:string,excludeId:string,take=4){try{let products=await supabaseSelect<any>("Product",{select:"*",isPublished:"eq.true"});const secondary=await supabaseSelect<any>("ProductSecondaryCategory",{select:"productId",categoryId:`eq.${categoryId}`}),ids=new Set(secondary.map(r=>r.productId));products=products.filter(p=>p.id!==excludeId&&(p.categoryId===categoryId||ids.has(p.id)));products.sort((a,b)=>a.isFeatured!==b.isFeatured?(a.isFeatured?-1:1):new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());return await hydrateProducts(products.slice(0,take))}catch(error){console.error("[queries] related products Data API read failed",error);return[]}}
export async function getServices(){try{return await supabaseSelect<any>("Service",{select:"*",isPublished:"eq.true",order:"createdAt.asc"})}catch(error){console.error("[queries] services Data API read failed",error);return[]}}
export async function getServiceBySlug(slug:string){try{const rows=await supabaseSelect<any>("Service",{select:"*",slug:`eq.${slug}`,isPublished:"eq.true",limit:"1"});return rows[0]??null}catch(error){console.error("[queries] service Data API read failed",error);return null}}
export async function getPageBySlug(slug:string){try{const rows=await supabaseSelect<any>("Page",{select:"*",slug:`eq.${slug}`,isPublished:"eq.true",limit:"1"});return rows[0]??null}catch(error){console.error("[queries] page Data API read failed",error);return null}}
function articleIsPublic(article:any,now=Date.now()){if(!article?.isPublished)return false;if(!article.publishedAt)return true;const publishedAt=new Date(article.publishedAt).getTime();return Number.isFinite(publishedAt)&&publishedAt<=now}
export async function getPublishedArticles(take=12){try{const articles=await supabaseSelect<any>("Article",{select:"*",isPublished:"eq.true",order:"publishedAt.desc,createdAt.desc"});return articles.filter(article=>articleIsPublic(article)).slice(0,take)}catch(error){console.error("[queries] articles Data API read failed",error);return[]}}
export async function getArticleBySlug(slug:string){try{const rows=await supabaseSelect<any>("Article",{select:"*",slug:`eq.${slug}`,isPublished:"eq.true",limit:"1"}),article=rows[0]??null;return articleIsPublic(article)?article:null}catch(error){console.error("[queries] article Data API read failed",error);return null}}
