import Link from "next/link";
import { BadgeDollarSign, ChevronLeft, ChevronRight } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import type { AdminLocale } from "@/lib/admin-i18n";
import { saveRentalPolicy } from "./actions";

type Row={id:string;sku:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;brandName?:string|null;rentalEligible:boolean;availableUnits:number;dailyRate?:number|null;weeklyRate?:number|null;monthlyRate?:number|null;depositAmount?:number|null;currency:string;minDays:number;maxDays?:number|null;isActive:boolean};
const C:Record<AdminLocale,Record<string,string>>={fa:{title:"سیاست‌های اجاره",sub:"قیمت، ودیعه، ظرفیت و مدت مجاز اجاره هر محصول را مدیریت کنید.",back:"درخواست‌های اجاره",saved:"ذخیره شد.",units:"واحد قابل اجاره",daily:"نرخ روزانه",weekly:"نرخ هفتگی",monthly:"نرخ ماهانه",deposit:"ودیعه",currency:"ارز",min:"حداقل روز",max:"حداکثر روز",active:"فعال",save:"ذخیره سیاست",empty:"هیچ محصولی به‌عنوان قابل اجاره علامت‌گذاری نشده است."},en:{title:"Rental policies",sub:"Manage pricing, deposit, capacity and allowed duration for each rental product.",back:"Rental requests",saved:"Saved.",units:"Available units",daily:"Daily rate",weekly:"Weekly rate",monthly:"Monthly rate",deposit:"Deposit",currency:"Currency",min:"Min days",max:"Max days",active:"Active",save:"Save policy",empty:"No products are marked rental eligible."},tr:{title:"Kiralama politikaları",sub:"Her kiralık ürün için fiyat, depozito, kapasite ve süreyi yönetin.",back:"Kiralama talepleri",saved:"Kaydedildi.",units:"Kullanılabilir adet",daily:"Günlük ücret",weekly:"Haftalık ücret",monthly:"Aylık ücret",deposit:"Depozito",currency:"Para birimi",min:"Min gün",max:"Maks gün",active:"Aktif",save:"Politikayı kaydet",empty:"Kiralama uygun ürünü yok."},ar:{title:"سياسات الإيجار",sub:"إدارة السعر والوديعة والسعة والمدة المسموحة لكل منتج.",back:"طلبات الإيجار",saved:"تم الحفظ.",units:"الوحدات المتاحة",daily:"السعر اليومي",weekly:"السعر الأسبوعي",monthly:"السعر الشهري",deposit:"الوديعة",currency:"العملة",min:"الحد الأدنى للأيام",max:"الحد الأقصى للأيام",active:"نشط",save:"حفظ السياسة",empty:"لا توجد منتجات محددة كقابلة للإيجار."}};
function name(r:Row,l:AdminLocale){return({fa:r.nameFa,tr:r.nameTr,en:r.nameEn,ar:r.nameAr}[l]||r.nameEn||r.nameFa||r.sku)}
export default async function Page({searchParams}:{searchParams:Promise<{saved?:string}>}){const sp=await searchParams,[locale,rows]=await Promise.all([currentAdminLocale(),adminRpc<Row[]>("admin_rental_policies",{})]);const t=C[locale],Arrow=locale==="fa"||locale==="ar"?ChevronRight:ChevronLeft;return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="flex items-center gap-2 text-3xl font-black text-[#001736]"><BadgeDollarSign className="h-7 w-7 text-[#009dd8]"/>{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.sub}</p></div><Link href="/admin/rentals" className="inline-flex min-h-10 items-center gap-2 rounded-xl border bg-white px-4 text-xs font-black"><Arrow className="h-4 w-4"/>{t.back}</Link></header>{sp.saved?<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-800">{t.saved}</div>:null}{rows.length?<div className="grid gap-4 xl:grid-cols-2">{rows.map(r=><form key={r.id} action={saveRentalPolicy} className="rounded-3xl border bg-white p-5 shadow-sm"><input type="hidden" name="productId" value={r.id}/><div><h2 className="font-black text-[#001736]">{name(r,locale)}</h2><p className="mt-1 text-xs text-[#747780]">{r.brandName||"—"} · <span dir="ltr">{r.sku}</span></p></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><F n="availableUnits" l={t.units} v={r.availableUnits} min="0"/><F n="dailyRate" l={t.daily} v={r.dailyRate}/><F n="weeklyRate" l={t.weekly} v={r.weeklyRate}/><F n="monthlyRate" l={t.monthly} v={r.monthlyRate}/><F n="depositAmount" l={t.deposit} v={r.depositAmount}/><label className="text-xs font-black">{t.currency}<input name="currency" defaultValue={r.currency||"IRR"} maxLength={8} dir="ltr" className="mt-2 h-11 w-full rounded-xl border px-3"/></label><F n="minDays" l={t.min} v={r.minDays} min="1"/><F n="maxDays" l={t.max} v={r.maxDays} min="1"/><label className="flex min-h-11 items-center gap-2 self-end rounded-xl border px-3 text-xs font-black"><input type="checkbox" name="isActive" defaultChecked={r.isActive}/>{t.active}</label></div><button className="mt-5 min-h-11 rounded-xl bg-[#ba0036] px-5 text-xs font-black text-white">{t.save}</button></form>)}</div>:<div className="rounded-3xl border border-dashed bg-white p-10 text-center text-sm font-bold text-[#747780]">{t.empty}</div>}</div>}
function F({n,l,v,min="0"}:{n:string;l:string;v:number|null|undefined;min?:string}){return <label className="text-xs font-black">{l}<input name={n} type="number" min={min} defaultValue={v??""} className="mt-2 h-11 w-full rounded-xl border px-3"/></label>}
