import { getLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { BadgeCheck, Headphones, ShieldCheck, Wrench } from "lucide-react";
import { Container } from "@/components/ui/container";
import { WarrantyForm } from "@/components/site/warranty-form";
import { getProducts } from "@/lib/queries";
import { customerRpc, getCustomerSession } from "@/lib/customer-auth";

const HERO_IMAGE="https://lh3.googleusercontent.com/aida/AEtjO1U1Zzri1WAPPMaApZwWUjBtEJW5tGj5LaUw6tMiH5OTgSYg8ZfC4gJTbkxWExkAYdo8Ut5lmTeyjYP4hCyF80ZFXKpNPsLqMrvI1e8xxrMV3W3pTwzZIwRkH28eyFZsAcTSKYVihv1z2qxCiHZlLj0IiOrUCKbiD3B7iaN_FLz4zPvLuAg2hZrJ2gvgqG1RGfzce79WnG0OA6gwCRMZ8PXjXsrId6L-BN0_e8LSABBuzpopv_4NLQnNiPVC";
type Device={id:string;serialNumber:string;status:string;startsAt:string;expiresAt:string;productNameFa?:string|null;productNameEn?:string|null;brand?:string|null;modelNumber?:string|null};type Club={devices:Device[]};
const pick=(locale:string,fa:string,en:string,tr:string,ar:string)=>locale==="en"?en:locale==="tr"?tr:locale==="ar"?ar:fa;
export default async function WarrantyPage(){
 const [locale,products,session]=await Promise.all([getLocale(),getProducts(),getCustomerSession()]); let devices:Device[]=[];if(session){try{devices=(await customerRpc<Club>("customer_club_dashboard")).devices||[]}catch{devices=[]}}
 const c={eyebrow:pick(locale,"تضمین کیفیت سطح بالینی","Clinical-grade quality assurance","Klinik düzey kalite güvencesi","ضمان جودة بمستوى سريري"),title:pick(locale,"پورتال گارانتی و خدمات پس از فروش","Warranty & after-sales portal","Garanti ve satış sonrası portalı","بوابة الضمان وخدمات ما بعد البيع"),body:pick(locale,"ثبت و فعال‌سازی گارانتی، مشاهده وضعیت تجهیزات و هدایت درخواست تعمیر یا سرویس در یک مسیر قابل پیگیری.","Register warranty, review device coverage and route repair/service requests through one traceable workflow.","Garanti kaydı, cihaz kapsamı ve servis taleplerini tek izlenebilir akışta yönetin.","سجل الضمان وتحقق من تغطية الأجهزة ووجّه طلبات الصيانة عبر مسار قابل للتتبع."),service:pick(locale,"درخواست خدمات (RMA)","Request service (RMA)","Servis talebi (RMA)","طلب خدمة (RMA)"),warrantyTitle:pick(locale,"ثبت و فعال‌سازی گارانتی","Register & activate warranty","Garanti kaydı ve aktivasyonu","تسجيل وتفعيل الضمان"),warrantyBody:pick(locale,"مدت پوشش از اطلاعات واقعی محصول خوانده می‌شود و شناسه امن برای پیگیری ایجاد می‌گردد.","Coverage comes from the real product record and a secure tracking identifier is created.","Kapsam gerçek ürün kaydından alınır ve güvenli takip kimliği oluşturulur.","تؤخذ مدة التغطية من سجل المنتج الحقيقي ويتم إنشاء معرف تتبع آمن."),register:pick(locale,"ثبت گارانتی","Register warranty","Garanti kaydı","تسجيل الضمان"),status:pick(locale,"استعلام گارانتی","Check warranty","Garanti sorgula","التحقق من الضمان"),myDevices:pick(locale,"وضعیت دستگاه‌های شما","Your registered devices","Kayıtlı cihazlarınız","أجهزتك المسجلة"),login:pick(locale,"برای مشاهده دستگاه‌های ثبت‌شده وارد حساب شوید","Sign in to view registered devices","Kayıtlı cihazları görmek için giriş yapın","سجل الدخول لعرض الأجهزة المسجلة")};
 return <main className="flex-1 bg-[#f4f7fb]"><section className="relative min-h-[560px] overflow-hidden bg-[#07305d] text-white"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:`url(${HERO_IMAGE})`}}/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(1,39,79,.93)_0%,rgba(1,39,79,.76)_48%,rgba(1,39,79,.55)_100%)] rtl:bg-[linear-gradient(270deg,rgba(1,39,79,.93)_0%,rgba(1,39,79,.76)_48%,rgba(1,39,79,.55)_100%)]"/><Container className="relative z-10 grid min-h-[560px] items-center gap-10 py-12 lg:grid-cols-[.8fr_1.2fr]"><div className="order-2 lg:order-1"><div className="rounded-3xl bg-white/90 p-7 text-[#001736] shadow-[0_24px_60px_rgba(0,0,0,.18)] backdrop-blur-md"><div className="flex items-start gap-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-[#001736] text-white"><ShieldCheck className="h-6 w-6"/></span><div><h2 className="text-2xl font-black">{c.warrantyTitle}</h2><p className="mt-3 text-sm leading-7 text-[#4f5965]">{c.warrantyBody}</p></div></div><div className="mt-6 flex flex-wrap gap-3"><a href="#register" className="rounded-xl bg-[#001736] px-5 py-3 text-xs font-black text-white">{c.register}</a><Link href="/warranty/status" className="rounded-xl border border-[#c4c6d0] bg-white px-5 py-3 text-xs font-black text-[#001736]">{c.status}</Link></div></div></div><div className="order-1 lg:order-2"><span className="inline-flex rounded-full border border-[#33c8ff]/30 bg-[#009dd8]/15 px-4 py-2 text-xs font-black text-[#9bdcff]">{c.eyebrow}</span><h1 className="mt-6 text-4xl font-black leading-[1.3] sm:text-6xl">{c.title}</h1><p className="mt-5 max-w-2xl text-sm leading-8 text-white/78 sm:text-base">{c.body}</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/support#new-ticket" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#009dd8] px-5 text-sm font-black text-white"><Wrench className="h-4 w-4"/>{c.service}</Link><Link href="/contact" className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/30 bg-white/8 px-5 text-sm font-black text-white"><Headphones className="h-4 w-4"/>{pick(locale,"پشتیبانی","Support","Destek","الدعم")}</Link></div></div></Container></section>
 <section className="py-10"><Container><div className="rounded-[2rem] border border-white bg-white p-6 shadow-[0_18px_50px_rgba(0,23,54,.055)] sm:p-8"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><BadgeCheck className="h-6 w-6 text-[#009dd8]"/><h2 className="text-2xl font-black text-[#001736]">{c.myDevices}</h2></div>{session?<Link href="/account" className="text-xs font-black text-[#ba0036]">{pick(locale,"پنل کاربری","Customer portal","Müşteri portalı","بوابة العميل")}</Link>:null}</div>{session?<div className="mt-6 space-y-3">{devices.map(d=><div key={d.id} className="rounded-2xl border border-[#dfe4ea] bg-[#f9fbfd] p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h3 className="font-black text-[#001736]">{locale==="fa"?(d.productNameFa||d.productNameEn):(d.productNameEn||d.productNameFa)}</h3><div className="mt-1 text-xs text-[#747780]">{[d.brand,d.modelNumber].filter(Boolean).join(" · ")}</div><div className="mt-2 font-mono text-xs text-[#5f6570]" dir="ltr">SN: {d.serialNumber}</div></div><div className="sm:text-end"><span className="rounded-full bg-emerald-50 px-3 py-1 text-[11px] font-black text-emerald-700">{d.status}</span><div className="mt-2 text-xs text-[#747780]">{pick(locale,"پوشش تا","Coverage to","Kapsam sonu","التغطية حتى")} {new Date(d.expiresAt).toLocaleDateString(locale)}</div></div></div></div>)}{!devices.length?<div className="rounded-2xl border border-dashed border-[#c4c6d0] p-8 text-center text-sm text-[#747780]">{pick(locale,"هنوز دستگاهی با گارانتی به حساب شما متصل نشده است.","No warranty device is linked to your account yet.","Hesabınıza bağlı garanti cihazı yok.","لا يوجد جهاز ضمان مرتبط بحسابك بعد.")}</div>:null}</div>:<div className="mt-6 rounded-2xl border border-dashed border-[#c4c6d0] bg-[#f9fbfd] p-8 text-center"><p className="text-sm text-[#5f6570]">{c.login}</p><Link href="/account/login" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-[#001736] px-5 text-xs font-black text-white">{pick(locale,"ورود","Sign in","Giriş","دخول")}</Link></div>}</div></Container></section>
 <section id="register" className="scroll-mt-28 pb-14"><Container><div className="mb-6 flex items-center gap-3"><BadgeCheck className="h-6 w-6 text-[#009dd8]"/><h2 className="text-2xl font-black text-[#001736]">{c.register}</h2></div><WarrantyForm products={products.map((p:any)=>({id:p.id,nameFa:p.nameFa,nameTr:p.nameTr,nameEn:p.nameEn,nameAr:p.nameAr,warrantyMonths:p.warrantyMonths}))}/></Container></section></main>;
}
