import { getLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { BadgeCheck, CalendarCheck2, Headphones, LifeBuoy, ShieldCheck, Wrench } from "lucide-react";
import { Container } from "@/components/ui/container";
import { WarrantyForm } from "@/components/site/warranty-form";
import { getProducts } from "@/lib/queries";

export default async function WarrantyPage() {
  const [locale, products] = await Promise.all([getLocale(), getProducts()]);
  const copy = locale === "fa"
    ? { eyebrow:"Hyper Doctor After-Sales", title:"پشتیبانی بی‌وقفه برای تجهیزات حیاتی", body:"گارانتی و خدمات پس از فروش Hyper Doctor برای ثبت شفاف محصول، پیگیری دوره پوشش و هدایت سریع درخواست‌های سرویس طراحی شده است.", register:"ثبت گارانتی", status:"استعلام گارانتی", service:"درخواست سرویس", values:[["گارانتی بر پایه اطلاعات واقعی محصول","مدت پوشش از همان محصول ثبت‌شده در کاتالوگ خوانده می‌شود و تاریخ پایان به‌صورت خودکار محاسبه می‌شود.","shield"],["پیگیری امن","برای هر ثبت گارانتی یک شناسه امن ساخته می‌شود تا وضعیت بدون افشای اطلاعات سایر مشتریان قابل بررسی باشد.","calendar"],["اتصال به پشتیبانی","در صورت نیاز به تعمیر یا سرویس می‌توانید مستقیماً از مرکز پشتیبانی تیکت ثبت کنید.","support"]] }
    : locale === "tr"
      ? { eyebrow:"Hyper Doctor After-Sales", title:"Kritik cihazlar için kesintisiz destek", body:"Hyper Doctor garanti ve satış sonrası merkezi, ürün kaydını, kapsam süresini ve servis yönlendirmesini şeffaf biçimde yönetir.", register:"Garanti kaydı", status:"Garanti sorgula", service:"Servis talebi", values:[["Gerçek ürün verisine dayalı garanti","Kapsam süresi katalogdaki gerçek ürün kaydından alınır ve bitiş tarihi otomatik hesaplanır.","shield"],["Güvenli takip","Her garanti kaydı için özel güvenli kimlik oluşturulur.","calendar"],["Destek bağlantısı","Onarım veya servis için doğrudan destek talebi oluşturabilirsiniz.","support"]] }
      : locale === "ar"
        ? { eyebrow:"Hyper Doctor After-Sales", title:"دعم مستمر للمعدات الحيوية", body:"يوفر مركز الضمان وما بعد البيع تسجيلاً شفافاً للمنتج ومتابعة مدة التغطية وربطاً سريعاً بخدمات الصيانة.", register:"تسجيل الضمان", status:"التحقق من الضمان", service:"طلب صيانة", values:[["ضمان مبني على بيانات المنتج الفعلية","تُقرأ مدة التغطية من سجل المنتج الحقيقي ويتم حساب تاريخ الانتهاء تلقائياً.","shield"],["متابعة آمنة","يتم إنشاء معرف آمن خاص لكل تسجيل ضمان.","calendar"],["الربط بالدعم","يمكن تسجيل تذكرة صيانة أو إصلاح مباشرة من مركز الدعم.","support"]] }
        : { eyebrow:"Hyper Doctor After-Sales", title:"Continuous support for critical equipment", body:"Hyper Doctor warranty and after-sales workflows provide transparent product registration, coverage tracking and direct routing to service support.", register:"Register warranty", status:"Check warranty", service:"Request service", values:[["Warranty from real product data","Coverage duration is read from the actual catalog record and expiry is calculated automatically.","shield"],["Secure tracking","Each warranty registration receives a private tracking identifier.","calendar"],["Connected support","Create a technical service or repair ticket directly from the support center.","support"]] };

  const icon = (key:string) => key === "shield" ? ShieldCheck : key === "calendar" ? CalendarCheck2 : Headphones;

  return <main className="flex-1 bg-[#f5f8fb] pb-16 pt-6 sm:pt-10"><Container>
    <section className="relative overflow-hidden rounded-[2rem] bg-[#001736] px-6 py-11 text-white shadow-[0_24px_65px_rgba(0,23,54,.17)] sm:px-10 lg:px-14 lg:py-14"><div className="absolute inset-y-0 end-0 w-1/2 bg-[radial-gradient(circle_at_center,rgba(0,157,216,.28),transparent_60%)]"/><div className="relative z-10 max-w-3xl"><BadgeCheck className="h-8 w-8 text-[#82cfff]"/><p className="mt-5 text-xs font-black uppercase tracking-[.18em] text-[#82cfff]">{copy.eyebrow}</p><h1 className="mt-3 text-3xl font-black leading-[1.35] sm:text-5xl">{copy.title}</h1><p className="mt-5 max-w-2xl text-sm leading-8 text-[#d6e3ff]/85 sm:text-base">{copy.body}</p><div className="mt-7 flex flex-wrap gap-3"><a href="#register" className="inline-flex min-h-12 items-center rounded-2xl bg-[#ba0036] px-5 text-sm font-black text-white">{copy.register}</a><Link href="/warranty/status" className="inline-flex min-h-12 items-center rounded-2xl border border-white/25 bg-white/10 px-5 text-sm font-black text-white backdrop-blur">{copy.status}</Link><Link href="/support" className="inline-flex min-h-12 items-center gap-2 rounded-2xl border border-white/25 bg-white/10 px-5 text-sm font-black text-white backdrop-blur"><Wrench className="h-4 w-4"/>{copy.service}</Link></div></div></section>
    <section className="py-8 sm:py-10"><div className="grid gap-4 md:grid-cols-3">{copy.values.map(([title,body,key])=>{const Icon=icon(key);return <article key={title} className="rounded-3xl border border-[#dfe4ea] bg-white p-6 shadow-[0_14px_38px_rgba(0,23,54,.045)]"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#d6e3ff] text-[#002b5b]"><Icon className="h-5 w-5"/></span><h2 className="mt-5 text-lg font-black text-[#001736]">{title}</h2><p className="mt-3 text-sm leading-7 text-[#5f6570]">{body}</p></article>})}</div></section>
    <section id="register" className="scroll-mt-28"><WarrantyForm products={products.map((p:any)=>({id:p.id,nameFa:p.nameFa,nameTr:p.nameTr,nameEn:p.nameEn,nameAr:p.nameAr,warrantyMonths:p.warrantyMonths}))}/></section>
    <section className="mt-8 rounded-3xl bg-[#001736] px-6 py-7 text-white sm:px-9"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><LifeBuoy className="h-6 w-6 text-[#82cfff]"/><p className="mt-3 text-sm font-black">Hyper Doctor Warranty & Technical Care</p></div><Link href="/support" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-xs font-black text-[#001736]"><Wrench className="h-4 w-4"/>{copy.service}</Link></div></section>
  </Container></main>;
}
