import Link from "next/link";
import {CheckCircle2,FileCheck2,ShieldAlert} from "lucide-react";
import {adminRpc} from "@/lib/admin-data";
import {currentAdminLocale} from "@/lib/admin-locale-server";
import type {AdminLocale} from "@/lib/admin-i18n";

type Verify={documentType:"CONTRACT"|"SETTLEMENT";version:number;storedSha256:string;actualSha256:string;valid:boolean;createdAt:string};
const pick=(l:AdminLocale,fa:string,en:string,tr:string,ar:string)=>l==="fa"?fa:l==="tr"?tr:l==="ar"?ar:en;
export default async function Page({params}:{params:Promise<{id:string}>}){const{id}=await params;const[l,contract,settlement]=await Promise.all([currentAdminLocale(),adminRpc<Verify|null>("admin_rental_document_verify",{p_rental_request_id:id,p_document_type:"CONTRACT"}),adminRpc<Verify|null>("admin_rental_document_verify",{p_rental_request_id:id,p_document_type:"SETTLEMENT"})]);const title=pick(l,"اعتبارسنجی اسناد اجاره","Rental document integrity","Kiralama belge bütünlüğü","سلامة مستندات الإيجار"),sub=pick(l,"Hash ذخیره‌شده با محتوای Snapshot دوباره محاسبه و مقایسه می‌شود. سند معتبر یعنی Snapshot تاریخی بدون تغییر باقی مانده است.","The stored hash is recomputed from the snapshot and compared again. A valid result means the historical snapshot is unchanged.","Kayıtlı hash, anlık görüntüden yeniden hesaplanır ve karşılaştırılır. Geçerli sonuç tarihsel kaydın değişmediğini gösterir.","تتم إعادة حساب التجزئة من اللقطة ومقارنتها. النتيجة الصالحة تعني أن اللقطة التاريخية لم تتغير."),back=pick(l,"بازگشت به چرخه اجاره","Back to rental lifecycle","Kiralama döngüsüne dön","العودة إلى دورة الإيجار"),contractTitle=pick(l,"قرارداد تحویل","Handover contract","Teslim sözleşmesi","عقد التسليم"),settlementTitle=pick(l,"گزارش تسویه نهایی","Final settlement report","Nihai uzlaşma raporu","تقرير التسوية النهائية");return <div className="mx-auto max-w-5xl space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#009dd8]">IMMUTABLE DOCUMENTS</p><h1 className="mt-2 flex items-center gap-2 text-3xl font-black text-[#001736]"><FileCheck2 className="h-7 w-7"/>{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#747780]">{sub}</p></div><Link href={`/admin/rentals/${id}/lifecycle`} className="rounded-xl border bg-white px-4 py-2 text-xs font-black text-[#001736]">{back}</Link></header><div className="grid gap-5 lg:grid-cols-2"><DocCard locale={l} title={contractTitle} data={contract} href={`/admin/rentals/${id}/contract`}/><DocCard locale={l} title={settlementTitle} data={settlement} href={`/admin/rentals/${id}/return-report`}/></div></div>}
function DocCard({locale,title,data,href}:{locale:AdminLocale;title:string;data:Verify|null;href:string}){const noDoc=pick(locale,"هنوز Snapshot نهایی ایجاد نشده است.","No final snapshot exists yet.","Henüz nihai anlık görüntü yok.","لم يتم إنشاء لقطة نهائية بعد."),valid=pick(locale,"Hash معتبر است","Hash verified","Hash doğrulandı","تم التحقق من التجزئة"),invalid=pick(locale,"مغایرت Hash — نیازمند بررسی فوری","Hash mismatch — immediate review required","Hash uyuşmazlığı — acil inceleme gerekli","اختلاف في التجزئة — يلزم فحص فوري"),open=pick(locale,"مشاهده سند","Open document","Belgeyi aç","فتح المستند"),version=pick(locale,"نسخه","Version","Sürüm","الإصدار"),stored=pick(locale,"SHA-256 ذخیره‌شده","Stored SHA-256","Kayıtlı SHA-256","SHA-256 المخزن"),actual=pick(locale,"SHA-256 محاسبه‌شده","Recomputed SHA-256","Yeniden hesaplanan SHA-256","SHA-256 المعاد حسابه");return <article className={`rounded-2xl border bg-white p-5 shadow-sm ${data&&!data.valid?"border-red-300":""}`}><h2 className="font-black text-[#001736]">{title}</h2>{!data?<p className="mt-4 rounded-xl border border-dashed p-4 text-sm font-bold text-[#747780]">{noDoc}</p>:<><div className={`mt-4 flex items-center gap-2 rounded-xl p-3 text-sm font-black ${data.valid?"bg-emerald-50 text-emerald-800":"bg-red-50 text-red-800"}`}>{data.valid?<CheckCircle2 className="h-5 w-5"/>:<ShieldAlert className="h-5 w-5"/>}{data.valid?valid:invalid}</div><dl className="mt-4 space-y-3 text-xs"><Row label={version} value={String(data.version)}/><Row label={stored} value={data.storedSha256}/><Row label={actual} value={data.actualSha256}/></dl><Link href={href} className="mt-5 inline-flex rounded-xl border border-[#b9dff0] bg-[#f4fbff] px-4 py-2 text-xs font-black text-[#002b5b]">{open}</Link></>}</article>}
function Row({label,value}:{label:string;value:string}){return <div><dt className="font-black text-[#747780]">{label}</dt><dd className="mt-1 break-all font-mono text-[11px] text-[#001736]" dir="ltr">{value}</dd></div>}
