import { Mail, Phone, Search, ShieldCheck, UserRound, UsersRound, WalletCards } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminCurrency, adminDate, adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { updateCustomer } from "./actions";

type Customer={id:string;fullName:string;email?:string|null;phone?:string|null;locale:string;isActive:boolean;marketingConsent:boolean;createdAt:string;orderCount:number;lifetimeValue:number};
const c:Record<AdminLocale,Record<string,string>>={
  fa:{eyebrow:"مدیریت ارتباط با مشتری",title:"مدیریت کاربران",subtitle:"وضعیت حساب، ارزش خرید و اطلاعات تماس مشتریان",shown:"کاربران نمایش‌داده‌شده",active:"حساب فعال",value:"ارزش خرید",searchPlaceholder:"جستجو با نام، موبایل یا ایمیل...",search:"جستجو",user:"کاربر",contact:"تماس",orders:"سفارش",purchaseValue:"ارزش خرید",joined:"عضویت",status:"وضعیت",manage:"مدیریت",unnamed:"بدون نام",activeStatus:"فعال",inactiveStatus:"غیرفعال",accountActive:"حساب فعال",marketing:"رضایت بازاریابی",save:"ذخیره",empty:"کاربری با این معیار پیدا نشد."},
  ar:{eyebrow:"إدارة علاقات العملاء",title:"إدارة العملاء",subtitle:"حالة الحساب وقيمة المشتريات ومعلومات الاتصال بالعملاء",shown:"العملاء المعروضون",active:"حسابات نشطة",value:"قيمة المشتريات",searchPlaceholder:"ابحث بالاسم أو الهاتف أو البريد الإلكتروني...",search:"بحث",user:"العميل",contact:"الاتصال",orders:"الطلبات",purchaseValue:"قيمة المشتريات",joined:"تاريخ الانضمام",status:"الحالة",manage:"الإدارة",unnamed:"بدون اسم",activeStatus:"نشط",inactiveStatus:"غير نشط",accountActive:"الحساب نشط",marketing:"موافقة التسويق",save:"حفظ",empty:"لم يتم العثور على عميل مطابق."},
  en:{eyebrow:"Customer CRM",title:"Customer management",subtitle:"Manage customer account status, purchase value and contact details",shown:"Customers shown",active:"Active accounts",value:"Purchase value",searchPlaceholder:"Search by name, phone or email...",search:"Search",user:"Customer",contact:"Contact",orders:"Orders",purchaseValue:"Purchase value",joined:"Joined",status:"Status",manage:"Manage",unnamed:"Unnamed",activeStatus:"Active",inactiveStatus:"Inactive",accountActive:"Active account",marketing:"Marketing consent",save:"Save",empty:"No customer matched these criteria."},
  tr:{eyebrow:"Müşteri CRM",title:"Müşteri yönetimi",subtitle:"Müşteri hesap durumu, satın alma değeri ve iletişim bilgilerini yönetin",shown:"Gösterilen müşteriler",active:"Aktif hesaplar",value:"Satın alma değeri",searchPlaceholder:"Ad, telefon veya e-posta ile ara...",search:"Ara",user:"Müşteri",contact:"İletişim",orders:"Sipariş",purchaseValue:"Satın alma değeri",joined:"Üyelik",status:"Durum",manage:"Yönetim",unnamed:"İsimsiz",activeStatus:"Aktif",inactiveStatus:"Pasif",accountActive:"Aktif hesap",marketing:"Pazarlama izni",save:"Kaydet",empty:"Bu kriterlere uyan müşteri bulunamadı."}
};

export default async function AdminCustomersPage({searchParams}:{searchParams:Promise<{q?:string}>}){
  const {q=""}=await searchParams;
  const [customers,l]=await Promise.all([adminRpc<Customer[]>("admin_customers",{p_search:q}),currentAdminLocale()]);
  const t=c[l];
  const active=customers.filter(c=>c.isActive).length;
  const totalValue=customers.reduce((a,c)=>a+c.lifetimeValue,0);
  return <div className="mx-auto max-w-[1450px] space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.subtitle}</p></div></div>
    <div className="grid gap-4 md:grid-cols-3"><Metric label={t.shown} value={adminNumber(customers.length,l)} icon={UsersRound}/><Metric label={t.active} value={adminNumber(active,l)} icon={ShieldCheck}/><Metric label={t.value} value={`${adminNumber(totalValue,l)} ${adminCurrency[l]}`} icon={WalletCards}/></div>
    <form className="flex gap-3 rounded-[1.5rem] border border-[#e2e6eb] bg-white p-4 shadow-sm"><label className="relative flex-1"><Search className="pointer-events-none absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9a9da5]"/><input name="q" defaultValue={q} placeholder={t.searchPlaceholder} className="h-11 w-full rounded-xl border border-[#dfe4ea] bg-[#f7fafd] ps-11 pe-4 text-sm outline-none focus:border-[#009dd8]"/></label><button className="rounded-xl bg-[#001736] px-5 text-xs font-black text-white">{t.search}</button></form>
    <section className="overflow-hidden rounded-[1.6rem] border border-[#e2e6eb] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-[#f7fafd] text-[11px] font-black text-[#747780]"><tr><th className="px-5 py-3 text-start">{t.user}</th><th className="px-5 py-3 text-start">{t.contact}</th><th className="px-5 py-3 text-start">{t.orders}</th><th className="px-5 py-3 text-start">{t.purchaseValue}</th><th className="px-5 py-3 text-start">{t.joined}</th><th className="px-5 py-3 text-start">{t.status}</th><th className="px-5 py-3 text-end">{t.manage}</th></tr></thead><tbody className="divide-y divide-[#edf0f2]">{customers.map(cu=>{const action=updateCustomer.bind(null,cu.id);return <tr key={cu.id} className="align-top hover:bg-[#fafcff]"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#edf4ff] text-[#002b5b]"><UserRound className="h-4.5 w-4.5"/></span><div><p className="font-black text-[#001736]">{cu.fullName||t.unnamed}</p><p className="mt-1 text-[10px] font-black uppercase text-[#009dd8]">{cu.locale}</p></div></div></td><td className="px-5 py-4"><div className="space-y-1.5 text-xs text-[#5f6570]">{cu.phone?<p className="flex items-center gap-2"><Phone className="h-3.5 w-3.5"/><span dir="ltr">{cu.phone}</span></p>:null}{cu.email?<p className="flex items-center gap-2"><Mail className="h-3.5 w-3.5"/><span dir="ltr">{cu.email}</span></p>:null}{!cu.phone&&!cu.email?"—":null}</div></td><td className="px-5 py-4 font-black text-[#001736]">{adminNumber(cu.orderCount,l)}</td><td className="px-5 py-4 font-black tabular-nums text-[#001736]">{adminNumber(cu.lifetimeValue,l)} {adminCurrency[l]}</td><td className="px-5 py-4 text-xs text-[#747780]">{adminDate(cu.createdAt,l)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${cu.isActive?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{cu.isActive?t.activeStatus:t.inactiveStatus}</span></td><td className="px-5 py-4"><form action={action} className="ms-auto w-44 space-y-2 rounded-xl border border-[#edf0f2] bg-[#fafcff] p-3 text-[11px]"><label className="flex items-center gap-2"><input type="checkbox" name="isActive" defaultChecked={cu.isActive}/> {t.accountActive}</label><label className="flex items-center gap-2"><input type="checkbox" name="marketingConsent" defaultChecked={cu.marketingConsent}/> {t.marketing}</label><button className="h-8 w-full rounded-lg bg-[#e80346] px-3 font-black text-white">{t.save}</button></form></td></tr>})}{customers.length===0?<tr><td colSpan={7} className="px-5 py-14 text-center text-[#8a8e96]">{t.empty}</td></tr>:null}</tbody></table></div></section>
  </div>;
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof UsersRound}){return <article className="rounded-[1.5rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf4ff] text-[#002b5b]"><Icon className="h-5 w-5"/></span><p className="mt-4 text-xs font-black text-[#747780]">{label}</p><p className="mt-1 text-2xl font-black text-[#001736]">{value}</p></article>}
