import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronLeft, ChevronRight, Layers3, Tags, Network } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { ProductForm } from "@/components/admin/product-form";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import type { AdminLocale } from "@/lib/admin-i18n";
import { setProductBrand } from "../../brands/actions";

type ProductDetail=Parameters<typeof ProductForm>[0]["product"]&{brandId?:string|null;brands?:Array<{id:string;name:string;isPublished:boolean}>;variants?:Array<{id:string}>};
const copy:Record<AdminLocale,Record<string,string>>={fa:{eyebrow:"ویرایشگر کاتالوگ",title:"ویرایش محصول",back:"بازگشت به محصولات",brand:"برند رسمی محصول",brandHelp:"Brand entity مرجع نمایش و جستجوی برند است.",noBrand:"بدون برند",saveBrand:"ثبت برند",variants:"مدیریت Variantها",variantCount:"Variant ثبت‌شده",catalog:"ساختار کاتالوگ",catalogHelp:"برند، دسته‌های ثانویه و طبقه‌بندی چندبعدی"},ar:{eyebrow:"محرر الكتالوج",title:"تعديل المنتج",back:"العودة إلى المنتجات",brand:"العلامة الرسمية للمنتج",brandHelp:"كيان العلامة هو المرجع الأساسي للعرض والبحث.",noBrand:"بدون علامة",saveBrand:"حفظ العلامة",variants:"إدارة التنويعات",variantCount:"تنويع مسجل",catalog:"هيكل الكتالوج",catalogHelp:"العلامة والفئات الثانوية والتصنيف متعدد الأبعاد"},en:{eyebrow:"Catalog editor",title:"Edit product",back:"Back to products",brand:"Canonical product brand",brandHelp:"The Brand entity is the canonical source for display and search.",noBrand:"No brand",saveBrand:"Save brand",variants:"Manage variants",variantCount:"variants registered",catalog:"Catalog structure",catalogHelp:"Brand, secondary categories and multidimensional taxonomy"},tr:{eyebrow:"Katalog düzenleyici",title:"Ürünü düzenle",back:"Ürünlere dön",brand:"Resmi ürün markası",brandHelp:"Marka varlığı gösterim ve arama için tek kaynaktır.",noBrand:"Markasız",saveBrand:"Markayı kaydet",variants:"Varyantları yönet",variantCount:"varyant kayıtlı",catalog:"Katalog yapısı",catalogHelp:"Marka, ikincil kategoriler ve çok boyutlu taksonomi"}};
export default async function EditProductPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const[product,locale]=await Promise.all([adminRpc<ProductDetail|null>("admin_product_detail",{p_id:id}),currentAdminLocale()]);if(!product)notFound();const t=copy[locale],Arrow=locale==="fa"||locale==="ar"?ChevronLeft:ChevronRight,brands=(product.brands??[]).filter(b=>b.isPublished||b.id===product.brandId);return <div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.12em] text-[#009dd8]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1></div><Link href="/admin/products" className="vitalis-focus inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#dfe4ea] bg-white px-4 text-xs font-black text-[#001736]"><Arrow className="h-4 w-4"/>{t.back}</Link></div><div className="mb-6 grid gap-4 xl:grid-cols-[1fr_auto_auto]"><section className="rounded-2xl border border-[#dfe4ea] bg-white p-5"><div className="flex items-center gap-2"><Tags className="h-5 w-5 text-[#009dd8]"/><h2 className="font-black text-[#001736]">{t.brand}</h2></div><p className="mt-1 text-xs text-[#747780]">{t.brandHelp}</p><form action={setProductBrand} className="mt-4 flex flex-col gap-3 sm:flex-row"><input type="hidden" name="productId" value={id}/><select name="brandId" defaultValue={product.brandId??""} className="h-11 min-w-0 flex-1 rounded-xl border border-[#dfe4ea] px-3 text-sm"><option value="">{t.noBrand}</option>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="h-11 rounded-xl bg-[#001736] px-5 text-xs font-black text-white">{t.saveBrand}</button></form></section><Link href={`/admin/products/${id}/catalog`} className="flex min-h-[132px] min-w-[240px] items-center gap-4 rounded-2xl border border-[#dfe4ea] bg-white p-5 transition hover:border-[#009dd8]/50"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e7f5fb] text-[#002b5b]"><Network className="h-5 w-5"/></span><span><b className="block text-sm text-[#001736]">{t.catalog}</b><span className="mt-1 block max-w-[210px] text-xs leading-5 text-[#747780]">{t.catalogHelp}</span></span></Link><Link href={`/admin/products/${id}/variants`} className="flex min-h-[132px] min-w-[240px] items-center gap-4 rounded-2xl border border-[#dfe4ea] bg-white p-5 transition hover:border-[#009dd8]/50"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e7f5fb] text-[#002b5b]"><Layers3 className="h-5 w-5"/></span><span><b className="block text-sm text-[#001736]">{t.variants}</b><span className="mt-1 block text-xs text-[#747780]">{product.variants?.length??0} {t.variantCount}</span></span></Link></div><ProductForm product={product}/></div>}
