import Link from "next/link";
import { FilePenLine, Plus, Pencil } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminDateTime, adminStatusText, type AdminLocale } from "@/lib/admin-i18n";
import { Badge } from "@/components/ui/badge";
import { DeleteButton } from "@/components/admin/delete-button";
import { deleteArticle } from "./actions";

type Article={id:string;slug:string;titleFa:string;titleTr:string;titleEn:string;titleAr:string;category:string;coverImage:string;isPublished:boolean;publishedAt?:string|null;createdAt:string};
const c:Record<AdminLocale,Record<string,string>>={fa:{eyebrow:"تحریریه",title:"مقالات",new:"مقاله جدید",name:"عنوان",category:"دسته",path:"مسیر",publish:"انتشار",scheduled:"زمان‌بندی‌شده",empty:"هنوز مقاله‌ای ثبت نشده است."},ar:{eyebrow:"التحرير",title:"المقالات",new:"مقالة جديدة",name:"العنوان",category:"التصنيف",path:"المسار",publish:"النشر",scheduled:"مجدولة",empty:"لا توجد مقالات مسجلة بعد."},en:{eyebrow:"Editorial",title:"Articles",new:"New article",name:"Title",category:"Category",path:"Path",publish:"Publication",scheduled:"Scheduled",empty:"No article has been registered yet."},tr:{eyebrow:"Editoryal",title:"Makaleler",new:"Yeni makale",name:"Başlık",category:"Kategori",path:"Yol",publish:"Yayın",scheduled:"Planlandı",empty:"Henüz makale kaydedilmedi."}};
export default async function AdminArticlesPage(){const [articles,l]=await Promise.all([adminRpc<Article[]>("admin_articles_bundle"),currentAdminLocale()]);const t=c[l];const now=Date.now();return <div><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-muted">{t.eyebrow}</p><h1 className="mt-2 text-2xl font-black text-foreground">{t.title}</h1></div><Link href="/admin/articles/new" className="flex min-h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-black text-white"><Plus className="h-4 w-4"/>{t.new}</Link></div><div className="mt-6 overflow-x-auto rounded-2xl border border-border bg-card"><table className="w-full text-sm"><thead><tr className="border-b border-border text-xs text-muted"><th className="px-4 py-3 text-start">{t.name}</th><th className="px-4 py-3 text-start">{t.category}</th><th className="px-4 py-3 text-start">{t.path}</th><th className="px-4 py-3 text-start">{t.publish}</th><th className="px-4 py-3"/></tr></thead><tbody>{articles.map(a=>{const publishAt=a.publishedAt?new Date(a.publishedAt).getTime():0;const scheduled=a.isPublished&&Number.isFinite(publishAt)&&publishAt>now;return <tr key={a.id} className="border-b border-border last:border-0"><td className="px-4 py-3"><div className="flex items-center gap-2"><FilePenLine className="h-4 w-4 text-primary"/><div><div className="font-black text-foreground">{a.titleFa||a.titleEn}</div><div className="mt-1 text-xs text-muted">{a.titleTr||"—"} · {a.titleAr||"—"}</div></div></div></td><td className="px-4 py-3 text-muted">{a.category||"—"}</td><td className="px-4 py-3 text-muted" dir="ltr">/articles/{a.slug}</td><td className="px-4 py-3"><div className="flex flex-col items-start gap-1">{scheduled?<Badge variant="muted">{t.scheduled}</Badge>:<Badge variant={a.isPublished?"success":"muted"}>{adminStatusText(a.isPublished?"PUBLISHED":"DRAFT",l)}</Badge>}{a.isPublished&&a.publishedAt?<span className="text-[11px] text-muted">{adminDateTime(a.publishedAt,l)}</span>:null}</div></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Link href={`/admin/articles/${a.id}`} className="flex h-9 w-9 items-center justify-center rounded-lg text-muted hover:bg-muted-bg"><Pencil className="h-4 w-4"/></Link><DeleteButton action={deleteArticle.bind(null,a.id)}/></div></td></tr>})}{!articles.length?<tr><td colSpan={5} className="px-4 py-12 text-center text-muted">{t.empty}</td></tr>:null}</tbody></table></div></div>}
