import Link from "next/link";
import { FilePenLine, Plus, Pencil } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { Badge } from "@/components/ui/badge";
import { DeleteButton } from "@/components/admin/delete-button";
import { deleteArticle } from "./actions";

type Article={id:string;slug:string;titleFa:string;titleTr:string;titleEn:string;titleAr:string;category:string;coverImage:string;isPublished:boolean;publishedAt?:string|null;createdAt:string};
export default async function AdminArticlesPage(){const articles=await adminRpc<Article[]>("admin_articles_bundle");return <div><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-muted">Editorial</p><h1 className="mt-2 text-2xl font-black text-foreground">مقالات</h1></div><Link href="/admin/articles/new" className="flex min-h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-black text-white"><Plus className="h-4 w-4"/>مقاله جدید</Link></div><div className="mt-6 overflow-x-auto rounded-2xl border border-border bg-card"><table className="w-full text-sm"><thead><tr className="border-b border-border text-xs text-muted"><th className="px-4 py-3 text-start">عنوان</th><th className="px-4 py-3 text-start">دسته</th><th className="px-4 py-3 text-start">مسیر</th><th className="px-4 py-3 text-start">انتشار</th><th className="px-4 py-3"/></tr></thead><tbody>{articles.map(a=><tr key={a.id} className="border-b border-border last:border-0"><td className="px-4 py-3"><div className="flex items-center gap-2"><FilePenLine className="h-4 w-4 text-primary"/><div><div className="font-black text-foreground">{a.titleFa||a.titleEn}</div><div className="mt-1 text-xs text-muted">{a.titleTr||"—"} · {a.titleAr||"—"}</div></div></div></td><td className="px-4 py-3 text-muted">{a.category||"—"}</td><td className="px-4 py-3 text-muted" dir="ltr">/articles/{a.slug}</td><td className="px-4 py-3"><Badge variant={a.isPublished?"success":"muted"}>{a.isPublished?"منتشر شده":"پیش‌نویس"}</Badge></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Link href={`/admin/articles/${a.id}`} className="flex h-9 w-9 items-center justify-center rounded-lg text-muted hover:bg-muted-bg"><Pencil className="h-4 w-4"/></Link><DeleteButton action={deleteArticle.bind(null,a.id)}/></div></td></tr>)}{!articles.length?<tr><td colSpan={5} className="px-4 py-12 text-center text-muted">هنوز مقاله‌ای ثبت نشده است.</td></tr>:null}</tbody></table></div></div>}
