import { getLocale } from "next-intl/server";
import { Container } from "@/components/ui/container";
import { RentalRequestForm } from "@/components/site/rental-request-form";
import { supabaseRpc } from "@/lib/supabase-rest";
import { BadgeCheck, CalendarRange, ShieldCheck } from "lucide-react";

function l(locale:string,fa:string,en:string,tr:string,ar:string){return locale==="fa"?fa:locale==="tr"?tr:locale==="ar"?ar:en}
export default async function RentalPage({searchParams}:{searchParams:Promise<{product?:string}>}){const locale=await getLocale(),sp=await searchParams;let products:any[]=[];try{products=await supabaseRpc<any[]>("public_rental_catalog",{p_product_id:null})}catch(error){console.error("[rental] catalog failed",error)}const initialProductId=products.some(p=>p.id===sp.product)?sp.product||"":"";return <main className="flex-1 bg-[#f7fafd] py-8 sm:py-12"><Container><div className="mx-auto max-w-5xl"><header className="mb-8"><p className="text-xs font-black uppercase tracking-[.16em] text-[#ba0036]">HYPER DOCTOR RENTAL</p><h1 className="mt-2 text-3xl font-black text-[#001736] sm:text-4xl">{l(locale,"درخواست اجاره تجهیزات پزشکی","Medical equipment rental request","Medikal ekipman kiralama talebi","طلب استئجار المعدات الطبية")}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[#747780]">{l(locale,"محصولات این صفحه دارای سیاست اجاره فعال هستند. نرخ‌ها، تعداد واحد قابل اجاره و بازه زمانی ثبت می‌شود و تأیید نهایی پس از کنترل موجودی هم‌زمان انجام خواهد شد.","Products on this page have an active rental policy. Rates, available units and requested dates are recorded, with final confirmation after overlap-aware availability validation.","Bu sayfadaki ürünlerin aktif kiralama politikası vardır. Fiyatlar, kullanılabilir adet ve tarihler kaydedilir; nihai onay çakışan rezervasyon kontrolünden sonra verilir.","تحتوي منتجات هذه الصفحة على سياسة إيجار نشطة. يتم تسجيل الأسعار والكمية المتاحة والفترة المطلوبة، ويصدر التأكيد النهائي بعد فحص التداخل في الحجوزات.")}</p></header><div className="mb-6 grid gap-3 sm:grid-cols-3"><Info icon={BadgeCheck} text={l(locale,"نرخ و ودیعه شفاف","Transparent rates & deposit","Şeffaf ücret ve depozito","أسعار ووديعة واضحة")}/><Info icon={CalendarRange} text={l(locale,"کنترل هم‌پوشانی رزروها","Overlap-aware availability","Çakışma kontrollü uygunluk","فحص تداخل الحجوزات")}/><Info icon={ShieldCheck} text={l(locale,"تأیید نهایی موجودی","Final inventory confirmation","Nihai stok onayı","التأكيد النهائي للمخزون")}/></div><RentalRequestForm locale={locale} products={products} initialProductId={initialProductId}/></div></Container></main>}
function Info({icon:Icon,text}:{icon:any;text:string}){return <div className="flex items-center gap-3 rounded-2xl border border-[#dfe4ea] bg-white p-4 text-xs font-bold text-[#43474f]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#e7f5fb] text-[#002b5b]"><Icon className="h-4.5 w-4.5"/></span><span>{text}</span></div>}
