import { getLocale } from "next-intl/server";
import { Container } from "@/components/ui/container";
import { RentalRequestForm } from "@/components/site/rental-request-form";
import { getProducts } from "@/lib/queries";
import { BadgeCheck, CalendarRange, ShieldCheck } from "lucide-react";

function l(locale:string,fa:string,en:string,tr:string,ar:string){return locale==="fa"?fa:locale==="tr"?tr:locale==="ar"?ar:en}
export default async function RentalPage(){const locale=await getLocale(),all=await getProducts({ignoreCatalogFilters:true}),products=all.filter((p:any)=>p.rentalEligible===true);return <main className="flex-1 bg-[#f7fafd] py-8 sm:py-12"><Container><div className="mx-auto max-w-5xl"><header className="mb-8"><p className="text-xs font-black uppercase tracking-[.16em] text-[#ba0036]">HYPER DOCTOR RENTAL</p><h1 className="mt-2 text-3xl font-black text-[#001736] sm:text-4xl">{l(locale,"درخواست اجاره تجهیزات پزشکی","Medical equipment rental request","Medikal ekipman kiralama talebi","طلب استئجار المعدات الطبية")}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[#747780]">{l(locale,"فقط محصولاتی که در کاتالوگ به‌صورت قابل اجاره تأیید شده‌اند در این فرم نمایش داده می‌شوند. پس از ثبت، تیم Hyper Doctor برای بررسی موجودی، مدت اجاره و شرایط تحویل با شما تماس می‌گیرد.","Only products explicitly marked rental-eligible in the catalog appear here. After submission, Hyper Doctor will contact you to confirm availability, rental duration and delivery conditions.","Yalnızca katalogda kiralanabilir olarak onaylanan ürünler burada görünür. Gönderimden sonra Hyper Doctor stok, kiralama süresi ve teslimat koşulları için sizinle iletişime geçer.","تظهر هنا فقط المنتجات المعتمدة في الكتالوج كقابلة للإيجار. بعد الإرسال سيتواصل معك فريق Hyper Doctor لتأكيد التوفر ومدة الإيجار وشروط التسليم.")}</p></header><div className="mb-6 grid gap-3 sm:grid-cols-3"><Info icon={BadgeCheck} text={l(locale,"فقط کالاهای تأییدشده برای اجاره","Rental-eligible catalog only","Yalnızca kiralanabilir katalog","منتجات مؤهلة للإيجار فقط")}/><Info icon={CalendarRange} text={l(locale,"ثبت بازه زمانی ترجیحی","Preferred rental dates","Tercih edilen kiralama tarihleri","تحديد فترة الإيجار المفضلة")}/><Info icon={ShieldCheck} text={l(locale,"تأیید نهایی پس از بررسی موجودی","Final confirmation after availability check","Stok kontrolünden sonra onay","التأكيد النهائي بعد فحص التوفر")}/></div><RentalRequestForm locale={locale} products={products}/></div></Container></main>}
function Info({icon:Icon,text}:{icon:any;text:string}){return <div className="flex items-center gap-3 rounded-2xl border border-[#dfe4ea] bg-white p-4 text-xs font-bold text-[#43474f]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#e7f5fb] text-[#002b5b]"><Icon className="h-4.5 w-4.5"/></span><span>{text}</span></div>}
