import Link from "next/link";
import { CalendarCheck2, Headphones, KeyRound, LogOut, Package, Settings2, ShieldCheck, Truck, UserRound } from "lucide-react";
import { customerRpc, requireCustomerSession } from "@/lib/customer-auth";
import { logoutAction, updateProfileAction } from "./actions";

type Order={id:string;orderNumber:string;total:number;status:string;currency:string;trackingCode:string;createdAt:string};
type Warranty={id:string;serialNumber:string;productId:string;productNameFa?:string|null;productNameEn?:string|null;startsAt:string;expiresAt:string;status:string;createdAt:string};
type Ticket={id:string;ticketNo:string;subject:string;category:string;status:string;priority:string;createdAt:string;updatedAt:string};
type Booking={id:string;serviceId:string;serviceNameFa?:string|null;serviceNameEn?:string|null;preferredDate:string;preferredTime:string;status:string;address?:string|null;notes?:string|null;createdAt:string;updatedAt:string};
type Bundle={profile:{id:string;email?:string|null;phone?:string|null;fullName:string;locale:string;marketingConsent?:boolean};orders:Order[];warranties:Warranty[];tickets:Ticket[];bookings:Booking[]};
const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(n);

export default async function AccountPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{saved?:string}>}){
  const {locale}=await params; const q=await searchParams; await requireCustomerSession(locale); const data=await customerRpc<Bundle>("customer_dashboard"); const logout=logoutAction.bind(null,locale); const save=updateProfileAction.bind(null,locale);
  return <main className="py-10 sm:py-14"><div className="mx-auto max-w-7xl px-4">
    <section className="overflow-hidden rounded-[2rem] bg-[#001736] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#33c8ff]">Customer Portal</p><h1 className="mt-2 text-3xl font-black">{data.profile.fullName||"حساب کاربری"}</h1><p className="mt-2 text-sm text-white/65" dir="ltr">{data.profile.email||data.profile.phone||""}</p></div><div className="flex flex-wrap gap-2"><Link href={`/${locale}/account/security`} className="flex min-h-11 items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 text-sm font-bold hover:bg-white/15"><KeyRound className="h-4 w-4"/>امنیت حساب</Link><form action={logout}><button className="flex min-h-11 items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 text-sm font-bold hover:bg-white/15"><LogOut className="h-4 w-4"/>خروج امن</button></form></div></div></section>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Package} label="سفارش‌ها" value={data.orders.length}/><Stat icon={CalendarCheck2} label="رزرو خدمات" value={data.bookings.length}/><Stat icon={ShieldCheck} label="گارانتی‌ها" value={data.warranties.length}/><Stat icon={Headphones} label="تیکت‌ها" value={data.tickets.length}/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div className="space-y-6">
      <Panel eyebrow="PURCHASES" title="سفارش‌های من" icon={Package}><div className="space-y-3">{data.orders.map(o=><Link href={`/${locale}/account/orders/${o.id}`} key={o.id} className="flex flex-col justify-between gap-3 rounded-xl border border-border bg-background p-4 transition hover:border-primary/40 sm:flex-row sm:items-center"><div><div className="font-black text-foreground" dir="ltr">{o.orderNumber}</div><div className="mt-1 text-xs text-muted">{new Date(o.createdAt).toLocaleDateString("fa-IR")} · {o.status}</div></div><div className="text-sm font-black text-foreground">{money(o.total)} تومان</div></Link>)}{!data.orders.length?<Empty text="هنوز سفارشی به این حساب متصل نشده است."/>:null}</div></Panel>
      <Panel eyebrow="SERVICES" title="رزروهای خدمات" icon={CalendarCheck2}><div className="grid gap-3 md:grid-cols-2">{data.bookings.map(b=><div key={b.id} className="rounded-xl border border-border bg-background p-4"><div className="font-black text-foreground">{b.serviceNameFa||b.serviceNameEn||b.serviceId}</div><div className="mt-2 text-xs text-muted">{new Date(`${b.preferredDate}T00:00:00`).toLocaleDateString("fa-IR")} · {b.preferredTime}</div><div className="mt-3 text-xs font-black text-primary">{b.status}</div>{b.notes?<p className="mt-3 line-clamp-2 text-xs leading-6 text-muted">{b.notes}</p>:null}</div>)}{!data.bookings.length?<div className="md:col-span-2"><Empty text="رزرو خدماتی برای این حساب ثبت نشده است."/></div>:null}</div><div className="mt-4 text-end"><Link href={`/${locale}/booking`} className="text-xs font-black text-primary">رزرو خدمت جدید</Link></div></Panel>
      <Panel eyebrow="WARRANTY" title="گارانتی‌های من" icon={ShieldCheck}><div className="grid gap-3 md:grid-cols-2">{data.warranties.map(w=><div key={w.id} className="rounded-xl border border-border bg-background p-4"><div className="font-black text-foreground">{w.productNameFa||w.productNameEn||w.productId}</div><div className="mt-2 text-xs text-muted" dir="ltr">S/N: {w.serialNumber}</div><div className="mt-3 flex justify-between text-xs"><span className="font-bold text-primary">{w.status}</span><span className="text-muted">تا {new Date(w.expiresAt).toLocaleDateString("fa-IR")}</span></div></div>)}{!data.warranties.length?<div className="md:col-span-2"><Empty text="گارانتی ثبت‌شده‌ای برای این حساب وجود ندارد."/></div>:null}</div></Panel>
      <Panel eyebrow="SUPPORT" title="درخواست‌های پشتیبانی" icon={Headphones}><div className="space-y-3">{data.tickets.map(t=><Link href={`/${locale}/account/support/${t.id}`} key={t.id} className="block rounded-xl border border-border bg-background p-4 transition hover:border-primary/40"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-center"><div><div className="font-black text-foreground">{t.subject}</div><div className="mt-1 text-xs text-muted" dir="ltr">{t.ticketNo}</div></div><div className="text-xs font-bold text-primary">{t.status} · {t.priority}</div></div></Link>)}{!data.tickets.length?<Empty text="هنوز تیکتی برای این حساب ثبت نشده است."/>:null}</div><div className="mt-4 text-end"><Link href={`/${locale}/support`} className="text-xs font-black text-primary">ثبت درخواست جدید</Link></div></Panel>
    </div><aside className="space-y-6"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><UserRound className="h-5 w-5 text-primary"/><h2 className="font-black text-foreground">مشخصات حساب</h2></div>{q.saved?<div className="mt-4 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-700">تغییرات ذخیره شد.</div>:null}<form action={save} className="mt-5 space-y-4"><Field label="نام و نام خانوادگی" name="fullName" value={data.profile.fullName}/><Field label="شماره موبایل" name="phone" value={data.profile.phone||""} dir="ltr"/><div><span className="mb-1.5 block text-xs font-bold text-muted">ایمیل</span><div className="rounded-xl border border-border bg-muted-bg px-3 py-3 text-sm text-muted" dir="ltr">{data.profile.email||"—"}</div></div><label className="flex items-start gap-3 rounded-xl border border-border p-3 text-xs leading-6 text-muted"><input type="checkbox" name="marketingConsent" defaultChecked={data.profile.marketingConsent} className="mt-1"/><span>دریافت اطلاع‌رسانی پیشنهادها و خدمات</span></label><button className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-black text-white"><Settings2 className="h-4 w-4"/>ذخیره پروفایل</button></form><Link href={`/${locale}/account/security`} className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-border text-sm font-black text-foreground hover:bg-muted-bg"><KeyRound className="h-4 w-4"/>تغییر رمز عبور</Link></section><section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2 text-primary"><Truck className="h-5 w-5"/><span className="font-black">پیگیری ارسال</span></div><p className="mt-3 text-xs leading-6 text-muted">کد رهگیری سفارش‌های ارسال‌شده در جزئیات هر سفارش نمایش داده می‌شود.</p></section></aside></div>
  </div></main>;
}
function Stat({icon:Icon,label,value}:{icon:typeof Package;label:string;value:number}){return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><Icon className="h-5 w-5 text-primary"/><div className="mt-3 text-2xl font-black text-foreground">{new Intl.NumberFormat("fa-IR").format(value)}</div><div className="mt-1 text-xs font-bold text-muted">{label}</div></div>}
function Panel({eyebrow,title,icon:Icon,children}:{eyebrow:string;title:string;icon:typeof Package;children:React.ReactNode}){return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-muted">{eyebrow}</p><h2 className="mt-1 text-lg font-black text-foreground">{title}</h2></div><Icon className="h-5 w-5 text-primary"/></div><div className="mt-4">{children}</div></section>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-border p-6 text-center text-xs text-muted">{text}</div>}
function Field({label,name,value,dir}:{label:string;name:string;value:string;dir?:"ltr"|"rtl"}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{label}</span><input name={name} defaultValue={value} required className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none focus:border-primary" dir={dir}/></label>}
