import Link from "next/link";
import { CalendarCheck2, Headphones, Home, KeyRound, LogOut, Package, PlusCircle, ShieldCheck, Truck, UserRound } from "lucide-react";
import { customerRpc, requireCustomerSession } from "@/lib/customer-auth";
import { logoutAction, updateProfileAction } from "./actions";

type Order={id:string;orderNumber:string;total:number;status:string;currency:string;trackingCode:string;createdAt:string};
type Warranty={id:string;serialNumber:string;productId:string;productNameFa?:string|null;productNameEn?:string|null;startsAt:string;expiresAt:string;status:string;createdAt:string};
type Ticket={id:string;ticketNo:string;subject:string;category:string;status:string;priority:string;createdAt:string;updatedAt:string};
type Booking={id:string;serviceId:string;serviceNameFa?:string|null;serviceNameEn?:string|null;preferredDate:string;preferredTime:string;status:string;address?:string|null;notes?:string|null;createdAt:string;updatedAt:string};
type Bundle={profile:{id:string;email?:string|null;phone?:string|null;fullName:string;locale:string;marketingConsent?:boolean};orders:Order[];warranties:Warranty[];tickets:Ticket[];bookings:Booking[]};
const pick=(locale:string,fa:string,en:string,tr:string,ar:string)=>locale==="en"?en:locale==="tr"?tr:locale==="ar"?ar:fa;
const num=(locale:string,n:number)=>new Intl.NumberFormat(locale).format(n);
const currencyText=(locale:string,currency?:string)=>{const c=(currency||"IRT").toUpperCase();if(c==="IRT")return pick(locale,"تومان","Toman","Toman","تومان");if(c==="IRR")return pick(locale,"ریال","IRR","IRR","ريال");return c};
const statusText=(locale:string,status:string)=>{const map:Record<string,[string,string,string,string]>={PENDING:["در انتظار","Pending","Bekliyor","قيد الانتظار"],PROCESSING:["در حال پردازش","Processing","İşleniyor","قيد المعالجة"],PAID:["پرداخت‌شده","Paid","Ödendi","مدفوع"],SHIPPED:["ارسال‌شده","Shipped","Gönderildi","تم الشحن"],DELIVERED:["تحویل‌شده","Delivered","Teslim edildi","تم التسليم"],COMPLETED:["تکمیل‌شده","Completed","Tamamlandı","مكتمل"],CANCELLED:["لغوشده","Cancelled","İptal edildi","ملغي"],REFUNDED:["بازپرداخت‌شده","Refunded","İade edildi","تم رد المبلغ"]};const v=map[String(status||"").toUpperCase()];return v?pick(locale,v[0],v[1],v[2],v[3]):status||"—"};
const serviceName=(locale:string,b:Booking)=>locale==="fa"?(b.serviceNameFa||b.serviceNameEn||b.serviceId):(b.serviceNameEn||b.serviceNameFa||b.serviceId);

export default async function AccountPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{saved?:string}>}){
 const {locale}=await params; const q=await searchParams; await requireCustomerSession(locale); const data=await customerRpc<Bundle>("customer_dashboard"); const logout=logoutAction.bind(null,locale); const save=updateProfileAction.bind(null,locale);
 const todayBookings=data.bookings.filter(b=>b.preferredDate===new Date().toISOString().slice(0,10));
 const pending=data.tickets.filter(t=>!["CLOSED","RESOLVED","COMPLETED"].includes(t.status)).length;
 const upcoming=data.bookings.filter(b=>new Date(`${b.preferredDate}T23:59:59`).getTime()>=Date.now()).slice(0,3);
 const labels={hello:pick(locale,"سلام","Hello","Merhaba","مرحباً"),summary:pick(locale,"خلاصه وضعیت امروز شما","Your status summary","Bugünkü durum özeti","ملخص حالتك اليوم"),today:pick(locale,"نوبت‌های امروز","Today’s bookings","Bugünkü randevular","مواعيد اليوم"),pending:pick(locale,"درخواست‌های معلق","Pending requests","Bekleyen talepler","الطلبات المعلقة"),manage:pick(locale,"مدیریت نوبت‌ها","Manage bookings","Randevuları yönet","إدارة المواعيد"),history:pick(locale,"تاریخچه سفارش‌ها","Order history","Sipariş geçmişi","سجل الطلبات"),upcoming:pick(locale,"نوبت‌های پیش‌رو","Upcoming bookings","Yaklaşan randevular","المواعيد القادمة"),all:pick(locale,"مشاهده همه","View all","Tümünü gör","عرض الكل"),profile:pick(locale,"پروفایل","Profile","Profil","الملف الشخصي"),home:pick(locale,"خانه","Home","Ana sayfa","الرئيسية"),book:pick(locale,"رزرو","Book","Randevu","حجز"),visits:pick(locale,"نوبت‌ها","My visits","Randevularım","مواعيدي")};
 return <main className="bg-[#f5f8fb] pb-28 pt-6 sm:pb-16 sm:pt-10"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <section className="rounded-[2rem] border border-white bg-white p-5 shadow-[0_18px_50px_rgba(0,23,54,.06)] sm:p-7"><div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-4"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-full border-4 border-[#d6e3ff] bg-[#eef4fa] text-[#001736]"><UserRound className="h-9 w-9"/></div><div><p className="text-sm font-bold text-[#747780]">{labels.hello}</p><h1 className="mt-1 text-2xl font-black text-[#001736] sm:text-3xl">{data.profile.fullName}</h1><p className="mt-2 text-sm text-[#5f6570]">{labels.summary}</p></div></div><div className="flex flex-wrap gap-2"><Link href={`/${locale}/account/security`} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#c4c6d0] bg-white px-4 text-xs font-black text-[#001736]"><KeyRound className="h-4 w-4"/>{pick(locale,"امنیت حساب","Security","Güvenlik","الأمان")}</Link><form action={logout}><button className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#001736] px-4 text-xs font-black text-white"><LogOut className="h-4 w-4"/>{pick(locale,"خروج","Sign out","Çıkış","خروج")}</button></form></div></div>
   <div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-[#dfe4ea] bg-[#f9fbfd] p-5 text-center"><CalendarCheck2 className="mx-auto h-7 w-7 text-[#c3003e]"/><div className="mt-3 text-4xl font-black text-[#001736]">{num(locale,todayBookings.length)}</div><div className="mt-2 text-sm font-bold text-[#43474f]">{labels.today}</div></div><div className="rounded-2xl border border-[#dfe4ea] bg-[#f9fbfd] p-5 text-center"><Headphones className="mx-auto h-7 w-7 text-[#001736]"/><div className="mt-3 text-4xl font-black text-[#001736]">{num(locale,pending)}</div><div className="mt-2 text-sm font-bold text-[#43474f]">{labels.pending}</div></div></div>
  </section>
  <section className="mt-6 grid gap-5 md:grid-cols-2"><Link href={`/${locale}/booking`} className="rounded-[1.75rem] border border-white bg-white p-7 text-center shadow-[0_14px_38px_rgba(0,23,54,.05)] transition hover:-translate-y-1"><span className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#e8edf3] text-[#001736]"><CalendarCheck2 className="h-8 w-8"/></span><h2 className="mt-6 text-xl font-black text-[#001736]">{labels.manage}</h2></Link><Link href={`/${locale}/account/orders`} className="rounded-[1.75rem] border border-white bg-white p-7 text-center shadow-[0_14px_38px_rgba(0,23,54,.05)] transition hover:-translate-y-1"><span className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#ffe4ed] text-[#c3003e]"><Package className="h-8 w-8"/></span><h2 className="mt-6 text-xl font-black text-[#001736]">{labels.history}</h2></Link></section>
  <section className="mt-6 rounded-[1.75rem] border border-white bg-white p-5 shadow-[0_14px_38px_rgba(0,23,54,.05)] sm:p-7"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-[#001736]">{labels.upcoming}</h2><Link href={`/${locale}/booking`} className="text-xs font-black text-[#001736]">{labels.all}</Link></div><div className="mt-5 space-y-3">{upcoming.map((b,index)=><div key={b.id} className="flex items-center gap-4 rounded-2xl border border-[#dfe4ea] bg-[#f9fbfd] p-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-[#e6eef5] text-xs font-black text-[#001736]">{num(locale,index+1)}</span><div className="min-w-0 flex-1"><div className="font-black text-[#001736]">{serviceName(locale,b)}</div><div className="mt-1 text-xs text-[#5f6570]">{new Date(`${b.preferredDate}T00:00:00`).toLocaleDateString(locale)} · {b.preferredTime}</div></div><span className={`h-3 w-3 shrink-0 rounded-full ${index===0?"bg-[#c3003e]":"bg-[#c4c6d0]"}`}/></div>)}{!upcoming.length?<Empty text={pick(locale,"نوبت آینده‌ای ثبت نشده است.","No upcoming bookings.","Yaklaşan randevu yok.","لا توجد مواعيد قادمة.")}/>:null}</div></section>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="space-y-6"><Panel title={pick(locale,"سفارش‌های اخیر","Recent orders","Son siparişler","الطلبات الأخيرة")} icon={Package}>{data.orders.slice(0,4).map(o=><Link href={`/${locale}/account/orders/${o.id}`} key={o.id} className="mb-3 flex items-center justify-between rounded-xl border border-[#dfe4ea] bg-[#f9fbfd] p-4 last:mb-0"><div><div className="font-black text-[#001736]" dir="ltr">{o.orderNumber}</div><div className="mt-1 text-xs text-[#747780]">{new Date(o.createdAt).toLocaleDateString(locale)} · {statusText(locale,o.status)}</div></div><div className="text-sm font-black text-[#001736]">{num(locale,o.total)} {currencyText(locale,o.currency)}</div></Link>)}{!data.orders.length?<Empty text={pick(locale,"هنوز سفارشی ثبت نشده است.","No orders yet.","Henüz sipariş yok.","لا توجد طلبات بعد.")}/>:null}</Panel><Panel title={pick(locale,"گارانتی و پشتیبانی","Warranty & support","Garanti ve destek","الضمان والدعم")} icon={ShieldCheck}><div className="grid gap-3 sm:grid-cols-2"><Link href={`/${locale}/warranty`} className="rounded-xl border border-[#dfe4ea] p-4 text-sm font-black text-[#001736]">{pick(locale,"ثبت گارانتی","Register warranty","Garanti kaydı","تسجيل الضمان")}</Link><Link href={`/${locale}/account/support`} className="rounded-xl border border-[#dfe4ea] p-4 text-sm font-black text-[#001736]">{pick(locale,"تیکت‌های من","My tickets","Taleplerim","تذاكري")}</Link></div></Panel></div>
   <aside className="space-y-6"><section className="rounded-[1.75rem] border border-white bg-white p-5 shadow-[0_14px_38px_rgba(0,23,54,.05)]"><div className="flex items-center gap-2"><UserRound className="h-5 w-5 text-[#001736]"/><h2 className="font-black text-[#001736]">{labels.profile}</h2></div>{q.saved?<div className="mt-4 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-700">{pick(locale,"تغییرات ذخیره شد.","Changes saved.","Değişiklikler kaydedildi.","تم حفظ التغييرات.")}</div>:null}<form action={save} className="mt-5 space-y-4"><Field label={pick(locale,"نام و نام خانوادگی","Full name","Ad soyad","الاسم الكامل")} name="fullName" value={data.profile.fullName}/><Field label={pick(locale,"شماره موبایل","Mobile","Telefon","الهاتف")} name="phone" value={data.profile.phone||""} dir="ltr"/><div><span className="mb-1.5 block text-xs font-bold text-[#747780]">{pick(locale,"ایمیل","Email","E-posta","البريد الإلكتروني")}</span><div className="rounded-xl border border-[#dfe4ea] bg-[#f5f8fb] px-3 py-3 text-sm text-[#747780]" dir="ltr">{data.profile.email||"—"}</div></div><label className="flex items-start gap-3 rounded-xl border border-[#dfe4ea] p-3 text-xs leading-6 text-[#5f6570]"><input type="checkbox" name="marketingConsent" defaultChecked={data.profile.marketingConsent} className="mt-1"/><span>{pick(locale,"دریافت اطلاع‌رسانی پیشنهادها و خدمات","Receive offers and service updates","Teklif ve hizmet bildirimleri","تلقي العروض وتحديثات الخدمات")}</span></label><button className="min-h-11 w-full rounded-xl bg-[#001736] px-4 text-sm font-black text-white">{pick(locale,"ذخیره پروفایل","Save profile","Profili kaydet","حفظ الملف")}</button></form></section><section className="rounded-[1.75rem] bg-[#001736] p-5 text-white"><Truck className="h-5 w-5 text-[#82cfff]"/><p className="mt-3 text-sm font-black">{pick(locale,"پیگیری سفارش","Order tracking","Sipariş takibi","تتبع الطلب")}</p><Link href={`/${locale}/order-tracking`} className="mt-4 inline-flex text-xs font-black text-[#82cfff]">{pick(locale,"مشاهده رهگیری","Track now","Şimdi takip et","تتبع الآن")}</Link></section></aside>
  </div>
 </div><nav className="fixed inset-x-0 bottom-0 z-40 border-t border-[#dfe4ea] bg-white/95 px-3 py-2 shadow-[0_-10px_30px_rgba(0,23,54,.08)] backdrop-blur sm:hidden"><div className="mx-auto grid max-w-md grid-cols-4"><Bottom href={`/${locale}`} icon={Home} label={labels.home}/><Bottom href={`/${locale}/booking`} icon={PlusCircle} label={labels.book}/><Bottom href={`/${locale}/account`} icon={CalendarCheck2} label={labels.visits}/><Bottom href={`/${locale}/account`} icon={UserRound} label={labels.profile} active/></div></nav></main>;
}
function Panel({title,icon:Icon,children}:{title:string;icon:typeof Package;children:React.ReactNode}){return <section className="rounded-[1.75rem] border border-white bg-white p-5 shadow-[0_14px_38px_rgba(0,23,54,.05)] sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black text-[#001736]">{title}</h2><Icon className="h-5 w-5 text-[#001736]"/></div>{children}</section>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#c4c6d0] p-6 text-center text-xs text-[#747780]">{text}</div>}
function Field({label,name,value,dir}:{label:string;name:string;value:string;dir?:"ltr"|"rtl"}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-[#747780]">{label}</span><input name={name} defaultValue={value} required className="h-11 w-full rounded-xl border border-[#c4c6d0] bg-white px-3 text-sm outline-none focus:border-[#001736]" dir={dir}/></label>}
function Bottom({href,icon:Icon,label,active}:{href:string;icon:typeof Home;label:string;active?:boolean}){return <Link href={href} className={`flex flex-col items-center gap-1 rounded-xl py-2 text-[10px] font-bold ${active?"bg-[#f5dbe5] text-[#c3003e]":"text-[#4f555e]"}`}><Icon className="h-5 w-5"/><span>{label}</span></Link>}
