import Link from "next/link";
import { SlidersHorizontal } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import type { AdminLocale } from "@/lib/admin-i18n";
import { saveProductAttributes } from "./actions";

type D={id:string;code:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;groupFa:string;groupTr:string;groupEn:string;groupAr:string;dataType:string;unit:string;options:string[]};type V={definitionId:string;valueText?:string|null;valueNumber?:number|string|null;valueBoolean?:boolean|null};type B={definitions:D[];values:V[]};type P={id:string;sku:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string};
const C:Record<AdminLocale,Record<string,string>>={fa:{title:"ویژگی‌های محصول",sub:"مقادیر استاندارد برای مقایسه و فیلتر را ثبت کنید.",back:"بازگشت به محصول",save:"ذخیره ویژگی‌ها",saved:"ذخیره شد.",yes:"بله",no:"خیر",empty:"هنوز Attribute فعالی تعریف نشده است."},en:{title:"Product attributes",sub:"Enter standardized values used by comparison and filtering.",back:"Back to product",save:"Save attributes",saved:"Saved.",yes:"Yes",no:"No",empty:"No active attribute definitions exist yet."},tr:{title:"Ürün özellikleri",sub:"Karşılaştırma ve filtreleme için standart değerleri girin.",back:"Ürüne dön",save:"Özellikleri kaydet",saved:"Kaydedildi.",yes:"Evet",no:"Hayır",empty:"Henüz aktif özellik tanımı yok."},ar:{title:"خصائص المنتج",sub:"أدخل القيم القياسية المستخدمة للمقارنة والتصفية.",back:"العودة إلى المنتج",save:"حفظ الخصائص",saved:"تم الحفظ.",yes:"نعم",no:"لا",empty:"لا توجد تعريفات خصائص نشطة بعد."}};
function loc(x:Record<string,unknown>,l:AdminLocale,key="name"){const suffix=l[0].toUpperCase()+l.slice(1);return String(x[`${key}${suffix}`]||x[`${key}En`]||x[`${key}Fa`]||x.code||"")}
function raw(v:V|undefined,d:D){if(!v)return"";if(d.dataType==="NUMBER")return v.valueNumber==null?"":String(v.valueNumber);if(d.dataType==="BOOLEAN")return v.valueBoolean==null?"":String(v.valueBoolean);return v.valueText||""}
export default async function ProductAttributesPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string}>}){const{id}=await params,sp=await searchParams;const[locale,p,b]=await Promise.all([currentAdminLocale(),adminRpc<P|null>("admin_product_detail",{p_id:id}),adminRpc<B>("admin_product_attributes",{p_product_id:id})]);if(!p)return <div>Product not found.</div>;const t=C[locale],values=new Map(b.values.map(v=>[v.definitionId,v]));const groups=[...new Set(b.definitions.map(d=>loc(d as unknown as Record<string,unknown>,locale,"group")||"General"))];return <div className="mx-auto max-w-5xl space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-black text-[#001736]"><SlidersHorizontal className="h-6 w-6 text-[#009dd8]"/>{t.title}</h1><p className="mt-2 text-sm font-bold text-[#43474f]">{loc(p as unknown as Record<string,unknown>,locale)} · <span dir="ltr">{p.sku}</span></p><p className="mt-1 text-xs text-[#747780]">{t.sub}</p></div><Link href={`/admin/products/${id}`} className="rounded-xl border bg-white px-4 py-2 text-xs font-black">{t.back}</Link></header>{sp.saved?<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-800">{t.saved}</div>:null}{b.definitions.length?<form action={saveProductAttributes} className="space-y-5"><input type="hidden" name="productId" value={id}/>{groups.map(group=><section key={group} className="rounded-3xl border bg-white p-5"><h2 className="font-black text-[#001736]">{group}</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{b.definitions.filter(d=>(loc(d as unknown as Record<string,unknown>,locale,"group")||"General")===group).map(d=>{const value=raw(values.get(d.id),d),name=loc(d as unknown as Record<string,unknown>,locale);return <label key={d.id} className="grid gap-1.5 text-xs font-bold text-[#43474f]"><span>{name}{d.unit?` (${d.unit})`:""}</span>{d.dataType==="BOOLEAN"?<select name={`attr_${d.id}`} defaultValue={value} className="h-11 rounded-xl border px-3"><option value="">—</option><option value="true">{t.yes}</option><option value="false">{t.no}</option></select>:d.dataType==="SELECT"?<select name={`attr_${d.id}`} defaultValue={value} className="h-11 rounded-xl border px-3"><option value="">—</option>{(d.options||[]).map(o=><option key={o} value={o}>{o}</option>)}</select>:<input name={`attr_${d.id}`} defaultValue={value} type={d.dataType==="NUMBER"?"number":"text"} step={d.dataType==="NUMBER"?"any":undefined} className="h-11 rounded-xl border px-3"/>}</label>})}</div></section>)}<button className="min-h-12 rounded-xl bg-[#e80346] px-6 text-sm font-black text-white">{t.save}</button></form>:<div className="rounded-3xl border border-dashed bg-white p-10 text-center text-sm text-[#8b9098]">{t.empty}</div>}</div>}
