import Link from "next/link";
import { ArrowLeft, Headphones, PlusCircle } from "lucide-react";
import { customerRpc, requireCustomerSession } from "@/lib/customer-auth";
import { formatLocalizedDateTime } from "@/lib/calendar";

type Ticket={id:string;ticketNo:string;subject:string;category:string;status:string;priority:string;createdAt:string;updatedAt:string};
type Bundle={tickets:Ticket[]};
const pick=(locale:string,fa:string,en:string,tr:string,ar:string)=>locale==="en"?en:locale==="tr"?tr:locale==="ar"?ar:fa;
const statusLabel=(locale:string,status:string)=>({OPEN:pick(locale,"باز","Open","Açık","مفتوح"),IN_PROGRESS:pick(locale,"در حال بررسی","In progress","İşlemde","قيد المعالجة"),WAITING_CUSTOMER:pick(locale,"منتظر پاسخ شما","Waiting for you","Yanıtınız bekleniyor","بانتظار ردك"),RESOLVED:pick(locale,"حل‌شده","Resolved","Çözüldü","تم الحل"),CLOSED:pick(locale,"بسته","Closed","Kapalı","مغلق")}[status]??status);
const priorityLabel=(locale:string,priority:string)=>({LOW:pick(locale,"کم","Low","Düşük","منخفض"),NORMAL:pick(locale,"عادی","Normal","Normal","عادي"),HIGH:pick(locale,"زیاد","High","Yüksek","مرتفع"),URGENT:pick(locale,"فوری","Urgent","Acil","عاجل")}[priority]??priority);
export default async function SupportListPage({params}:{params:Promise<{locale:string}>}){const {locale}=await params;await requireCustomerSession(locale);const data=await customerRpc<Bundle>("customer_dashboard");const rtl=locale==="fa"||locale==="ar";return <main className="bg-[#f5f8fb] py-10 sm:py-14"><div className="mx-auto max-w-5xl px-4"><div className="flex items-center justify-between gap-4"><Link href={`/${locale}/account`} className="inline-flex items-center gap-2 text-sm font-bold text-[#001736]"><ArrowLeft className={`h-4 w-4 ${rtl?"rotate-180":""}`}/>{pick(locale,"بازگشت به پنل","Back to dashboard","Panele dön","العودة إلى اللوحة")}</Link><Link href={`/${locale}/support`} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#001736] px-4 text-xs font-black text-white"><PlusCircle className="h-4 w-4"/>{pick(locale,"درخواست جدید","New request","Yeni talep","طلب جديد")}</Link></div><section className="mt-5 rounded-[2rem] border border-white bg-white p-6 shadow-[0_20px_55px_rgba(0,23,54,.07)] sm:p-8"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#001736] text-white"><Headphones className="h-5 w-5"/></span><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#747780]">Hyper Doctor Support</p><h1 className="mt-1 text-2xl font-black text-[#001736]">{pick(locale,"درخواست‌های پشتیبانی من","My support requests","Destek taleplerim","طلبات الدعم الخاصة بي")}</h1></div></div><div className="mt-6 space-y-3">{data.tickets.map(t=><Link href={`/${locale}/account/support/${t.id}`} key={t.id} className="block rounded-2xl border border-[#dfe4ea] bg-[#f9fbfd] p-5 transition hover:border-[#001736]/30"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><div className="font-black text-[#001736]">{t.subject}</div><div className="mt-1 text-xs text-[#747780]" dir="ltr">{t.ticketNo}</div></div><div className="flex items-center gap-2"><span className="rounded-full bg-[#edf4ff] px-3 py-1 text-[11px] font-black text-[#002b5b]">{statusLabel(locale,t.status)}</span><span className="rounded-full bg-[#ffe8ee] px-3 py-1 text-[11px] font-black text-[#ba0036]">{priorityLabel(locale,t.priority)}</span></div></div><div className="mt-3 text-xs text-[#747780]">{formatLocalizedDateTime(t.updatedAt||t.createdAt,locale)}</div></Link>)}{!data.tickets.length?<div className="rounded-2xl border border-dashed border-[#c4c6d0] p-10 text-center text-sm text-[#747780]">{pick(locale,"هنوز درخواست پشتیبانی ثبت نکرده‌اید.","You have not created a support request yet.","Henüz destek talebi oluşturmadınız.","لم تنشئ طلب دعم بعد.")}</div>:null}</div></section></div></main>}
