import Link from "next/link";
import { Search, History, ShieldCheck } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminNumber, type AdminLocale } from "@/lib/admin-i18n";

type Row={id:string;sourceFile:string;sourceRow:number;legacyCode:string;legacyName:string;barcode:string;legacySku:string;brand:string;unit:string;historicalPurchasePrice:number|null;historicalSellingPrice:number|null;historicalInitialStock:number|null;historicalMinStock:number|null;mainGroup:string;subGroup:string;status:string};
const T:Record<AdminLocale,Record<string,string>>={
 fa:{title:"رجیستری هویت کالاهای قدیمی",desc:"مرجع تطبیق کدهای واقعی Hyper Doctor از داده‌های قدیمی. قیمت و موجودی این بخش تاریخی است و هرگز قیمت/موجودی جاری فروشگاه محسوب نمی‌شود.",search:"جستجو در نام، کد، بارکد یا برند",go:"جستجو",code:"کد قدیمی",name:"نام قدیمی",source:"منبع",historical:"اطلاعات تاریخی",purchase:"خرید",sale:"فروش",stock:"موجودی اولیه",none:"موردی یافت نشد",back:"بازگشت به Staging"},
 en:{title:"Legacy product identity registry",desc:"Reference-only reconciliation data from historical Hyper Doctor datasets. Prices and stock shown here are historical and never current storefront commerce data.",search:"Search name, code, barcode or brand",go:"Search",code:"Legacy code",name:"Legacy name",source:"Source",historical:"Historical data",purchase:"Purchase",sale:"Selling",stock:"Initial stock",none:"No records found",back:"Back to staging"},
 tr:{title:"Eski ürün kimlik kayıtları",desc:"Hyper Doctor eski veri kümelerinden yalnızca referans amaçlı kimlik eşleştirme verileri. Buradaki fiyat ve stok güncel mağaza verisi değildir.",search:"Ad, kod, barkod veya marka ara",go:"Ara",code:"Eski kod",name:"Eski ad",source:"Kaynak",historical:"Tarihsel veri",purchase:"Alış",sale:"Satış",stock:"İlk stok",none:"Kayıt bulunamadı",back:"Staging'e dön"},
 ar:{title:"سجل هويات المنتجات القديمة",desc:"بيانات مرجعية فقط لمطابقة هويات Hyper Doctor من الأنظمة القديمة. الأسعار والمخزون هنا تاريخية وليست بيانات المتجر الحالية.",search:"البحث بالاسم أو الرمز أو الباركود أو العلامة",go:"بحث",code:"الرمز القديم",name:"الاسم القديم",source:"المصدر",historical:"بيانات تاريخية",purchase:"شراء",sale:"بيع",stock:"المخزون الأولي",none:"لا توجد نتائج",back:"العودة إلى المرحلي"}
};
function money(v:number|null,locale:AdminLocale){return v==null?"—":adminNumber(v,locale)}
export default async function Page({searchParams}:{searchParams:Promise<{q?:string}>}){
 const [{q=""},locale]=await Promise.all([searchParams,currentAdminLocale()]);const t=T[locale];
 const rows=await adminRpc<Row[]>("admin_legacy_catalog_identity_search",{p_query:q,p_limit:100});
 return <div className="mx-auto max-w-[1500px] space-y-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin/products/staging" className="text-xs font-black text-[#002b5b]">← {t.back}</Link><h1 className="mt-3 flex items-center gap-2 text-3xl font-black"><History className="h-7 w-7"/>{t.title}</h1><p className="mt-2 max-w-4xl text-sm leading-7 text-muted">{t.desc}</p></div><div className="rounded-2xl border bg-emerald-50 px-4 py-3 text-xs font-black text-emerald-800"><ShieldCheck className="me-2 inline h-4 w-4"/>REFERENCE ONLY</div></div>
  <form className="flex gap-2 rounded-3xl border bg-white p-4"><div className="relative flex-1"><Search className="absolute start-3 top-3 h-4 w-4 text-muted"/><input name="q" defaultValue={q} placeholder={t.search} className="min-h-10 w-full rounded-xl border ps-10 pe-3 text-sm"/></div><button className="rounded-xl bg-[#002b5b] px-5 text-xs font-black text-white">{t.go}</button></form>
  <section className="overflow-hidden rounded-3xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead><tr>{[t.code,t.name,t.source,t.historical].map(x=><th key={x} className="border-b px-5 py-3 text-start">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b align-top last:border-0"><td className="px-5 py-4"><b dir="ltr">{r.legacyCode}</b>{r.barcode?<div className="mt-1 text-xs text-muted" dir="ltr">{r.barcode}</div>:null}</td><td className="px-5 py-4"><b>{r.legacyName}</b>{r.brand?<div className="mt-1 text-xs text-muted">{r.brand}</div>:null}</td><td className="px-5 py-4 text-xs"><div>{r.sourceFile}</div><div className="mt-1 text-muted">row {adminNumber(r.sourceRow,locale)}</div></td><td className="px-5 py-4 text-xs"><div>{t.purchase}: {money(r.historicalPurchasePrice,locale)}</div><div>{t.sale}: {money(r.historicalSellingPrice,locale)}</div><div>{t.stock}: {money(r.historicalInitialStock,locale)}</div></td></tr>)}{rows.length===0?<tr><td colSpan={4} className="px-6 py-16 text-center text-muted">{t.none}</td></tr>:null}</tbody></table></div></section>
 </div>
}
