import { Search, ShieldCheck, UserPlus, KeyRound } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminDateTime, adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { adminRoleLabels, type AdminRole } from "@/lib/admin-permissions";
import { requireAdminRole } from "@/lib/admin-auth";
import { revokeAdminSessions, saveAdminTeamMember } from "./actions";

type Member={id:string;email:string;name:string;role:AdminRole;isActive:boolean;createdAt:string;updatedAt:string;activeSessions:number;lastSeenAt?:string|null};
const C:Record<AdminLocale,Record<string,string>>={
  fa:{title:"تیم مدیریت و دسترسی‌ها",sub:"ایجاد مدیر، تعیین نقش، فعال یا غیرفعال‌سازی و کنترل نشست‌های مدیریتی",search:"جستجو با نام، ایمیل یا نقش...",find:"جستجو",new:"افزودن مدیر جدید",name:"نام",email:"ایمیل",role:"نقش",password:"رمز عبور",passHelp:"حداقل ۱۲ کاراکتر",active:"حساب فعال",create:"ایجاد مدیر",members:"اعضای تیم",sessions:"نشست فعال",lastSeen:"آخرین فعالیت",never:"بدون فعالیت",save:"ذخیره",reset:"رمز جدید اختیاری",revoke:"لغو همه نشست‌ها",self:"حساب فعلی",empty:"عضوی با این معیار پیدا نشد."},
  ar:{title:"فريق الإدارة والصلاحيات",sub:"إنشاء المديرين وتحديد الأدوار وتفعيل الحسابات والتحكم في الجلسات",search:"ابحث بالاسم أو البريد أو الدور...",find:"بحث",new:"إضافة مدير جديد",name:"الاسم",email:"البريد الإلكتروني",role:"الدور",password:"كلمة المرور",passHelp:"12 حرفاً على الأقل",active:"الحساب نشط",create:"إنشاء المدير",members:"أعضاء الفريق",sessions:"جلسات نشطة",lastSeen:"آخر نشاط",never:"لا يوجد نشاط",save:"حفظ",reset:"كلمة مرور جديدة اختيارية",revoke:"إلغاء كل الجلسات",self:"الحساب الحالي",empty:"لا يوجد عضو مطابق."},
  en:{title:"Admin team & access",sub:"Create administrators, assign roles, enable or disable accounts, and control active sessions",search:"Search name, email or role...",find:"Search",new:"Add administrator",name:"Name",email:"Email",role:"Role",password:"Password",passHelp:"At least 12 characters",active:"Account active",create:"Create administrator",members:"Team members",sessions:"active sessions",lastSeen:"Last activity",never:"No activity",save:"Save changes",reset:"Optional new password",revoke:"Revoke all sessions",self:"Current account",empty:"No team member matched."},
  tr:{title:"Yönetim ekibi ve erişimler",sub:"Yönetici oluşturun, rol atayın, hesapları etkinleştirin ve oturumları kontrol edin",search:"Ad, e-posta veya rol ara...",find:"Ara",new:"Yeni yönetici",name:"Ad",email:"E-posta",role:"Rol",password:"Parola",passHelp:"En az 12 karakter",active:"Hesap aktif",create:"Yönetici oluştur",members:"Ekip üyeleri",sessions:"aktif oturum",lastSeen:"Son etkinlik",never:"Etkinlik yok",save:"Kaydet",reset:"İsteğe bağlı yeni parola",revoke:"Tüm oturumları sonlandır",self:"Mevcut hesap",empty:"Eşleşen ekip üyesi yok."}
};
const roles:AdminRole[]=["SUPER_ADMIN","EDITOR","SUPPORT","SALES"];

export default async function AdminTeamPage({searchParams}:{searchParams:Promise<{q?:string}>}){
  const session=await requireAdminRole(["SUPER_ADMIN"]);
  const [{q=""},l]=await Promise.all([searchParams,currentAdminLocale()]);
  const query=q.trim().slice(0,100),t=C[l];
  const members=await adminRpc<Member[]>("admin_team_list",{p_search:query});
  return <div className="mx-auto max-w-6xl space-y-6">
    <div><div className="flex items-center gap-2 text-[#009dd8]"><ShieldCheck className="h-5 w-5"/><span className="text-xs font-black uppercase">RBAC</span></div><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.sub}</p></div>
    <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-black"><UserPlus className="h-5 w-5"/>{t.new}</h2><form action={saveAdminTeamMember} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input name="name" required minLength={2} maxLength={120} placeholder={t.name} className="h-11 rounded-xl border px-3"/><input name="email" required type="email" dir="ltr" placeholder={t.email} className="h-11 rounded-xl border px-3"/><select name="role" defaultValue="EDITOR" className="h-11 rounded-xl border px-3">{roles.map(r=><option key={r} value={r}>{adminRoleLabels[l][r]}</option>)}</select><input name="password" required type="password" minLength={12} maxLength={200} dir="ltr" placeholder={`${t.password} — ${t.passHelp}`} className="h-11 rounded-xl border px-3"/><div className="flex items-center gap-2"><label className="flex flex-1 items-center gap-2 text-xs font-bold"><input name="isActive" type="checkbox" defaultChecked/>{t.active}</label><button className="h-11 rounded-xl bg-[#001736] px-4 text-xs font-black text-white">{t.create}</button></div></form></section>
    <form action="/admin/team" className="flex gap-2"><label className="relative flex-1"><Search className="pointer-events-none absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9a9da5]"/><input name="q" defaultValue={query} placeholder={t.search} className="h-11 w-full rounded-xl border bg-white ps-10 pe-3"/></label><button className="rounded-xl bg-[#001736] px-5 text-xs font-black text-white">{t.find}</button></form>
    <section className="space-y-3"><h2 className="font-black text-[#001736]">{t.members} — {adminNumber(members.length,l)}</h2>{members.map(m=>{const self=m.id===session.id;return <article key={m.id} className="rounded-2xl border bg-white p-5 shadow-sm"><form action={saveAdminTeamMember} className="grid gap-3 lg:grid-cols-[1fr_1.2fr_.9fr_.9fr_auto]"><input type="hidden" name="id" value={m.id}/><input name="name" defaultValue={m.name} required className="h-11 rounded-xl border px-3"/><input name="email" defaultValue={m.email} required type="email" dir="ltr" className="h-11 rounded-xl border px-3"/>{self?<><input type="hidden" name="role" value={m.role}/><div className="flex h-11 items-center rounded-xl bg-[#f4f7fb] px-3 text-xs font-black">{adminRoleLabels[l][m.role]} · {t.self}</div></>:<select name="role" defaultValue={m.role} className="h-11 rounded-xl border px-3">{roles.map(r=><option key={r} value={r}>{adminRoleLabels[l][r]}</option>)}</select>}{self?<><input type="hidden" name="isActive" value="on"/><div className="flex h-11 items-center rounded-xl bg-emerald-50 px-3 text-xs font-black text-emerald-700">{t.active}</div></>:<label className="flex h-11 items-center gap-2 rounded-xl border px-3 text-xs font-bold"><input name="isActive" type="checkbox" defaultChecked={m.isActive}/>{t.active}</label>}<button className="h-11 rounded-xl bg-[#e80346] px-4 text-xs font-black text-white">{t.save}</button>{!self?<div className="lg:col-span-5 grid gap-3 sm:grid-cols-[1fr_auto]"><label className="relative"><KeyRound className="absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9a9da5]"/><input name="password" type="password" minLength={12} maxLength={200} dir="ltr" placeholder={`${t.reset} — ${t.passHelp}`} className="h-10 w-full rounded-xl border ps-10 pe-3 text-xs"/></label><div/></div>:null}</form><div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t pt-3 text-xs text-[#747780]"><span>{adminNumber(m.activeSessions,l)} {t.sessions} · {t.lastSeen}: {m.lastSeenAt?adminDateTime(m.lastSeenAt,l):t.never}</span>{!self?<form action={revokeAdminSessions}><input type="hidden" name="id" value={m.id}/><button className="rounded-lg border border-red-200 px-3 py-2 font-black text-red-700">{t.revoke}</button></form>:null}</div></article>})}{members.length===0?<div className="rounded-2xl border bg-white p-10 text-center text-sm text-[#747780]">{t.empty}</div>:null}</section>
  </div>;
}
