import { getLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { Bot, BookOpenText, CircleHelp, Headphones, LifeBuoy, Search, ShieldCheck, TicketCheck, TriangleAlert, UserRound, Wrench } from "lucide-react";
import { Container } from "@/components/ui/container";
import { SupportForm } from "@/components/site/support-form";
import { getCustomerSession } from "@/lib/customer-auth";

const pick=(locale:string,fa:string,en:string,tr:string,ar:string)=>locale==="en"?en:locale==="tr"?tr:locale==="ar"?ar:fa;
export default async function SupportPage() {
 const [locale,customer]=await Promise.all([getLocale(),getCustomerSession()]);
 const c={title:pick(locale,"چگونه می‌توانیم به شما کمک کنیم؟","How can we help?","Size nasıl yardımcı olabiliriz?","كيف يمكننا مساعدتك؟"),body:pick(locale,"مرکز پشتیبانی Hyper Doctor برای راهنمای تجهیزات، گارانتی، گزارش خرابی و پیگیری درخواست‌ها در دسترس شماست.","Hyper Doctor support brings device guidance, warranty, fault reporting and ticket tracking together.","Hyper Doctor destek merkezi cihaz rehberi, garanti, arıza bildirimi ve talep takibini bir araya getirir.","يجمع مركز دعم Hyper Doctor إرشادات الأجهزة والضمان والإبلاغ عن الأعطال وتتبع الطلبات."),search:pick(locale,"پاسخ سوال خود را در راهنما پیدا کنید","Find an answer in the help center","Yardım merkezinde yanıt bulun","ابحث عن إجابة في مركز المساعدة"),supportCats:pick(locale,"دسته‌بندی‌های پشتیبانی","Support categories","Destek kategorileri","فئات الدعم"),ticket:pick(locale,"پیگیری خودکار تیکت‌ها","Track support tickets","Destek taleplerini takip et","تتبع تذاكر الدعم"),newTicket:pick(locale,"ثبت درخواست جدید","Create a new request","Yeni talep oluştur","إنشاء طلب جديد"),account:pick(locale,"ورود به پنل کاربری","Open customer portal","Müşteri portalını aç","فتح بوابة العميل")};
 const cards=[
  {icon:Wrench,title:pick(locale,"عیب‌یابی دستگاه‌ها","Device troubleshooting","Cihaz sorun giderme","استكشاف أعطال الأجهزة"),body:pick(locale,"مشکل فنی، روشن‌نشدن، هشدار و سرویس تجهیزات را ثبت کنید.","Report technical faults, alarms and service needs.","Teknik arıza, alarm ve servis ihtiyaçlarını bildirin.","أبلغ عن الأعطال والتنبيهات واحتياجات الصيانة."),href:"#new-ticket"},
  {icon:BookOpenText,title:pick(locale,"دفترچه راهنما و سوالات","Guides & common questions","Kılavuzlar ve sorular","الأدلة والأسئلة"),body:pick(locale,"پاسخ‌های ایمن و کاربردی برای استفاده و نگهداری تجهیزات.","Practical guidance for using and maintaining equipment.","Cihaz kullanımı ve bakımı için pratik rehberler.","إرشادات عملية لاستخدام الأجهزة وصيانتها."),href:"/faq"},
  {icon:TriangleAlert,title:pick(locale,"گزارش خرابی","Fault report","Arıza bildirimi","الإبلاغ عن عطل"),body:pick(locale,"مدل، سریال و شرح مشکل را برای بررسی تیم فنی ارسال کنید.","Send model, serial and fault details to the technical team.","Model, seri ve arıza ayrıntılarını teknik ekibe gönderin.","أرسل الطراز والرقم التسلسلي وتفاصيل العطل للفريق الفني."),href:"#new-ticket"},
  {icon:ShieldCheck,title:pick(locale,"گارانتی و خدمات پس از فروش","Warranty & after-sales","Garanti ve satış sonrası","الضمان وما بعد البيع"),body:pick(locale,"ثبت، استعلام و پیگیری پوشش گارانتی تجهیزات.","Register and check equipment warranty coverage.","Cihaz garantisini kaydedin ve sorgulayın.","سجل وتحقق من تغطية ضمان الأجهزة."),href:"/warranty"},
 ];
 return <main className="flex-1 bg-[#f5f8fb] pb-16 pt-6 sm:pt-10"><Container>
  <section className="relative overflow-hidden rounded-[2rem] border border-[#dfe4ea] bg-[#f8fbff] px-6 py-9 shadow-[0_18px_55px_rgba(0,23,54,.06)] sm:px-10 lg:px-14 lg:py-12"><div className="absolute start-10 top-1/2 hidden h-32 w-32 -translate-y-1/2 items-center justify-center rounded-full bg-[#001736] text-white shadow-[0_16px_35px_rgba(0,23,54,.18)] lg:flex"><Bot className="h-14 w-14 text-[#8eb7f2]"/></div><div className="mx-auto max-w-3xl text-center lg:me-0 lg:max-w-[70%] lg:text-start"><p className="text-xs font-black uppercase tracking-[.18em] text-[#ba0036]">Hyper Doctor Support</p><h1 className="mt-4 text-3xl font-black leading-[1.3] text-[#001736] sm:text-5xl">{c.title}</h1><p className="mt-4 text-sm leading-8 text-[#5f6570] sm:text-base">{c.body}</p><Link href="/faq" className="mt-6 flex min-h-14 items-center gap-3 rounded-2xl border border-[#c4c6d0] bg-white px-4 text-sm text-[#747780] shadow-sm transition hover:border-[#001736]/35"><Search className="h-5 w-5 text-[#001736]"/><span className="flex-1 text-start">{c.search}</span><span className="rounded-xl bg-[#001736] px-4 py-2 text-xs font-black text-white">{pick(locale,"جستجو","Search","Ara","بحث")}</span></Link></div></section>

  <section className="mt-8 grid gap-6 lg:grid-cols-[.72fr_1.28fr]"><div><div className="mb-4 flex items-center gap-2"><CircleHelp className="h-5 w-5 text-[#001736]"/><h2 className="text-xl font-black text-[#001736]">{c.supportCats}</h2></div><div className="space-y-3">{cards.map(({icon:Icon,title,body,href})=><Link key={title} href={href} className="flex items-center gap-4 rounded-2xl border border-[#dfe4ea] bg-white p-4 shadow-[0_8px_25px_rgba(0,23,54,.035)] transition hover:border-[#009dd8]/45"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#edf4ff] text-[#002b5b]"><Icon className="h-5 w-5"/></span><span className="min-w-0"><strong className="block text-sm font-black text-[#001736]">{title}</strong><span className="mt-1 block text-xs leading-6 text-[#747780]">{body}</span></span></Link>)}</div></div>
   <div className="grid gap-4 sm:grid-cols-2"><article className="rounded-[1.75rem] border border-[#dfe4ea] bg-white p-6 shadow-[0_14px_38px_rgba(0,23,54,.045)]"><Headphones className="h-7 w-7 text-[#009dd8]"/><h2 className="mt-4 text-xl font-black text-[#001736]">{pick(locale,"پشتیبانی تخصصی تجهیزات","Specialist equipment support","Uzman cihaz desteği","دعم متخصص للأجهزة")}</h2><p className="mt-3 text-sm leading-7 text-[#5f6570]">{pick(locale,"برای طبقه‌بندی سریع‌تر مشکل، مدل دستگاه، شماره سریال و شرح واضح خرابی را وارد کنید.","Include model, serial number and a clear description for faster classification.","Daha hızlı sınıflandırma için model, seri ve açık arıza açıklaması ekleyin.","أدخل الطراز والرقم التسلسلي ووصفاً واضحاً للعطل لتسريع التصنيف.")}</p><a href="#new-ticket" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-[#001736] px-4 text-xs font-black text-white">{c.newTicket}</a></article><article className="rounded-[1.75rem] border border-[#dfe4ea] bg-white p-6 shadow-[0_14px_38px_rgba(0,23,54,.045)]"><TicketCheck className="h-7 w-7 text-[#ba0036]"/><h2 className="mt-4 text-xl font-black text-[#001736]">{c.ticket}</h2><p className="mt-3 text-sm leading-7 text-[#5f6570]">{pick(locale,"وضعیت و پاسخ‌های درخواست‌های پشتیبانی را از پنل خود مشاهده کنید یا با شناسه امن پیگیری کنید.","Review ticket status and replies in your account or use secure guest tracking.","Talep durumunu ve yanıtları hesabınızdan ya da güvenli takip ile görüntüleyin.","راجع حالة التذاكر والردود من حسابك أو عبر التتبع الآمن.")}</p><div className="mt-5 flex flex-wrap gap-2"><Link href={customer?"/account/support":"/account/login"} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#ba0036] px-4 text-xs font-black text-white"><UserRound className="h-4 w-4"/>{customer?c.ticket:c.account}</Link><Link href="/support/status" className="inline-flex min-h-11 items-center rounded-xl border border-[#c4c6d0] px-4 text-xs font-black text-[#001736]">{pick(locale,"پیگیری مهمان","Guest tracking","Misafir takibi","تتبع الضيف")}</Link></div></article></div>
  </section>
  <section id="new-ticket" className="mt-8 scroll-mt-28"><div className="mb-4"><p className="text-xs font-black uppercase tracking-[.15em] text-[#ba0036]">RMA / Technical Care</p><h2 className="mt-2 text-2xl font-black text-[#001736]">{c.newTicket}</h2></div><SupportForm/></section>
  <section className="mt-8 flex flex-col justify-between gap-5 rounded-[1.75rem] bg-[#001736] px-6 py-7 text-white sm:flex-row sm:items-center sm:px-8"><div><LifeBuoy className="h-6 w-6 text-[#82cfff]"/><h2 className="mt-3 text-lg font-black">{c.ticket}</h2><p className="mt-1 text-sm text-white/60">{pick(locale,"وضعیت درخواست‌های خود را همیشه از مسیر امن بررسی کنید.","Always review your requests through the secure tracking flow.","Taleplerinizi her zaman güvenli takip akışından kontrol edin.","راجع طلباتك دائماً عبر مسار التتبع الآمن.")}</p></div><Link href={customer?"/account/support":"/support/status"} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white px-5 text-xs font-black text-[#001736]"><TicketCheck className="h-4 w-4"/>{c.ticket}</Link></section>
 </Container></main>;
}
