import Link from "next/link";
import { ArrowUpLeft, BarChart3, CircleDollarSign, CreditCard, Package, ShoppingBag, Users } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";

type ReportBundle = {
  summary: { orders: number; paidOrders: number; revenue: number; discounts: number; shipping: number; customers: number; products: number; lowStock: number };
  recent: Array<{ id:string; orderNumber:string; customerName:string; total:number; status:string; gateway:string; paymentRefId?:string|null; createdAt:string }>;
  daily: Array<{ dateKey:string; orderCount:number; revenue:number }>;
};
const money=(n:number)=>new Intl.NumberFormat("fa-IR").format(n);

export default async function AdminReportsPage(){
  const data=await adminRpc<ReportBundle>("admin_reports_bundle");
  const max=Math.max(1,...data.daily.map(d=>d.revenue));
  const paidRate=data.summary.orders?Math.round((data.summary.paidOrders/data.summary.orders)*100):0;
  const cards=[
    {label:"فروش خالص",value:`${money(data.summary.revenue)} تومان`,sub:"پرداخت‌های تأییدشده",icon:CircleDollarSign,tone:"text-emerald-700 bg-emerald-50"},
    {label:"کل سفارش‌ها",value:money(data.summary.orders),sub:`${money(data.summary.paidOrders)} پرداخت‌شده`,icon:ShoppingBag,tone:"text-[#002b5b] bg-[#edf4ff]"},
    {label:"نرخ پرداخت",value:`${money(paidRate)}٪`,sub:"نسبت سفارش موفق",icon:CreditCard,tone:"text-[#ba0036] bg-[#fff0f3]"},
    {label:"مشتریان",value:money(data.summary.customers),sub:`${money(data.summary.products)} محصول`,icon:Users,tone:"text-[#725400] bg-amber-50"},
  ];
  return <div className="mx-auto max-w-[1450px] space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">Sales Intelligence</p><h1 className="mt-2 text-3xl font-black text-[#001736]">گزارش عملکرد فروش</h1><p className="mt-2 text-sm text-[#747780]">نمای تحلیلی فروش، سفارش‌ها و رفتار پرداخت بر اساس داده واقعی</p></div><Link href="/admin/transactions" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#001736] px-4 text-xs font-black text-white"><CreditCard className="h-4 w-4"/>تراکنش‌های مالی</Link></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,sub,icon:Icon,tone})=><article key={label} className="rounded-[1.5rem] border border-[#e2e6eb] bg-white p-5 shadow-[0_12px_30px_rgba(0,23,54,.04)]"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5"/></div><p className="mt-4 text-xs font-black text-[#747780]">{label}</p><p className="mt-1 text-2xl font-black tabular-nums text-[#001736]">{value}</p><p className="mt-1 text-[11px] text-[#9a9da5]">{sub}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-[.68fr_1.32fr]">
      <section className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-[#747780]">خلاصه مالی</p><h2 className="mt-1 text-lg font-black text-[#001736]">ترکیب سفارش‌ها</h2></div><BarChart3 className="h-5 w-5 text-[#009dd8]"/></div><div className="mt-6 flex items-center justify-center"><div className="relative flex h-44 w-44 items-center justify-center rounded-full" style={{background:`conic-gradient(#001736 0 ${paidRate}%, #e80346 ${paidRate}% ${Math.min(100,paidRate+Math.round((data.summary.discounts/Math.max(1,data.summary.revenue))*100))}%, #e9edf2 0)`}}><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full bg-white"><span className="text-3xl font-black text-[#001736]">{money(paidRate)}٪</span><span className="text-[10px] font-bold text-[#747780]">پرداخت موفق</span></div></div></div><div className="mt-6 grid gap-2 text-xs"><div className="flex justify-between rounded-xl bg-[#f7fafd] px-3 py-2"><span>تخفیف‌ها</span><b>{money(data.summary.discounts)}</b></div><div className="flex justify-between rounded-xl bg-[#f7fafd] px-3 py-2"><span>هزینه ارسال</span><b>{money(data.summary.shipping)}</b></div><div className="flex justify-between rounded-xl bg-[#f7fafd] px-3 py-2"><span>کم‌موجود</span><b>{money(data.summary.lowStock)}</b></div></div></section>
      <section className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-[#747780]">۳۰ روز اخیر</p><h2 className="mt-1 text-lg font-black text-[#001736]">روند فروش</h2></div><span className="rounded-full bg-[#edf4ff] px-3 py-1.5 text-[10px] font-black text-[#002b5b]">Revenue Trend</span></div><div className="mt-7 flex h-60 items-end gap-1.5 overflow-x-auto border-b border-[#edf0f2] pb-1">{data.daily.map(d=><div key={d.dateKey} className="group flex min-w-5 flex-1 flex-col items-center justify-end gap-2" title={`${d.dateKey} — ${money(d.revenue)}`}><div className="w-full rounded-t-lg bg-[#d6e3ff] transition group-hover:bg-[#002b5b]" style={{height:`${Math.max(6,(d.revenue/max)*205)}px`}}/><span className="hidden text-[9px] text-[#9a9da5] 2xl:block">{d.dateKey.slice(5)}</span></div>)}{data.daily.length===0?<div className="m-auto text-sm text-[#8a8e96]">هنوز فروش ثبت‌شده‌ای وجود ندارد.</div>:null}</div></section>
    </div>
    <section className="overflow-hidden rounded-[1.6rem] border border-[#e2e6eb] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#edf0f2] px-5 py-4"><div><h2 className="font-black text-[#001736]">تراکنش‌های اخیر</h2><p className="mt-1 text-[11px] text-[#8a8e96]">آخرین سفارش‌های ثبت‌شده</p></div><Link href="/admin/transactions" className="inline-flex items-center gap-1 text-xs font-black text-[#e80346]">مشاهده همه<ArrowUpLeft className="h-3.5 w-3.5"/></Link></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-[#f7fafd] text-[11px] font-black text-[#747780]"><tr><th className="px-5 py-3 text-start">سفارش</th><th className="px-5 py-3 text-start">مشتری</th><th className="px-5 py-3 text-start">درگاه</th><th className="px-5 py-3 text-start">مبلغ</th><th className="px-5 py-3 text-start">وضعیت</th><th className="px-5 py-3 text-start">تاریخ</th></tr></thead><tbody className="divide-y divide-[#edf0f2]">{data.recent.map(r=><tr key={r.id} className="hover:bg-[#fafcff]"><td className="px-5 py-4 font-mono text-xs font-black text-[#002b5b]" dir="ltr">{r.orderNumber}</td><td className="px-5 py-4 font-bold text-[#43474f]">{r.customerName}</td><td className="px-5 py-4 text-xs text-[#747780]" dir="ltr">{r.gateway || "—"}</td><td className="px-5 py-4 font-black tabular-nums text-[#001736]">{money(r.total)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${r.status==="PAID"?"bg-emerald-50 text-emerald-700":r.status==="FAILED"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{r.status}</span></td><td className="px-5 py-4 text-xs text-[#747780]">{new Date(r.createdAt).toLocaleString("fa-IR")}</td></tr>)}{data.recent.length===0?<tr><td colSpan={6} className="px-5 py-12 text-center text-[#8a8e96]">تراکنشی ثبت نشده است.</td></tr>:null}</tbody></table></div></section>
  </div>;
}
