import Link from "next/link";
import { notFound } from "next/navigation";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import type { AdminLocale } from "@/lib/admin-i18n";
import { PrintButton } from "@/components/admin/print-button";

type RentalDetail={id:string;productId:string;customerName:string;phone:string;email?:string|null;preferredStartDate?:string|null;preferredEndDate?:string|null;address?:string|null;notes?:string|null;locale:string;status:string;adminNotes?:string|null;createdAt:string;updatedAt:string;sku:string;modelNumber?:string|null;nameFa:string;nameTr:string;nameEn:string;nameAr:string;brandName?:string|null};
const C:Record<AdminLocale,Record<string,string>>={fa:{title:"فرم درخواست اجاره تجهیزات",print:"چاپ",back:"بازگشت",request:"شماره درخواست",product:"محصول",brand:"برند",sku:"SKU",model:"مدل",customer:"نام مشتری",phone:"تلفن",email:"ایمیل",period:"بازه ترجیحی",address:"آدرس",notes:"توضیحات مشتری",adminNotes:"یادداشت داخلی",status:"وضعیت",created:"تاریخ ثبت",signature:"امضا / تأیید مسئول"},tr:{title:"Ekipman kiralama talep formu",print:"Yazdır",back:"Geri",request:"Talep no",product:"Ürün",brand:"Marka",sku:"SKU",model:"Model",customer:"Müşteri",phone:"Telefon",email:"E-posta",period:"Tercih edilen dönem",address:"Adres",notes:"Müşteri notları",adminNotes:"İç not",status:"Durum",created:"Oluşturulma",signature:"Yetkili imza / onay"},en:{title:"Medical equipment rental request",print:"Print",back:"Back",request:"Request ID",product:"Product",brand:"Brand",sku:"SKU",model:"Model",customer:"Customer",phone:"Phone",email:"Email",period:"Preferred period",address:"Address",notes:"Customer notes",adminNotes:"Internal notes",status:"Status",created:"Created",signature:"Responsible staff signature / approval"},ar:{title:"نموذج طلب استئجار المعدات",print:"طباعة",back:"رجوع",request:"رقم الطلب",product:"المنتج",brand:"العلامة",sku:"SKU",model:"الموديل",customer:"العميل",phone:"الهاتف",email:"البريد الإلكتروني",period:"الفترة المفضلة",address:"العنوان",notes:"ملاحظات العميل",adminNotes:"ملاحظات داخلية",status:"الحالة",created:"تاريخ الإنشاء",signature:"توقيع / اعتماد المسؤول"}};
function localName(r:RentalDetail,l:AdminLocale){return({fa:r.nameFa,tr:r.nameTr,en:r.nameEn,ar:r.nameAr}[l]||r.nameEn||r.nameFa)}
function Row({k,v}:{k:string;v:string}){return <div className="grid grid-cols-[150px_1fr] border-b border-[#d7dce2] py-2.5 text-sm last:border-0"><b className="text-[#5f6570]">{k}</b><span className="break-words font-semibold text-[#101828]">{v||"—"}</span></div>}
export default async function RentalPrintPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const[locale,row]=await Promise.all([currentAdminLocale(),adminRpc<RentalDetail|null>("admin_rental_request_detail",{p_id:id})]);if(!row)notFound();const t=C[locale],dir=locale==="fa"||locale==="ar"?"rtl":"ltr";return <main dir={dir} className="min-h-screen bg-[#eef1f4] p-4 print:bg-white print:p-0"><style>{`@page{size:A4;margin:12mm} @media print{body{background:white!important}.rental-sheet{box-shadow:none!important;border:0!important;max-width:none!important}}`}</style><div className="mx-auto mb-3 flex max-w-[190mm] justify-between gap-2 print:hidden"><Link href={`/admin/rentals/${id}`} className="inline-flex min-h-10 items-center rounded-xl border bg-white px-4 text-xs font-black">{t.back}</Link><PrintButton label={t.print}/></div><article className="rental-sheet mx-auto max-w-[190mm] rounded-2xl border border-[#cfd5dc] bg-white p-[10mm] shadow-sm"><header className="border-b-2 border-[#001736] pb-4"><p className="text-xs font-black tracking-[.16em] text-[#009dd8]">VITALIS GROUP · HYPER DOCTOR</p><h1 className="mt-2 text-2xl font-black text-[#001736]">{t.title}</h1><div className="mt-3 flex flex-wrap justify-between gap-3 text-xs text-[#5f6570]"><span><b>{t.request}:</b> <span dir="ltr">{row.id}</span></span><span><b>{t.created}:</b> {new Date(row.createdAt).toLocaleString(locale)}</span></div></header><section className="mt-5"><Row k={t.product} v={localName(row,locale)}/><Row k={t.brand} v={row.brandName||"—"}/><Row k={t.sku} v={row.sku}/><Row k={t.model} v={row.modelNumber||"—"}/><Row k={t.customer} v={row.customerName}/><Row k={t.phone} v={row.phone}/><Row k={t.email} v={row.email||"—"}/><Row k={t.period} v={`${row.preferredStartDate||"—"} → ${row.preferredEndDate||"—"}`}/><Row k={t.address} v={row.address||"—"}/><Row k={t.status} v={row.status}/></section><section className="mt-5 grid gap-4 md:grid-cols-2"><div className="min-h-28 rounded-xl border border-[#d7dce2] p-4"><p className="text-xs font-black text-[#5f6570]">{t.notes}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{row.notes||"—"}</p></div><div className="min-h-28 rounded-xl border border-[#d7dce2] p-4"><p className="text-xs font-black text-[#5f6570]">{t.adminNotes}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{row.adminNotes||"—"}</p></div></section><footer className="mt-10 grid grid-cols-2 gap-8 text-xs font-bold text-[#5f6570]"><div className="border-t border-[#9aa0aa] pt-2">{t.signature}</div><div className="border-t border-[#9aa0aa] pt-2">HYPER DOCTOR</div></footer></article></main>}
