import { AlertTriangle, Boxes, PackageCheck, Search, Warehouse } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminDate, adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { adjustStock } from "./actions";

type Movement={delta:number;reason:string;note:string;createdAt:string};
type ProductStock={id:string;sku:string;nameFa:string;nameEn:string;brand:string;stock:number;lowStockThreshold:number;isPublished:boolean;movements:Movement[]};
type InventoryBundle={products:ProductStock[];totalStock:number;lowStock:number};
const c:Record<AdminLocale,Record<string,string>>={
  fa:{eyebrow:"کنترل موجودی",title:"مدیریت موجودی تجهیزات",subtitle:"کنترل موجودی، هشدار کمبود و ثبت گردش انبار بر اساس داده واقعی",total:"کل موجودی",low:"کم‌موجود",healthy:"موجودی سالم",searchPlaceholder:"جستجو با نام، SKU یا برند...",search:"جستجو",noBrand:"بدون برند",threshold:"آستانه هشدار",published:"منتشرشده",draft:"پیش‌نویس",current:"موجودی فعلی",purchase:"خرید/ورود",sale:"اصلاح فروش",return:"مرجوعی",damaged:"آسیب‌دیده",manual:"اصلاح دستی",notePlaceholder:"یادداشت اختیاری",submit:"ثبت تغییر",change:"تغییر",reason:"علت",note:"یادداشت",time:"زمان",empty:"هنوز محصولی برای مدیریت موجودی وجود ندارد."},
  ar:{eyebrow:"التحكم بالمخزون",title:"إدارة مخزون المعدات",subtitle:"متابعة المخزون والتنبيه عند الانخفاض وتسجيل حركات المستودع اعتماداً على البيانات الفعلية",total:"إجمالي المخزون",low:"مخزون منخفض",healthy:"مخزون سليم",searchPlaceholder:"ابحث بالاسم أو SKU أو العلامة التجارية...",search:"بحث",noBrand:"بدون علامة تجارية",threshold:"حد التنبيه",published:"منشور",draft:"مسودة",current:"المخزون الحالي",purchase:"شراء/إدخال",sale:"تعديل مبيعات",return:"مرتجع",damaged:"تالف",manual:"تعديل يدوي",notePlaceholder:"ملاحظة اختيارية",submit:"تسجيل التغيير",change:"التغيير",reason:"السبب",note:"ملاحظة",time:"الوقت",empty:"لا توجد منتجات لإدارة المخزون بعد."},
  en:{eyebrow:"Inventory Control",title:"Equipment inventory management",subtitle:"Monitor stock, low-stock alerts and warehouse movements from live data",total:"Total stock",low:"Low stock",healthy:"Healthy stock",searchPlaceholder:"Search by name, SKU or brand...",search:"Search",noBrand:"No brand",threshold:"Alert threshold",published:"Published",draft:"Draft",current:"Current stock",purchase:"Purchase / inbound",sale:"Sales adjustment",return:"Return",damaged:"Damaged",manual:"Manual adjustment",notePlaceholder:"Optional note",submit:"Save change",change:"Change",reason:"Reason",note:"Note",time:"Time",empty:"There are no products to manage in inventory yet."},
  tr:{eyebrow:"Stok Kontrolü",title:"Ekipman stok yönetimi",subtitle:"Canlı verilerle stokları, düşük stok uyarılarını ve depo hareketlerini yönetin",total:"Toplam stok",low:"Düşük stok",healthy:"Sağlıklı stok",searchPlaceholder:"Ad, SKU veya marka ile ara...",search:"Ara",noBrand:"Markasız",threshold:"Uyarı eşiği",published:"Yayında",draft:"Taslak",current:"Mevcut stok",purchase:"Satın alma / giriş",sale:"Satış düzeltmesi",return:"İade",damaged:"Hasarlı",manual:"Manuel düzeltme",notePlaceholder:"İsteğe bağlı not",submit:"Değişikliği kaydet",change:"Değişim",reason:"Neden",note:"Not",time:"Zaman",empty:"Henüz yönetilecek stok ürünü yok."}
};
const reasonText=(reason:string,l:AdminLocale,t:Record<string,string>)=>({PURCHASE:t.purchase,SALE_ADJUSTMENT:t.sale,RETURN:t.return,DAMAGED:t.damaged,MANUAL:t.manual}[reason]||reason);

export default async function AdminInventoryPage({searchParams}:{searchParams:Promise<{q?:string}>}){
  const {q=""}=await searchParams;
  const [data,l]=await Promise.all([adminRpc<InventoryBundle>("admin_inventory",{p_search:q}),currentAdminLocale()]);
  const t=c[l];
  const healthy=data.products.filter(p=>p.stock>p.lowStockThreshold).length;
  return <div className="mx-auto max-w-[1450px] space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.subtitle}</p></div></div>
    <div className="grid gap-4 md:grid-cols-3"><Metric label={t.total} value={adminNumber(data.totalStock,l)} icon={Boxes}/><Metric label={t.low} value={adminNumber(data.lowStock,l)} icon={AlertTriangle}/><Metric label={t.healthy} value={adminNumber(healthy,l)} icon={Warehouse}/></div>
    <form className="flex gap-3 rounded-[1.5rem] border border-[#e2e6eb] bg-white p-4 shadow-sm"><label className="relative flex-1"><Search className="pointer-events-none absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9a9da5]"/><input name="q" defaultValue={q} placeholder={t.searchPlaceholder} className="h-11 w-full rounded-xl border border-[#dfe4ea] bg-[#f7fafd] ps-11 pe-4 text-sm outline-none focus:border-[#009dd8]"/></label><button className="rounded-xl bg-[#001736] px-5 text-xs font-black text-white">{t.search}</button></form>
    <div className="space-y-4">{data.products.map(p=>{const action=adjustStock.bind(null,p.id);const low=p.stock<=p.lowStockThreshold;return <article key={p.id} className="overflow-hidden rounded-[1.6rem] border border-[#e2e6eb] bg-white shadow-sm"><div className="flex flex-col justify-between gap-4 border-b border-[#edf0f2] p-5 xl:flex-row xl:items-center"><div className="flex items-start gap-3"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${low?"bg-red-50 text-[#e80346]":"bg-[#edf4ff] text-[#002b5b]"}`}><PackageCheck className="h-5 w-5"/></span><div><p dir="ltr" className="font-mono text-[10px] font-black text-[#009dd8]">{p.sku}</p><h2 className="mt-1 text-lg font-black text-[#001736]">{p.nameFa||p.nameEn}</h2><p className="mt-1 text-xs text-[#747780]">{p.brand||t.noBrand} · {t.threshold} {adminNumber(p.lowStockThreshold,l)}</p></div></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1.5 text-[10px] font-black ${p.isPublished?"bg-emerald-50 text-emerald-700":"bg-[#f1f4f7] text-[#747780]"}`}>{p.isPublished?t.published:t.draft}</span><div className={`min-w-28 rounded-xl px-4 py-3 text-center ${low?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}><div className="text-2xl font-black">{adminNumber(p.stock,l)}</div><div className="text-[10px] font-black">{t.current}</div></div></div></div>
      <div className="p-5"><form action={action} className="grid gap-3 md:grid-cols-[120px_170px_1fr_auto]"><input name="delta" type="number" step="1" required placeholder="+10 / -2" className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm outline-none focus:border-[#009dd8]"/><select name="reason" className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"><option value="PURCHASE">{t.purchase}</option><option value="SALE_ADJUSTMENT">{t.sale}</option><option value="RETURN">{t.return}</option><option value="DAMAGED">{t.damaged}</option><option value="MANUAL">{t.manual}</option></select><input name="note" placeholder={t.notePlaceholder} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm outline-none focus:border-[#009dd8]"/><button className="h-11 rounded-xl bg-[#e80346] px-5 text-xs font-black text-white">{t.submit}</button></form>{p.movements.length?<div className="mt-5 overflow-x-auto rounded-2xl border border-[#edf0f2]"><table className="w-full min-w-[620px] text-xs"><thead className="bg-[#f7fafd] text-[#747780]"><tr><th className="px-4 py-3 text-start">{t.change}</th><th className="px-4 py-3 text-start">{t.reason}</th><th className="px-4 py-3 text-start">{t.note}</th><th className="px-4 py-3 text-start">{t.time}</th></tr></thead><tbody className="divide-y divide-[#edf0f2]">{p.movements.map((m,i)=><tr key={`${m.createdAt}-${i}`}><td className={`px-4 py-3 font-black ${m.delta>0?"text-emerald-700":"text-red-700"}`} dir="ltr">{m.delta>0?`+${m.delta}`:m.delta}</td><td className="px-4 py-3">{reasonText(m.reason,l,t)}</td><td className="px-4 py-3 text-[#747780]">{m.note||"—"}</td><td className="px-4 py-3 text-[#747780]">{adminDate(m.createdAt,l)}</td></tr>)}</tbody></table></div>:null}</div></article>})}{data.products.length===0?<div className="rounded-[1.6rem] border border-dashed border-[#cfd5dc] bg-white p-12 text-center text-sm text-[#8a8e96]">{t.empty}</div>:null}</div>
  </div>;
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof Boxes}){return <article className="rounded-[1.5rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf4ff] text-[#002b5b]"><Icon className="h-5 w-5"/></span><p className="mt-4 text-xs font-black text-[#747780]">{label}</p><p className="mt-1 text-2xl font-black text-[#001736]">{value}</p></article>}
