import Link from "next/link";
import { CheckCircle2, CircleDollarSign, ImageOff, PackageCheck, Search, ShieldAlert, Store, Warehouse } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { saveBranchPrice, saveWarehouseStock } from "./actions";

type Branch={id:string;code:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;currency:string;isPublished:boolean;salesEnabled?:boolean;paymentGateway?:string};
type WarehouseRow={id:string;code:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;isActive:boolean};
type ProductRow={id:string;sku:string;slug:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;published:boolean;hasImage:boolean;hasVariants:boolean;effectivePrice:number;compareAtPrice:number|null;available:number;ready:boolean;blockers:string[]};
type Bundle={branch:Branch|null;branches:Branch[];warehouses:WarehouseRow[];products:ProductRow[];summary:{total:number;ready:number;blocked:number}};
type WarehouseInventory={productId:string;onHand:number;reserved:number;available:number};
const copy={
fa:{eyebrow:"مرکز کنترل لانچ",title:"کنترل تجارت و آماده‌سازی فروش",subtitle:"قیمت واقعی شعبه، موجودی واقعی انبار و وضعیت نهایی قابل‌فروش بودن هر محصول در یک صفحه",branch:"شعبه",search:"جستجو",ready:"آماده فروش",blocked:"مسدود",total:"کل محصولات",sales:"فروش شعبه",gateway:"درگاه",price:"قیمت جاری شعبه",compare:"قیمت قبل",savePrice:"ثبت قیمت",stock:"موجودی قابل فروش",warehouse:"انبار",onHand:"موجودی فیزیکی",reserved:"رزرو",saveStock:"ثبت موجودی",edit:"ویرایش محصول",variants:"مدیریت Variant",noProducts:"هنوز محصولی وجود ندارد.",noWarehouse:"برای این شعبه انبار فعالی تعریف نشده است.",yes:"فعال",no:"غیرفعال"},
ar:{eyebrow:"مركز إطلاق التجارة",title:"التحكم بجاهزية المتجر",subtitle:"السعر الفعلي للفرع والمخزون الفعلي وحالة قابلية البيع في شاشة واحدة",branch:"الفرع",search:"بحث",ready:"جاهز للبيع",blocked:"محظور",total:"إجمالي المنتجات",sales:"مبيعات الفرع",gateway:"بوابة الدفع",price:"سعر الفرع الحالي",compare:"السعر السابق",savePrice:"حفظ السعر",stock:"المخزون المتاح",warehouse:"المستودع",onHand:"المخزون الفعلي",reserved:"محجوز",saveStock:"حفظ المخزون",edit:"تعديل المنتج",variants:"إدارة التنويعات",noProducts:"لا توجد منتجات بعد.",noWarehouse:"لا يوجد مستودع نشط لهذا الفرع.",yes:"مفعّل",no:"معطّل"},
en:{eyebrow:"Launch control center",title:"Commerce readiness control",subtitle:"Real branch price, real warehouse stock and final sellability status in one workspace",branch:"Branch",search:"Search",ready:"Sellable",blocked:"Blocked",total:"Products",sales:"Branch sales",gateway:"Gateway",price:"Current branch price",compare:"Compare-at",savePrice:"Save price",stock:"Available stock",warehouse:"Warehouse",onHand:"On hand",reserved:"Reserved",saveStock:"Save stock",edit:"Edit product",variants:"Manage variants",noProducts:"No products yet.",noWarehouse:"No active warehouse exists for this branch.",yes:"Enabled",no:"Disabled"},
tr:{eyebrow:"Lansman kontrol merkezi",title:"Ticaret hazırlık kontrolü",subtitle:"Gerçek şube fiyatı, gerçek depo stoğu ve satışa hazır olma durumu tek ekranda",branch:"Şube",search:"Ara",ready:"Satışa hazır",blocked:"Engelli",total:"Ürünler",sales:"Şube satışı",gateway:"Ödeme altyapısı",price:"Güncel şube fiyatı",compare:"Eski fiyat",savePrice:"Fiyatı kaydet",stock:"Satılabilir stok",warehouse:"Depo",onHand:"Fiziksel stok",reserved:"Rezerve",saveStock:"Stoğu kaydet",edit:"Ürünü düzenle",variants:"Varyantları yönet",noProducts:"Henüz ürün yok.",noWarehouse:"Bu şube için aktif depo yok.",yes:"Aktif",no:"Pasif"}
} as const;
function name(row:{nameFa:string;nameTr:string;nameEn:string;nameAr:string},l:AdminLocale){return({fa:row.nameFa,tr:row.nameTr,en:row.nameEn,ar:row.nameAr}[l]||row.nameEn||row.nameFa)}
const blockerCopy:Record<AdminLocale,Record<string,string>>={fa:{NOT_PUBLISHED:"منتشر نشده",IMAGE_MISSING:"تصویر واقعی ندارد",SALES_DISABLED:"فروش شعبه غیرفعال",GATEWAY_NOT_ZARINPAL:"درگاه زرین‌پال فعال نیست",CURRENCY_NOT_IRT:"ارز شعبه تومان نیست",NO_SELLABLE_VARIANT:"Variant قابل فروش ندارد",PRICE_MISSING:"قیمت جاری ندارد",STOCK_MISSING:"موجودی واقعی ندارد"},ar:{NOT_PUBLISHED:"غير منشور",IMAGE_MISSING:"لا توجد صورة حقيقية",SALES_DISABLED:"مبيعات الفرع معطلة",GATEWAY_NOT_ZARINPAL:"زرين پال غير مفعّل",CURRENCY_NOT_IRT:"عملة الفرع ليست تومان",NO_SELLABLE_VARIANT:"لا يوجد تنويع قابل للبيع",PRICE_MISSING:"لا يوجد سعر حالي",STOCK_MISSING:"لا يوجد مخزون فعلي"},en:{NOT_PUBLISHED:"Not published",IMAGE_MISSING:"Real image missing",SALES_DISABLED:"Branch sales disabled",GATEWAY_NOT_ZARINPAL:"Zarinpal not enabled",CURRENCY_NOT_IRT:"Branch currency is not IRT",NO_SELLABLE_VARIANT:"No sellable variant",PRICE_MISSING:"Current price missing",STOCK_MISSING:"Real stock missing"},tr:{NOT_PUBLISHED:"Yayında değil",IMAGE_MISSING:"Gerçek görsel eksik",SALES_DISABLED:"Şube satışı kapalı",GATEWAY_NOT_ZARINPAL:"Zarinpal aktif değil",CURRENCY_NOT_IRT:"Şube para birimi IRT değil",NO_SELLABLE_VARIANT:"Satılabilir varyant yok",PRICE_MISSING:"Güncel fiyat eksik",STOCK_MISSING:"Gerçek stok eksik"}};

export default async function CommercePage({searchParams}:{searchParams:Promise<{branch?:string;q?:string}>}){
 const{branch="",q=""}=await searchParams;const l=await currentAdminLocale(),t=copy[l];
 const data=await adminRpc<Bundle>("admin_commerce_control_center",{p_branch_id:branch||null,p_search:q||null});
 const activeWarehouses=data.warehouses.filter(w=>w.isActive);const inventories=await Promise.all(activeWarehouses.map(async w=>({warehouse:w,rows:await adminRpc<WarehouseInventory[]>("admin_warehouse_inventory",{p_warehouse_id:w.id,p_search:q||null})})));
 const invByWarehouse=new Map(inventories.map(x=>[x.warehouse.id,new Map(x.rows.map(r=>[r.productId,r]))]));
 return <div className="mx-auto max-w-[1550px] space-y-6"><header><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.subtitle}</p></header>
 <div className="grid gap-4 md:grid-cols-3"><Metric icon={Store} label={t.total} value={adminNumber(data.summary.total,l)}/><Metric icon={CheckCircle2} label={t.ready} value={adminNumber(data.summary.ready,l)} good/><Metric icon={ShieldAlert} label={t.blocked} value={adminNumber(data.summary.blocked,l)} warn/></div>
 <section className="rounded-[1.5rem] border border-[#e2e6eb] bg-white p-4 shadow-sm"><form className="grid gap-3 lg:grid-cols-[260px_1fr_auto]"><select name="branch" defaultValue={data.branch?.id||""} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm">{data.branches.map(b=><option key={b.id} value={b.id}>{name(b,l)} · {b.code}</option>)}</select><label className="relative"><Search className="absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9aa0aa]"/><input name="q" defaultValue={q} className="h-11 w-full rounded-xl border border-[#dfe4ea] bg-[#f7fafd] ps-11 pe-3 text-sm"/></label><button className="h-11 rounded-xl bg-[#001736] px-6 text-xs font-black text-white">{t.search}</button></form>{data.branch?<div className="mt-4 flex flex-wrap gap-2 text-xs"><Badge label={`${t.branch}: ${name(data.branch,l)}`}/><Badge label={`${t.sales}: ${data.branch.salesEnabled?t.yes:t.no}`} ok={data.branch.salesEnabled}/><Badge label={`${t.gateway}: ${data.branch.paymentGateway||"DISABLED"}`} ok={data.branch.paymentGateway==="ZARINPAL"}/><Badge label={data.branch.currency}/></div>:null}</section>
 <div className="space-y-4">{data.products.map(p=><article key={p.id} className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-[10px] font-black ${p.ready?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{p.ready?t.ready:t.blocked}</span>{!p.hasImage?<ImageOff className="h-4 w-4 text-red-500"/>:null}</div><p dir="ltr" className="mt-3 font-mono text-[10px] font-black text-[#009dd8]">{p.sku}</p><h2 className="mt-1 text-lg font-black text-[#001736]">{name(p,l)}</h2><div className="mt-2 flex flex-wrap gap-1.5">{p.blockers.map(b=><span key={b} className="rounded-lg bg-[#fff3f6] px-2 py-1 text-[10px] font-bold text-[#a4002e]">{blockerCopy[l][b]||b}</span>)}</div></div><div className="text-end"><p className="text-xs text-[#747780]">{t.stock}</p><p className="text-2xl font-black text-[#001736]">{adminNumber(p.available,l)}</p></div></div>
 <div className="mt-5 grid gap-4 xl:grid-cols-[1fr_1.4fr_auto]"><form action={saveBranchPrice} className="rounded-2xl border border-[#edf0f2] bg-[#f7fafd] p-4"><input type="hidden" name="branchId" value={data.branch?.id||""}/><input type="hidden" name="productId" value={p.id}/><div className="grid gap-2 sm:grid-cols-2"><label className="text-[11px] font-bold text-[#5f6570]">{t.price}<input name="price" type="number" min="1" step="1" defaultValue={p.effectivePrice>0?p.effectivePrice:""} required className="mt-1 h-10 w-full rounded-xl border border-[#dfe4ea] bg-white px-3"/></label><label className="text-[11px] font-bold text-[#5f6570]">{t.compare}<input name="compareAtPrice" type="number" min="0" step="1" defaultValue={p.compareAtPrice??""} className="mt-1 h-10 w-full rounded-xl border border-[#dfe4ea] bg-white px-3"/></label></div><button className="mt-3 h-10 w-full rounded-xl bg-[#002b5b] text-xs font-black text-white"><CircleDollarSign className="me-1 inline h-4 w-4"/>{t.savePrice}</button></form>
 {p.hasVariants?<div className="rounded-2xl border border-[#edf0f2] bg-[#f7fafd] p-4"><p className="text-xs font-bold text-[#747780]">{blockerCopy[l].NO_SELLABLE_VARIANT}</p><Link href={`/admin/products/${p.id}/variants`} className="mt-3 inline-flex h-10 items-center rounded-xl bg-[#001736] px-4 text-xs font-black text-white">{t.variants}</Link></div>:activeWarehouses.length?<form action={saveWarehouseStock} className="rounded-2xl border border-[#edf0f2] bg-[#f7fafd] p-4"><input type="hidden" name="productId" value={p.id}/><div className="grid gap-2 sm:grid-cols-3"><label className="text-[11px] font-bold text-[#5f6570]">{t.warehouse}<select name="warehouseId" className="mt-1 h-10 w-full rounded-xl border border-[#dfe4ea] bg-white px-2">{activeWarehouses.map(w=><option key={w.id} value={w.id}>{name(w,l)} · {w.code}</option>)}</select></label><label className="text-[11px] font-bold text-[#5f6570]">{t.onHand}<input name="onHand" type="number" min="0" step="1" defaultValue={invByWarehouse.get(activeWarehouses[0].id)?.get(p.id)?.onHand??0} required className="mt-1 h-10 w-full rounded-xl border border-[#dfe4ea] bg-white px-3"/></label><label className="text-[11px] font-bold text-[#5f6570]">{t.reserved}<input name="reserved" type="number" min="0" step="1" defaultValue={invByWarehouse.get(activeWarehouses[0].id)?.get(p.id)?.reserved??0} required className="mt-1 h-10 w-full rounded-xl border border-[#dfe4ea] bg-white px-3"/></label></div><button className="mt-3 h-10 w-full rounded-xl bg-[#e80346] text-xs font-black text-white"><Warehouse className="me-1 inline h-4 w-4"/>{t.saveStock}</button></form>:<div className="rounded-2xl border border-dashed border-[#d5dbe2] bg-[#f7fafd] p-4 text-xs text-[#747780]">{t.noWarehouse}</div>}
 <Link href={`/admin/products/${p.id}`} className="flex min-h-12 items-center justify-center rounded-2xl border border-[#dfe4ea] px-5 text-xs font-black text-[#001736]">{t.edit}</Link></div></article>)}{data.products.length===0?<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-sm text-[#8a8e96]">{t.noProducts}</div>:null}</div></div>
}
function Metric({icon:Icon,label,value,good,warn}:{icon:typeof PackageCheck;label:string;value:string;good?:boolean;warn?:boolean}){return <article className="rounded-[1.5rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${good?"bg-emerald-50 text-emerald-700":warn?"bg-red-50 text-red-700":"bg-[#edf4ff] text-[#002b5b]"}`}><Icon className="h-5 w-5"/></span><p className="mt-4 text-xs font-black text-[#747780]">{label}</p><p className="mt-1 text-2xl font-black text-[#001736]">{value}</p></article>}
function Badge({label,ok}:{label:string;ok?:boolean}){return <span className={`rounded-full px-3 py-1.5 font-bold ${ok===false?"bg-red-50 text-red-700":ok?"bg-emerald-50 text-emerald-700":"bg-[#f1f4f7] text-[#5f6570]"}`}>{label}</span>}
