import Link from "next/link";
import { Database, FileClock, Upload } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminNumber, type AdminLocale } from "@/lib/admin-i18n";

type Source={id:string;sourceType:string;title:string;sourceDate:string|null;reference:string;status:string;productCount:number};
const C:Record<AdminLocale,Record<string,string>>={fa:{eyebrow:"ردیابی داده",title:"منابع کاتالوگ",desc:"منبع هر داده محصول و سابقه قیمت بدون مخلوط شدن با قیمت و موجودی جاری فروشگاه.",import:"ورود کاتالوگ",empty:"هنوز منبعی ثبت نشده است.",type:"نوع",source:"منبع",date:"تاریخ",reference:"مرجع",products:"محصولات",status:"وضعیت"},en:{eyebrow:"Data provenance",title:"Catalog sources",desc:"Trace product data and historical prices without mixing them with current store price or stock.",import:"Import catalog",empty:"No catalog source has been registered yet.",type:"Type",source:"Source",date:"Date",reference:"Reference",products:"Products",status:"Status"},tr:{eyebrow:"Veri kaynağı",title:"Katalog kaynakları",desc:"Ürün verisini ve geçmiş fiyatları güncel mağaza fiyatı ve stoğundan ayrı izleyin.",import:"Katalog aktar",empty:"Henüz katalog kaynağı yok.",type:"Tür",source:"Kaynak",date:"Tarih",reference:"Referans",products:"Ürünler",status:"Durum"},ar:{eyebrow:"مصدر البيانات",title:"مصادر الكتالوج",desc:"تتبع بيانات المنتجات والأسعار التاريخية دون خلطها بالسعر أو المخزون الحالي.",import:"استيراد كتالوج",empty:"لم يتم تسجيل أي مصدر بعد.",type:"النوع",source:"المصدر",date:"التاريخ",reference:"المرجع",products:"المنتجات",status:"الحالة"}};
export default async function Page(){const[locale,sources]=await Promise.all([currentAdminLocale(),adminRpc<Source[]>("admin_catalog_sources")]);const t=C[locale];return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-[#009dd8]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black">{t.title}</h1><p className="mt-2 max-w-3xl text-sm text-[#747780]">{t.desc}</p></div><Link href="/admin/products/import" className="inline-flex min-h-11 items-center gap-2 rounded-2xl bg-[#002b5b] px-5 text-sm font-black text-white"><Upload className="h-4 w-4"/>{t.import}</Link></div><section className="mt-7 overflow-hidden rounded-3xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr>{[t.type,t.source,t.date,t.reference,t.products,t.status].map(x=><th key={x} className="border-b px-5 py-3 text-start">{x}</th>)}</tr></thead><tbody>{sources.map(s=><tr key={s.id} className="border-b last:border-0"><td className="px-5 py-4"><span className="rounded-full bg-[#eef4ff] px-3 py-1 text-xs font-black text-[#002b5b]">{s.sourceType}</span></td><td className="px-5 py-4"><div className="flex items-center gap-2"><Database className="h-4 w-4 text-[#009dd8]"/><b>{s.title}</b></div></td><td className="px-5 py-4" dir="ltr">{s.sourceDate||"—"}</td><td className="max-w-xs truncate px-5 py-4" title={s.reference}>{s.reference||"—"}</td><td className="px-5 py-4">{adminNumber(Number(s.productCount||0),locale)}</td><td className="px-5 py-4">{s.status}</td></tr>)}{!sources.length?<tr><td colSpan={6} className="px-6 py-16 text-center"><FileClock className="mx-auto h-8 w-8 text-[#9aa0aa]"/><p className="mt-4 font-black">{t.empty}</p></td></tr>:null}</tbody></table></div></section></div>}
