import { CheckboxField, TextAreaField, TextField } from "@/components/admin/form-field";
import { ImageUploadField } from "@/components/admin/image-upload-field";
import { RichTextEditor } from "@/components/admin/rich-text-editor";
import { upsertArticle } from "@/app/admin/(protected)/articles/actions";

type ArticleValue={id?:string;slug?:string;titleFa?:string;titleTr?:string;titleEn?:string;titleAr?:string;excerptFa?:string;excerptTr?:string;excerptEn?:string;excerptAr?:string;contentFa?:string;contentTr?:string;contentEn?:string;contentAr?:string;coverImage?:string;category?:string;tags?:string;isPublished?:boolean};
function Editor({label,name,value,dir}:{label:string;name:string;value?:string;dir:"rtl"|"ltr"}){return <div><span className="mb-1.5 block text-xs font-medium text-muted">{label}</span><RichTextEditor name={name} defaultValue={value} dir={dir}/></div>}
export function ArticleForm({article}:{article?:ArticleValue}){return <form action={upsertArticle} className="max-w-6xl space-y-6 pb-16">{article?.id?<input type="hidden" name="id" value={article.id}/>:null}
<section className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-4 font-black text-foreground">اطلاعات مقاله</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><TextField label="عنوان فارسی" name="titleFa" defaultValue={article?.titleFa} required/><TextField label="Türkçe başlık" name="titleTr" defaultValue={article?.titleTr} dir="ltr"/><TextField label="English title" name="titleEn" defaultValue={article?.titleEn} dir="ltr" required/><TextField label="العنوان العربي" name="titleAr" defaultValue={article?.titleAr}/></div><div className="mt-4 grid gap-4 md:grid-cols-3"><TextField label="اسلاگ" name="slug" defaultValue={article?.slug} dir="ltr"/><TextField label="دسته مقاله" name="category" defaultValue={article?.category}/><TextField label="برچسب‌ها (JSON Array)" name="tags" defaultValue={article?.tags??"[]"} dir="ltr"/></div></section>
<section className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-4 font-black text-foreground">خلاصه چهارزبانه</h2><div className="grid gap-4 lg:grid-cols-2"><TextAreaField label="خلاصه فارسی" name="excerptFa" defaultValue={article?.excerptFa} rows={4}/><TextAreaField label="Türkçe özet" name="excerptTr" defaultValue={article?.excerptTr} rows={4} dir="ltr"/><TextAreaField label="English excerpt" name="excerptEn" defaultValue={article?.excerptEn} rows={4} dir="ltr"/><TextAreaField label="الملخص العربي" name="excerptAr" defaultValue={article?.excerptAr} rows={4}/></div></section>
<section className="grid gap-5 xl:grid-cols-2"><Editor label="محتوای فارسی" name="contentFa" value={article?.contentFa} dir="rtl"/><Editor label="Türkçe içerik" name="contentTr" value={article?.contentTr} dir="ltr"/><Editor label="English content" name="contentEn" value={article?.contentEn} dir="ltr"/><Editor label="المحتوى العربي" name="contentAr" value={article?.contentAr} dir="rtl"/></section>
<section className="rounded-2xl border border-border bg-card p-5"><ImageUploadField label="تصویر کاور" name="coverImage" defaultValue={article?.coverImage}/><div className="mt-5"><CheckboxField label="منتشر شده" name="isPublished" defaultChecked={article?.isPublished}/></div></section>
<div className="sticky bottom-4 z-20 flex justify-end"><button className="min-h-12 rounded-xl bg-primary px-8 text-sm font-black text-white shadow-lg">ذخیره مقاله</button></div></form>}
