import { CheckboxField, TextAreaField, TextField } from "@/components/admin/form-field";
import { ImageUploadField } from "@/components/admin/image-upload-field";
import { RichTextEditor } from "@/components/admin/rich-text-editor";
import { upsertArticle } from "@/app/admin/(protected)/articles/actions";
import type { AdminLocale } from "@/lib/admin-i18n";

type ArticleValue={id?:string;slug?:string;titleFa?:string;titleTr?:string;titleEn?:string;titleAr?:string;excerptFa?:string;excerptTr?:string;excerptEn?:string;excerptAr?:string;contentFa?:string;contentTr?:string;contentEn?:string;contentAr?:string;coverImage?:string;category?:string;tags?:string;isPublished?:boolean};
const c:Record<AdminLocale,Record<string,string>>={
  fa:{info:"اطلاعات مقاله",faTitle:"عنوان فارسی",trTitle:"عنوان ترکی",enTitle:"عنوان انگلیسی",arTitle:"عنوان عربی",slug:"اسلاگ",category:"دسته مقاله",tags:"برچسب‌ها (JSON Array)",summaries:"خلاصه چهارزبانه",faExcerpt:"خلاصه فارسی",trExcerpt:"خلاصه ترکی",enExcerpt:"خلاصه انگلیسی",arExcerpt:"خلاصه عربی",faContent:"محتوای فارسی",trContent:"محتوای ترکی",enContent:"محتوای انگلیسی",arContent:"محتوای عربی",cover:"تصویر کاور",published:"منتشر شده",save:"ذخیره مقاله"},
  ar:{info:"معلومات المقالة",faTitle:"العنوان الفارسي",trTitle:"العنوان التركي",enTitle:"العنوان الإنجليزي",arTitle:"العنوان العربي",slug:"المسار المختصر",category:"تصنيف المقالة",tags:"الوسوم (JSON Array)",summaries:"الملخص بأربع لغات",faExcerpt:"الملخص الفارسي",trExcerpt:"الملخص التركي",enExcerpt:"الملخص الإنجليزي",arExcerpt:"الملخص العربي",faContent:"المحتوى الفارسي",trContent:"المحتوى التركي",enContent:"المحتوى الإنجليزي",arContent:"المحتوى العربي",cover:"صورة الغلاف",published:"منشورة",save:"حفظ المقالة"},
  en:{info:"Article information",faTitle:"Persian title",trTitle:"Turkish title",enTitle:"English title",arTitle:"Arabic title",slug:"Slug",category:"Article category",tags:"Tags (JSON Array)",summaries:"Four-language summary",faExcerpt:"Persian excerpt",trExcerpt:"Turkish excerpt",enExcerpt:"English excerpt",arExcerpt:"Arabic excerpt",faContent:"Persian content",trContent:"Turkish content",enContent:"English content",arContent:"Arabic content",cover:"Cover image",published:"Published",save:"Save article"},
  tr:{info:"Makale bilgileri",faTitle:"Farsça başlık",trTitle:"Türkçe başlık",enTitle:"İngilizce başlık",arTitle:"Arapça başlık",slug:"Slug",category:"Makale kategorisi",tags:"Etiketler (JSON Array)",summaries:"Dört dilli özet",faExcerpt:"Farsça özet",trExcerpt:"Türkçe özet",enExcerpt:"İngilizce özet",arExcerpt:"Arapça özet",faContent:"Farsça içerik",trContent:"Türkçe içerik",enContent:"İngilizce içerik",arContent:"Arapça içerik",cover:"Kapak görseli",published:"Yayında",save:"Makaleyi kaydet"}
};
function Editor({label,name,value,dir}:{label:string;name:string;value?:string;dir:"rtl"|"ltr"}){return <div><span className="mb-1.5 block text-xs font-medium text-muted">{label}</span><RichTextEditor name={name} defaultValue={value} dir={dir}/></div>}
export function ArticleForm({article,locale="fa"}:{article?:ArticleValue;locale?:AdminLocale}){const t=c[locale];return <form action={upsertArticle} className="max-w-6xl space-y-6 pb-16">{article?.id?<input type="hidden" name="id" value={article.id}/>:null}
<section className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-4 font-black text-foreground">{t.info}</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><TextField label={t.faTitle} name="titleFa" defaultValue={article?.titleFa} required/><TextField label={t.trTitle} name="titleTr" defaultValue={article?.titleTr} dir="ltr"/><TextField label={t.enTitle} name="titleEn" defaultValue={article?.titleEn} dir="ltr" required/><TextField label={t.arTitle} name="titleAr" defaultValue={article?.titleAr}/></div><div className="mt-4 grid gap-4 md:grid-cols-3"><TextField label={t.slug} name="slug" defaultValue={article?.slug} dir="ltr"/><TextField label={t.category} name="category" defaultValue={article?.category}/><TextField label={t.tags} name="tags" defaultValue={article?.tags??"[]"} dir="ltr"/></div></section>
<section className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-4 font-black text-foreground">{t.summaries}</h2><div className="grid gap-4 lg:grid-cols-2"><TextAreaField label={t.faExcerpt} name="excerptFa" defaultValue={article?.excerptFa} rows={4}/><TextAreaField label={t.trExcerpt} name="excerptTr" defaultValue={article?.excerptTr} rows={4} dir="ltr"/><TextAreaField label={t.enExcerpt} name="excerptEn" defaultValue={article?.excerptEn} rows={4} dir="ltr"/><TextAreaField label={t.arExcerpt} name="excerptAr" defaultValue={article?.excerptAr} rows={4}/></div></section>
<section className="grid gap-5 xl:grid-cols-2"><Editor label={t.faContent} name="contentFa" value={article?.contentFa} dir="rtl"/><Editor label={t.trContent} name="contentTr" value={article?.contentTr} dir="ltr"/><Editor label={t.enContent} name="contentEn" value={article?.contentEn} dir="ltr"/><Editor label={t.arContent} name="contentAr" value={article?.contentAr} dir="rtl"/></section>
<section className="rounded-2xl border border-border bg-card p-5"><ImageUploadField label={t.cover} name="coverImage" defaultValue={article?.coverImage}/><div className="mt-5"><CheckboxField label={t.published} name="isPublished" defaultChecked={article?.isPublished}/></div></section>
<div className="sticky bottom-4 z-20 flex justify-end"><button className="min-h-12 rounded-xl bg-primary px-8 text-sm font-black text-white shadow-lg">{t.save}</button></div></form>}
