"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, FileSpreadsheet, Loader2, ShieldCheck, UploadCloud } from "lucide-react";
import { adminNumber, type AdminLocale } from "@/lib/admin-i18n";

type PreflightRow={line:number;sku:string;slug:string;action:"create"|"update";errors:string[];warnings:string[]};
type Preflight={total:number;create:number;update:number;errorRows:number;warningRows:number;canApply:boolean;rows:PreflightRow[]};
type Result={mode:"preview"|"apply";created?:number;updated?:number;failed?:number;format?:string;preflight:Preflight;source?:{id?:string;sourceType:string;title:string;sourceDate?:string|null;reference?:string};policy?:Record<string,string>;errors?:{line:number;sku:string;error:string}[]};

const ISSUE:Record<string,Record<AdminLocale,string>>={
 missing_sku:{fa:"SKU وارد نشده",tr:"SKU eksik",en:"SKU is missing",ar:"SKU مفقود"},missing_category:{fa:"دسته‌بندی وارد نشده",tr:"Kategori eksik",en:"Category is missing",ar:"الفئة مفقودة"},unknown_category:{fa:"categorySlug در سایت وجود ندارد",tr:"categorySlug sitede yok",en:"categorySlug does not exist",ar:"categorySlug غير موجود"},duplicate_sku_in_file:{fa:"SKU در فایل تکراری است",tr:"Dosyada yinelenen SKU",en:"Duplicate SKU in file",ar:"SKU مكرر في الملف"},slug_conflict:{fa:"Slug با محصول دیگری تداخل دارد",tr:"Slug başka ürünle çakışıyor",en:"Slug conflicts with another product",ar:"Slug يتعارض مع منتج آخر"},missing_price:{fa:"قیمت جاری وارد نشده",tr:"Güncel fiyat eksik",en:"Current price is missing",ar:"السعر الحالي مفقود"},missing_image:{fa:"تصویر محصول ثبت نشده",tr:"Ürün görseli eksik",en:"Product image is missing",ar:"صورة المنتج مفقودة"},out_of_stock:{fa:"موجودی جاری صفر است",tr:"Güncel stok sıfır",en:"Current stock is zero",ar:"المخزون الحالي صفر"},publish_requires_price:{fa:"محصول Published باید قیمت جاری معتبر داشته باشد",tr:"Published ürün geçerli güncel fiyat gerektirir",en:"Published product requires a valid current price",ar:"المنتج المنشور يحتاج سعراً حالياً صالحاً"},publish_requires_image:{fa:"محصول Published باید تصویر داشته باشد",tr:"Published ürün görsel gerektirir",en:"Published product requires an image",ar:"المنتج المنشور يحتاج صورة"},missing_name_fa:{fa:"نام فارسی ناقص است",tr:"Farsça ad eksik",en:"Persian name is missing",ar:"الاسم الفارسي مفقود"},missing_name_tr:{fa:"نام ترکی ناقص است",tr:"Türkçe ad eksik",en:"Turkish name is missing",ar:"الاسم التركي مفقود"},missing_name_en:{fa:"نام انگلیسی ناقص است",tr:"İngilizce ad eksik",en:"English name is missing",ar:"الاسم الإنجليزي مفقود"},missing_name_ar:{fa:"نام عربی ناقص است",tr:"Arapça ad eksik",en:"Arabic name is missing",ar:"الاسم العربي مفقود"},missing_slug:{fa:"Slug قابل تولید نیست",tr:"Slug üretilemiyor",en:"Slug cannot be generated",ar:"تعذر إنشاء Slug"}
};
const TEXT:Record<AdminLocale,Record<string,string>>={
 fa:{heading:"ورود واقعی کاتالوگ با منبع قابل رهگیری",description:"ابتدا منبع و سیاست قیمت/موجودی را مشخص کن. فایل Preview می‌شود و هیچ ردیفی تا تأیید نهایی نوشته نمی‌شود.",source:"منبع داده",sourceType:"نوع منبع",sourceTitle:"عنوان منبع",sourceDate:"تاریخ منبع",reference:"مرجع / شماره نسخه",commerce:"رفتار قیمت و موجودی",priceTreatment:"قیمت فایل",stockTreatment:"موجودی فایل",priceKind:"نوع قیمت تاریخی",currency:"واحد پول",ignore:"وارد داده جاری نشود",current:"به‌عنوان داده جاری ثبت شود",historical:"فقط به‌عنوان سابقه قیمت ذخیره شود",template:"دانلود قالب خالی CSV",choose:"CSV، XLSX یا PDF انتخاب کن",selected:"فایل انتخاب‌شده",limits:"حداکثر 5MB · ۲۰۰۰ محصول · PDF حداکثر ۱۰۰ صفحه",select:"انتخاب فایل",preview:"بررسی و پیش‌نمایش",previewBusy:"در حال اعتبارسنجی...",apply:"تأیید و ورود واقعی",applyBusy:"در حال ثبت...",previewOk:"Preflight کامل شد",blocked:"فایل خطای مسدودکننده دارد",created:"جدید",updated:"به‌روزرسانی",errors:"خطادار",warnings:"هشدار",row:"ردیف",issues:"موارد نیازمند بررسی",completed:"Import واقعی با Provenance ثبت شد",tips:"قانون لانچ",tipsBody:"کاتالوگ و لیست قیمت تاریخی نباید قیمت یا موجودی جاری فروشگاه را تغییر دهند. Current فقط وقتی انتخاب شود که فایل واقعاً منبع جاری Hyper Doctor باشد. هر محصول واردشده به منبع خود متصل می‌شود.",genericError:"عملیات ناموفق بود."},
 en:{heading:"Real catalog import with traceable provenance",description:"Define the source and commerce policy first. The file is previewed and no row is written before explicit confirmation.",source:"Data source",sourceType:"Source type",sourceTitle:"Source title",sourceDate:"Source date",reference:"Reference / version",commerce:"Price & stock policy",priceTreatment:"File price",stockTreatment:"File stock",priceKind:"Historical price type",currency:"Currency",ignore:"Do not write as current data",current:"Write as current data",historical:"Store only as historical price",template:"Download blank CSV",choose:"Choose CSV, XLSX or PDF",selected:"Selected file",limits:"5MB max · 2,000 products · PDF 100 pages",select:"Choose file",preview:"Validate & preview",previewBusy:"Validating...",apply:"Confirm real import",applyBusy:"Writing...",previewOk:"Preflight completed",blocked:"Blocking errors found",created:"New",updated:"Updates",errors:"Errors",warnings:"Warnings",row:"Row",issues:"Review items",completed:"Real import stored with provenance",tips:"Launch rule",tipsBody:"Catalogs and historical price lists must not change current store price or stock. Choose Current only for a verified current Hyper Doctor source. Every imported product is linked to its source.",genericError:"Operation failed."},
 tr:{heading:"İzlenebilir kaynakla gerçek katalog aktarımı",description:"Önce kaynak ve fiyat/stok politikasını belirleyin. Dosya önizlenir; açık onaydan önce hiçbir satır yazılmaz.",source:"Veri kaynağı",sourceType:"Kaynak türü",sourceTitle:"Kaynak başlığı",sourceDate:"Kaynak tarihi",reference:"Referans / sürüm",commerce:"Fiyat ve stok politikası",priceTreatment:"Dosya fiyatı",stockTreatment:"Dosya stoğu",priceKind:"Geçmiş fiyat türü",currency:"Para birimi",ignore:"Güncel veri olarak yazma",current:"Güncel veri olarak yaz",historical:"Yalnız geçmiş fiyat olarak sakla",template:"Boş CSV indir",choose:"CSV, XLSX veya PDF seçin",selected:"Seçilen dosya",limits:"En fazla 5MB · 2.000 ürün · PDF 100 sayfa",select:"Dosya seç",preview:"Doğrula ve önizle",previewBusy:"Doğrulanıyor...",apply:"Onayla ve gerçek aktarım",applyBusy:"Kaydediliyor...",previewOk:"Ön kontrol tamamlandı",blocked:"Engelleyici hatalar bulundu",created:"Yeni",updated:"Güncelleme",errors:"Hata",warnings:"Uyarı",row:"Satır",issues:"İncelenecekler",completed:"Kaynak bilgisiyle gerçek aktarım tamamlandı",tips:"Lansman kuralı",tipsBody:"Kataloglar ve geçmiş fiyat listeleri güncel mağaza fiyatını veya stoğunu değiştirmemelidir. Current yalnız doğrulanmış güncel Hyper Doctor kaynağı için seçilmelidir.",genericError:"İşlem başarısız."},
 ar:{heading:"استيراد كتالوج حقيقي مع مصدر قابل للتتبع",description:"حدد المصدر وسياسة السعر والمخزون أولاً. تتم المعاينة ولا تتم كتابة أي صف قبل التأكيد الصريح.",source:"مصدر البيانات",sourceType:"نوع المصدر",sourceTitle:"عنوان المصدر",sourceDate:"تاريخ المصدر",reference:"المرجع / الإصدار",commerce:"سياسة السعر والمخزون",priceTreatment:"سعر الملف",stockTreatment:"مخزون الملف",priceKind:"نوع السعر التاريخي",currency:"العملة",ignore:"لا تسجله كبيانات حالية",current:"سجله كبيانات حالية",historical:"احفظه كسعر تاريخي فقط",template:"تنزيل CSV فارغ",choose:"اختر CSV أو XLSX أو PDF",selected:"الملف المحدد",limits:"5MB · 2000 منتج · PDF 100 صفحة",select:"اختيار الملف",preview:"تحقق ومعاينة",previewBusy:"جارٍ التحقق...",apply:"تأكيد الاستيراد الحقيقي",applyBusy:"جارٍ الحفظ...",previewOk:"اكتمل الفحص",blocked:"تم العثور على أخطاء مانعة",created:"جديد",updated:"تحديث",errors:"أخطاء",warnings:"تحذيرات",row:"صف",issues:"بحاجة للمراجعة",completed:"اكتمل الاستيراد مع حفظ المصدر",tips:"قاعدة الإطلاق",tipsBody:"الكتالوجات وقوائم الأسعار التاريخية لا يجب أن تغير سعر أو مخزون المتجر الحالي. اختر Current فقط لمصدر Hyper Doctor الحالي الموثق.",genericError:"فشلت العملية."}
};
const sourceTypes=["CATALOG","PRICE_LIST","INVENTORY_EXPORT","SUPPLIER_FILE","MANUAL_ADMIN","OTHER"];
const priceKinds=["SELLING","PARTNER","PURCHASE","CONSUMER","OTHER"];
function issueLabel(code:string,locale:AdminLocale){return ISSUE[code]?.[locale]||code.replaceAll("_"," ")}

export function ProductImportPanel({locale}:{locale:AdminLocale}){
 const t=TEXT[locale],ref=useRef<HTMLInputElement>(null);const[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState<"preview"|"apply"|null>(null),[error,setError]=useState<string|null>(null),[result,setResult]=useState<Result|null>(null);
 const[sourceType,setSourceType]=useState("CATALOG"),[sourceTitle,setSourceTitle]=useState(""),[sourceDate,setSourceDate]=useState(""),[sourceReference,setSourceReference]=useState("");const[priceTreatment,setPriceTreatment]=useState("ignore"),[stockTreatment,setStockTreatment]=useState("ignore"),[priceKind,setPriceKind]=useState("OTHER"),[currency,setCurrency]=useState("IRT");
 async function run(mode:"preview"|"apply"){if(!file||!sourceTitle.trim())return;setBusy(mode);setError(null);if(mode==="preview")setResult(null);try{const body=new FormData();body.append("file",file);body.append("mode",mode);body.append("sourceType",sourceType);body.append("sourceTitle",sourceTitle.trim());body.append("sourceDate",sourceDate);body.append("sourceReference",sourceReference.trim());body.append("priceTreatment",priceTreatment);body.append("stockTreatment",stockTreatment);body.append("priceKind",priceKind);body.append("currency",currency);const response=await fetch("/api/admin/products/import",{method:"POST",body}),data=await response.json().catch(()=>({}));if(!response.ok){if(data.preflight)setResult(data);throw new Error(data.error||t.genericError)}setResult(data)}catch(e){setError(e instanceof Error?e.message:t.genericError)}finally{setBusy(null)}}
 const p=result?.preflight,problemRows=p?.rows.filter(x=>x.errors.length||x.warnings.length)??[];
 const input="min-h-11 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary";
 return <div className="space-y-5">
  <section className="rounded-2xl border bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-base font-black">{t.heading}</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-muted">{t.description}</p></div><Link href="/templates/product-import-template.csv" target="_blank" className="inline-flex min-h-10 items-center gap-2 rounded-xl border bg-muted-bg px-4 text-xs font-bold"><FileSpreadsheet className="h-4 w-4"/>{t.template}</Link></div>
   <div className="mt-6 grid gap-4 rounded-2xl border bg-muted-bg/40 p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold">{t.sourceType}<select className={`${input} mt-2`} value={sourceType} onChange={e=>{setSourceType(e.target.value);setResult(null)}}>{sourceTypes.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-bold">{t.sourceTitle}<input className={`${input} mt-2`} value={sourceTitle} onChange={e=>{setSourceTitle(e.target.value);setResult(null)}} required/></label><label className="text-xs font-bold">{t.sourceDate}<input type="date" className={`${input} mt-2`} value={sourceDate} onChange={e=>{setSourceDate(e.target.value);setResult(null)}}/></label><label className="text-xs font-bold">{t.reference}<input className={`${input} mt-2`} value={sourceReference} onChange={e=>{setSourceReference(e.target.value);setResult(null)}}/></label></div>
   <div className="mt-4 grid gap-4 rounded-2xl border bg-muted-bg/40 p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold">{t.priceTreatment}<select className={`${input} mt-2`} value={priceTreatment} onChange={e=>{setPriceTreatment(e.target.value);setResult(null)}}><option value="ignore">{t.ignore}</option><option value="historical">{t.historical}</option><option value="current">{t.current}</option></select></label><label className="text-xs font-bold">{t.stockTreatment}<select className={`${input} mt-2`} value={stockTreatment} onChange={e=>{setStockTreatment(e.target.value);setResult(null)}}><option value="ignore">{t.ignore}</option><option value="current">{t.current}</option></select></label><label className="text-xs font-bold">{t.priceKind}<select disabled={priceTreatment==="ignore"} className={`${input} mt-2 disabled:opacity-50`} value={priceKind} onChange={e=>setPriceKind(e.target.value)}>{priceKinds.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-bold">{t.currency}<select disabled={priceTreatment==="ignore"} className={`${input} mt-2 disabled:opacity-50`} value={currency} onChange={e=>setCurrency(e.target.value)}>{["IRT","IRR","TRY","USD","EUR"].map(x=><option key={x}>{x}</option>)}</select></label></div>
   <div className="mt-5 rounded-2xl border border-dashed bg-muted-bg/60 p-6 text-center"><input ref={ref} type="file" accept=".csv,text/csv,.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,.pdf,application/pdf" className="hidden" onChange={e=>{setFile(e.target.files?.[0]??null);setResult(null);setError(null)}}/><UploadCloud className="mx-auto h-9 w-9 text-primary-glow"/><p className="mt-3 text-sm font-bold">{file?`${t.selected}: ${file.name}`:t.choose}</p><p className="mt-1 text-xs text-muted">{t.limits}</p><div className="mt-4 flex flex-wrap justify-center gap-3"><button type="button" onClick={()=>ref.current?.click()} className="min-h-10 rounded-xl border bg-white px-4 text-xs font-bold">{t.select}</button><button type="button" onClick={()=>run("preview")} disabled={!file||!sourceTitle.trim()||Boolean(busy)} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-primary px-5 text-xs font-black text-white disabled:opacity-50">{busy==="preview"?<Loader2 className="h-4 w-4 animate-spin"/>:<ShieldCheck className="h-4 w-4"/>}{busy==="preview"?t.previewBusy:t.preview}</button>{p?.canApply&&result?.mode==="preview"?<button type="button" onClick={()=>run("apply")} disabled={Boolean(busy)} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-emerald-700 px-5 text-xs font-black text-white disabled:opacity-50">{busy==="apply"?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}{busy==="apply"?t.applyBusy:t.apply}</button>:null}</div></div>
  </section>
  {p?<section className={`rounded-2xl border p-5 ${p.canApply?"border-emerald-200 bg-emerald-50":"border-amber-300 bg-amber-50"}`}><div className="flex items-center gap-2 text-sm font-black">{p.canApply?<CheckCircle2 className="h-5 w-5 text-emerald-700"/>:<AlertTriangle className="h-5 w-5 text-amber-700"/>}{result?.mode==="apply"?t.completed:p.canApply?t.previewOk:t.blocked}{result?.format?` · ${result.format.toUpperCase()}`:""}</div><p className="mt-2 text-xs text-muted">{result?.source?.title} · {result?.source?.sourceType}{result?.source?.sourceDate?` · ${result.source.sourceDate}`:""}</p><div className="mt-4 grid grid-cols-2 gap-3 text-center sm:grid-cols-4">{[[t.created,p.create],[t.updated,p.update],[t.errors,p.errorRows],[t.warnings,p.warningRows]].map(([label,value])=><div key={label as string} className="rounded-xl bg-white p-3"><div className="text-xl font-black">{adminNumber(value as number,locale)}</div><div className="mt-1 text-xs text-muted">{label}</div></div>)}</div>{problemRows.length?<div className="mt-5 max-h-80 overflow-auto rounded-xl border bg-white p-3"><p className="mb-2 flex items-center gap-1.5 text-xs font-black"><AlertTriangle className="h-4 w-4"/>{t.issues}</p>{problemRows.slice(0,100).map((x,i)=><div key={`${x.line}-${x.sku}-${i}`} className="border-b py-2 last:border-0"><p className="text-xs font-black">{t.row} {adminNumber(x.line,locale)} {x.sku?`· ${x.sku}`:""}</p><p className="mt-1 text-xs leading-6 text-muted">{[...x.errors,...x.warnings].map(code=>issueLabel(code,locale)).join(" · ")}</p></div>)}</div>:null}</section>:null}
  {error?<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>:null}
  <section className="rounded-2xl border bg-white p-5 text-sm leading-7 text-muted"><h3 className="font-black text-foreground">{t.tips}</h3><p className="mt-2">{t.tipsBody}</p></section>
 </div>;
}
