"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { LayoutDashboard, Package, FileUp, FolderTree, Stethoscope, CalendarCheck2, FileText, ShoppingBag, ImageIcon, Settings, Headphones, MessageSquareText, ShieldCheck, UsersRound, Boxes, Star, BadgePercent, BarChart3, PanelsTopLeft, Newspaper, CreditCard, ChevronLeft, UserCog, ScrollText, Tags, Layers3, ClipboardList, SlidersHorizontal, GalleryVerticalEnd, MapPinned, Store } from "lucide-react";
import { cn } from "@/lib/utils";
import { canAdminAccessPath, type AdminRole } from "@/lib/admin-permissions";
import type { AdminLocale } from "./locale-switcher";

const labels={fa:["داشبورد","گزارش فروش","تراکنش‌های مالی","مرکز کنترل فروش","محتوا و محصولات","محصولات","ورود گروهی کالا","برندها","طبقه‌بندی چندبعدی","ویژگی‌های ساختاریافته","کالکشن‌ها","موجودی و انبار","شعب و انبارها","دسته‌بندی‌ها","خدمات","رزرو خدمات","درخواست‌های اجاره","سفارش‌ها","مشتریان","نظرات","تخفیف‌ها","تیکت‌های پشتیبانی","پیام‌های تماس","گارانتی","مقالات","بنرها و جشنواره","صفحات","رسانه‌ها","تیم و دسترسی‌ها","گزارش فعالیت مدیران","تنظیمات"],ar:["لوحة التحكم","تقارير المبيعات","المعاملات المالية","مركز التحكم بالمبيعات","المحتوى والمنتجات","المنتجات","استيراد المنتجات","العلامات التجارية","التصنيف متعدد الأبعاد","الخصائص المنظمة","المجموعات","المخزون","الفروع والمستودعات","التصنيفات","الخدمات","حجوزات الخدمات","طلبات الإيجار","الطلبات","العملاء","المراجعات","الخصومات","تذاكر الدعم","رسائل الاتصال","الضمان","المقالات","اللافتات والحملات","الصفحات","الوسائط","الفريق والصلاحيات","سجل نشاط الإدارة","الإعدادات"],en:["Dashboard","Sales reports","Financial transactions","Commerce control","Content & products","Products","Bulk import","Brands","Taxonomy","Structured attributes","Collections","Inventory","Branches & warehouses","Categories","Services","Service bookings","Rental requests","Orders","Customers","Reviews","Discounts","Support tickets","Contact messages","Warranty","Articles","Banners & campaigns","Pages","Media","Team & roles","Admin audit log","Settings"],tr:["Kontrol paneli","Satış raporları","Finansal işlemler","Ticaret kontrolü","İçerik ve ürünler","Ürünler","Toplu içe aktarma","Markalar","Taksonomi","Yapılandırılmış özellikler","Koleksiyonlar","Stok ve envanter","Şubeler ve depolar","Kategoriler","Hizmetler","Hizmet rezervasyonları","Kiralama talepleri","Siparişler","Müşteriler","Yorumlar","İndirimler","Destek talepleri","İletişim mesajları","Garanti","Makaleler","Banner ve kampanyalar","Sayfalar","Medya","Ekip ve roller","Yönetici işlem kaydı","Ayarlar"]} as const;
const baseItems=[["/admin",LayoutDashboard],["/admin/reports",BarChart3],["/admin/transactions",CreditCard],["/admin/commerce",Store],["/admin/content",PanelsTopLeft],["/admin/products",Package],["/admin/products/import",FileUp],["/admin/brands",Tags],["/admin/taxonomy",Layers3],["/admin/attributes",SlidersHorizontal],["/admin/collections",GalleryVerticalEnd],["/admin/inventory",Boxes],["/admin/locations",MapPinned],["/admin/categories",FolderTree],["/admin/services",Stethoscope],["/admin/bookings",CalendarCheck2],["/admin/rentals",ClipboardList],["/admin/orders",ShoppingBag],["/admin/customers",UsersRound],["/admin/reviews",Star],["/admin/discounts",BadgePercent],["/admin/support",Headphones],["/admin/contacts",MessageSquareText],["/admin/warranties",ShieldCheck],["/admin/articles",Newspaper],["/admin/banners",PanelsTopLeft],["/admin/pages",FileText],["/admin/media",ImageIcon],["/admin/team",UserCog],["/admin/audit",ScrollText],["/admin/settings",Settings]] as const;
export function AdminSidebar({locale="fa",role}:{locale?:AdminLocale;role:AdminRole}){const pathname=usePathname();return <nav className="flex flex-col gap-1.5 p-3" aria-label={locale==="fa"?"ناوبری مدیریت":locale==="ar"?"تنقل الإدارة":"Admin navigation"}>{baseItems.map(([href,Icon],index)=>{if(!canAdminAccessPath(role,href))return null;const active=href==="/admin"?pathname==="/admin":href==="/admin/products"?pathname==="/admin/products"||/^\/admin\/products\/(new|[^/]+)$/.test(pathname):pathname.startsWith(href);return <Link key={href} href={href} className={cn("group flex min-h-11 items-center gap-3 rounded-xl px-3 text-[13px] font-bold transition-all",active?"bg-[#e80346] text-white shadow-[0_8px_22px_rgba(232,3,70,.20)]":"text-[#5f6570] hover:bg-[#f1f4f7] hover:text-[#001736]")}><Icon className="h-4.5 w-4.5 shrink-0" aria-hidden="true"/><span className="flex-1">{labels[locale][index]}</span><ChevronLeft className={cn("h-3.5 w-3.5 opacity-0 transition rtl:rotate-0 ltr:rotate-180",active?"opacity-100":"group-hover:opacity-40")}/></Link>})}</nav>}
