"use client";

import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import type { AdminLocale } from "@/lib/admin-i18n";

type SpecRow={key:string;fa:string;tr:string;en:string;ar:string};
const copy:Record<AdminLocale,{legend:string;key:string;fa:string;tr:string;en:string;ar:string;remove:string;add:string}>={fa:{legend:"مشخصات فنی چندزبانه",key:"ویژگی / کلید",fa:"مقدار فارسی",tr:"مقدار ترکی",en:"مقدار انگلیسی",ar:"مقدار عربی",remove:"حذف مشخصه",add:"افزودن مشخصه"},ar:{legend:"المواصفات الفنية متعددة اللغات",key:"الخاصية / المفتاح",fa:"القيمة الفارسية",tr:"القيمة التركية",en:"القيمة الإنجليزية",ar:"القيمة العربية",remove:"حذف الخاصية",add:"إضافة خاصية"},en:{legend:"Multilingual technical specifications",key:"Attribute / key",fa:"Persian value",tr:"Turkish value",en:"English value",ar:"Arabic value",remove:"Remove specification",add:"Add specification"},tr:{legend:"Çok dilli teknik özellikler",key:"Özellik / anahtar",fa:"Farsça değer",tr:"Türkçe değer",en:"İngilizce değer",ar:"Arapça değer",remove:"Özelliği kaldır",add:"Özellik ekle"}};
function parseInitial(json:string):SpecRow[]{try{const parsed=JSON.parse(json) as Record<string,string|Partial<Omit<SpecRow,"key">>>;return Object.entries(parsed).map(([key,value])=>typeof value==="string"?{key,fa:value,tr:value,en:value,ar:value}:{key,fa:value.fa??"",tr:value.tr??"",en:value.en??"",ar:value.ar??""})}catch{return[]}}
export function SpecsEditor({name,defaultValue,locale="fa"}:{name:string;defaultValue?:string;locale?:AdminLocale}){const[rows,setRows]=useState<SpecRow[]>(()=>parseInitial(defaultValue??"{}"));const t=copy[locale];const serialized=JSON.stringify(Object.fromEntries(rows.filter(row=>row.key.trim()).map(row=>[row.key.trim(),{fa:row.fa,tr:row.tr,en:row.en,ar:row.ar}])));function update(index:number,patch:Partial<SpecRow>){setRows(previous=>previous.map((row,i)=>i===index?{...row,...patch}:row))}return <fieldset className="rounded-2xl border border-border bg-white p-4 sm:p-5"><legend className="px-2 text-xs font-bold text-muted">{t.legend}</legend><input type="hidden" name={name} value={serialized}/><div className="space-y-3">{rows.map((row,index)=><div key={index} className="rounded-xl border border-border bg-muted-bg/50 p-3"><div className="grid gap-2 lg:grid-cols-[1.1fr_1fr_1fr_1fr_1fr_auto]"><input placeholder={t.key} value={row.key} onChange={e=>update(index,{key:e.target.value})} className="vitalis-focus h-10 rounded-lg border border-border bg-white px-2.5 text-xs"/><input placeholder={t.fa} value={row.fa} onChange={e=>update(index,{fa:e.target.value})} className="vitalis-focus h-10 rounded-lg border border-border bg-white px-2.5 text-xs"/><input placeholder={t.tr} dir="ltr" value={row.tr} onChange={e=>update(index,{tr:e.target.value})} className="vitalis-focus h-10 rounded-lg border border-border bg-white px-2.5 text-xs"/><input placeholder={t.en} dir="ltr" value={row.en} onChange={e=>update(index,{en:e.target.value})} className="vitalis-focus h-10 rounded-lg border border-border bg-white px-2.5 text-xs"/><input placeholder={t.ar} dir="rtl" value={row.ar} onChange={e=>update(index,{ar:e.target.value})} className="vitalis-focus h-10 rounded-lg border border-border bg-white px-2.5 text-xs"/><button type="button" onClick={()=>setRows(previous=>previous.filter((_,i)=>i!==index))} className="vitalis-focus flex h-10 w-10 items-center justify-center rounded-lg text-muted transition hover:bg-accent/10 hover:text-accent" aria-label={t.remove}><Trash2 className="h-4 w-4" aria-hidden="true"/></button></div></div>)}</div><button type="button" onClick={()=>setRows(previous=>[...previous,{key:"",fa:"",tr:"",en:"",ar:""}])} className="vitalis-focus mt-3 flex min-h-10 w-fit items-center gap-1.5 rounded-xl border border-dashed border-border px-4 text-xs font-bold text-foreground transition hover:border-primary/40 hover:bg-muted-bg"><Plus className="h-3.5 w-3.5" aria-hidden="true"/>{t.add}</button></fieldset>}
