import { TextField, SelectField } from "@/components/admin/form-field";
import { ImageUploadField } from "@/components/admin/image-upload-field";
import { adminRpc } from "@/lib/admin-data";
import { updateSiteSettings } from "./actions";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import type { AdminLocale } from "@/lib/admin-i18n";

type S={holdingName:string;holdingLogoUrl:string;subBrandName:string;subBrandLogoUrl:string;contactPhone:string;contactEmail:string;address:string;instagramUrl:string;telegramUrl:string;whatsappUrl:string;defaultLocale:string;supportedLocales:string;currency:string;businessTimeZone:string};
const C:Record<AdminLocale,Record<string,string>>={
fa:{eyebrow:"پیکربندی سیستم",title:"تنظیمات سایت",brand:"برند",holding:"نام هلدینگ",store:"نام برند فروشگاه",holdingLogo:"لوگوی هلدینگ",storeLogo:"لوگوی فروشگاه",contact:"اطلاعات تماس",phone:"تلفن تماس",email:"ایمیل",address:"آدرس",social:"شبکه‌های اجتماعی",language:"زبان، واحد پول و زمان",default:"زبان پیش‌فرض",currency:"واحد پول پایه",timezone:"منطقه زمانی کسب‌وکار",note:"زبان‌های فعال سایت FA / TR / EN / AR هستند. مقادیر زبان، ارز، ایمیل، لینک‌ها و منطقه زمانی در سطح سرور و پایگاه‌داده اعتبارسنجی می‌شوند.",save:"ذخیره تغییرات"},
ar:{eyebrow:"إعداد النظام",title:"إعدادات الموقع",brand:"العلامة التجارية",holding:"اسم المجموعة",store:"اسم علامة المتجر",holdingLogo:"شعار المجموعة",storeLogo:"شعار المتجر",contact:"بيانات الاتصال",phone:"الهاتف",email:"البريد الإلكتروني",address:"العنوان",social:"الشبكات الاجتماعية",language:"اللغة والعملة والمنطقة الزمنية",default:"اللغة الافتراضية",currency:"العملة الأساسية",timezone:"المنطقة الزمنية للأعمال",note:"لغات الموقع النشطة هي FA / TR / EN / AR. يتم التحقق من اللغة والعملة والبريد والروابط والمنطقة الزمنية على الخادم وفي قاعدة البيانات.",save:"حفظ التغييرات"},
en:{eyebrow:"System configuration",title:"Site settings",brand:"Brand",holding:"Holding name",store:"Store brand name",holdingLogo:"Holding logo",storeLogo:"Store logo",contact:"Contact information",phone:"Contact phone",email:"Email",address:"Address",social:"Social networks",language:"Language, currency & time",default:"Default language",currency:"Base currency",timezone:"Business time zone",note:"Active site languages are FA / TR / EN / AR. Locale, currency, email, social URLs and time zone are validated server-side and in the database.",save:"Save changes"},
tr:{eyebrow:"Sistem yapılandırması",title:"Site ayarları",brand:"Marka",holding:"Grup adı",store:"Mağaza marka adı",holdingLogo:"Grup logosu",storeLogo:"Mağaza logosu",contact:"İletişim bilgileri",phone:"Telefon",email:"E-posta",address:"Adres",social:"Sosyal ağlar",language:"Dil, para birimi ve saat",default:"Varsayılan dil",currency:"Temel para birimi",timezone:"İşletme saat dilimi",note:"Aktif site dilleri FA / TR / EN / AR'dır. Dil, para birimi, e-posta, sosyal bağlantılar ve saat dilimi sunucu ve veritabanında doğrulanır.",save:"Değişiklikleri kaydet"}
};
const TIME_ZONES=[{value:"Asia/Tehran",label:"Asia/Tehran — Iran"},{value:"Europe/Istanbul",label:"Europe/Istanbul — Türkiye"},{value:"UTC",label:"UTC"}];
export default async function Page(){const[s,l]=await Promise.all([adminRpc<S|null>("admin_site_settings"),currentAdminLocale()]);const x=s??{holdingName:"VITALIS Group",holdingLogoUrl:"",subBrandName:"Hyper Doctor",subBrandLogoUrl:"",contactPhone:"",contactEmail:"",address:"",instagramUrl:"",telegramUrl:"",whatsappUrl:"",defaultLocale:"fa",supportedLocales:"fa,tr,en,ar",currency:"IRT",businessTimeZone:"Asia/Tehran"};const t=C[l];return <div><div className="mb-6"><p className="text-xs font-black uppercase">{t.eyebrow}</p><h1 className="mt-2 text-2xl font-black">{t.title}</h1></div><form action={updateSiteSettings} className="max-w-4xl space-y-5 pb-12"><section className="rounded-2xl border bg-card p-5"><h2>{t.brand}</h2><div className="grid gap-4 sm:grid-cols-2"><TextField label={t.holding} name="holdingName" defaultValue={x.holdingName} required/><TextField label={t.store} name="subBrandName" defaultValue={x.subBrandName} required/><ImageUploadField label={t.holdingLogo} name="holdingLogoUrl" defaultValue={x.holdingLogoUrl}/><ImageUploadField label={t.storeLogo} name="subBrandLogoUrl" defaultValue={x.subBrandLogoUrl}/></div></section><section className="rounded-2xl border bg-card p-5"><h2>{t.contact}</h2><div className="grid gap-4 sm:grid-cols-2"><TextField label={t.phone} name="contactPhone" defaultValue={x.contactPhone} type="tel" dir="ltr" inputMode="tel"/><TextField label={t.email} name="contactEmail" defaultValue={x.contactEmail} type="email" dir="ltr" inputMode="email"/></div><TextField label={t.address} name="address" defaultValue={x.address}/></section><section className="rounded-2xl border bg-card p-5"><h2>{t.social}</h2><div className="grid gap-4 sm:grid-cols-3"><TextField label="Instagram" name="instagramUrl" defaultValue={x.instagramUrl} type="url" dir="ltr" inputMode="url"/><TextField label="Telegram" name="telegramUrl" defaultValue={x.telegramUrl} type="url" dir="ltr" inputMode="url"/><TextField label="WhatsApp" name="whatsappUrl" defaultValue={x.whatsappUrl} type="url" dir="ltr" inputMode="url"/></div></section><section className="rounded-2xl border bg-card p-5"><h2>{t.language}</h2><div className="grid gap-4 sm:grid-cols-3"><SelectField label={t.default} name="defaultLocale" defaultValue={x.defaultLocale} options={[{value:"fa",label:"فارسی"},{value:"tr",label:"Türkçe"},{value:"en",label:"English"},{value:"ar",label:"العربية"}]}/><SelectField label={t.currency} name="currency" defaultValue={x.currency} options={[{value:"IRT",label:"IRT"},{value:"TRY",label:"TRY"},{value:"USD",label:"USD"},{value:"EUR",label:"EUR"}]}/><SelectField label={t.timezone} name="businessTimeZone" defaultValue={x.businessTimeZone||"Asia/Tehran"} options={TIME_ZONES}/></div><p className="mt-3 text-xs leading-6 text-muted">{t.note}</p></section><div className="sticky bottom-4 flex justify-end"><button className="min-h-12 rounded-xl bg-primary px-7 text-sm font-black text-white">{t.save}</button></div></form></div>}
