import { NextResponse } from "next/server";
import { adminRpc } from "@/lib/admin-data";

function parseCsv(input:string):Record<string,string>[]{const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<input.length;i++){const ch=input[i],next=input[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(ch===","&&!quoted){row.push(cell.trim());cell="";continue}if((ch==="\n"||ch==="\r")&&!quoted){if(ch==="\r"&&next==="\n")i++;row.push(cell.trim());cell="";if(row.some(Boolean))rows.push(row);row=[];continue}cell+=ch}row.push(cell.trim());if(row.some(Boolean))rows.push(row);const[headers,...body]=rows;if(!headers)return[];const normalized=headers.map(h=>h.replace(/^\uFEFF/,"").trim());return body.map(values=>Object.fromEntries(normalized.map((h,i)=>[h,values[i]??""])))}
function excelValue(value:unknown){if(value==null)return"";if(value instanceof Date)return value.toISOString().slice(0,10);if(typeof value==="object"){const v=value as {text?:string;result?:unknown;richText?:Array<{text:string}>};if(v.text!=null)return String(v.text);if(v.result!=null)return String(v.result);if(Array.isArray(v.richText))return v.richText.map(x=>x.text).join("")}return String(value)}
async function parseXlsx(file:File):Promise<Record<string,string>[]>{const ExcelJS=(await import("exceljs")).default;const workbook=new ExcelJS.Workbook();const data=Buffer.from(await file.arrayBuffer()) as unknown as Parameters<typeof workbook.xlsx.load>[0];await workbook.xlsx.load(data);if(workbook.worksheets.length>10)throw new Error("Workbook sheet limit is 10");const sheet=workbook.worksheets[0];if(!sheet)return[];if(sheet.columnCount>80)throw new Error("Worksheet column limit is 80");if(sheet.rowCount>2001)throw new Error("Worksheet row limit is 2000 products plus header");const headers=(sheet.getRow(1).values as unknown[]).slice(1).map(v=>excelValue(v).replace(/^\uFEFF/,"").trim());if(!headers.some(Boolean))return[];const rows:Record<string,string>[]=[];for(let i=2;i<=sheet.rowCount;i++){const values=(sheet.getRow(i).values as unknown[]).slice(1);const item=Object.fromEntries(headers.map((h,j)=>[h,excelValue(values[j]).trim()]));if(Object.values(item).some(Boolean))rows.push(item)}return rows}
function normalizeBoolean(value:string|undefined,fallback=false){if(!String(value??"").trim())return fallback;return["1","true","yes","y","on","published"].includes(String(value).trim().toLowerCase())}
function validJson(value:string|undefined,fallback:string){if(!String(value??"").trim())return fallback;return JSON.stringify(JSON.parse(String(value)))}
function cleanNumber(value:string|undefined,fallback=""){const raw=String(value??"").replace(/[,_\s]/g,"").trim();if(!raw)return fallback;const n=Number(raw);if(!Number.isFinite(n))throw new Error(`Invalid number: ${value}`);return String(Math.trunc(n))}
function required(value:string|undefined){return Boolean(String(value??"").trim())}
type ImportRowResult={id:string;sku:string;slug:string;created:boolean};
export async function POST(request:Request){const form=await request.formData().catch(()=>null);if(!form)return NextResponse.json({error:"Invalid multipart payload"},{status:400});const file=form.get("file");if(!(file instanceof File))return NextResponse.json({error:"CSV or XLSX file is required"},{status:400});if(file.size>5*1024*1024)return NextResponse.json({error:"Import file is too large (5MB max)"},{status:400});const isCsv=/\.csv$/i.test(file.name)||String(file.type).toLowerCase().includes("csv"),isXlsx=/\.xlsx$/i.test(file.name);if(!isCsv&&!isXlsx)return NextResponse.json({error:"Only CSV and XLSX files are allowed"},{status:400});let rows:Record<string,string>[];try{rows=isXlsx?await parseXlsx(file):parseCsv((await file.text()).replace(/^\uFEFF/,""))}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to read import file"},{status:400})}if(!rows.length)return NextResponse.json({error:"Import file contains no product rows"},{status:400});if(rows.length>2000)return NextResponse.json({error:"Import row limit is 2000 products"},{status:400});let created=0,updated=0;const errors:{line:number;sku:string;error:string}[]=[];for(const[index,source]of rows.entries()){try{const mandatory=["sku","categorySlug","nameFa","nameTr","nameEn","nameAr"] as const;const missing=mandatory.filter(key=>!required(source[key]));if(missing.length)throw new Error(`Required fields missing: ${missing.join(", ")}`);const row:Record<string,unknown>={...source,sku:source.sku.trim(),categorySlug:source.categorySlug.trim(),nameFa:source.nameFa.trim(),nameTr:source.nameTr.trim(),nameEn:source.nameEn.trim(),nameAr:source.nameAr.trim(),price:cleanNumber(source.price,"0"),compareAtPrice:cleanNumber(source.compareAtPrice),costPrice:cleanNumber(source.costPrice),stock:cleanNumber(source.stock,"0"),lowStockThreshold:cleanNumber(source.lowStockThreshold,"2"),minOrderQty:cleanNumber(source.minOrderQty,"1"),maxOrderQty:cleanNumber(source.maxOrderQty),weightGrams:cleanNumber(source.weightGrams),lengthMm:cleanNumber(source.lengthMm),widthMm:cleanNumber(source.widthMm),heightMm:cleanNumber(source.heightMm),warrantyMonths:cleanNumber(source.warrantyMonths),specs:validJson(source.specs,"{}"),tags:validJson(source.tags,"[]"),isPublished:normalizeBoolean(source.isPublished),isFeatured:normalizeBoolean(source.isFeatured),isNewArrival:normalizeBoolean(source.isNewArrival)};const images=(source.imageUrls||"").split(";").map(url=>url.trim()).filter(Boolean).slice(0,12);delete row.imageUrls;const result=await adminRpc<ImportRowResult>("admin_import_product_row",{p_row:row,p_images:images});if(result.created)created++;else updated++}catch(error){errors.push({line:index+2,sku:source.sku||"",error:error instanceof Error?error.message:"Unknown import error"})}}return NextResponse.json({created,updated,failed:errors.length,format:isXlsx?"xlsx":"csv",errors:errors.slice(0,100)},{status:errors.length===rows.length?400:200})}
