import Link from "next/link";
import { ArrowLeft, Package, Truck } from "lucide-react";
import { customerRpc, requireCustomerSession } from "@/lib/customer-auth";
import { formatLocalizedDate } from "@/lib/calendar";

type Order={id:string;orderNumber:string;total:number;status:string;currency:string;trackingCode?:string|null;createdAt:string};
type Bundle={orders:Order[]};
const pick=(locale:string,fa:string,en:string,tr:string,ar:string)=>locale==="en"?en:locale==="tr"?tr:locale==="ar"?ar:fa;
const statusText=(locale:string,status:string)=>{const map:Record<string,[string,string,string,string]>={PENDING:["در انتظار","Pending","Bekliyor","قيد الانتظار"],PENDING_PAYMENT:["در انتظار پرداخت","Pending payment","Ödeme bekleniyor","بانتظار الدفع"],PAYMENT_REVIEW:["نیازمند بررسی پرداخت","Payment review","Ödeme incelemesi","مراجعة الدفع"],PROCESSING:["در حال پردازش","Processing","İşleniyor","قيد المعالجة"],PAID:["پرداخت‌شده","Paid","Ödendi","مدفوع"],SHIPPED:["ارسال‌شده","Shipped","Gönderildi","تم الشحن"],DELIVERED:["تحویل‌شده","Delivered","Teslim edildi","تم التسليم"],COMPLETED:["تکمیل‌شده","Completed","Tamamlandı","مكتمل"],FAILED:["ناموفق","Failed","Başarısız","فشل"],CANCELLED:["لغوشده","Cancelled","İptal edildi","ملغي"],REFUNDED:["بازپرداخت‌شده","Refunded","İade edildi","تم رد المبلغ"]};const v=map[String(status||"").toUpperCase()];return v?pick(locale,v[0],v[1],v[2],v[3]):status||"—"};
const currencyText=(locale:string,currency?:string)=>{const c=(currency||"IRT").toUpperCase();if(c==="IRT")return pick(locale,"تومان","Toman","Toman","تومان");if(c==="IRR")return pick(locale,"ریال","IRR","IRR","ريال");return c};
const numberText=(locale:string,n:number)=>new Intl.NumberFormat(locale).format(n);
export default async function OrdersPage({params}:{params:Promise<{locale:string}>}){const {locale}=await params;await requireCustomerSession(locale);const data=await customerRpc<Bundle>("customer_dashboard");const rtl=locale==="fa"||locale==="ar";return <main className="bg-[#f5f8fb] py-10 sm:py-14"><div className="mx-auto max-w-5xl px-4"><Link href={`/${locale}/account`} className="inline-flex items-center gap-2 text-sm font-bold text-[#001736]"><ArrowLeft className={`h-4 w-4 ${rtl?"rotate-180":""}`}/>{pick(locale,"بازگشت به پنل","Back to dashboard","Panele dön","العودة إلى اللوحة")}</Link><section className="mt-5 rounded-[2rem] border border-white bg-white p-6 shadow-[0_20px_55px_rgba(0,23,54,.07)] sm:p-8"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#001736] text-white"><Package className="h-5 w-5"/></span><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#747780]">Hyper Doctor</p><h1 className="mt-1 text-2xl font-black text-[#001736]">{pick(locale,"تاریخچه سفارش‌ها","Order history","Sipariş geçmişi","سجل الطلبات")}</h1></div></div><div className="mt-6 space-y-3">{data.orders.map(o=><Link href={`/${locale}/account/orders/${o.id}`} key={o.id} className="flex flex-col justify-between gap-3 rounded-2xl border border-[#dfe4ea] bg-[#f9fbfd] p-5 transition hover:border-[#001736]/30 sm:flex-row sm:items-center"><div><div className="font-black text-[#001736]" dir="ltr">{o.orderNumber}</div><div className="mt-1 text-xs text-[#747780]">{formatLocalizedDate(o.createdAt,locale,{year:"numeric",month:"short",day:"numeric"})} · {statusText(locale,o.status)}</div>{o.trackingCode?<div className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-[#002b5b]"><Truck className="h-3.5 w-3.5"/><span>{pick(locale,"کد رهگیری","Tracking","Takip","التتبع")}:</span><span dir="ltr">{o.trackingCode}</span></div>:null}</div><div className="text-sm font-black text-[#001736]">{numberText(locale,o.total)} {currencyText(locale,o.currency)}</div></Link>)}{!data.orders.length?<div className="rounded-2xl border border-dashed border-[#c4c6d0] p-10 text-center text-sm text-[#747780]">{pick(locale,"هنوز سفارشی برای این حساب ثبت نشده است.","No orders are linked to this account yet.","Bu hesaba bağlı henüz sipariş yok.","لا توجد طلبات مرتبطة بهذا الحساب بعد.")}</div>:null}</div></section></div></main>}
