"use client";

import { useEffect, useMemo, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { Minus, Plus, ShoppingCart, Check, Layers3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useCart } from "@/lib/cart-context";
import { formatPrice } from "@/lib/utils";

type Variant={id:string;name:string;sku:string;price:number|null;compareAtPrice:number|null;stock:number;attributes:string};
function l(locale:string,fa:string,en:string,tr:string,ar:string){if(locale==="en")return en;if(locale==="tr")return tr;if(locale==="ar")return ar;return fa}
function currencyLabel(currency:string|undefined|null,locale:string,fallback:string){if(!currency||currency==="IRT")return fallback;if(currency==="TRY")return locale==="fa"?"لیر":locale==="ar"?"ليرة":locale==="tr"?"TL":"TRY";return currency}

export function AddToCartButton({ type,id,variantId,variantName,nameFa,nameTr,nameEn,nameAr,price,image,disabled,minQuantity,maxQuantity }:{type:"product"|"service";id:string;variantId?:string|null;variantName?:string|null;nameFa:string;nameTr?:string;nameEn:string;nameAr?:string;price:number;image?:string|null;disabled?:boolean;minQuantity?:number|null;maxQuantity?:number|null}){
  const t=useTranslations("shop"),c=useTranslations("common"),locale=useLocale(),{add}=useCart();
  const[variants,setVariants]=useState<Variant[]>([]),[loaded,setLoaded]=useState(type!=="product"),[selectedId,setSelectedId]=useState(variantId||""),[commerceReady,setCommerceReady]=useState(false),[checkoutEnabled,setCheckoutEnabled]=useState(false),[storeCurrency,setStoreCurrency]=useState<string|null>(null);
  const selected=useMemo(()=>variants.find(v=>v.id===selectedId)??null,[variants,selectedId]);
  useEffect(()=>{let active=true;const load=()=>{setCommerceReady(false);fetch("/api/store-commerce",{headers:{Accept:"application/json"}}).then(r=>r.ok?r.json():{commerce:null}).then(data=>{if(!active)return;const commerce=data?.commerce;setCheckoutEnabled(commerce?.salesEnabled===true&&commerce?.paymentGateway==="ZARINPAL"&&commerce?.currency==="IRT");setStoreCurrency(typeof commerce?.currency==="string"?commerce.currency:null);setCommerceReady(true)}).catch(()=>{if(active){setCheckoutEnabled(false);setCommerceReady(true)}})};load();window.addEventListener("hd-branch-change",load);return()=>{active=false;window.removeEventListener("hd-branch-change",load)}},[]);
  useEffect(()=>{if(type!=="product"||variantId){setLoaded(true);return;}let active=true;fetch(`/api/product-variants?id=${encodeURIComponent(id)}`,{headers:{Accept:"application/json"}}).then(r=>r.ok?r.json():{variants:[]}).then(data=>{if(!active)return;const list=Array.isArray(data?.variants)?data.variants:[];setVariants(list);if(list.length===1)setSelectedId(list[0].id);setLoaded(true)}).catch(()=>{if(active){setVariants([]);setLoaded(true)}});return()=>{active=false}},[id,type,variantId]);
  const effectiveVariantId=variantId||selected?.id||undefined,effectiveVariantName=variantName||selected?.name||undefined,effectivePrice=selected?.price??price,variantStock=selected?Math.max(0,Math.floor(Number(selected.stock)||0)):null;const rawMin=Number(minQuantity),min=type==="service"?1:minQuantity!=null&&Number.isFinite(rawMin)&&rawMin>0?Math.min(50,Math.max(1,Math.floor(rawMin))):1,rawMax=Number(maxQuantity),explicitZero=maxQuantity!==null&&maxQuantity!==undefined&&Number.isFinite(rawMax)&&rawMax<=0;let max=type==="service"?1:maxQuantity!==null&&maxQuantity!==undefined&&Number.isFinite(rawMax)&&rawMax>0?Math.max(min,Math.min(50,Math.floor(rawMax))):null;if(variantStock!==null)max=max===null?Math.min(50,variantStock):Math.min(max,variantStock);const needsVariant=variants.length>0&&!effectiveVariantId,missingProductImage=type==="product"&&!String(image||"").trim(),missingPrice=type==="product"&&(!Number.isFinite(Number(effectivePrice))||Number(effectivePrice)<=0),unavailable=Boolean(disabled)||!loaded||!commerceReady||!checkoutEnabled||needsVariant||missingProductImage||missingPrice||explicitZero||(max!==null&&max<min);const[quantity,setQuantity]=useState(min),[added,setAdded]=useState(false);
  useEffect(()=>{setQuantity(q=>Math.max(min,max===null?q:Math.min(max,q)))},[min,max,selectedId]);
  const decreaseLabel=l(locale,"کاهش تعداد","Decrease quantity","Adedi azalt","تقليل الكمية"),increaseLabel=l(locale,"افزایش تعداد","Increase quantity","Adedi artır","زيادة الكمية"),addedLabel=l(locale,"به سبد خرید اضافه شد","Added to cart","Sepete eklendi","تمت الإضافة إلى السلة"),minimumLabel=l(locale,"حداقل تعداد سفارش","Minimum order quantity","Minimum sipariş adedi","الحد الأدنى للطلب"),variantLabel=l(locale,"انتخاب مدل / تنوع","Choose variant","Varyant seçin","اختر التنويع"),variantRequired=l(locale,"برای خرید یک گزینه را انتخاب کنید.","Choose a variant to purchase.","Satın almak için bir varyant seçin.","اختر تنويعاً لإتمام الشراء."),checkoutDisabled=l(locale,"پرداخت آنلاین این شعبه آماده نیست","Checkout is not available for this branch","Bu şubede ödeme hazır değil","الدفع غير متاح لهذا الفرع"),dataPending=l(locale,"اطلاعات فروش این محصول هنوز کامل نشده است","This product is not yet ready for sale","Bu ürün henüz satışa hazır değil","هذا المنتج غير جاهز للبيع بعد"),currency=currencyLabel(storeCurrency,locale,c("currency"));
  return <div>{variants.length>0?<div className="mb-4 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] p-3"><label className="mb-2 flex items-center gap-2 text-xs font-black text-[#001736]"><Layers3 className="h-4 w-4 text-[#009dd8]"/>{variantLabel}</label><select value={selectedId} onChange={e=>setSelectedId(e.target.value)} className="h-11 w-full rounded-xl border border-[#dfe4ea] bg-white px-3 text-sm"><option value="">— {variantLabel} —</option>{variants.map(v=><option key={v.id} value={v.id} disabled={v.stock<=0}>{v.name} · {v.sku}{v.stock<=0?` · ${l(locale,"ناموجود","Out of stock","Stokta yok","غير متوفر")}`:""}</option>)}</select>{selected?<div className="mt-2 flex flex-wrap items-center justify-between gap-2 text-xs"><span dir="ltr" className="text-[#747780]">SKU: {selected.sku}</span><b className="text-[#ba0036]">{formatPrice(effectivePrice,locale)} {currency}</b></div>:<p className="mt-2 text-[11px] text-[#747780]">{variantRequired}</p>}</div>:null}<div className="flex flex-wrap items-center gap-3"><div className="flex items-center overflow-hidden rounded-xl border border-border bg-white shadow-sm"><button type="button" onClick={()=>setQuantity(q=>Math.max(min,q-1))} disabled={unavailable||quantity<=min} className="vitalis-focus flex h-12 w-12 items-center justify-center disabled:opacity-40" aria-label={decreaseLabel}><Minus className="h-4 w-4"/></button><span className="w-10 text-center text-sm font-bold tabular-nums">{new Intl.NumberFormat(locale).format(quantity)}</span><button type="button" onClick={()=>setQuantity(q=>max===null?q+1:Math.min(max,q+1))} disabled={unavailable||(max!==null&&quantity>=max)} className="vitalis-focus flex h-12 w-12 items-center justify-center disabled:opacity-40" aria-label={increaseLabel}><Plus className="h-4 w-4"/></button></div><Button type="button" size="lg" disabled={unavailable} className="min-h-12 min-w-48 rounded-xl bg-primary px-6 font-bold text-white" onClick={()=>{if(unavailable)return;const cartId=type==="product"&&effectiveVariantId?`${id}::${effectiveVariantId}`:id;add({type,id:cartId,variantId:effectiveVariantId,variantName:effectiveVariantName,nameFa,nameTr,nameEn,nameAr,price:effectivePrice,image,quantity,minQuantity:type==="service"?1:min,maxQuantity:type==="service"?1:max});setAdded(true);window.setTimeout(()=>setAdded(false),1500)}}>{added?<Check className="h-4 w-4"/>:<ShoppingCart className="h-4 w-4"/>}{added?addedLabel:missingProductImage||missingPrice?dataPending:commerceReady&&!checkoutEnabled?checkoutDisabled:t("addToCart")}</Button></div>{type==="product"&&min>1?<p className="mt-2 text-xs font-bold text-[#747780]">{minimumLabel}: {new Intl.NumberFormat(locale).format(min)}</p>:null}</div>
}
