import { RefreshCw, Search, SlidersHorizontal, TriangleAlert } from "lucide-react";
import { Link } from "@/i18n/navigation";
import { Container } from "@/components/ui/container";
import { CatalogProductCardV286 } from "@/components/site/catalog-product-card-v286";
import { getCatalogV286 } from "@/lib/catalog-v286";
import { localizedName } from "@/lib/i18n-content";

function l(locale:string,fa:string,en:string,tr:string,ar:string){if(locale==="en")return en;if(locale==="tr")return tr;if(locale==="ar")return ar;return fa}

export async function CatalogStorefrontV286({locale,categorySlug,searchParams}:{locale:string;categorySlug?:string;searchParams:Promise<{q?:string;brand?:string;sort?:string}>}){
  const sp=await searchParams;
  const data=await getCatalogV286({categorySlug,q:sp.q,brand:sp.brand,sort:sp.sort});
  const clearHref=categorySlug?`/shop/${categorySlug}`:"/shop";

  if(data.status==="unavailable"){
    return <main className="flex-1 bg-[#f7fafd] pb-16"><Container className="pt-6 sm:pt-8">
      <section className="rounded-3xl bg-[#001736] p-6 text-white shadow-[0_22px_60px_rgba(0,23,54,.16)] sm:p-9"><span className="inline-flex rounded-full bg-white/10 px-3 py-1.5 text-[11px] font-black text-[#82cfff]">V286 • VERIFIED CATALOG</span><h1 className="mt-4 text-3xl font-black sm:text-4xl">{l(locale,"کاتالوگ تجهیزات پزشکی","Medical equipment catalog","Medikal ekipman kataloğu","كتالوج المعدات الطبية")}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/72">{l(locale,"اطلاعات کاتالوگ فقط از منبع تأییدشده بارگذاری می‌شود و در زمان اختلال با داده ساختگی جایگزین نمی‌شود.","Catalog data is loaded only from the verified source and is never replaced with fabricated data during an outage.","Katalog verileri yalnızca doğrulanmış kaynaktan yüklenir ve kesinti sırasında uydurma verilerle değiştirilmez.","يتم تحميل بيانات الكتالوج من المصدر الموثق فقط ولا يتم استبدالها ببيانات مصطنعة أثناء الانقطاع.")}</p></section>
      <section role="status" className="mt-6 rounded-2xl border border-[#f0c36a] bg-[#fffaf0] p-6 shadow-[0_8px_24px_rgba(0,23,54,.045)] sm:p-8"><div className="flex items-start gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#fff0c9] text-[#8a5a00]"><TriangleAlert className="h-6 w-6"/></span><div><h2 className="text-lg font-black text-[#001736]">{l(locale,"کاتالوگ موقتاً در دسترس نیست","Catalog temporarily unavailable","Katalog geçici olarak kullanılamıyor","الكتالوج غير متاح مؤقتاً")}</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-[#5d6169]">{l(locale,"ارتباط با منبع داده تأییدشده موقتاً برقرار نیست. هیچ محصول، قیمت یا موجودی حدسی نمایش داده نمی‌شود. چند لحظه دیگر دوباره تلاش کنید.","The verified data source is temporarily unreachable. No guessed products, prices or stock are shown. Please try again shortly.","Doğrulanmış veri kaynağına geçici olarak ulaşılamıyor. Tahmini ürün, fiyat veya stok gösterilmez. Lütfen kısa süre sonra tekrar deneyin.","يتعذر الوصول مؤقتاً إلى مصدر البيانات الموثق. لن يتم عرض منتجات أو أسعار أو مخزون تقديري. يرجى المحاولة بعد قليل.")}</p><div className="mt-5 flex flex-wrap gap-3"><Link href={clearHref} className="vitalis-focus inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#002b5b] px-5 text-xs font-black text-white"><RefreshCw className="h-4 w-4"/>{l(locale,"تلاش دوباره","Try again","Tekrar dene","إعادة المحاولة")}</Link><Link href="/contact" className="vitalis-focus inline-flex min-h-11 items-center rounded-xl border border-[#c4c6d0] bg-white px-5 text-xs font-black text-[#001736]">{l(locale,"تماس با ما","Contact us","İletişim","اتصل بنا")}</Link></div></div></div></section>
    </Container></main>;
  }

  const title=data.activeCategory?localizedName(locale,data.activeCategory):l(locale,"کاتالوگ تجهیزات پزشکی","Medical equipment catalog","Medikal ekipman kataloğu","كتالوج المعدات الطبية");
  return <main className="flex-1 bg-[#f7fafd] pb-16"><Container className="pt-6 sm:pt-8">
    <section className="rounded-3xl bg-[#001736] p-6 text-white shadow-[0_22px_60px_rgba(0,23,54,.16)] sm:p-9"><span className="inline-flex rounded-full bg-white/10 px-3 py-1.5 text-[11px] font-black text-[#82cfff]">V286 • VERIFIED CATALOG</span><h1 className="mt-4 text-3xl font-black sm:text-4xl">{title}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/72">{l(locale,"فقط محصولاتی نمایش داده می‌شوند که تصویر و شواهد منبع آن‌ها تأیید شده است. قیمت، موجودی و امکان خرید تا زمان تأیید اپراتور فروش نمایش داده نمی‌شود.","Only products with verified source-backed media are shown. Price, stock and checkout stay hidden until operator approval.","Yalnızca kaynağı doğrulanmış görsellere sahip ürünler gösterilir. Fiyat, stok ve ödeme operatör onayına kadar gizli kalır.","تُعرض فقط المنتجات ذات الوسائط الموثقة بالمصدر. يبقى السعر والمخزون والدفع مخفياً حتى موافقة المشغل.")}</p><div className="mt-5 inline-flex rounded-xl bg-white/10 px-4 py-2 text-xs font-black">{new Intl.NumberFormat(locale).format(data.total)} {l(locale,"نتیجه تأییدشده","verified results","doğrulanmış sonuç","نتيجة موثقة")}</div></section>

    <section className="mt-6 rounded-2xl border border-[#e0e3e6] bg-white p-4 shadow-[0_8px_24px_rgba(0,23,54,.045)] sm:p-5"><form action={`/${locale}${clearHref}`} method="get" className="grid gap-3 lg:grid-cols-[1fr_auto_auto]" role="search"><label className="relative"><span className="sr-only">{l(locale,"جستجو","Search","Ara","بحث")}</span><Search className="pointer-events-none absolute end-4 top-1/2 h-5 w-5 -translate-y-1/2 text-[#747780]"/><input name="q" defaultValue={sp.q??""} placeholder={l(locale,"نام محصول، مدل، SKU یا برند...","Product, model, SKU or brand...","Ürün, model, SKU veya marka...","المنتج أو الموديل أو SKU أو العلامة...")} className="vitalis-focus h-12 w-full rounded-xl border border-[#c4c6d0] bg-[#f9fbfd] px-4 pe-12 text-sm font-bold text-[#181c1e]"/></label>{sp.brand?<input type="hidden" name="brand" value={sp.brand}/>:null}<select name="sort" defaultValue={sp.sort==="name"?"name":"newest"} className="vitalis-focus h-12 rounded-xl border border-[#c4c6d0] bg-white px-4 text-sm font-bold text-[#001736]"><option value="newest">{l(locale,"جدیدترین","Newest","En yeni","الأحدث")}</option><option value="name">{l(locale,"نام محصول","Product name","Ürün adı","اسم المنتج")}</option></select><button className="vitalis-focus inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#002b5b] px-5 text-sm font-black text-white"><SlidersHorizontal className="h-4 w-4"/>{l(locale,"اعمال","Apply","Uygula","تطبيق")}</button></form>
      <div className="mt-4 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><Link href={clearHref} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-black ${!sp.brand?"border-[#002b5b] bg-[#002b5b] text-white":"border-[#d7dbe0] bg-white text-[#43474f]"}`}>{l(locale,"همه برندها","All brands","Tüm markalar","كل العلامات")}</Link>{data.brands.map((brand:any)=><Link key={brand.id} href={`${clearHref}?brand=${encodeURIComponent(brand.id)}`} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-bold ${sp.brand===brand.id?"border-[#002b5b] bg-[#002b5b] text-white":"border-[#d7dbe0] bg-white text-[#43474f]"}`}>{brand.name} <span className="opacity-70">({brand.count})</span></Link>)}</div>
    </section>

    <section className="mt-6"><div className="flex gap-2 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><Link href="/shop" className={`shrink-0 rounded-full px-4 py-2 text-xs font-black ${!categorySlug?"bg-[#001736] text-white":"bg-white text-[#43474f]"}`}>{l(locale,"همه دسته‌ها","All categories","Tüm kategoriler","كل الفئات")}</Link>{data.categories.map((category:any)=><Link key={category.id} href={`/shop/${category.slug}`} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${categorySlug===category.slug?"bg-[#d6e3ff] text-[#001736]":"bg-white text-[#43474f]"}`}>{localizedName(locale,category)} <span className="opacity-65">({category.count})</span></Link>)}</div></section>

    <section className="mt-6"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black text-[#001736]">{l(locale,"محصولات تأییدشده","Verified products","Doğrulanmış ürünler","المنتجات الموثقة")}</h2><p className="mt-1 text-xs text-[#747780]">{new Intl.NumberFormat(locale).format(data.total)} {l(locale,"محصول","products","ürün","منتج")}</p></div>{(sp.q||sp.brand||sp.sort)?<Link href={clearHref} className="text-xs font-black text-[#ba0036]">{l(locale,"پاک کردن فیلترها","Clear filters","Filtreleri temizle","مسح عوامل التصفية")}</Link>:null}</div>{data.products.length?<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{data.products.map((product:any)=><CatalogProductCardV286 key={product.id} product={product} locale={locale}/>)}</div>:<div className="rounded-2xl border border-dashed border-[#c4c6d0] bg-white p-10 text-center"><strong className="text-sm font-black text-[#001736]">{l(locale,"محصولی با این فیلتر پیدا نشد","No products match these filters","Bu filtrelerle ürün bulunamadı","لم يتم العثور على منتجات بهذه المرشحات")}</strong></div>}</section>
  </Container></main>
}
