import { getTranslations, getLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { Instagram, Mail, MapPin, MessageCircle, Phone, Send, ShieldCheck, Stethoscope, Truck } from "lucide-react";
import { getNavPages, getSiteSettings } from "@/lib/site-data";
import { HyperDoctorLogo, VetrixMark } from "./logo";

function l(locale:string,fa:string,en:string,tr:string,ar:string){if(locale==="en")return en;if(locale==="tr")return tr;if(locale==="ar")return ar;return fa;}
function pageTitle(locale:string,p:{slug:string;titleFa:string;titleTr:string;titleEn:string;titleAr:string}){const values=locale==="fa"?[p.titleFa,p.titleAr,p.titleEn,p.titleTr]:locale==="ar"?[p.titleAr,p.titleFa,p.titleEn,p.titleTr]:locale==="tr"?[p.titleTr,p.titleEn,p.titleFa,p.titleAr]:[p.titleEn,p.titleTr,p.titleFa,p.titleAr];return values.find(Boolean)||p.slug;}

export async function Footer() {
  const locale = await getLocale();
  const t = await getTranslations("footer");
  const navT = await getTranslations("nav");
  const brandT = await getTranslations("brand");
  const [pages, settings] = await Promise.all([getNavPages(), getSiteSettings()]);
  const hasContactDetails = Boolean(settings.contactPhone || settings.contactEmail || settings.address);
  const socials=[
    settings.instagramUrl?{href:settings.instagramUrl,label:"Instagram",Icon:Instagram}:null,
    settings.telegramUrl?{href:settings.telegramUrl,label:"Telegram",Icon:Send}:null,
    settings.whatsappUrl?{href:settings.whatsappUrl,label:"WhatsApp",Icon:MessageCircle}:null,
  ].filter(Boolean) as Array<{href:string;label:string;Icon:typeof Instagram}>;
  const linkClass = "vitalis-focus rounded-md transition hover:text-white focus-visible:text-white";
  const coreSlugs=new Set(["home","shop","services","club","articles","about","contact","order-tracking","support","warranty","faq"]);
  const extraPages=pages.filter(p=>!coreSlugs.has(p.slug)).slice(0,3);

  return <footer className="mt-auto rounded-t-[2rem] bg-[#001736] text-white shadow-[0_-16px_50px_rgba(0,23,54,.08)] sm:rounded-t-[2.6rem]">
    <div className="mx-auto max-w-7xl px-4 pb-10 pt-12 sm:px-6 sm:pt-14 lg:px-8">
      <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.35fr_.85fr_.85fr_1fr]">
        <div><Link href="/" className="vitalis-focus inline-flex rounded-2xl bg-white px-3 py-2 text-[#001736]" aria-label={settings.subBrandName || brandT("subBrand")}><HyperDoctorLogo tagline={brandT("tagline")} name={settings.subBrandName} logoUrl={settings.subBrandLogoUrl}/></Link><p className="mt-5 max-w-sm text-sm leading-7 text-white/65">{t("about")}</p><div className="mt-5 flex flex-wrap items-center gap-2 text-xs text-white/55"><span>{l(locale,"عضو اکوسیستم","Part of","Bir parçası","جزء من")}</span><VetrixMark className="h-5 w-5" logoUrl={settings.holdingLogoUrl} name={settings.holdingName}/><strong className="text-white/85">{settings.holdingName}</strong></div>{socials.length?<div className="mt-5 flex gap-2">{socials.map(({href,label,Icon})=><a key={label} href={href} target="_blank" rel="noopener noreferrer" aria-label={label} className="vitalis-focus flex h-10 w-10 items-center justify-center rounded-xl border border-white/12 bg-white/[.06] text-white/70 transition hover:bg-white/12 hover:text-white"><Icon className="h-4 w-4"/></a>)}</div>:null}</div>
        <div><h3 className="mb-4 text-sm font-black text-white">{t("quickLinks")}</h3><ul className="space-y-3 text-sm text-white/58"><li><Link href="/shop" className={linkClass}>{navT("shop")}</Link></li><li><Link href="/services" className={linkClass}>{navT("services")}</Link></li><li><Link href="/articles" className={linkClass}>{l(locale,"مجله علمی","Journal","Bilimsel dergi","المجلة العلمية")}</Link></li><li><Link href="/about" className={linkClass}>{navT("about")}</Link></li><li><Link href="/contact" className={linkClass}>{navT("contact")}</Link></li>{extraPages.map(p=><li key={p.slug}><Link href={`/${p.slug}`} className={linkClass}>{pageTitle(locale,p)}</Link></li>)}</ul></div>
        <div><h3 className="mb-4 text-sm font-black text-white">{l(locale,"خدمات مشتریان","Customer care","Müşteri hizmetleri","خدمة العملاء")}</h3><ul className="space-y-3 text-sm text-white/58"><li><Link href="/club" className={linkClass}>{l(locale,"باشگاه مشتریان","Customer Club","Müşteri Kulübü","نادي العملاء")}</Link></li><li><Link href="/order-tracking" className={linkClass}>{l(locale,"رهگیری سفارش","Order Tracking","Sipariş Takibi","تتبع الطلب")}</Link></li><li><Link href="/support" className={linkClass}>{l(locale,"مرکز پشتیبانی","Support Center","Destek Merkezi","مركز الدعم")}</Link></li><li><Link href="/warranty" className={linkClass}>{l(locale,"گارانتی و خدمات پس از فروش","Warranty & After-sales","Garanti ve satış sonrası","الضمان وما بعد البيع")}</Link></li><li><Link href="/faq" className={linkClass}>{l(locale,"سوالات متداول","FAQ","SSS","الأسئلة الشائعة")}</Link></li></ul></div>
        <div><h3 className="mb-4 text-sm font-black text-white">{t("contactTitle")}</h3><ul className="space-y-4 text-sm text-white/62">{settings.contactPhone?<li className="flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white/8 text-[#82cfff]"><Phone className="h-4 w-4"/></span><a href={`tel:${settings.contactPhone.replace(/\s+/g,"")}`} dir="ltr" className="vitalis-focus rounded-md transition hover:text-white">{settings.contactPhone}</a></li>:null}{settings.contactEmail?<li className="flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white/8 text-[#82cfff]"><Mail className="h-4 w-4"/></span><a href={`mailto:${settings.contactEmail}`} dir="ltr" className="vitalis-focus rounded-md break-all transition hover:text-white">{settings.contactEmail}</a></li>:null}{settings.address?<li className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white/8 text-[#82cfff]"><MapPin className="h-4 w-4"/></span><span className="leading-6">{settings.address}</span></li>:null}{!hasContactDetails?<li><p className="text-xs leading-6 text-white/55">{l(locale,"اطلاعات تماس هنوز ثبت نشده است.","Contact details have not been configured yet.","İletişim bilgileri henüz yapılandırılmadı.","لم يتم إعداد بيانات التواصل بعد.")}</p><Link href="/contact" className="vitalis-focus mt-3 inline-flex rounded-xl border border-white/15 bg-white/8 px-3 py-2 text-xs font-black text-white transition hover:bg-white/14">{navT("contact")}</Link></li>:null}</ul></div>
      </div>
      <div className="mt-10 grid gap-3 border-t border-white/10 pt-7 sm:grid-cols-3">{[[ShieldCheck,l(locale,"تضمین اصالت تجهیزات","Authenticity assurance","Orijinallik güvencesi","ضمان الأصالة")],[Truck,l(locale,"تحویل ایمن و مطمئن","Safe delivery","Güvenli teslimat","توصيل آمن")],[Stethoscope,l(locale,"مشاوره و پشتیبانی تخصصی","Specialist support","Uzman destek","دعم متخصص")]].map(([Icon,label])=>{const I=Icon as typeof ShieldCheck;return <div key={String(label)} className="flex items-center gap-3 rounded-xl bg-white/[.045] px-4 py-3 text-xs font-bold text-white/68"><I className="h-4 w-4 shrink-0 text-[#82cfff]"/>{label as string}</div>;})}</div>
    </div>
    <div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-5 text-[11px] text-white/45 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><p>© {new Date().getFullYear()} {settings.subBrandName || brandT("subBrand")} — {t("rights")}</p><p>{settings.holdingName || "VITALIS Group"} • MedTech System</p></div></div>
  </footer>;
}
