import Image from "next/image";
import { Link } from "@/i18n/navigation";
import { getPublicCollections } from "@/lib/catalog-extensions";
import { ArrowLeft, ArrowRight, GalleryVerticalEnd } from "lucide-react";

function l(locale:string,fa:string,en:string,tr:string,ar:string){return locale==="fa"?fa:locale==="tr"?tr:locale==="ar"?ar:en}
function title(c:any,locale:string){return (locale==="fa"?c.titleFa:locale==="tr"?c.titleTr:locale==="ar"?c.titleAr:c.titleEn)||c.titleEn||c.titleFa||c.slug}
export async function HomeCollections({locale}:{locale:string}){
  const collections=await getPublicCollections(6);if(!collections.length)return null;const Arrow=locale==="fa"||locale==="ar"?ArrowLeft:ArrowRight;
  return <section className="mb-16 sm:mb-20"><div className="flex items-end justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-[.14em] text-[#009dd8]">HYPER DOCTOR COLLECTIONS</span><h2 className="stitch-section-title mt-2 text-start">{l(locale,"کالکشن‌های منتخب","Curated collections","Seçilmiş koleksiyonlar","المجموعات المختارة")}</h2></div><Link href="/collections" className="vitalis-focus rounded-lg text-sm font-bold text-[#002b5b]">{l(locale,"مشاهده همه","View all","Tümünü gör","عرض الكل")}</Link></div><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{collections.map(c=><Link key={c.id} href={`/collection/${c.slug}`} className="group overflow-hidden rounded-3xl border border-[#dfe4ea] bg-white shadow-[0_10px_30px_rgba(0,23,54,.05)] transition hover:-translate-y-1"><div className="relative h-36 bg-gradient-to-br from-[#d6e3ff] via-[#f1f4f7] to-[#c6e7ff]">{c.heroImageUrl?<Image src={c.heroImageUrl} alt="" fill className="object-cover transition duration-500 group-hover:scale-[1.03]" sizes="(max-width:768px) 100vw, 33vw"/>:<div className="flex h-full items-center justify-center"><GalleryVerticalEnd className="h-10 w-10 text-[#002b5b]"/></div>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-black text-[#001736]">{title(c,locale)}</h3><span className="shrink-0 rounded-full bg-[#f1f4f7] px-2.5 py-1 text-[10px] font-black text-[#43474f]">{c.productCount}</span></div><span className="mt-4 inline-flex items-center gap-1 text-xs font-black text-[#002b5b]">{l(locale,"مشاهده مجموعه","Explore","İncele","استكشف")}<Arrow className="h-3.5 w-3.5"/></span></div></Link>)}</div></section>
}
