import Link from "next/link";
import { CheckCircle2, CircleAlert, Database, FileCheck2, Image, PackageCheck, Rocket, ShieldCheck, ShoppingCart, Store, Warehouse } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminNumber, type AdminLocale } from "@/lib/admin-i18n";

type Branch={id:string;code:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;currency:string;published:boolean;default:boolean;salesEnabled:boolean;paymentGateway:string};
type Summary={catalogSources:number;stagingBatches:number;stagingItems:number;stagingApproved:number;stagingPromoted:number;products:number;draftProducts:number;publishedProducts:number;sourceBackedProducts:number;productsWithVerifiedMedia:number;verifiedMediaEvidence:number;branchPrices:number;warehouseInventoryRows:number;commerceSources:number;commerceEvidence:number;orders:number;branches:Branch[]};
const C={
fa:{eyebrow:"عملیات لانچ",title:"مرکز کنترل نهایی انتشار",desc:"وضعیت واقعی زنجیره کاتالوگ تا پرداخت را از یک صفحه بررسی کنید. این صفحه هیچ داده‌ای تولید یا Publish نمی‌کند.",catalog:"منابع کاتالوگ",staging:"ردیف‌های Staging",promoted:"Promote شده",products:"Product Master",sourceBacked:"محصول منبع‌دار",verifiedMedia:"محصول با تصویر Verified",prices:"قیمت جاری شعبه",stock:"ردیف موجودی واقعی",orders:"سفارش‌ها",pipeline:"مراحل باقی‌مانده",branches:"آمادگی شعبه",runtime:"آمادگی Runtime",goStaging:"فعال‌سازی و Review کاتالوگ",goLaunch:"Publish Gate",goMedia:"کتابخانه رسانه",goCommerce:"قیمت و موجودی",serviceRole:"Service Role سرور",siteUrl:"آدرس Production",merchant:"Merchant ID زرین‌پال",sandbox:"Sandbox زرین‌پال",configured:"آماده",missing:"ناقص",production:"Production",sandboxOn:"Sandbox روشن",noBranches:"هیچ شعبه‌ای تعریف نشده است."},
en:{eyebrow:"Launch operations",title:"Final launch control center",desc:"Inspect the real catalog-to-payment pipeline in one place. This page never creates or publishes data.",catalog:"Catalog sources",staging:"Staging rows",promoted:"Promoted",products:"Product master",sourceBacked:"Source-backed products",verifiedMedia:"Products with verified media",prices:"Current branch prices",stock:"Real inventory rows",orders:"Orders",pipeline:"Remaining pipeline",branches:"Branch readiness",runtime:"Runtime readiness",goStaging:"Activate & review catalog",goLaunch:"Publish gate",goMedia:"Media library",goCommerce:"Price & inventory",serviceRole:"Server service role",siteUrl:"Production site URL",merchant:"Zarinpal merchant ID",sandbox:"Zarinpal sandbox",configured:"Ready",missing:"Missing",production:"Production",sandboxOn:"Sandbox enabled",noBranches:"No branch is configured."},
tr:{eyebrow:"Lansman operasyonları",title:"Son lansman kontrol merkezi",desc:"Katalogdan ödemeye kadar gerçek süreci tek ekranda kontrol edin. Bu sayfa veri oluşturmaz veya yayınlamaz.",catalog:"Katalog kaynakları",staging:"Staging satırları",promoted:"Aktarılan",products:"Product master",sourceBacked:"Kaynaklı ürünler",verifiedMedia:"Doğrulanmış görselli ürünler",prices:"Güncel şube fiyatları",stock:"Gerçek stok satırları",orders:"Siparişler",pipeline:"Kalan süreç",branches:"Şube hazırlığı",runtime:"Runtime hazırlığı",goStaging:"Kataloğu etkinleştir ve incele",goLaunch:"Yayın kapısı",goMedia:"Medya kütüphanesi",goCommerce:"Fiyat ve stok",serviceRole:"Sunucu service role",siteUrl:"Production site adresi",merchant:"Zarinpal merchant ID",sandbox:"Zarinpal sandbox",configured:"Hazır",missing:"Eksik",production:"Production",sandboxOn:"Sandbox açık",noBranches:"Tanımlı şube yok."},
ar:{eyebrow:"عمليات الإطلاق",title:"مركز التحكم النهائي بالإطلاق",desc:"تحقق من المسار الحقيقي من الكتالوج إلى الدفع في شاشة واحدة. هذه الصفحة لا تنشئ بيانات ولا تنشر منتجات.",catalog:"مصادر الكتالوج",staging:"صفوف المرحلي",promoted:"تم النقل",products:"Product master",sourceBacked:"منتجات موثقة المصدر",verifiedMedia:"منتجات بصور موثقة",prices:"أسعار الفروع الحالية",stock:"صفوف المخزون الفعلي",orders:"الطلبات",pipeline:"المراحل المتبقية",branches:"جاهزية الفروع",runtime:"جاهزية Runtime",goStaging:"تفعيل ومراجعة الكتالوج",goLaunch:"بوابة النشر",goMedia:"مكتبة الوسائط",goCommerce:"السعر والمخزون",serviceRole:"Service Role للخادم",siteUrl:"عنوان Production",merchant:"معرف زرین‌بال",sandbox:"Sandbox زرین‌بال",configured:"جاهز",missing:"ناقص",production:"Production",sandboxOn:"Sandbox مفعّل",noBranches:"لا يوجد فرع معرف."}
} as const;
function bname(b:Branch,l:AdminLocale){return({fa:b.nameFa,tr:b.nameTr,en:b.nameEn,ar:b.nameAr}[l]||b.nameEn||b.nameFa||b.code)}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold text-muted">{label}</p><p className="mt-2 text-2xl font-black text-[#001736]">{value}</p></div>}
function Health({label,ok,text}:{label:string;ok:boolean;text:string}){return <div className="flex items-center justify-between gap-3 rounded-xl border bg-white px-4 py-3"><div className="flex items-center gap-2">{ok?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<CircleAlert className="h-4 w-4 text-amber-600"/>}<span className="text-xs font-black">{label}</span></div><span className={`text-xs font-bold ${ok?"text-emerald-700":"text-amber-700"}`}>{text}</span></div>}
export default async function LaunchOpsPage(){
 const l=await currentAdminLocale(),t=C[l];const s=await adminRpc<Summary>("admin_launch_operations_summary");
 const site=process.env.NEXT_PUBLIC_SITE_URL||"";const siteOk=(()=>{try{const u=new URL(site);return u.protocol==="https:"||u.hostname==="localhost"}catch{return false}})();
 const serviceRole=Boolean(process.env.SUPABASE_SERVICE_ROLE_KEY);const merchant=Boolean(process.env.ZARINPAL_MERCHANT_ID&&process.env.ZARINPAL_MERCHANT_ID!=="00000000-0000-0000-0000-000000000000");const sandbox=String(process.env.ZARINPAL_SANDBOX||"").toLowerCase()==="true";
 return <div className="mx-auto max-w-[1500px] space-y-6"><header><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 max-w-4xl text-sm leading-7 text-muted">{t.desc}</p></header>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label={t.catalog} value={adminNumber(s.catalogSources,l)}/><Metric label={t.staging} value={adminNumber(s.stagingItems,l)}/><Metric label={t.promoted} value={adminNumber(s.stagingPromoted,l)}/><Metric label={t.products} value={adminNumber(s.products,l)}/><Metric label={t.sourceBacked} value={adminNumber(s.sourceBackedProducts,l)}/><Metric label={t.verifiedMedia} value={adminNumber(s.productsWithVerifiedMedia,l)}/><Metric label={t.prices} value={adminNumber(s.branchPrices,l)}/><Metric label={t.stock} value={adminNumber(s.warehouseInventoryRows,l)}/></div>
 <section className="rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 font-black"><Rocket className="h-5 w-5 text-[#e80346]"/>{t.pipeline}</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Link href="/admin/products/staging" className="rounded-2xl border p-4 text-sm font-black hover:border-[#009dd8]"><Database className="mb-3 h-5 w-5"/>{t.goStaging}</Link><Link href="/admin/media" className="rounded-2xl border p-4 text-sm font-black hover:border-[#009dd8]"><Image className="mb-3 h-5 w-5"/>{t.goMedia}</Link><Link href="/admin/commerce" className="rounded-2xl border p-4 text-sm font-black hover:border-[#009dd8]"><Warehouse className="mb-3 h-5 w-5"/>{t.goCommerce}</Link><Link href="/admin/products/launch" className="rounded-2xl border p-4 text-sm font-black hover:border-emerald-500"><PackageCheck className="mb-3 h-5 w-5"/>{t.goLaunch}</Link></div></section>
 <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-3xl border bg-[#f7fafd] p-5"><h2 className="flex items-center gap-2 font-black"><Store className="h-5 w-5 text-[#009dd8]"/>{t.branches}</h2><div className="mt-4 space-y-3">{s.branches.map(b=>{const ok=b.published&&b.salesEnabled&&b.currency==="IRT"&&b.paymentGateway==="ZARINPAL";return <div key={b.id} className="rounded-2xl border bg-white p-4"><div className="flex items-center justify-between gap-3"><b>{bname(b,l)} · {b.code}</b>{ok?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:<CircleAlert className="h-5 w-5 text-amber-600"/>}</div><p className="mt-2 text-xs text-muted">{b.currency} · {b.paymentGateway} · sales={String(b.salesEnabled)} · published={String(b.published)}</p></div>})}{!s.branches.length?<p className="text-sm text-muted">{t.noBranches}</p>:null}</div></section>
 <section className="rounded-3xl border bg-[#f7fafd] p-5"><h2 className="flex items-center gap-2 font-black"><ShieldCheck className="h-5 w-5 text-[#009dd8]"/>{t.runtime}</h2><div className="mt-4 space-y-3"><Health label={t.serviceRole} ok={serviceRole} text={serviceRole?t.configured:t.missing}/><Health label={t.siteUrl} ok={siteOk} text={siteOk?t.configured:t.missing}/><Health label={t.merchant} ok={merchant} text={merchant?t.configured:t.missing}/><Health label={t.sandbox} ok={!sandbox} text={sandbox?t.sandboxOn:t.production}/></div></section></div>
 <div className="grid gap-3 sm:grid-cols-3"><Metric label={t.orders} value={adminNumber(s.orders,l)}/><Metric label="Commerce evidence" value={adminNumber(s.commerceEvidence,l)}/><Metric label="Verified media evidence" value={adminNumber(s.verifiedMediaEvidence,l)}/></div></div>
}
