import Image from "next/image";
import { getLocale } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { Container } from "@/components/ui/container";
import { getPublicCollections } from "@/lib/catalog-extensions";
import { ArrowLeft, ArrowRight, GalleryVerticalEnd, PackageSearch } from "lucide-react";

function l(locale:string,fa:string,en:string,tr:string,ar:string){return locale==="fa"?fa:locale==="tr"?tr:locale==="ar"?ar:en}
function title(c:any,locale:string){return (locale==="fa"?c.titleFa:locale==="tr"?c.titleTr:locale==="ar"?c.titleAr:c.titleEn)||c.titleEn||c.titleFa||c.slug}
function description(c:any,locale:string){return (locale==="fa"?c.descriptionFa:locale==="tr"?c.descriptionTr:locale==="ar"?c.descriptionAr:c.descriptionEn)||c.descriptionEn||c.descriptionFa||""}

export default async function CollectionsPage(){
  const locale=await getLocale(),collections=await getPublicCollections(60),Arrow=locale==="fa"||locale==="ar"?ArrowLeft:ArrowRight;
  return <main className="flex-1 bg-[#f7fafd] py-8 sm:py-12"><Container>
    <header className="mx-auto max-w-4xl text-center"><span className="inline-flex items-center gap-2 rounded-full bg-[#e7f5fb] px-4 py-2 text-xs font-black text-[#002b5b]"><GalleryVerticalEnd className="h-4 w-4"/>HYPER DOCTOR COLLECTIONS</span><h1 className="mt-5 text-3xl font-black text-[#001736] sm:text-4xl">{l(locale,"کالکشن‌های منتخب تجهیزات پزشکی","Curated medical equipment collections","Seçilmiş medikal ekipman koleksiyonları","مجموعات مختارة من المعدات الطبية")}</h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-8 text-[#747780]">{l(locale,"مجموعه‌های واقعی منتشرشده از پنل مدیریت؛ برای انتخاب سریع‌تر محصولات مرتبط، کاربردهای مشخص و سناریوهای مراقبتی.","Real collections published from Admin, organized for faster discovery by product relationship, use case and care scenario.","Yönetim panelinden yayımlanan gerçek koleksiyonlar; ürün ilişkisi, kullanım alanı ve bakım senaryosuna göre daha hızlı keşif için düzenlenir.","مجموعات فعلية منشورة من لوحة الإدارة لتسهيل اكتشاف المنتجات حسب العلاقة والاستخدام وسيناريو الرعاية.")}</p></header>
    {collections.length?<section className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{collections.map(c=><Link key={c.id} href={`/collection/${c.slug}`} className="group overflow-hidden rounded-3xl border border-[#dfe4ea] bg-white shadow-[0_12px_36px_rgba(0,23,54,.055)] transition hover:-translate-y-1 hover:shadow-[0_20px_48px_rgba(0,23,54,.09)]"><div className="relative h-48 bg-gradient-to-br from-[#d6e3ff] via-[#f1f4f7] to-[#c6e7ff]">{c.heroImageUrl?<Image src={c.heroImageUrl} alt="" fill className="object-cover transition duration-500 group-hover:scale-[1.03]" sizes="(max-width:768px) 100vw, 33vw"/>:<div className="flex h-full items-center justify-center"><GalleryVerticalEnd className="h-12 w-12 text-[#002b5b]"/></div>}<div className="absolute inset-x-0 bottom-0 h-20 bg-gradient-to-t from-[#001736]/55 to-transparent"/></div><div className="p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-black text-[#001736]">{title(c,locale)}</h2><p className="mt-2 line-clamp-2 text-xs leading-6 text-[#747780]">{description(c,locale)||l(locale,"مجموعه منتخب محصولات","Curated product group","Seçilmiş ürün grubu","مجموعة منتجات مختارة")}</p></div><span className="shrink-0 rounded-full bg-[#f1f4f7] px-3 py-1 text-[10px] font-black text-[#43474f]">{c.productCount} {l(locale,"محصول","products","ürün","منتج")}</span></div><span className="mt-5 inline-flex items-center gap-1.5 text-xs font-black text-[#002b5b]">{l(locale,"مشاهده کالکشن","View collection","Koleksiyonu gör","عرض المجموعة")}<Arrow className="h-3.5 w-3.5"/></span></div></Link>)}</section>:<div className="mx-auto mt-10 flex max-w-3xl flex-col items-center rounded-3xl border border-dashed bg-white p-10 text-center"><PackageSearch className="h-9 w-9 text-[#747780]"/><h2 className="mt-4 text-base font-black text-[#001736]">{l(locale,"هنوز کالکشن عمومی منتشر نشده است","No public collections have been published yet","Henüz herkese açık koleksiyon yayımlanmadı","لم يتم نشر مجموعات عامة بعد")}</h2></div>}
  </Container></main>
}
