import Link from "next/link";
import { ArrowLeft, Fingerprint, History, AlertTriangle, CheckCircle2 } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { setStagingSiteSku } from "../../../actions";

type Item={id:string;rowNumber:number;sourceSku:string;sourceModel:string;siteSku:string;identityStatus:string;payload:Record<string,unknown>;validation:{errors?:string[];warnings?:string[]};status:string};
type Detail={batch:{id:string;title:string};source:{title:string};items:Item[]};
type Candidate={id:string;sourceFile:string;sourceRow:number;legacyCode:string;legacyName:string;barcode:string;brand:string;unit:string;historicalPurchasePrice:number|null;historicalSellingPrice:number|null;historicalInitialStock:number|null;historicalMinStock:number|null;mainGroup:string;subGroup:string;score:number};
const T:Record<AdminLocale,Record<string,string>>={
 fa:{back:"بازگشت به Batch",title:"تطبیق هویت داخلی کالا",source:"هویت منبع",current:"SKU داخلی فعلی",noneCurrent:"هنوز تأیید نشده",candidates:"کاندیدهای داده قدیمی",notice:"این پیشنهادها فقط برای تطبیق هویت هستند. انتخاب هر کد باید توسط مدیر تأیید شود؛ قیمت و موجودی نشان‌داده‌شده تاریخی‌اند و وارد فروشگاه جاری نمی‌شوند.",use:"استفاده به‌عنوان SKU داخلی",manual:"ورود دستی SKU",save:"تأیید SKU",noCandidate:"کاندید قابل اتکایی پیدا نشد؛ SKU واقعی را دستی ثبت کنید.",score:"امتیاز تطبیق",historical:"تاریخی",sale:"فروش",stock:"موجودی اولیه"},
 en:{back:"Back to batch",title:"Resolve internal product identity",source:"Source identity",current:"Current site SKU",noneCurrent:"Not verified yet",candidates:"Historical identity candidates",notice:"Suggestions are reconciliation references only. An admin must explicitly approve the code; historical price/stock never becomes current storefront commerce data.",use:"Use as site SKU",manual:"Enter site SKU manually",save:"Verify SKU",noCandidate:"No reliable candidate found; enter the real site SKU manually.",score:"Match score",historical:"Historical",sale:"Selling",stock:"Initial stock"},
 tr:{back:"Batch'e dön",title:"İç ürün kimliğini eşleştir",source:"Kaynak kimliği",current:"Mevcut site SKU",noneCurrent:"Henüz doğrulanmadı",candidates:"Eski kimlik adayları",notice:"Öneriler yalnızca kimlik eşleştirme referansıdır. Kod yönetici tarafından açıkça doğrulanmalıdır; tarihsel fiyat/stok güncel mağaza verisine aktarılmaz.",use:"Site SKU olarak kullan",manual:"Site SKU'yu elle gir",save:"SKU doğrula",noCandidate:"Güvenilir aday bulunamadı; gerçek site SKU'yu elle girin.",score:"Eşleşme puanı",historical:"Tarihsel",sale:"Satış",stock:"İlk stok"},
 ar:{back:"العودة إلى الدفعة",title:"مطابقة الهوية الداخلية للمنتج",source:"هوية المصدر",current:"SKU الحالي",noneCurrent:"لم يتم اعتماده بعد",candidates:"مرشحو الهوية القديمة",notice:"هذه الاقتراحات مراجع للمطابقة فقط. يجب أن يعتمد المدير الرمز صراحة؛ السعر والمخزون التاريخيان لا ينتقلان إلى بيانات المتجر الحالية.",use:"استخدام كـ SKU داخلي",manual:"إدخال SKU يدوياً",save:"اعتماد SKU",noCandidate:"لم يتم العثور على مرشح موثوق؛ أدخل SKU الحقيقي يدوياً.",score:"درجة المطابقة",historical:"تاريخي",sale:"بيع",stock:"المخزون الأولي"}
};
function label(item:Item){const p=item.payload;return String(p.nameFa||p.nameEn||p.nameTr||p.nameAr||item.sourceModel||item.sourceSku||"—")}
export default async function Page({params}:{params:Promise<{id:string;itemId:string}>}){
 const {id,itemId}=await params;const [locale,d,candidates]=await Promise.all([currentAdminLocale(),adminRpc<Detail>("admin_catalog_staging_batch_detail",{p_batch_id:id}),adminRpc<Candidate[]>("admin_catalog_staging_identity_suggestions",{p_item_id:itemId,p_limit:20})]);
 const t=T[locale],item=d.items.find(x=>x.id===itemId);if(!item)throw new Error("staging item not found");
 return <div className="mx-auto max-w-5xl space-y-6"><div><Link href={`/admin/products/staging/${id}`} className="inline-flex items-center gap-2 text-xs font-black text-[#002b5b]"><ArrowLeft className="h-4 w-4"/>{t.back}</Link><h1 className="mt-4 flex items-center gap-2 text-3xl font-black"><Fingerprint className="h-7 w-7"/>{t.title}</h1><p className="mt-2 text-sm text-muted">{label(item)} · {d.source.title}</p></div>
 <section className="grid gap-4 md:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><div className="text-xs font-black text-muted">{t.source}</div><div className="mt-3 font-black" dir="ltr">{item.sourceSku||"—"}</div><div className="mt-1 text-sm" dir="ltr">{item.sourceModel||"—"}</div></div><div className="rounded-3xl border bg-white p-5"><div className="text-xs font-black text-muted">{t.current}</div><div className="mt-3 font-black" dir="ltr">{item.identityStatus==="VERIFIED"?item.siteSku:t.noneCurrent}</div></div></section>
 <section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 text-amber-800"/><p className="text-xs leading-6 text-amber-950/80">{t.notice}</p></div></section>
 <section className="rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 text-lg font-black"><History className="h-5 w-5"/>{t.candidates}</h2><div className="mt-4 space-y-3">{candidates.map(c=><div key={c.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-black">{c.legacyName}</div><div className="mt-1 text-sm font-bold" dir="ltr">{c.legacyCode}</div><div className="mt-1 text-[11px] text-muted">{c.sourceFile} · row {adminNumber(c.sourceRow,locale)}</div></div><div className="rounded-full bg-sky-50 px-3 py-1 text-xs font-black text-sky-800">{t.score}: {adminNumber(c.score,locale)}</div></div><div className="mt-3 grid gap-2 text-xs text-muted sm:grid-cols-3"><span>{t.historical} {t.sale}: {c.historicalSellingPrice==null?"—":adminNumber(c.historicalSellingPrice,locale)}</span><span>{t.historical} {t.stock}: {c.historicalInitialStock==null?"—":adminNumber(c.historicalInitialStock,locale)}</span><span>{c.brand||c.subGroup||"—"}</span></div><form action={setStagingSiteSku.bind(null,id,item.id)} className="mt-3"><input type="hidden" name="siteSku" value={c.legacyCode}/><button className="inline-flex min-h-9 items-center gap-1 rounded-xl bg-[#002b5b] px-4 text-xs font-black text-white"><CheckCircle2 className="h-4 w-4"/>{t.use}</button></form></div>)}{candidates.length===0?<p className="py-6 text-center text-sm text-muted">{t.noCandidate}</p>:null}</div></section>
 <section className="rounded-3xl border bg-white p-5"><h2 className="font-black">{t.manual}</h2><form action={setStagingSiteSku.bind(null,id,item.id)} className="mt-3 flex gap-2"><input name="siteSku" defaultValue={item.siteSku||""} required maxLength={100} className="min-h-10 flex-1 rounded-xl border px-3 text-sm" dir="ltr"/><button className="rounded-xl bg-emerald-700 px-5 text-xs font-black text-white">{t.save}</button></form></section>
 </div>
}
