import Link from "next/link";
import { Gift, Diamond, MonitorHeart, Star, ArrowLeft, Sparkles } from "lucide-react";
import { customerRpc, getCustomerSession } from "@/lib/customer-auth";

type Device={id:string;serialNumber:string;status:string;expiresAt:string;createdAt:string;productNameFa?:string|null;productNameEn?:string|null;brand?:string|null;modelNumber?:string|null};
type Offer={id:string;code:string;type:"PERCENT"|"FIXED";value:number;minOrderAmount?:number|null;maxDiscount?:number|null;expiresAt?:string|null};
type Club={profile:{fullName:string};lifetimeSpend:number;points:number;tier:"BRONZE"|"SILVER"|"GOLD"|"PLATINUM";nextTierPoints:number;spendPerPoint:number;devices:Device[];offers:Offer[]};
const tierLabel={BRONZE:"برنزی (Bronze)",SILVER:"نقره‌ای (Silver)",GOLD:"طلایی (Gold)",PLATINUM:"پلاتینیوم (Platinum)"};
const number=(n:number)=>new Intl.NumberFormat("fa-IR").format(n);

export default async function ClubPage({params}:{params:Promise<{locale:string}>}){
 const {locale}=await params; const session=await getCustomerSession();
 if(!session)return <main className="py-16"><div className="mx-auto max-w-3xl px-4"><section className="overflow-hidden rounded-[2rem] bg-[#001736] p-8 text-center text-white shadow-xl sm:p-12"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-white/10"><Star className="h-8 w-8 text-[#33c8ff]"/></div><h1 className="mt-6 text-3xl font-black">باشگاه مشتریان Hyper Doctor</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-white/65">برای مشاهده امتیاز واقعی، سطح وفاداری، تجهیزات ثبت‌شده و پیشنهادهای فعال وارد حساب کاربری شوید.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href={`/${locale}/account/login`} className="rounded-xl bg-[#009dd8] px-6 py-3 text-sm font-black text-white">ورود به حساب</Link><Link href={`/${locale}/account/register`} className="rounded-xl border border-white/15 bg-white/10 px-6 py-3 text-sm font-black text-white">ثبت‌نام</Link></div></section></div></main>;
 const data=await customerRpc<Club>("customer_club_dashboard"); const progress=data.tier==="PLATINUM"?100:Math.max(4,Math.min(100,Math.round((data.points/(data.points+data.nextTierPoints))*100)));
 return <main className="py-10 sm:py-14"><div className="mx-auto max-w-7xl px-4"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-primary">Hyper Doctor Loyalty</p><h1 className="mt-2 text-3xl font-black text-foreground">باشگاه مشتریان</h1><p className="mt-2 text-sm text-muted">سلام {data.profile.fullName}، به پنل اختصاصی خود خوش آمدید.</p></div><Link href={`/${locale}/account`} className="hidden items-center gap-2 text-xs font-black text-primary sm:flex"><ArrowLeft className="h-4 w-4"/>پنل کاربری</Link></div>
 <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><section className="overflow-hidden rounded-[2rem] bg-[#001736] p-6 text-white shadow-xl sm:p-8"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[#33c8ff]"><Diamond className="h-5 w-5"/><span className="text-xs font-black">وفاداری</span></div><div className="mt-5 text-4xl font-black">{number(data.points)}</div><div className="mt-1 text-xs text-white/60">امتیاز کل</div></div><Sparkles className="h-8 w-8 text-white/15"/></div><div className="mt-8"><div className="flex justify-between text-xs"><span className="text-white/60">سطح فعلی</span><span className="font-black text-[#33c8ff]">{tierLabel[data.tier]}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#33c8ff]" style={{width:`${progress}%`}}/></div><div className="mt-3 flex justify-between text-[11px] text-white/55"><span>هر امتیاز = {number(data.spendPerPoint)} تومان خرید تأییدشده</span><span>{data.nextTierPoints?`${number(data.nextTierPoints)} امتیاز تا سطح بعد`:"بالاترین سطح"}</span></div></div><div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-4"><div className="text-xs text-white/55">ارزش خرید تأییدشده</div><div className="mt-1 text-lg font-black">{number(data.lifetimeSpend)} تومان</div></div></section>
 <section className="rounded-[2rem] border border-border bg-card p-6 shadow-sm sm:p-8"><div className="flex items-center gap-2"><MonitorHeart className="h-5 w-5 text-primary"/><h2 className="font-black text-foreground">مرکز تجهیزات ثبت‌شده</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{data.devices.map(d=><div key={d.id} className="rounded-2xl border border-border bg-background p-4"><div className="font-black text-foreground">{d.productNameFa||d.productNameEn||"تجهیز پزشکی"}</div><div className="mt-1 text-xs text-muted">{[d.brand,d.modelNumber].filter(Boolean).join(" · ")||"—"}</div><div className="mt-3 text-xs text-muted" dir="ltr">SN: {d.serialNumber}</div><div className="mt-4 flex justify-between text-xs"><span className="font-black text-primary">{d.status}</span><span className="text-muted">گارانتی تا {new Date(d.expiresAt).toLocaleDateString("fa-IR")}</span></div></div>)}{!data.devices.length?<div className="sm:col-span-2 rounded-xl border border-dashed border-border p-7 text-center text-xs text-muted">هنوز تجهیزی با گارانتی به حساب شما متصل نشده است.</div>:null}</div></section></div>
 <section className="mt-6 rounded-[2rem] border border-border bg-card p-6 shadow-sm sm:p-8"><div className="flex items-center gap-2"><Gift className="h-5 w-5 text-primary"/><h2 className="text-lg font-black text-foreground">پیشنهادهای فعال</h2></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.offers.map(o=><article key={o.id} className="rounded-2xl border border-border bg-background p-5"><div className="inline-flex rounded-lg bg-primary/10 px-2 py-1 text-[10px] font-black text-primary">پیشنهاد ویژه</div><div className="mt-4 text-2xl font-black text-foreground">{o.type==="PERCENT"?`${number(o.value)}٪ تخفیف`:`${number(o.value)} تومان تخفیف`}</div><p className="mt-2 text-xs leading-6 text-muted">{o.minOrderAmount?`حداقل خرید ${number(o.minOrderAmount)} تومان. `:""}{o.maxDiscount?`سقف تخفیف ${number(o.maxDiscount)} تومان.`:""}</p><div className="mt-5 flex items-center justify-between"><code className="rounded-lg border border-dashed border-primary/40 bg-white px-3 py-2 text-sm font-black text-primary">{o.code}</code>{o.expiresAt?<span className="text-[10px] text-muted">تا {new Date(o.expiresAt).toLocaleDateString("fa-IR")}</span>:null}</div></article>)}{!data.offers.length?<div className="md:col-span-2 xl:col-span-3 rounded-xl border border-dashed border-border p-8 text-center text-xs text-muted">در حال حاضر کد تخفیف فعالی وجود ندارد.</div>:null}</div></section>
 </div></main>;
}
