import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { BadgeCheck, Box, ChevronLeft, ChevronRight, Headphones, RefreshCw, ShieldCheck, TriangleAlert } from "lucide-react";
import { Link } from "@/i18n/navigation";
import { Container } from "@/components/ui/container";
import { ProductGallery } from "@/components/site/product-gallery";
import { getCatalogProductV286 } from "@/lib/catalog-v286";
import { localizedDescription, localizedName, pickLocalized } from "@/lib/i18n-content";
import { isValidSlug } from "@/lib/slug";

function l(locale:string,fa:string,en:string,tr:string,ar:string){if(locale==="en")return en;if(locale==="tr")return tr;if(locale==="ar")return ar;return fa}
function specValue(locale:string,value:any){if(value==null)return"—";if(typeof value==="object")return pickLocalized(locale,value)||"—";return String(value)}

export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{
  const{locale,slug}=await params;if(!isValidSlug(slug))return{robots:{index:false,follow:true}};
  const lookup=await getCatalogProductV286(slug);
  if(lookup.status==="unavailable")return{title:l(locale,"کاتالوگ موقتاً در دسترس نیست","Catalog temporarily unavailable","Katalog geçici olarak kullanılamıyor","الكتالوج غير متاح مؤقتاً"),robots:{index:false,follow:true}};
  const product=lookup.product;if(!product)return{robots:{index:false,follow:true}};
  return{title:localizedName(locale,product),alternates:{canonical:`/${locale}/catalog/${slug}`},robots:{index:product.isPublished===true,follow:true}};
}

export default async function CatalogProductPage({params}:{params:Promise<{locale:string;slug:string}>}){
  const{locale,slug}=await params;if(!isValidSlug(slug))notFound();
  const lookup=await getCatalogProductV286(slug);
  if(lookup.status==="unavailable")return <main className="flex-1 bg-[#f7fafd] py-8 sm:py-12"><Container><section role="status" className="mx-auto max-w-3xl rounded-3xl border border-[#f0c36a] bg-[#fffaf0] p-6 shadow-[0_18px_48px_rgba(0,23,54,.07)] sm:p-9"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#fff0c9] text-[#8a5a00]"><TriangleAlert className="h-6 w-6"/></span><h1 className="mt-5 text-2xl font-black text-[#001736] sm:text-3xl">{l(locale,"اطلاعات این محصول موقتاً در دسترس نیست","This product is temporarily unavailable","Bu ürün bilgileri geçici olarak kullanılamıyor","معلومات هذا المنتج غير متاحة مؤقتاً")}</h1><p className="mt-3 text-sm leading-8 text-[#5d6169]">{l(locale,"ارتباط با منبع داده تأییدشده موقتاً برقرار نیست. برای جلوگیری از نمایش اطلاعات حدسی، محصول تا بازیابی اتصال از همان منبع بارگذاری نمی‌شود.","The verified data source is temporarily unreachable. To avoid showing guessed information, this product will not be rendered until that source is reachable again.","Doğrulanmış veri kaynağına geçici olarak ulaşılamıyor. Tahmini bilgi göstermemek için kaynak yeniden erişilebilir olana kadar ürün oluşturulmaz.","يتعذر الوصول مؤقتاً إلى مصدر البيانات الموثق. لتجنب عرض معلومات تقديرية، لن يتم عرض المنتج حتى يعود المصدر متاحاً.")}</p><div className="mt-6 flex flex-wrap gap-3"><Link href={`/catalog/${slug}`} className="vitalis-focus inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#002b5b] px-5 text-xs font-black text-white"><RefreshCw className="h-4 w-4"/>{l(locale,"تلاش دوباره","Try again","Tekrar dene","إعادة المحاولة")}</Link><Link href="/shop" className="vitalis-focus inline-flex min-h-11 items-center rounded-xl border border-[#c4c6d0] bg-white px-5 text-xs font-black text-[#001736]">{l(locale,"بازگشت به فروشگاه","Back to shop","Mağazaya dön","العودة إلى المتجر")}</Link></div></section></Container></main>;
  const product=lookup.product;if(!product)notFound();
  const name=localizedName(locale,product),description=localizedDescription(locale,product),categoryName=product.category?localizedName(locale,product.category):"",brand=product.brandEntity?.name||product.brand||"",Arrow=locale==="fa"||locale==="ar"?ChevronLeft:ChevronRight;
  let specs:Record<string,any>={};try{specs=typeof product.specs==="string"?JSON.parse(product.specs):(product.specs??{})}catch{specs={}}
  const entries=Object.entries(specs).filter(([,value])=>value!=null&&String(specValue(locale,value)).trim()!=="").slice(0,40),priceKnown=product.commerceReady===true&&Number(product.price)>0;
  return <main className="flex-1 bg-[#f7fafd] py-6 sm:py-9"><Container>
    <nav className="mb-6 flex flex-wrap items-center gap-2 text-[11px] font-medium text-[#747780]" aria-label="Breadcrumb"><Link href="/">{l(locale,"خانه","Home","Ana sayfa","الرئيسية")}</Link><Arrow className="h-3.5 w-3.5"/><Link href="/shop">{l(locale,"فروشگاه","Shop","Mağaza","المتجر")}</Link>{product.category?.slug&&categoryName?<><Arrow className="h-3.5 w-3.5"/><Link href={`/shop/${product.category.slug}`}>{categoryName}</Link></>:null}<Arrow className="h-3.5 w-3.5"/><strong className="max-w-[22rem] truncate text-[#181c1e]">{name}</strong></nav>

    <section className="grid gap-8 lg:grid-cols-[1.02fr_.98fr] lg:items-start lg:gap-12"><ProductGallery images={product.images??[]} locale={locale} fallbackAlt={name}/><div><div className="flex flex-wrap items-center gap-2">{brand?<span className="rounded-full border border-[#d7dbe0] bg-white px-3 py-1.5 text-[11px] font-black text-[#43474f]">{brand}</span>:null}<span className="inline-flex items-center gap-1.5 rounded-full bg-[#e2f7eb] px-3 py-1.5 text-[11px] font-black text-[#187143]"><ShieldCheck className="h-3.5 w-3.5"/>{l(locale,"مدیای منبع‌دار تأییدشده","Verified source media","Doğrulanmış kaynak görseli","وسائط مصدر موثقة")}</span></div><h1 className="mt-5 text-3xl font-black leading-[1.35] text-[#001736] sm:text-4xl">{name}</h1><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#747780]">{product.modelNumber?<span>{l(locale,"مدل","Model","Model","الموديل")}: <strong className="text-[#181c1e]">{product.modelNumber}</strong></span>:null}{product.sku?<span>SKU: <strong className="text-[#181c1e]">{product.sku}</strong></span>:null}</div>{description?<p className="mt-6 whitespace-pre-line text-sm leading-8 text-[#43474f]">{description}</p>:null}
      <div className="mt-7 rounded-[1.5rem] border border-[#e0e3e6] bg-white p-6 shadow-[0_18px_48px_rgba(0,23,54,.07)]">{priceKnown?<div><p className="text-xs font-bold text-[#747780]">{l(locale,"قیمت فروش","Sales price","Satış fiyatı","سعر البيع")}</p><strong className="mt-2 block text-3xl font-black text-[#001736]">{new Intl.NumberFormat(locale).format(Number(product.price))}</strong></div>:<div className="flex items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#eef4f9] text-[#002b5b]"><Box className="h-5 w-5"/></span><div><h2 className="text-sm font-black text-[#001736]">{l(locale,"اطلاعات فروش هنوز توسط اپراتور تأیید نشده است","Sales information has not been approved by the operator yet","Satış bilgileri henüz operatör tarafından onaylanmadı","لم تتم الموافقة على معلومات البيع من قبل المشغل بعد")}</h2><p className="mt-2 text-xs leading-6 text-[#747780]">{l(locale,"برای این محصول قیمت، موجودی یا امکان خرید ساختگی نمایش داده نمی‌شود. پس از ثبت داده واقعی، خرید به‌صورت خودکار فعال خواهد شد.","No fabricated price, stock or checkout state is shown. Commerce will activate only after real data is approved.","Bu ürün için uydurma fiyat, stok veya ödeme durumu gösterilmez. Gerçek veriler onaylandığında satış etkinleşir.","لا يتم عرض سعر أو مخزون أو حالة شراء مصطنعة. يتم تفعيل البيع فقط بعد اعتماد البيانات الحقيقية.")}</p></div></div>}<Link href="/contact" className="vitalis-focus mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#002b5b] px-5 text-xs font-black text-white"><Headphones className="h-4 w-4"/>{l(locale,"استعلام و مشاوره","Request information","Bilgi ve danışmanlık","الاستعلام والاستشارة")}</Link></div>
    </div></section>

    <section className="mt-10 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><BadgeCheck className="h-5 w-5 text-[#187143]"/><h2 className="mt-3 text-sm font-black text-[#001736]">{l(locale,"تأیید منبع","Source verification","Kaynak doğrulama","توثيق المصدر")}</h2><p className="mt-2 text-xs leading-6 text-[#747780]">{l(locale,"تصویر این کالا با شواهد کاتالوگ رسمی تطبیق داده شده است.","This product image is matched to verified catalog evidence.","Bu ürün görseli doğrulanmış katalog kanıtıyla eşleştirilmiştir.","تمت مطابقة صورة المنتج مع دليل كتالوج موثق.")}</p></div><div className="rounded-2xl border bg-white p-5"><Box className="h-5 w-5 text-[#002b5b]"/><h2 className="mt-3 text-sm font-black text-[#001736]">{l(locale,"قیمت و موجودی","Price & stock","Fiyat ve stok","السعر والمخزون")}</h2><p className="mt-2 text-xs leading-6 text-[#747780]">{l(locale,"فقط از داده واقعی و تأییدشده اپراتور استفاده می‌شود.","Only real operator-approved commerce data is used.","Yalnızca operatör onaylı gerçek satış verileri kullanılır.","تُستخدم فقط بيانات البيع الحقيقية المعتمدة من المشغل.")}</p></div><div className="rounded-2xl border bg-white p-5"><Headphones className="h-5 w-5 text-[#ba0036]"/><h2 className="mt-3 text-sm font-black text-[#001736]">{l(locale,"پشتیبانی تخصصی","Specialist support","Uzman destek","دعم متخصص")}</h2><p className="mt-2 text-xs leading-6 text-[#747780]">{l(locale,"برای انتخاب مدل و بررسی سازگاری با تیم هایپر دکتر تماس بگیرید.","Contact Hyper Doctor for model selection and compatibility guidance.","Model seçimi ve uyumluluk için Hyper Doctor ile iletişime geçin.","تواصل مع Hyper Doctor لاختيار الموديل والتحقق من التوافق.")}</p></div></section>

    {entries.length?<section className="mt-10 overflow-hidden rounded-2xl border border-[#e0e3e6] bg-white"><div className="border-b bg-[#f1f4f7] px-5 py-4"><h2 className="text-lg font-black text-[#001736]">{l(locale,"مشخصات ثبت‌شده","Recorded specifications","Kayıtlı özellikler","المواصفات المسجلة")}</h2></div><div>{entries.map(([key,value],index)=><div key={key} className={`grid gap-2 px-5 py-4 text-sm sm:grid-cols-[minmax(180px,.35fr)_1fr] ${index%2?"bg-[#f7fafd]":"bg-white"}`}><strong className="text-[#43474f]">{key}</strong><span className="text-[#181c1e]">{specValue(locale,value)}</span></div>)}</div></section>:null}
  </Container></main>
}
