import Link from "next/link";
import {
  AlertTriangle, CalendarClock, CreditCard, Headphones, Package, ReceiptText, ShieldCheck,
  ShoppingBag, Stethoscope, UsersRound, WalletCards,
} from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { formatPrice } from "@/lib/utils";

type DashboardData = {
  stats: { products:number; publishedProducts:number; services:number; orders:number; paidOrders:number; revenue:number; openTickets:number; pendingBookings:number; activeWarranties:number; newContacts:number };
  recentOrders: Array<{ id:string; orderNumber:string; customerName:string; total:number; status:string; createdAt:string }>;
  lowStock: Array<{ id:string; nameFa:string; nameEn:string; stock:number; sku:string }>;
  recentTickets: Array<{ id:string; ticketNo:string; subject:string; priority:string; status:string; guestName?:string|null; createdAt:string }>;
};
const statusFa:Record<string,string>={PENDING_PAYMENT:"در انتظار پرداخت",PAID:"پرداخت‌شده",PROCESSING:"در حال پردازش",SHIPPED:"ارسال‌شده",COMPLETED:"تکمیل‌شده",CANCELLED:"لغوشده",FAILED:"ناموفق"};

export default async function AdminDashboardPage(){
  const data=await adminRpc<DashboardData>("admin_dashboard");
  const s=data.stats;
  const cards=[
    {label:"فروش کل",value:`${formatPrice(s.revenue,"fa")} تومان`,sub:`${s.paidOrders} پرداخت موفق`,icon:WalletCards,tone:"bg-[#edf4ff] text-[#002b5b]"},
    {label:"سفارش‌ها",value:new Intl.NumberFormat("fa-IR").format(s.orders),sub:"کل سفارش‌های ثبت‌شده",icon:ShoppingBag,tone:"bg-emerald-50 text-emerald-700"},
    {label:"محصولات",value:new Intl.NumberFormat("fa-IR").format(s.publishedProducts),sub:`${s.products} کل محصول`,icon:Package,tone:"bg-amber-50 text-amber-700"},
    {label:"تیکت باز",value:new Intl.NumberFormat("fa-IR").format(s.openTickets),sub:"نیازمند پیگیری",icon:Headphones,tone:"bg-[#fff0f3] text-[#e80346]"},
  ];
  const quick=[
    {label:"رزروهای در انتظار",value:s.pendingBookings,icon:CalendarClock,href:"/admin/bookings"},
    {label:"گارانتی فعال",value:s.activeWarranties,icon:ShieldCheck,href:"/admin/warranties"},
    {label:"خدمات فعال",value:s.services,icon:Stethoscope,href:"/admin/services"},
    {label:"پیام جدید",value:s.newContacts,icon:UsersRound,href:"/admin/contacts"},
  ];
  return <div className="mx-auto max-w-[1450px] space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">Hyper Doctor Control Center</p><h1 className="mt-2 text-3xl font-black text-[#001736]">داشبورد مدیریت</h1><p className="mt-2 text-sm text-[#747780]">نمای لحظه‌ای فروشگاه، خدمات، پشتیبانی و خدمات پس از فروش</p></div><div className="flex gap-2"><Link href="/admin/products/new" className="rounded-xl bg-[#e80346] px-4 py-3 text-xs font-black text-white">افزودن محصول</Link><Link href="/admin/reports" className="rounded-xl border border-[#dfe4ea] bg-white px-4 py-3 text-xs font-black text-[#001736]">گزارش فروش</Link></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,sub,icon:Icon,tone})=><article key={label} className="rounded-[1.55rem] border border-[#e2e6eb] bg-white p-5 shadow-[0_12px_30px_rgba(0,23,54,.04)]"><div className="flex items-start justify-between gap-4"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5"/></span><span className="text-[10px] font-black text-emerald-600">LIVE</span></div><p className="mt-5 text-xs font-black text-[#747780]">{label}</p><p className="mt-1 text-2xl font-black tabular-nums text-[#001736]">{value}</p><p className="mt-1 text-[11px] text-[#9a9da5]">{sub}</p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
      <section className="overflow-hidden rounded-[1.6rem] border border-[#e2e6eb] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#edf0f2] px-5 py-4"><div><h2 className="font-black text-[#001736]">سفارش‌های اخیر</h2><p className="mt-1 text-[11px] text-[#8a8e96]">آخرین فعالیت‌های فروش</p></div><Link href="/admin/orders" className="text-xs font-black text-[#e80346]">مشاهده همه</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-[#f7fafd] text-[11px] font-black text-[#747780]"><tr><th className="px-5 py-3 text-start">شماره سفارش</th><th className="px-5 py-3 text-start">مشتری</th><th className="px-5 py-3 text-start">مبلغ</th><th className="px-5 py-3 text-start">وضعیت</th><th className="px-5 py-3 text-start">تاریخ</th></tr></thead><tbody className="divide-y divide-[#edf0f2]">{data.recentOrders.map(o=><tr key={o.id} className="hover:bg-[#fafcff]"><td className="px-5 py-4"><Link href={`/admin/orders/${o.id}`} dir="ltr" className="font-mono text-xs font-black text-[#002b5b]">{o.orderNumber}</Link></td><td className="px-5 py-4 font-bold text-[#43474f]">{o.customerName}</td><td className="px-5 py-4 font-black tabular-nums text-[#001736]">{formatPrice(o.total,"fa")}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${o.status==="PAID"?"bg-emerald-50 text-emerald-700":o.status==="FAILED"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{statusFa[o.status]||o.status}</span></td><td className="px-5 py-4 text-xs text-[#747780]">{new Date(o.createdAt).toLocaleDateString("fa-IR")}</td></tr>)}{data.recentOrders.length===0?<tr><td colSpan={5} className="px-5 py-14 text-center text-[#8a8e96]">هنوز سفارشی ثبت نشده است.</td></tr>:null}</tbody></table></div></section>
      <section className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#001736] text-white"><CreditCard className="h-5 w-5"/></span><div><h2 className="font-black text-[#001736]">میانبر عملیاتی</h2><p className="text-[11px] text-[#8a8e96]">وضعیت‌های مهم امروز</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-1">{quick.map(({label,value,icon:Icon,href})=><Link key={label} href={href} className="flex items-center gap-3 rounded-2xl border border-[#edf0f2] bg-[#fafcff] p-3.5 transition hover:border-[#009dd8]/30"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white text-[#002b5b] shadow-sm"><Icon className="h-4 w-4"/></span><span className="flex-1 text-xs font-black text-[#43474f]">{label}</span><b className="text-lg text-[#001736]">{new Intl.NumberFormat("fa-IR").format(value)}</b></Link>)}</div></section>
    </div>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-red-50 text-[#e80346]"><AlertTriangle className="h-5 w-5"/></span><div><h2 className="font-black text-[#001736]">هشدار موجودی</h2><p className="text-[11px] text-[#8a8e96]">کالاهای نیازمند توجه</p></div></div><div className="mt-5 space-y-2.5">{data.lowStock.map(p=><Link key={p.id} href={`/admin/products/${p.id}`} className="flex items-center justify-between gap-3 rounded-xl bg-[#f9fbfd] p-3"><div className="min-w-0"><p className="truncate text-xs font-black text-[#001736]">{p.nameFa||p.nameEn}</p><p dir="ltr" className="mt-1 text-[10px] text-[#8a8e96]">{p.sku}</p></div><span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-black text-red-700">{p.stock}</span></Link>)}{data.lowStock.length===0?<div className="rounded-xl bg-emerald-50 p-4 text-center text-xs font-black text-emerald-700">هشدار موجودی نداریم.</div>:null}</div></section>
      <section className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf4ff] text-[#002b5b]"><ReceiptText className="h-5 w-5"/></span><div><h2 className="font-black text-[#001736]">پشتیبانی اخیر</h2><p className="text-[11px] text-[#8a8e96]">آخرین تیکت‌های ثبت‌شده</p></div></div><div className="mt-5 space-y-2.5">{data.recentTickets.map(t=><Link key={t.id} href={`/admin/support/${t.id}`} className="block rounded-xl border border-[#edf0f2] bg-[#fafcff] p-3"><div className="flex items-center justify-between gap-3"><span dir="ltr" className="font-mono text-[10px] font-black text-[#e80346]">{t.ticketNo}</span><span className="text-[10px] font-black text-[#747780]">{t.priority}</span></div><p className="mt-2 line-clamp-1 text-xs font-black text-[#001736]">{t.subject}</p></Link>)}{data.recentTickets.length===0?<div className="rounded-xl bg-[#f7fafd] p-4 text-center text-xs text-[#747780]">تیکت جدیدی وجود ندارد.</div>:null}</div></section>
    </div>
  </div>;
}
