import Link from "next/link";
import { ShieldCheck, KeyRound, ArrowLeft } from "lucide-react";
import { requireCustomerSession } from "@/lib/customer-auth";
import { changePasswordAction } from "../actions";

export default async function AccountSecurityPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{status?:string}>}){
  const {locale}=await params; const q=await searchParams; await requireCustomerSession(locale); const action=changePasswordAction.bind(null,locale);
  const message=q.status==="changed"?"رمز عبور با موفقیت تغییر کرد.":q.status==="invalid"?"رمز فعلی صحیح نیست.":q.status==="mismatch"?"رمز جدید و تکرار آن یکسان نیست.":q.status==="short"?"رمز جدید باید حداقل ۸ کاراکتر باشد.":null;
  return <main className="py-14"><div className="mx-auto max-w-xl px-4"><Link href={`/${locale}/account`} className="inline-flex items-center gap-2 text-sm font-bold text-primary"><ArrowLeft className="h-4 w-4"/>بازگشت به حساب</Link><section className="mt-5 vitalis-glass rounded-[2rem] border border-white/70 p-7 shadow-xl sm:p-10"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 text-primary"><ShieldCheck className="h-7 w-7"/></div><h1 className="mt-6 text-2xl font-black text-foreground">امنیت حساب</h1><p className="mt-2 text-sm leading-7 text-muted">برای تغییر رمز، ابتدا رمز فعلی را وارد کنید. پس از تغییر، نشست‌های فعال روی دستگاه‌های دیگر بسته می‌شوند.</p>{message?<div className={`mt-5 rounded-xl border p-3 text-xs font-bold ${q.status==="changed"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-red-200 bg-red-50 text-red-700"}`}>{message}</div>:null}<form action={action} className="mt-6 space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">رمز فعلی</span><input name="currentPassword" type="password" required autoComplete="current-password" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">رمز جدید</span><input name="newPassword" type="password" required minLength={8} maxLength={128} autoComplete="new-password" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">تکرار رمز جدید</span><input name="confirmPassword" type="password" required minLength={8} maxLength={128} autoComplete="new-password" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label><button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-black text-white"><KeyRound className="h-4 w-4"/>تغییر رمز عبور</button></form></section></div></main>;
}
