import Link from "next/link";
import { ArrowLeft, ArrowRight, KeyRound, ShieldCheck } from "lucide-react";
import { requireCustomerSession } from "@/lib/customer-auth";
import { PasswordField } from "@/components/site/password-field";
import { changePasswordAction } from "../actions";

const pick=(locale:string,fa:string,en:string,tr:string,ar:string)=>locale==="en"?en:locale==="tr"?tr:locale==="ar"?ar:fa;
export default async function AccountSecurityPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{status?:string}>}){
 const {locale}=await params; const q=await searchParams; await requireCustomerSession(locale); const action=changePasswordAction.bind(null,locale); const rtl=locale==="fa"||locale==="ar"; const BackIcon=rtl?ArrowRight:ArrowLeft;
 const message=q.status==="changed"?pick(locale,"رمز عبور با موفقیت تغییر کرد.","Password changed successfully.","Şifre başarıyla değiştirildi.","تم تغيير كلمة المرور بنجاح."):q.status==="invalid"?pick(locale,"رمز فعلی صحیح نیست.","Current password is incorrect.","Mevcut şifre yanlış.","كلمة المرور الحالية غير صحيحة."):q.status==="mismatch"?pick(locale,"رمز جدید و تکرار آن یکسان نیست.","New passwords do not match.","Yeni şifreler eşleşmiyor.","كلمتا المرور الجديدتان غير متطابقتين."):q.status==="short"?pick(locale,"رمز جدید باید بین ۸ تا ۱۲۸ کاراکتر باشد.","Password must be between 8 and 128 characters.","Şifre 8 ile 128 karakter arasında olmalı.","يجب أن تتكون كلمة المرور من 8 إلى 128 حرفاً."):q.status==="failed"?pick(locale,"تغییر رمز در حال حاضر انجام نشد. لطفاً کمی بعد دوباره تلاش کنید.","The password could not be changed right now. Please try again shortly.","Şifre şu anda değiştirilemedi. Lütfen kısa süre sonra tekrar deneyin.","تعذر تغيير كلمة المرور حالياً. يرجى المحاولة مرة أخرى بعد قليل."):null;
 const show=pick(locale,"نمایش رمز عبور","Show password","Şifreyi göster","إظهار كلمة المرور"); const hide=pick(locale,"پنهان کردن رمز عبور","Hide password","Şifreyi gizle","إخفاء كلمة المرور");
 const field=(name:string,label:string,autoComplete:string)=><label className="block"><span className="mb-2 block text-sm font-bold text-[#43474f]">{label}</span><PasswordField name={name} required minLength={8} maxLength={128} autoComplete={autoComplete} showLabel={show} hideLabel={hide}/></label>;
 return <main className="bg-[#f5f8fb] py-10 sm:py-14"><div className="mx-auto max-w-2xl px-4"><Link href={`/${locale}/account`} className="inline-flex items-center gap-2 text-sm font-bold text-[#001736]"><BackIcon className="h-4 w-4"/>{pick(locale,"بازگشت به حساب","Back to account","Hesaba dön","العودة إلى الحساب")}</Link><section className="mt-5 rounded-[2rem] border border-white bg-white p-7 shadow-[0_22px_60px_rgba(0,23,54,.08)] sm:p-10"><div className="flex items-center gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-[#edf4ff] text-[#001736]"><ShieldCheck className="h-8 w-8"/></span><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#747780]">Hyper Doctor Security</p><h1 className="mt-2 text-2xl font-black text-[#001736]">{pick(locale,"امنیت حساب","Account security","Hesap güvenliği","أمان الحساب")}</h1></div></div><p className="mt-5 text-sm leading-7 text-[#5f6570]">{pick(locale,"برای تغییر رمز، ابتدا رمز فعلی را وارد کنید. پس از تغییر، نشست‌های فعال روی دستگاه‌های دیگر بسته می‌شوند.","Enter your current password first. Other active sessions are revoked after a successful change.","Önce mevcut şifrenizi girin. Başarılı değişiklikten sonra diğer oturumlar kapatılır.","أدخل كلمة المرور الحالية أولاً. بعد التغيير الناجح يتم إلغاء الجلسات النشطة الأخرى.")}</p>{message?<div role={q.status==="changed"?"status":"alert"} className={`mt-5 rounded-xl border p-3 text-xs font-bold ${q.status==="changed"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-red-200 bg-red-50 text-red-700"}`}>{message}</div>:null}<form action={action} className="mt-7 space-y-4">{field("currentPassword",pick(locale,"رمز فعلی","Current password","Mevcut şifre","كلمة المرور الحالية"),"current-password")}{field("newPassword",pick(locale,"رمز جدید","New password","Yeni şifre","كلمة المرور الجديدة"),"new-password")}{field("confirmPassword",pick(locale,"تکرار رمز جدید","Confirm new password","Yeni şifre tekrar","تأكيد كلمة المرور الجديدة"),"new-password")}<button className="flex min-h-13 w-full items-center justify-center gap-2 rounded-xl bg-[#001736] px-5 text-sm font-black text-white"><KeyRound className="h-4 w-4"/>{pick(locale,"تغییر رمز عبور","Change password","Şifreyi değiştir","تغيير كلمة المرور")}</button></form></section></div></main>;
}
