import Link from "next/link";
import { DatabaseZap, FileCheck2, Layers3, PackageCheck, ShieldCheck } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { createStagingBatch, stageHooshmandHistoricalPriceMaster, stageVerifiedBwellStarter, stageVerifiedJtsWheelchairStarter } from "./actions";

type Source={id:string;sourceType:string;title:string;sourceDate:string|null;reference:string;status:string;productCount:number};
type Batch={id:string;title:string;status:string;sourceTitle:string;sourceType:string;pricePolicy:string;stockPolicy:string;currency:string;total:number;valid:number;needsReview:number;approved:number;promoted:number;createdAt:string};

const C:Record<AdminLocale,Record<string,string>>={
fa:{eyebrow:"محصول واقعی",title:"Product Master Staging",desc:"محصولات منبع‌دار ابتدا اینجا به‌صورت Draft بررسی می‌شوند؛ فقط ردیف تأییدشده می‌تواند به کاتالوگ اصلی منتقل شود.",sources:"منابع",empty:"هنوز Batch استیجینگ ساخته نشده است.",new:"ساخت Batch جدید",source:"منبع",batch:"عنوان Batch",price:"سیاست قیمت",stock:"سیاست موجودی",create:"ساخت",bwell:"B.Well 2025–2026",bwellSub:"۹ مدل منبع‌دار؛ بدون قیمت، موجودی، تصویر یا گارانتی ساختگی.",jts:"JTS ویلچر دستی",jtsSub:"۹ مدل متمایز از کاتالوگ JTS؛ بدون ادعای نمایندگی رسمی و بدون قیمت یا موجودی فرضی.",hooshmand:"Hooshmand — اردیبهشت ۱۴۰۵",hooshmandSub:"۴۱ SKU از Price List؛ قیمت فقط Historical Consumer Price است و موجودی از این منبع تعیین نمی‌شود.",stage:"ساخت Staging",total:"کل",valid:"معتبر",review:"نیازمند بررسی",approved:"تأیید",promoted:"منتقل‌شده",open:"باز کردن",policy:"سیاست تجارت"},
en:{eyebrow:"Real products",title:"Product Master Staging",desc:"Source-backed products are reviewed here as Drafts first; only approved rows can be promoted to the product master.",sources:"Sources",empty:"No staging batch exists yet.",new:"Create staging batch",source:"Source",batch:"Batch title",price:"Price policy",stock:"Stock policy",create:"Create",bwell:"B.Well 2025–2026",bwellSub:"Nine source-backed models with no fabricated price, stock, image or warranty.",jts:"JTS manual wheelchairs",jtsSub:"Nine distinct catalogue models with no official-representation claim and no inferred current price or stock.",hooshmand:"Hooshmand — Ordibehesht 1405",hooshmandSub:"41 price-list SKUs; prices are historical consumer observations only and this source never establishes inventory.",stage:"Stage pack",total:"Total",valid:"Valid",review:"Needs review",approved:"Approved",promoted:"Promoted",open:"Open",policy:"Commerce policy"},
tr:{eyebrow:"Gerçek ürünler",title:"Product Master Staging",desc:"Kaynaklı ürünler önce Taslak olarak burada incelenir; yalnızca onaylanan satırlar ana kataloğa aktarılır.",sources:"Kaynaklar",empty:"Henüz staging batch yok.",new:"Yeni staging batch",source:"Kaynak",batch:"Batch başlığı",price:"Fiyat politikası",stock:"Stok politikası",create:"Oluştur",bwell:"B.Well 2025–2026",bwellSub:"Dokuz kaynaklı model; uydurma fiyat, stok, görsel veya garanti yok.",jts:"JTS manuel tekerlekli sandalyeler",jtsSub:"Dokuz ayrı katalog modeli; resmi temsilcilik iddiası, güncel fiyat veya stok varsayımı yok.",hooshmand:"Hooshmand — Ordibehesht 1405",hooshmandSub:"41 fiyat-listesi SKU'su; fiyatlar yalnızca geçmiş tüketici gözlemidir ve stok kanıtlamaz.",stage:"Paketi stage et",total:"Toplam",valid:"Geçerli",review:"İnceleme",approved:"Onaylı",promoted:"Aktarıldı",open:"Aç",policy:"Ticaret politikası"},
ar:{eyebrow:"منتجات حقيقية",title:"Product Master Staging",desc:"تتم مراجعة المنتجات الموثقة بالمصدر هنا كمسودات أولاً، ولا تُنقل إلى الكتالوج الرئيسي إلا بعد الاعتماد.",sources:"المصادر",empty:"لا توجد دفعات مرحلية بعد.",new:"إنشاء دفعة مرحلية",source:"المصدر",batch:"عنوان الدفعة",price:"سياسة السعر",stock:"سياسة المخزون",create:"إنشاء",bwell:"B.Well 2025–2026",bwellSub:"تسعة نماذج موثقة دون سعر أو مخزون أو صورة أو ضمان مختلق.",jts:"كراسي JTS اليدوية",jtsSub:"تسعة نماذج مستقلة من الكتالوج دون ادعاء تمثيل رسمي أو افتراض سعر أو مخزون حالي.",hooshmand:"Hooshmand — أرديبهشت 1405",hooshmandSub:"41 SKU من قائمة الأسعار؛ الأسعار ملاحظات تاريخية للمستهلك فقط ولا تثبت المخزون.",stage:"إنشاء Staging",total:"الإجمالي",valid:"صالح",review:"يحتاج مراجعة",approved:"معتمد",promoted:"منقول",open:"فتح",policy:"سياسة التجارة"}
};

function PackCard({title,description,action}:{title:string;description:string;action:()=>Promise<void>}){return <section className="rounded-3xl border border-sky-200 bg-sky-50 p-5 sm:p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-6 w-6 shrink-0 text-sky-700"/><div><h2 className="font-black">{title}</h2><p className="mt-2 text-sm leading-7 text-sky-950/70">{description}</p></div></div><form action={action} className="mt-5"><button className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-sky-800 px-5 text-sm font-black text-white"><FileCheck2 className="h-4 w-4"/>{title}</button></form></section>}

export default async function Page(){
 const [locale,sources,batches]=await Promise.all([currentAdminLocale(),adminRpc<Source[]>("admin_catalog_sources"),adminRpc<Batch[]>("admin_catalog_staging_batches")]);
 const t=C[locale];
 return <div className="mx-auto max-w-7xl space-y-7">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-[#009dd8]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black">{t.title}</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-[#747780]">{t.desc}</p></div><Link href="/admin/products/sources" className="inline-flex min-h-11 items-center gap-2 rounded-2xl border bg-white px-5 text-sm font-black"><DatabaseZap className="h-4 w-4"/>{t.sources}</Link></div>

  <section className="rounded-3xl border bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><Layers3 className="h-5 w-5 text-[#002b5b]"/><h2 className="font-black">{t.new}</h2></div><form action={createStagingBatch} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-bold lg:col-span-2">{t.source}<select name="sourceId" required className="mt-2 h-11 w-full rounded-xl border px-3"><option value="">—</option>{sources.filter(s=>s.status==="CONFIRMED").map(s=><option key={s.id} value={s.id}>{s.title} · {s.sourceType}</option>)}</select></label><label className="text-xs font-bold lg:col-span-2">{t.batch}<input name="title" required className="mt-2 h-11 w-full rounded-xl border px-3"/></label><label className="text-xs font-bold">{t.price}<select name="pricePolicy" defaultValue="IGNORE" className="mt-2 h-11 w-full rounded-xl border px-3"><option value="IGNORE">IGNORE</option><option value="HISTORICAL">HISTORICAL</option><option value="CURRENT">CURRENT</option></select></label><label className="text-xs font-bold">{t.stock}<select name="stockPolicy" defaultValue="IGNORE" className="mt-2 h-11 w-full rounded-xl border px-3"><option value="IGNORE">IGNORE</option><option value="CURRENT">CURRENT</option></select></label><input type="hidden" name="priceKind" value="OTHER"/><input type="hidden" name="currency" value="IRT"/><div className="flex items-end lg:col-span-2"><button className="min-h-11 rounded-xl bg-[#002b5b] px-5 text-sm font-black text-white">{t.create}</button></div></form></section>

  <div className="grid gap-5 lg:grid-cols-3"><PackCard title={t.bwell} description={t.bwellSub} action={stageVerifiedBwellStarter}/><PackCard title={t.jts} description={t.jtsSub} action={stageVerifiedJtsWheelchairStarter}/><PackCard title={t.hooshmand} description={t.hooshmandSub} action={stageHooshmandHistoricalPriceMaster}/></div>

  <section className="overflow-hidden rounded-3xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr>{[t.batch,t.source,t.policy,t.total,t.valid,t.review,t.approved,t.promoted,""].map((x,i)=><th key={`${x}-${i}`} className="border-b px-5 py-3 text-start">{x}</th>)}</tr></thead><tbody>{batches.map(b=><tr key={b.id} className="border-b last:border-0"><td className="px-5 py-4"><b>{b.title}</b><div className="mt-1 text-xs text-muted">{b.status}</div></td><td className="px-5 py-4">{b.sourceTitle}<div className="mt-1 text-xs text-muted">{b.sourceType}</div></td><td className="px-5 py-4 text-xs">{b.pricePolicy} / {b.stockPolicy} · {b.currency}</td><td className="px-5 py-4">{adminNumber(Number(b.total||0),locale)}</td><td className="px-5 py-4">{adminNumber(Number(b.valid||0),locale)}</td><td className="px-5 py-4">{adminNumber(Number(b.needsReview||0),locale)}</td><td className="px-5 py-4">{adminNumber(Number(b.approved||0),locale)}</td><td className="px-5 py-4">{adminNumber(Number(b.promoted||0),locale)}</td><td className="px-5 py-4"><Link href={`/admin/products/staging/${b.id}`} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-black"><PackageCheck className="h-4 w-4"/>{t.open}</Link></td></tr>)}{!batches.length?<tr><td colSpan={9} className="px-6 py-16 text-center text-muted">{t.empty}</td></tr>:null}</tbody></table></div></section>
 </div>;
}
