import Link from "next/link";
import { redirect } from "next/navigation";
import { LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { getCustomerSession } from "@/lib/customer-auth";
import { loginAction } from "../../actions";

const copy={fa:{title:"ورود به حساب کاربری",sub:"سفارش‌ها، گارانتی و درخواست‌های پشتیبانی را در یک پنل مدیریت کنید.",id:"ایمیل یا شماره موبایل",pass:"رمز عبور",submit:"ورود امن",forgot:"رمز عبور را فراموش کرده‌اید؟",new:"حساب ندارید؟",register:"ثبت‌نام"},tr:{title:"Hesabınıza giriş yapın",sub:"Siparişlerinizi, garantilerinizi ve destek taleplerinizi tek panelden yönetin.",id:"E-posta veya telefon",pass:"Şifre",submit:"Güvenli giriş",forgot:"Şifrenizi mi unuttunuz?",new:"Hesabınız yok mu?",register:"Kayıt ol"},en:{title:"Sign in to your account",sub:"Manage orders, warranties and support requests from one secure dashboard.",id:"Email or phone",pass:"Password",submit:"Secure sign in",forgot:"Forgot password?",new:"New here?",register:"Create account"},ar:{title:"تسجيل الدخول إلى حسابك",sub:"إدارة الطلبات والضمان والدعم من لوحة واحدة آمنة.",id:"البريد الإلكتروني أو الهاتف",pass:"كلمة المرور",submit:"تسجيل دخول آمن",forgot:"نسيت كلمة المرور؟",new:"ليس لديك حساب؟",register:"إنشاء حساب"}} as const;

export default async function LoginPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{error?:string;reset?:string}>}){
  const {locale}=await params; const q=await searchParams; if(await getCustomerSession()) redirect(`/${locale}/account`);
  const t=copy[locale as keyof typeof copy]??copy.fa; const action=loginAction.bind(null,locale);
  return <main className="relative overflow-hidden py-12 sm:py-20"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_15%,rgba(0,157,216,.18),transparent_32%),radial-gradient(circle_at_85%_75%,rgba(0,43,91,.15),transparent_34%)]"/><div className="relative mx-auto grid max-w-5xl gap-8 px-4 lg:grid-cols-[1.05fr_.95fr]">
    <section className="hidden rounded-[2rem] bg-[#001736] p-10 text-white shadow-2xl lg:flex lg:flex-col lg:justify-between"><div><div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10"><ShieldCheck className="h-7 w-7 text-[#33c8ff]"/></div><h1 className="mt-8 text-4xl font-black leading-tight">Hyper Doctor<br/><span className="text-[#33c8ff]">Customer Portal</span></h1><p className="mt-5 max-w-md text-sm leading-7 text-white/70">{t.sub}</p></div><div className="grid grid-cols-2 gap-3 text-xs"><div className="rounded-2xl border border-white/10 bg-white/5 p-4">SSL / HttpOnly Session</div><div className="rounded-2xl border border-white/10 bg-white/5 p-4">Orders · Warranty · Support</div></div></section>
    <section className="vitalis-glass rounded-[2rem] border border-white/70 p-6 shadow-xl sm:p-9"><div className="mb-8"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><LockKeyhole className="h-6 w-6"/></div><h2 className="mt-5 text-2xl font-black text-foreground">{t.title}</h2><p className="mt-2 text-sm leading-7 text-muted lg:hidden">{t.sub}</p></div>
      {q.error?<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{q.error==="invalid"?"اطلاعات ورود صحیح نیست.":"لطفاً همه فیلدهای لازم را کامل کنید."}</div>:null}{q.reset?<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-700">رمز عبور با موفقیت تغییر کرد.</div>:null}
      <form action={action} className="space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{t.id}</span><div className="flex h-12 items-center gap-2 rounded-xl border border-border bg-white px-3"><Mail className="h-4 w-4 text-muted"/><input name="identifier" required autoComplete="username" className="h-full w-full bg-transparent text-sm outline-none" dir="ltr"/></div></label><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{t.pass}</span><input name="password" type="password" required minLength={8} autoComplete="current-password" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label><div className="flex items-center justify-end"><Link href={`/${locale}/account/forgot-password`} className="text-xs font-bold text-primary hover:underline">{t.forgot}</Link></div><button className="min-h-12 w-full rounded-xl bg-primary px-5 text-sm font-black text-white shadow-lg transition hover:-translate-y-0.5">{t.submit}</button></form>
      <p className="mt-6 text-center text-sm text-muted">{t.new} <Link href={`/${locale}/account/register`} className="font-black text-primary">{t.register}</Link></p>
    </section></div></main>;
}
