import Link from "next/link";
import { redirect } from "next/navigation";
import { Eye, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import { getCustomerSession } from "@/lib/customer-auth";
import { loginAction } from "../actions";

const BG="https://lh3.googleusercontent.com/aida/AEtjO1XsKXqpr5yRiWfVB-d1KkBSurcii3IusZ5vZkc9D6KJcRR2SW3LlkVb-kaVx_yZRT4vSqEEXeoUFzdyWN1mHWFmDkkjV0keIXfXF5byYE9NeKt9mmkYsTvRI_72rpslADLitqr6hLFZbB00yBCLxSbIuFZH0nRc_vYfHwwI8A90SQDK_1CQZEkrKVxZxSq7dDRJdxfuXX2drvm5TWsE7CK0UMYZrEKP-RBsNaS2WC7uZ_nDW4mmGG21XSWG";
const copy={fa:{title:"ورود به حساب کاربری",id:"ایمیل یا شماره موبایل",pass:"رمز عبور",submit:"ورود",forgot:"فراموشی رمز عبور؟",new:"حساب ندارید؟",register:"ثبت‌نام",secure:"اتصال امن و محافظت‌شده"},tr:{title:"Hesabınıza giriş yapın",id:"E-posta veya telefon",pass:"Şifre",submit:"Giriş",forgot:"Şifrenizi mi unuttunuz?",new:"Hesabınız yok mu?",register:"Kayıt ol",secure:"Güvenli bağlantı"},en:{title:"Sign in to your account",id:"Email or phone",pass:"Password",submit:"Sign in",forgot:"Forgot password?",new:"New here?",register:"Create account",secure:"Secure protected connection"},ar:{title:"تسجيل الدخول",id:"البريد الإلكتروني أو الهاتف",pass:"كلمة المرور",submit:"دخول",forgot:"نسيت كلمة المرور؟",new:"ليس لديك حساب؟",register:"إنشاء حساب",secure:"اتصال آمن ومحمي"}} as const;

export default async function LoginPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{error?:string;reset?:string}>}){
 const {locale}=await params; const q=await searchParams; if(await getCustomerSession())redirect(`/${locale}/account`); const t=copy[locale as keyof typeof copy]??copy.fa; const action=loginAction.bind(null,locale);
 return <main className="relative min-h-[calc(100vh-5rem)] overflow-hidden bg-[#f7fafd] py-10 sm:py-16" style={{backgroundImage:`linear-gradient(rgba(247,250,253,.91),rgba(247,250,253,.96)),url(${BG})`,backgroundSize:"520px"}}><div className="mx-auto max-w-xl px-4">
  <div className="mb-7 text-center"><div className="text-3xl font-black tracking-tight text-[#001736]">Hyper Doctor</div><p className="mt-2 text-sm text-[#747780]">{t.title}</p></div>
  <section className="rounded-[2rem] border border-white/80 bg-white/88 p-6 shadow-[0_28px_80px_rgba(0,23,54,.12)] backdrop-blur-xl sm:p-9">
   <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-[#d6e3ff] bg-[#edf4ff] text-[#001736]"><UserRound className="h-7 w-7"/></div>
   {q.error?<div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-3 text-center text-xs font-bold text-red-700">{q.error==="invalid"?"اطلاعات ورود صحیح نیست.":"لطفاً همه فیلدهای لازم را کامل کنید."}</div>:null}{q.reset?<div className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-center text-xs font-bold text-emerald-700">رمز عبور با موفقیت تغییر کرد.</div>:null}
   <form action={action} className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold text-[#181c1e]">{t.id}</span><div className="flex h-14 items-center gap-3 rounded-xl border-2 border-[#747780] bg-white px-4 focus-within:border-[#001736]"><UserRound className="h-5 w-5 shrink-0 text-[#001736]"/><input name="identifier" required autoComplete="username" dir="ltr" className="h-full w-full bg-transparent text-sm outline-none"/></div></label><label className="block"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-bold text-[#181c1e]">{t.pass}</span><Link href={`/${locale}/account/forgot-password`} className="text-xs font-bold text-[#001736] hover:underline">{t.forgot}</Link></div><div className="flex h-14 items-center gap-3 rounded-xl border-2 border-[#747780] bg-white px-4 focus-within:border-[#001736]"><LockKeyhole className="h-5 w-5 shrink-0 text-[#001736]"/><input name="password" type="password" required minLength={8} autoComplete="current-password" dir="ltr" className="h-full w-full bg-transparent text-sm outline-none"/><Eye className="h-5 w-5 shrink-0 text-[#181c1e]"/></div></label><button className="min-h-14 w-full rounded-xl bg-[#001736] px-5 text-sm font-black text-white shadow-[0_14px_28px_rgba(0,23,54,.18)] transition hover:bg-[#002b5b]">{t.submit}</button></form>
   <p className="mt-6 text-center text-sm text-[#5f6570]">{t.new} <Link href={`/${locale}/account/register`} className="font-black text-[#001736] underline underline-offset-4">{t.register}</Link></p><div className="mt-7 flex items-center justify-center gap-2 border-t border-[#e0e3e6] pt-5 text-[11px] text-[#747780]"><ShieldCheck className="h-4 w-4"/>{t.secure} · SSL</div>
  </section>
 </div></main>;
}
