"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { adminRpc } from "@/lib/admin-data";

function b(v:FormDataEntryValue|null){return v==="on"||v==="true"}
export async function saveCollection(formData:FormData){const id=String(formData.get("id")||"").trim();const data:any={id:id||undefined,slug:String(formData.get("slug")||"").trim(),titleFa:String(formData.get("titleFa")||"").trim(),titleTr:String(formData.get("titleTr")||"").trim(),titleEn:String(formData.get("titleEn")||"").trim(),titleAr:String(formData.get("titleAr")||"").trim(),descriptionFa:String(formData.get("descriptionFa")||""),descriptionTr:String(formData.get("descriptionTr")||""),descriptionEn:String(formData.get("descriptionEn")||""),descriptionAr:String(formData.get("descriptionAr")||""),heroImageUrl:String(formData.get("heroImageUrl")||"").trim(),seoTitleFa:String(formData.get("seoTitleFa")||""),seoTitleTr:String(formData.get("seoTitleTr")||""),seoTitleEn:String(formData.get("seoTitleEn")||""),seoTitleAr:String(formData.get("seoTitleAr")||""),seoDescriptionFa:String(formData.get("seoDescriptionFa")||""),seoDescriptionTr:String(formData.get("seoDescriptionTr")||""),seoDescriptionEn:String(formData.get("seoDescriptionEn")||""),seoDescriptionAr:String(formData.get("seoDescriptionAr")||""),isPublished:b(formData.get("isPublished")),sortOrder:Number(formData.get("sortOrder")||0)};const r=await adminRpc<{id:string}>("admin_upsert_collection",{p_data:data});revalidatePath("/admin/collections");revalidatePath("/","layout");redirect(`/admin/collections/${r.id}?saved=1`);}
export async function archiveCollection(formData:FormData){const id=String(formData.get("id")||"").trim();if(id)await adminRpc("admin_archive_collection",{p_id:id});revalidatePath("/admin/collections");revalidatePath("/","layout");}
export async function saveCollectionProducts(formData:FormData){const id=String(formData.get("id")||"").trim();const ids=formData.getAll("productIds").map(String).map(x=>x.trim()).filter(Boolean).slice(0,500);await adminRpc("admin_set_collection_products",{p_collection_id:id,p_product_ids:ids});revalidatePath(`/admin/collections/${id}`);revalidatePath("/","layout");redirect(`/admin/collections/${id}?saved=1`);}
