import Link from "next/link";
import { GalleryVerticalEnd } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import type { AdminLocale } from "@/lib/admin-i18n";
import { archiveCollection, saveCollection } from "./actions";

type CItem={id:string;slug:string;titleFa:string;titleTr:string;titleEn:string;titleAr:string;isPublished:boolean;sortOrder:number;productCount:number};type B={collections:CItem[]};
const C:Record<AdminLocale,Record<string,string>>={fa:{title:"کالکشن‌ها",sub:"صفحات مستقل و قابل سئو برای مجموعه‌های منتخب محصولات.",new:"کالکشن جدید",slug:"Slug",fa:"عنوان فارسی",tr:"عنوان ترکی",en:"عنوان انگلیسی",ar:"عنوان عربی",image:"تصویر Hero",order:"ترتیب",active:"منتشر شده",save:"ایجاد و ادامه",edit:"ویرایش و محصولات",archive:"آرشیو",products:"محصول",empty:"هنوز کالکشنی ساخته نشده است."},en:{title:"Collections",sub:"Independent SEO-ready landing pages for curated product groups.",new:"New collection",slug:"Slug",fa:"Persian title",tr:"Turkish title",en:"English title",ar:"Arabic title",image:"Hero image URL",order:"Order",active:"Published",save:"Create & continue",edit:"Edit & products",archive:"Archive",products:"products",empty:"No collections yet."},tr:{title:"Koleksiyonlar",sub:"Seçilmiş ürün grupları için bağımsız SEO uyumlu sayfalar.",new:"Yeni koleksiyon",slug:"Slug",fa:"Farsça başlık",tr:"Türkçe başlık",en:"İngilizce başlık",ar:"Arapça başlık",image:"Hero görsel URL",order:"Sıra",active:"Yayında",save:"Oluştur ve devam et",edit:"Düzenle ve ürünler",archive:"Arşivle",products:"ürün",empty:"Henüz koleksiyon yok."},ar:{title:"المجموعات",sub:"صفحات مستقلة محسّنة لمحركات البحث لمجموعات المنتجات المختارة.",new:"مجموعة جديدة",slug:"Slug",fa:"العنوان الفارسي",tr:"العنوان التركي",en:"العنوان الإنجليزي",ar:"العنوان العربي",image:"رابط صورة البطل",order:"الترتيب",active:"منشور",save:"إنشاء ومتابعة",edit:"تحرير والمنتجات",archive:"أرشفة",products:"منتج",empty:"لا توجد مجموعات بعد."}};
function n(x:CItem,l:AdminLocale){return({fa:x.titleFa,tr:x.titleTr,en:x.titleEn,ar:x.titleAr}[l]||x.titleEn||x.titleFa)}
export default async function CollectionsPage(){const[locale,b]=await Promise.all([currentAdminLocale(),adminRpc<B>("admin_collections_bundle",{})]);const t=C[locale],f="h-10 rounded-xl border border-[#dfe4ea] px-3 text-sm";return <div className="mx-auto max-w-7xl space-y-6"><header><h1 className="flex items-center gap-2 text-2xl font-black text-[#001736]"><GalleryVerticalEnd className="h-6 w-6 text-[#009dd8]"/>{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.sub}</p></header><section className="rounded-3xl border bg-white p-5"><h2 className="mb-4 font-black text-[#001736]">{t.new}</h2><form action={saveCollection} className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input name="slug" required dir="ltr" placeholder={t.slug} className={f}/><input name="titleFa" required placeholder={t.fa} className={f}/><input name="titleTr" placeholder={t.tr} className={f}/><input name="titleEn" required placeholder={t.en} className={f}/><input name="titleAr" placeholder={t.ar} className={f}/><input name="heroImageUrl" dir="ltr" placeholder={t.image} className={`${f} xl:col-span-2`}/><input name="sortOrder" type="number" defaultValue="0" placeholder={t.order} className={f}/><label className="flex h-10 items-center gap-2 rounded-xl border px-3 text-xs font-bold"><input type="checkbox" name="isPublished"/>{t.active}</label><button className="h-10 rounded-xl bg-[#e80346] px-5 text-xs font-black text-white xl:col-span-3">{t.save}</button></form></section>{b.collections.length?<div className="grid gap-4 lg:grid-cols-2">{b.collections.map(x=><article key={x.id} className="rounded-3xl border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black text-[#001736]">{n(x,locale)}</h2><p className="mt-1 text-xs text-[#747780]" dir="ltr">/{x.slug}</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-black ${x.isPublished?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{x.isPublished?t.active:"Draft"}</span></div><p className="mt-3 text-xs text-[#747780]">{x.productCount} {t.products}</p><div className="mt-4 flex items-center justify-between"><Link href={`/admin/collections/${x.id}`} className="rounded-xl bg-[#001736] px-4 py-2 text-xs font-black text-white">{t.edit}</Link><form action={archiveCollection}><input type="hidden" name="id" value={x.id}/><button className="text-xs font-black text-[#ba0036]">{t.archive}</button></form></div></article>)}</div>:<div className="rounded-3xl border border-dashed bg-white p-10 text-center text-sm text-[#8b9098]">{t.empty}</div>}</div>}
