import Link from "next/link";
import { FileText, ImageIcon, Newspaper, Package, PanelsTopLeft } from "lucide-react";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import type { AdminLocale } from "@/lib/admin-i18n";

const copy:Record<AdminLocale,{eyebrow:string;title:string;subtitle:string;enter:string;modules:Array<{href:string;title:string;body:string;kind:string}>}>={
  fa:{eyebrow:"عملیات محتوا",title:"مدیریت محتوا و محصولات",subtitle:"مرکز دسترسی سریع به کاتالوگ، محتوا، بنرها و رسانه‌های سایت",enter:"ورود به بخش",modules:[{href:"/admin/products",title:"مدیریت محصولات",body:"کاتالوگ، قیمت، موجودی، وضعیت انتشار و ویرایش محصول",kind:"products"},{href:"/admin/articles",title:"مقالات و مجله علمی",body:"ایجاد و ویرایش محتوای علمی چهارزبانه",kind:"articles"},{href:"/admin/banners",title:"بنرها و جشنواره",body:"مدیریت اسلایدها، تصاویر کمپین و زمان‌بندی انتشار",kind:"banners"},{href:"/admin/pages",title:"صفحات سایت",body:"مدیریت صفحات محتوایی و وضعیت انتشار",kind:"pages"},{href:"/admin/media",title:"رسانه‌ها",body:"مدیریت فایل‌های تصویری و رسانه‌ای",kind:"media"}]},
  ar:{eyebrow:"عمليات المحتوى",title:"إدارة المحتوى والمنتجات",subtitle:"مركز وصول سريع إلى الكتالوج والمحتوى واللافتات ووسائط الموقع",enter:"فتح القسم",modules:[{href:"/admin/products",title:"إدارة المنتجات",body:"الكتالوج والأسعار والمخزون وحالة النشر وتحرير المنتجات",kind:"products"},{href:"/admin/articles",title:"المقالات والمجلة العلمية",body:"إنشاء وتحرير محتوى علمي بأربع لغات",kind:"articles"},{href:"/admin/banners",title:"اللافتات والحملات",body:"إدارة الشرائح وصور الحملات وجدولة النشر",kind:"banners"},{href:"/admin/pages",title:"صفحات الموقع",body:"إدارة صفحات المحتوى وحالة النشر",kind:"pages"},{href:"/admin/media",title:"الوسائط",body:"إدارة الصور والملفات الإعلامية",kind:"media"}]},
  en:{eyebrow:"Content Operations",title:"Content & product management",subtitle:"Quick access to catalog, editorial content, banners and site media",enter:"Open section",modules:[{href:"/admin/products",title:"Product management",body:"Catalog, pricing, inventory, publication status and product editing",kind:"products"},{href:"/admin/articles",title:"Articles & scientific magazine",body:"Create and edit four-language scientific content",kind:"articles"},{href:"/admin/banners",title:"Banners & campaigns",body:"Manage slides, campaign imagery and publishing schedules",kind:"banners"},{href:"/admin/pages",title:"Site pages",body:"Manage content pages and publishing status",kind:"pages"},{href:"/admin/media",title:"Media library",body:"Manage image and media assets",kind:"media"}]},
  tr:{eyebrow:"İçerik Operasyonları",title:"İçerik ve ürün yönetimi",subtitle:"Katalog, içerik, banner ve site medya alanlarına hızlı erişim",enter:"Bölüme gir",modules:[{href:"/admin/products",title:"Ürün yönetimi",body:"Katalog, fiyat, stok, yayın durumu ve ürün düzenleme",kind:"products"},{href:"/admin/articles",title:"Makaleler ve bilimsel dergi",body:"Dört dilde bilimsel içerik oluşturma ve düzenleme",kind:"articles"},{href:"/admin/banners",title:"Banner ve kampanyalar",body:"Slaytları, kampanya görsellerini ve yayın takvimini yönetin",kind:"banners"},{href:"/admin/pages",title:"Site sayfaları",body:"İçerik sayfalarını ve yayın durumunu yönetin",kind:"pages"},{href:"/admin/media",title:"Medya",body:"Görsel ve medya dosyalarını yönetin",kind:"media"}]}
};
const iconFor=(kind:string)=>kind==="products"?Package:kind==="articles"?Newspaper:kind==="banners"?PanelsTopLeft:kind==="pages"?FileText:ImageIcon;
const toneFor=(kind:string)=>kind==="products"?"bg-[#001736] text-white":kind==="articles"?"bg-[#edf4ff] text-[#002b5b]":kind==="banners"?"bg-[#fff0f3] text-[#e80346]":kind==="pages"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700";

export default async function AdminContentHubPage(){
  const l=await currentAdminLocale(); const t=copy[l];
  return <div className="mx-auto max-w-[1450px]">
    <div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.subtitle}</p></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{t.modules.map(({href,title,body,kind})=>{const Icon=iconFor(kind);return <Link key={href} href={href} className="group rounded-[1.6rem] border border-[#e2e6eb] bg-white p-6 shadow-[0_12px_30px_rgba(0,23,54,.04)] transition hover:-translate-y-1 hover:shadow-[0_18px_40px_rgba(0,23,54,.08)]"><span className={`flex h-12 w-12 items-center justify-center rounded-2xl ${toneFor(kind)}`}><Icon className="h-5 w-5"/></span><h2 className="mt-5 text-lg font-black text-[#001736]">{title}</h2><p className="mt-2 text-sm leading-7 text-[#747780]">{body}</p><span className="mt-5 inline-flex text-xs font-black text-[#e80346]">{t.enter} ←</span></Link>})}</div>
  </div>;
}
