import { notFound } from "next/navigation";
import { getLocale, getTranslations } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { Container } from "@/components/ui/container";
import { ProductGallery } from "@/components/site/product-gallery";
import { AddToCartButton } from "@/components/site/add-to-cart-button";
import { ProductActions } from "@/components/site/product-actions";
import { ShopProductCard } from "@/components/site/shop-product-card";
import { formatPrice } from "@/lib/utils";
import { localizedDescription, localizedName, pickLocalized } from "@/lib/i18n-content";
import { getProductBySlug, getRelatedProducts } from "@/lib/queries";
import { isValidSlug } from "@/lib/slug";
import { BadgeCheck, CheckCircle2, ChevronLeft, ChevronRight, Headphones, Home, Network, Star, Stethoscope, Tags, Truck } from "lucide-react";

type LocalizedSpec=string|{fa?:string;tr?:string;en?:string;ar?:string};
type Specs=Record<string,LocalizedSpec>;
type ProductReview={id:string;authorName:string;rating:number;title?:string|null;body?:string|null};
type StructuredAttribute={id:string;code:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;groupFa:string;groupTr:string;groupEn:string;groupAr:string;dataType:string;unit:string;valueText?:string|null;valueNumber?:number|string|null;valueBoolean?:boolean|null};
type TaxonomyTerm={id:string;dimension:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string};
type CatalogRelation={relationType:string;sortOrder:number;product:any};
function l(locale:string,fa:string,en:string,tr:string,ar:string){if(locale==="en")return en;if(locale==="tr")return tr;if(locale==="ar")return ar;return fa}
function localizedSpecValue(locale:string,value:LocalizedSpec){return typeof value==="string"?value:pickLocalized(locale,value)}
function attrName(a:StructuredAttribute,locale:string){return pickLocalized(locale,{fa:a.nameFa,tr:a.nameTr,en:a.nameEn,ar:a.nameAr})||a.nameEn||a.nameFa||a.code}
function attrGroup(a:StructuredAttribute,locale:string){return pickLocalized(locale,{fa:a.groupFa,tr:a.groupTr,en:a.groupEn,ar:a.groupAr})||a.groupEn||a.groupFa||l(locale,"مشخصات فنی","Technical specifications","Teknik özellikler","المواصفات الفنية")}
function attrValue(a:StructuredAttribute,locale:string){let value="—";if(a.dataType==="BOOLEAN")value=a.valueBoolean?l(locale,"بله","Yes","Evet","نعم"):l(locale,"خیر","No","Hayır","لا");else if(a.dataType==="NUMBER")value=a.valueNumber==null?"—":String(a.valueNumber);else value=a.valueText?.trim()||"—";return value!=="—"&&a.unit?`${value} ${a.unit}`:value}
const dimensionLabel=(dimension:string,locale:string)=>({REGULATORY_CLASSIFICATION:l(locale,"طبقه‌بندی رگولاتوری","Regulatory classification","Düzenleyici sınıflandırma","التصنيف التنظيمي"),MEDICAL_SPECIALTY:l(locale,"تخصص پزشکی","Medical specialty","Tıbbi uzmanlık","التخصص الطبي"),CLINICAL_APPLICATION:l(locale,"کاربرد بالینی","Clinical application","Klinik uygulama","التطبيق السريري"),INTENDED_USE:l(locale,"کاربری موردنظر","Intended use","Amaçlanan kullanım","الاستخدام المقصود"),CARE_SETTING:l(locale,"محیط مراقبت","Care setting","Bakım ortamı","بيئة الرعاية"),PRODUCT_TYPE:l(locale,"نوع محصول","Product type","Ürün tipi","نوع المنتج"),PRODUCT_TECHNOLOGY:l(locale,"فناوری","Technology","Teknoloji","التقنية"),COLLECTION:l(locale,"کالکشن","Collection","Koleksiyon","المجموعة"),COMPATIBILITY:l(locale,"سازگاری","Compatibility","Uyumluluk","التوافق")}[dimension]||dimension);
function termName(term:TaxonomyTerm,locale:string){return pickLocalized(locale,{fa:term.nameFa,tr:term.nameTr,en:term.nameEn,ar:term.nameAr})||term.nameEn||term.nameFa}
function rowClass(index:number){return `grid gap-2 px-5 py-4 text-sm sm:grid-cols-[minmax(180px,.35fr)_1fr] sm:px-6 ${index%2?"bg-[#f7fafd]":"bg-white"}`}

export default async function ProductPage({params}:{params:Promise<{slug:string}>}){
 const{slug}=await params;if(!isValidSlug(slug))notFound();const[locale,t,c]=await Promise.all([getLocale(),getTranslations("shop"),getTranslations("common")]);const product=await getProductBySlug(slug);if(!product)notFound();const related=await getRelatedProducts(product.categoryId,product.id);let specs:Specs={};try{specs=typeof product.specs==="string"?JSON.parse(product.specs) as Specs:(product.specs??{}) as Specs}catch{specs={}}const legacySpecs=Object.entries(specs),structured=(product.structuredAttributes??[]) as StructuredAttribute[],taxonomy=(product.taxonomyTerms??[]) as TaxonomyTerm[],relations=(product.catalogRelations??[]) as CatalogRelation[],name=localizedName(locale,product),description=localizedDescription(locale,product),categoryName=product.category?localizedName(locale,product.category):"",image=product.images?.[0],reviews=(product.reviews??[]) as ProductReview[],validRatings=reviews.map(r=>Number(r.rating)).filter(r=>Number.isFinite(r)&&r>=1&&r<=5),avgRating=validRatings.length?validRatings.reduce((a,b)=>a+b,0)/validRatings.length:null,Arrow=locale==="fa"||locale==="ar"?ChevronLeft:ChevronRight,hasDiscount=Number(product.compareAtPrice)>Number(product.price)&&Number(product.price)>=0,discount=hasDiscount?Math.round((1-product.price/product.compareAtPrice)*100):0,stock=Math.max(0,Math.floor(Number(product.stock)||0)),purchaseMin=Math.max(1,Math.min(50,Math.floor(Number(product.minOrderQty)||1))),configuredMax=product.maxOrderQty==null?null:Math.max(0,Math.floor(Number(product.maxOrderQty)||0)),purchaseMax=configuredMax===null?stock:Math.min(stock,configuredMax),canPurchase=purchaseMax>=purchaseMin,stockBelowMinimum=stock>0&&!canPurchase,brandName=product.brandEntity?.name||"";
 const groupedAttributes=new Map<string,StructuredAttribute[]>();for(const attr of structured){const group=attrGroup(attr,locale),list=groupedAttributes.get(group)??[];list.push(attr);groupedAttributes.set(group,list)}const taxonomyGroups=[...new Set(taxonomy.map(x=>x.dimension))].map(d=>({dimension:d,items:taxonomy.filter(x=>x.dimension===d)}));const compatible=relations.filter(r=>r.relationType==="COMPATIBLE_WITH").map(r=>r.product).slice(0,4),accessories=relations.filter(r=>r.relationType==="ACCESSORY").map(r=>r.product).slice(0,4);
 return <main className="flex-1 bg-[#f7fafd] py-5 sm:py-8 lg:py-10"><Container>
  <nav className="mb-6 flex flex-wrap items-center gap-2 text-[11px] font-medium text-[#747780]" aria-label={l(locale,"مسیر صفحه","Breadcrumb","Sayfa yolu","مسار الصفحة")}><Link href="/">{l(locale,"خانه","Home","Ana sayfa","الرئيسية")}</Link><Arrow className="h-3.5 w-3.5"/><Link href="/shop">{l(locale,"فروشگاه","Shop","Mağaza","المتجر")}</Link>{categoryName&&product.category?.slug?<><Arrow className="h-3.5 w-3.5"/><Link href={`/shop/${product.category.slug}`}>{categoryName}</Link></>:null}<Arrow className="h-3.5 w-3.5"/><strong className="max-w-[22rem] truncate text-[#181c1e]">{name}</strong></nav>
  <section className="grid gap-8 lg:grid-cols-[1.04fr_.96fr] lg:items-start lg:gap-12"><ProductGallery images={product.images??[]} locale={locale} fallbackAlt={name}/><div className="lg:pt-1"><div className="flex flex-wrap items-center gap-2">{brandName?<span className="rounded-full border bg-white px-3 py-1.5 text-[11px] font-black text-[#43474f]">{brandName}</span>:null}{product.rentalEligible?<Link href={`/rental?product=${encodeURIComponent(product.id)}`} className="rounded-full bg-[#e7f5fb] px-3 py-1.5 text-[11px] font-black text-[#002b5b]">{l(locale,"قابل اجاره","Rental eligible","Kiralanabilir","قابل للإيجار")}</Link>:null}{stockBelowMinimum?<span className="rounded-full bg-[#fff2cc] px-3 py-1.5 text-[11px] font-black text-[#765700]">{l(locale,"موجودی کمتر از حداقل سفارش","Stock below minimum order quantity","Stok minimum sipariş miktarının altında","المخزون أقل من الحد الأدنى للطلب")}</span>:stock>0?<span className="inline-flex items-center gap-1.5 rounded-full bg-[#e2f7eb] px-3 py-1.5 text-[11px] font-black text-[#187143]"><CheckCircle2 className="h-3.5 w-3.5"/>{t("inStock")}</span>:<span className="rounded-full bg-[#ffdada] px-3 py-1.5 text-[11px] font-black text-[#920028]">{t("outOfStock")}</span>}</div>
   <h1 className="mt-5 text-3xl font-black leading-[1.35] text-[#001736] sm:text-4xl lg:text-[2.6rem]">{name}</h1><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-[#747780]">{avgRating!==null?<span className="inline-flex items-center gap-1.5"><Star className="h-4.5 w-4.5 fill-[#f4b942] text-[#f4b942]"/><strong className="text-[#181c1e]">{avgRating.toFixed(1)}</strong><span>({validRatings.length})</span></span>:null}{product.modelNumber?<span>{l(locale,"مدل","Model","Model","الموديل")}: <strong className="text-[#181c1e]">{product.modelNumber}</strong></span>:null}{product.sku?<span>SKU: <strong className="text-[#181c1e]">{product.sku}</strong></span>:null}</div>{description?<p className="mt-6 whitespace-pre-line text-sm leading-8 text-[#43474f]">{description}</p>:null}
   <div className="mt-7 rounded-[1.6rem] border bg-white p-6 shadow-[0_20px_54px_rgba(0,23,54,.075)] sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div>{hasDiscount?<div className="mb-1 text-sm text-[#9aa0aa] line-through">{formatPrice(product.compareAtPrice,locale)} {c("currency")}</div>:null}<div className="flex items-baseline gap-2"><strong className="text-3xl font-black text-[#001736] sm:text-4xl">{formatPrice(product.price,locale)}</strong><span className="text-xs font-bold text-[#747780]">{c("currency")}</span></div></div>{discount>0?<span className="rounded-xl bg-[#ba0036] px-3 py-2 text-xs font-black text-white">{discount}% {l(locale,"تخفیف","OFF","İNDİRİM","خصم")}</span>:null}</div><div className="mt-6"><AddToCartButton type="product" id={product.id} nameFa={product.nameFa} nameTr={product.nameTr} nameEn={product.nameEn} nameAr={product.nameAr} price={product.price} image={image?.url} disabled={!canPurchase} minQuantity={purchaseMin} maxQuantity={purchaseMax}/></div><div className="mt-3"><ProductActions productId={product.id}/></div></div>
   <div className="mt-5 grid grid-cols-2 gap-3">{product.professionalUse?<div className="rounded-2xl border bg-white p-4"><Stethoscope className="h-5 w-5 text-[#009dd8]"/><strong className="mt-3 block text-xs text-[#001736]">{l(locale,"مناسب استفاده حرفه‌ای / کلینیکی","Professional / clinical use","Profesyonel / klinik kullanım","استخدام مهني / سريري")}</strong></div>:null}{product.homeUse?<div className="rounded-2xl border bg-white p-4"><Home className="h-5 w-5 text-[#009dd8]"/><strong className="mt-3 block text-xs text-[#001736]">{l(locale,"مناسب استفاده خانگی","Home use","Ev kullanımı","استخدام منزلي")}</strong></div>:null}{product.rentalEligible?<div className="rounded-2xl border bg-white p-4"><Truck className="h-5 w-5 text-[#009dd8]"/><strong className="mt-3 block text-xs text-[#001736]">{l(locale,"امکان درخواست اجاره","Rental request available","Kiralama talebi mevcut","طلب الإيجار متاح")}</strong></div>:null}{product.warrantyMonths?<div className="rounded-2xl border bg-white p-4"><BadgeCheck className="h-5 w-5 text-[#009dd8]"/><strong className="mt-3 block text-xs text-[#001736]">{product.warrantyMonths} {l(locale,"ماه گارانتی","months warranty","ay garanti","شهر ضمان")}</strong></div>:null}</div>
  </div></section>
  <section className="mt-8 rounded-2xl border bg-white p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#e7f5fb] text-[#002b5b]"><Headphones className="h-5 w-5"/></span><div><h2 className="text-sm font-black text-[#001736]">{l(locale,"نیاز به راهنمایی دارید؟","Need product guidance?","Ürün desteğine mi ihtiyacınız var?","هل تحتاج إلى إرشاد حول المنتج؟")}</h2><p className="mt-1 text-xs leading-6 text-[#747780]">{l(locale,"برای بررسی مشخصات، سازگاری و انتخاب محصول مناسب با تیم پشتیبانی تماس بگیرید.","Contact support to review specifications, compatibility and product selection.","Özellikler, uyumluluk ve ürün seçimi için destek ekibiyle iletişime geçin.","تواصل مع الدعم لمراجعة المواصفات والتوافق واختيار المنتج.")}</p><Link href="/contact" className="mt-2 inline-flex text-xs font-black text-[#002b5b] hover:underline">{l(locale,"تماس با ما","Contact us","İletişim","اتصل بنا")}</Link></div></div></section>
  {taxonomyGroups.length?<section className="mt-12 sm:mt-16"><div className="mb-5 flex items-center gap-3"><Network className="h-6 w-6 text-[#009dd8]"/><h2 className="text-2xl font-black text-[#001736]">{l(locale,"پروفایل بالینی و کاتالوگ","Clinical & catalog profile","Klinik ve katalog profili","الملف السريري والكتالوج")}</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{taxonomyGroups.map(group=><article key={group.dimension} className="rounded-2xl border bg-white p-5"><h3 className="text-xs font-black text-[#747780]">{dimensionLabel(group.dimension,locale)}</h3><div className="mt-3 flex flex-wrap gap-2">{group.items.map(term=><span key={term.id} className="rounded-full bg-[#f1f4f7] px-3 py-1.5 text-xs font-bold text-[#001736]">{termName(term,locale)}</span>)}</div></article>)}</div></section>:null}
  {structured.length?<section className="mt-12 sm:mt-16"><div className="mb-5 flex items-center gap-3"><Tags className="h-6 w-6 text-[#009dd8]"/><h2 className="text-2xl font-black text-[#001736]">{l(locale,"مشخصات ساختاریافته","Structured specifications","Yapılandırılmış özellikler","المواصفات المنظمة")}</h2></div><div className="space-y-5">{[...groupedAttributes.entries()].map(([group,items])=><section key={group} className="overflow-hidden rounded-3xl border bg-white"><h3 className="border-b bg-[#f7fafd] px-5 py-4 text-sm font-black text-[#001736]">{group}</h3><dl>{items.map((attr,index)=><div key={attr.id} className={rowClass(index)}><dt className="font-semibold text-[#747780]">{attrName(attr,locale)}</dt><dd className="font-bold text-[#181c1e]">{attrValue(attr,locale)}</dd></div>)}</dl></section>)}</div></section>:legacySpecs.length?<section className="mt-12 sm:mt-16"><h2 className="mb-5 text-2xl font-black text-[#001736]">{t("specsTitle")}</h2><dl className="overflow-hidden rounded-3xl border bg-white">{legacySpecs.map(([key,value],index)=><div key={key} className={rowClass(index)}><dt className="font-semibold text-[#747780]">{key}</dt><dd className="font-bold text-[#181c1e]">{localizedSpecValue(locale,value)}</dd></div>)}</dl></section>:null}
  {compatible.length?<section className="mt-12 sm:mt-16"><h2 className="mb-5 text-2xl font-black text-[#001736]">{l(locale,"محصولات سازگار","Compatible products","Uyumlu ürünler","المنتجات المتوافقة")}</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{compatible.map(p=><ShopProductCard key={p.id} product={p}/>)}</div></section>:null}
  {accessories.length?<section className="mt-12 sm:mt-16"><h2 className="mb-5 text-2xl font-black text-[#001736]">{l(locale,"لوازم جانبی مرتبط","Related accessories","İlgili aksesuarlar","الملحقات ذات الصلة")}</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{accessories.map(p=><ShopProductCard key={p.id} product={p}/>)}</div></section>:null}
  {reviews.length?<section className="mt-12 sm:mt-16"><div className="flex items-center justify-between gap-4"><h2 className="text-2xl font-black text-[#001736]">{l(locale,"نظر خریداران","Customer reviews","Müşteri yorumları","آراء العملاء")}</h2><span className="text-xs font-bold text-[#747780]">{reviews.length}</span></div><div className="mt-5 grid gap-4 md:grid-cols-2">{reviews.slice(0,6).map(review=><article key={review.id} className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-[#001736]">{review.authorName}</strong>{Number(review.rating)>=1&&Number(review.rating)<=5?<span className="flex items-center gap-1 text-xs font-black text-[#8a6400]"><Star className="h-4 w-4 fill-[#f4b942] text-[#f4b942]"/>{review.rating}/5</span>:null}</div>{review.title?<h3 className="mt-3 text-sm font-bold">{review.title}</h3>:null}{review.body?<p className="mt-2 text-sm leading-7 text-[#43474f]">{review.body}</p>:null}</article>)}</div></section>:null}
  {related.length?<section className="mt-12 sm:mt-16"><div className="mb-6 flex items-center justify-between gap-4"><h2 className="text-2xl font-black text-[#001736]">{t("relatedTitle")}</h2>{product.category?.slug?<Link href={`/shop/${product.category.slug}`} className="inline-flex items-center gap-1 text-xs font-black text-[#ba0036]">{l(locale,"مشاهده همه","View all","Tümünü gör","عرض الكل")}<Arrow className="h-4 w-4"/></Link>:null}</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{related.map(p=><ShopProductCard key={p.id} product={p}/>)}</div></section>:null}
 </Container></main>
}
