import { BadgePercent, CalendarClock, TicketPercent, UsersRound } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminCurrency, adminDate, adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { upsertCoupon } from "./actions";

type Coupon={id:string;code:string;type:"PERCENT"|"FIXED";value:number;minOrderAmount?:number|null;maxDiscount?:number|null;usageLimit?:number|null;usageLimitPerUser?:number|null;startsAt?:string|null;expiresAt?:string|null;isActive:boolean;usageCount:number};
const c:Record<AdminLocale,Record<string,string>>={
  fa:{eyebrow:"کمپین‌ها",title:"مدیریت کدهای تخفیف",subtitle:"ساخت و پایش کدهای درصدی یا مبلغ ثابت با محدودیت زمانی و تعداد استفاده",activeCodes:"کدهای فعال",totalUsage:"کل استفاده",createdCodes:"کدهای ساخته‌شده",newCode:"ایجاد کد جدید",newCodeSub:"تنظیمات کد تخفیف",code:"کد تخفیف",percent:"درصدی",fixed:"مبلغ ثابت",value:"مقدار",minOrder:"حداقل مبلغ سفارش",maxDiscount:"حداکثر تخفیف",usageLimit:"سقف کل استفاده",perUser:"سقف هر کاربر",active:"فعال",start:"شروع",end:"پایان",create:"ایجاد کد تخفیف",recent:"کدهای فعال و اخیر",recentSub:"نمایش وضعیت و میزان استفاده",inactive:"غیرفعال",usage:"استفاده",empty:"هنوز کد تخفیفی ساخته نشده است."},
  ar:{eyebrow:"العروض",title:"إدارة أكواد الخصم",subtitle:"إنشاء ومتابعة خصومات نسبية أو ثابتة مع حدود زمنية وحدود للاستخدام",activeCodes:"الأكواد النشطة",totalUsage:"إجمالي الاستخدام",createdCodes:"الأكواد المنشأة",newCode:"إنشاء كود جديد",newCodeSub:"إعدادات كود الخصم",code:"كود الخصم",percent:"نسبة مئوية",fixed:"مبلغ ثابت",value:"القيمة",minOrder:"الحد الأدنى للطلب",maxDiscount:"الحد الأقصى للخصم",usageLimit:"إجمالي حد الاستخدام",perUser:"حد الاستخدام لكل عميل",active:"نشط",start:"البداية",end:"النهاية",create:"إنشاء كود خصم",recent:"الأكواد النشطة والحديثة",recentSub:"عرض الحالة وعدد مرات الاستخدام",inactive:"غير نشط",usage:"الاستخدام",empty:"لم يتم إنشاء أي كود خصم بعد."},
  en:{eyebrow:"Promotions",title:"Discount code management",subtitle:"Create and monitor percentage or fixed discounts with time and usage limits",activeCodes:"Active codes",totalUsage:"Total usage",createdCodes:"Codes created",newCode:"Create new code",newCodeSub:"Discount code settings",code:"Discount code",percent:"Percentage",fixed:"Fixed amount",value:"Value",minOrder:"Minimum order amount",maxDiscount:"Maximum discount",usageLimit:"Total usage limit",perUser:"Limit per customer",active:"Active",start:"Starts",end:"Ends",create:"Create discount code",recent:"Active & recent codes",recentSub:"Status and usage overview",inactive:"Inactive",usage:"Usage",empty:"No discount code has been created yet."},
  tr:{eyebrow:"Kampanyalar",title:"İndirim kodu yönetimi",subtitle:"Yüzde veya sabit tutarlı indirimleri zaman ve kullanım limitleriyle oluşturun ve izleyin",activeCodes:"Aktif kodlar",totalUsage:"Toplam kullanım",createdCodes:"Oluşturulan kodlar",newCode:"Yeni kod oluştur",newCodeSub:"İndirim kodu ayarları",code:"İndirim kodu",percent:"Yüzde",fixed:"Sabit tutar",value:"Değer",minOrder:"Minimum sipariş tutarı",maxDiscount:"Maksimum indirim",usageLimit:"Toplam kullanım limiti",perUser:"Müşteri başına limit",active:"Aktif",start:"Başlangıç",end:"Bitiş",create:"İndirim kodu oluştur",recent:"Aktif ve son kodlar",recentSub:"Durum ve kullanım özeti",inactive:"Pasif",usage:"Kullanım",empty:"Henüz indirim kodu oluşturulmadı."}
};

export default async function AdminDiscountsPage(){
  const [coupons,l]=await Promise.all([adminRpc<Coupon[]>("admin_coupons"),currentAdminLocale()]);
  const t=c[l];
  const active=coupons.filter(c=>c.isActive).length;
  const used=coupons.reduce((a,c)=>a+c.usageCount,0);
  return <div className="mx-auto max-w-[1450px] space-y-6">
    <div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.subtitle}</p></div>
    <div className="grid gap-4 md:grid-cols-3"><Metric label={t.activeCodes} value={adminNumber(active,l)} icon={BadgePercent}/><Metric label={t.totalUsage} value={adminNumber(used,l)} icon={UsersRound}/><Metric label={t.createdCodes} value={adminNumber(coupons.length,l)} icon={TicketPercent}/></div>
    <section className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]">
      <form action={upsertCoupon} className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#001736] text-white"><TicketPercent className="h-5 w-5"/></span><div><h2 className="font-black text-[#001736]">{t.newCode}</h2><p className="text-[11px] text-[#8a8e96]">{t.newCodeSub}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input name="code" required placeholder={t.code} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm uppercase outline-none" dir="ltr"/><select name="type" className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"><option value="PERCENT">{t.percent}</option><option value="FIXED">{t.fixed}</option></select><input name="value" required type="number" min="0" placeholder={t.value} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"/><input name="minOrderAmount" type="number" min="0" placeholder={t.minOrder} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"/><input name="maxDiscount" type="number" min="0" placeholder={t.maxDiscount} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"/><input name="usageLimit" type="number" min="1" placeholder={t.usageLimit} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"/><input name="usageLimitPerUser" type="number" min="1" placeholder={t.perUser} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"/><label className="flex h-11 items-center gap-2 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"><input type="checkbox" name="isActive" defaultChecked/> {t.active}</label><label className="space-y-1"><span className="text-[10px] font-black text-[#747780]">{t.start}</span><input name="startsAt" type="datetime-local" className="h-11 w-full rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"/></label><label className="space-y-1"><span className="text-[10px] font-black text-[#747780]">{t.end}</span><input name="expiresAt" type="datetime-local" className="h-11 w-full rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"/></label></div><button className="mt-4 h-11 w-full rounded-xl bg-[#e80346] px-5 text-sm font-black text-white">{t.create}</button></form>
      <section className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black text-[#001736]">{t.recent}</h2><p className="mt-1 text-[11px] text-[#8a8e96]">{t.recentSub}</p></div><BadgePercent className="h-5 w-5 text-[#009dd8]"/></div><div className="mt-5 space-y-3">{coupons.map(cu=><article key={cu.id} className="rounded-2xl border border-[#edf0f2] bg-[#fafcff] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span dir="ltr" className="font-mono text-sm font-black text-[#002b5b]">{cu.code}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black ${cu.isActive?"bg-emerald-50 text-emerald-700":"bg-[#edf0f2] text-[#747780]"}`}>{cu.isActive?t.active:t.inactive}</span></div><p className="mt-2 text-xl font-black text-[#001736]">{cu.type==="PERCENT"?`${adminNumber(cu.value,l)}%`:`${adminNumber(cu.value,l)} ${adminCurrency[l]}`}</p></div><div className="text-end text-xs text-[#747780]"><p>{t.usage}: <b>{adminNumber(cu.usageCount,l)}{cu.usageLimit?` / ${adminNumber(cu.usageLimit,l)}`:""}</b></p>{cu.expiresAt?<p className="mt-1 flex items-center gap-1"><CalendarClock className="h-3.5 w-3.5"/>{adminDate(cu.expiresAt,l)}</p>:null}</div></div><div className="mt-3 grid gap-2 sm:grid-cols-2 text-xs"><div className="rounded-xl bg-white px-3 py-2 text-[#5f6570]">{t.minOrder}: <b>{cu.minOrderAmount?`${adminNumber(cu.minOrderAmount,l)} ${adminCurrency[l]}`:"—"}</b></div><div className="rounded-xl bg-white px-3 py-2 text-[#5f6570]">{t.maxDiscount}: <b>{cu.maxDiscount?`${adminNumber(cu.maxDiscount,l)} ${adminCurrency[l]}`:"—"}</b></div></div></article>)}{coupons.length===0?<div className="rounded-2xl border border-dashed border-[#cfd5dc] p-10 text-center text-sm text-[#8a8e96]">{t.empty}</div>:null}</div></section>
    </section>
  </div>;
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof BadgePercent}){return <article className="rounded-[1.5rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf4ff] text-[#002b5b]"><Icon className="h-5 w-5"/></span><p className="mt-4 text-xs font-black text-[#747780]">{label}</p><p className="mt-1 text-2xl font-black text-[#001736]">{value}</p></article>}
