import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Headphones, Send } from "lucide-react";
import { customerRpc, requireCustomerSession } from "@/lib/customer-auth";
import { replyTicketAction } from "./actions";

type Message={id:string;senderType:string;senderName:string;body:string;attachmentUrl:string;createdAt:string};
type Ticket={id:string;ticketNo:string;subject:string;category:string;status:string;priority:string;deviceInfo?:string|null;createdAt:string;updatedAt:string;messages:Message[]};

export default async function CustomerTicketPage({params,searchParams}:{params:Promise<{locale:string;id:string}>;searchParams:Promise<{sent?:string}>}){
  const {locale,id}=await params; const q=await searchParams; await requireCustomerSession(locale); const ticket=await customerRpc<Ticket|null>("customer_ticket_detail",{p_id:id}); if(!ticket) notFound(); const action=replyTicketAction.bind(null,locale,id);
  return <main className="py-10 sm:py-14"><div className="mx-auto max-w-4xl px-4"><Link href={`/${locale}/account`} className="inline-flex items-center gap-2 text-sm font-bold text-primary"><ArrowLeft className="h-4 w-4"/>بازگشت به حساب</Link><section className="mt-5 overflow-hidden rounded-[2rem] border border-border bg-card shadow-sm"><div className="bg-[#001736] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2 text-[#33c8ff]"><Headphones className="h-5 w-5"/><span className="text-xs font-black" dir="ltr">{ticket.ticketNo}</span></div><h1 className="mt-3 text-2xl font-black">{ticket.subject}</h1><p className="mt-2 text-xs text-white/60">{ticket.category} · {new Date(ticket.createdAt).toLocaleString("fa-IR")}</p></div><div className="rounded-xl bg-white/10 px-4 py-3 text-xs font-black">{ticket.status} · {ticket.priority}</div></div>{ticket.deviceInfo?<p className="mt-5 rounded-xl border border-white/10 bg-white/5 p-3 text-xs leading-6 text-white/70">{ticket.deviceInfo}</p>:null}</div>
      <div className="p-5 sm:p-7"><div className="space-y-4">{ticket.messages.map(m=>{const mine=m.senderType==="CUSTOMER";return <div key={m.id} className={`flex ${mine?"justify-start":"justify-end"}`}><div className={`max-w-[88%] rounded-2xl p-4 ${mine?"bg-primary/10 text-foreground":"bg-[#001736] text-white"}`}><div className={`text-[10px] font-black ${mine?"text-primary":"text-[#33c8ff]"}`}>{m.senderName||m.senderType}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{m.body}</p><div className={`mt-2 text-[10px] ${mine?"text-muted":"text-white/50"}`}>{new Date(m.createdAt).toLocaleString("fa-IR")}</div></div></div>})}{ticket.messages.length===0?<div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted">هنوز پیامی ثبت نشده است.</div>:null}</div>{q.sent?<div className="mt-5 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-700">پاسخ شما ثبت شد.</div>:null}<form action={action} className="mt-6 rounded-2xl border border-border bg-background p-4"><label className="block"><span className="mb-2 block text-xs font-bold text-muted">پاسخ شما</span><textarea name="body" required minLength={2} maxLength={4000} rows={5} className="w-full resize-y rounded-xl border border-border bg-white p-3 text-sm leading-7 outline-none focus:border-primary"/></label><div className="mt-3 flex justify-end"><button className="flex min-h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-black text-white"><Send className="h-4 w-4"/>ارسال پاسخ</button></div></form></div></section></div></main>;
}
