import { Search, ScrollText } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminDateTime, adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { requireAdminRole } from "@/lib/admin-auth";

type AuditRow={id:string;adminId?:string|null;actorName:string;actorEmail:string;actorRole:string;action:string;entity:string;entityId?:string|null;details:Record<string,unknown>;createdAt:string};
const C:Record<AdminLocale,Record<string,string>>={
  fa:{title:"گزارش فعالیت مدیران",sub:"ردیابی تغییرات حساس مدیریتی و عملیات امنیتی",search:"جستجو با مدیر، ایمیل، عملیات یا شناسه...",find:"جستجو",all:"همه عملیات",created:"ایجاد مدیر",updated:"ویرایش مدیر",revoked:"لغو نشست‌ها",actor:"مدیر",action:"عملیات",entity:"بخش",details:"جزئیات",date:"زمان",empty:"رکوردی پیدا نشد."},
  ar:{title:"سجل نشاط الإدارة",sub:"تتبع التغييرات الإدارية الحساسة والعمليات الأمنية",search:"ابحث بالمدير أو البريد أو العملية أو المعرّف...",find:"بحث",all:"كل العمليات",created:"إنشاء مدير",updated:"تعديل مدير",revoked:"إلغاء الجلسات",actor:"المدير",action:"العملية",entity:"الكيان",details:"التفاصيل",date:"الوقت",empty:"لا توجد سجلات."},
  en:{title:"Admin audit log",sub:"Trace sensitive administrative changes and security operations",search:"Search administrator, email, action or entity ID...",find:"Search",all:"All actions",created:"Admin created",updated:"Admin updated",revoked:"Sessions revoked",actor:"Administrator",action:"Action",entity:"Entity",details:"Details",date:"Time",empty:"No audit records found."},
  tr:{title:"Yönetici işlem kaydı",sub:"Hassas yönetim değişikliklerini ve güvenlik işlemlerini izleyin",search:"Yönetici, e-posta, işlem veya kimlik ara...",find:"Ara",all:"Tüm işlemler",created:"Yönetici oluşturuldu",updated:"Yönetici güncellendi",revoked:"Oturumlar sonlandırıldı",actor:"Yönetici",action:"İşlem",entity:"Varlık",details:"Detaylar",date:"Zaman",empty:"Kayıt bulunamadı."}
};
const actionLabels=(t:Record<string,string>)=>({ADMIN_CREATED:t.created,ADMIN_UPDATED:t.updated,ADMIN_SESSIONS_REVOKED:t.revoked});
export default async function AdminAuditPage({searchParams}:{searchParams:Promise<{q?:string;action?:string}>}){
  await requireAdminRole(["SUPER_ADMIN"]);
  const [{q="",action=""},l]=await Promise.all([searchParams,currentAdminLocale()]);const t=C[l];const query=q.trim().slice(0,100);const filter=action.trim().slice(0,80);
  const rows=await adminRpc<AuditRow[]>("admin_audit_logs",{p_search:query,p_action:filter});const labels=actionLabels(t);
  return <div className="mx-auto max-w-6xl space-y-6"><div><div className="flex items-center gap-2 text-[#009dd8]"><ScrollText className="h-5 w-5"/><span className="text-xs font-black uppercase">Audit</span></div><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.sub}</p></div><form action="/admin/audit" className="grid gap-2 sm:grid-cols-[1fr_220px_auto]"><label className="relative"><Search className="pointer-events-none absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9a9da5]"/><input name="q" defaultValue={query} placeholder={t.search} className="h-11 w-full rounded-xl border bg-white ps-10 pe-3"/></label><select name="action" defaultValue={filter} className="h-11 rounded-xl border bg-white px-3"><option value="">{t.all}</option><option value="ADMIN_CREATED">{t.created}</option><option value="ADMIN_UPDATED">{t.updated}</option><option value="ADMIN_SESSIONS_REVOKED">{t.revoked}</option></select><button className="rounded-xl bg-[#001736] px-5 text-xs font-black text-white">{t.find}</button></form><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4 text-xs font-black text-[#747780]">{adminNumber(rows.length,l)} {t.all}</div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="bg-[#f7fafd] text-xs text-[#747780]"><tr><th className="px-4 py-3 text-start">{t.date}</th><th className="px-4 py-3 text-start">{t.actor}</th><th className="px-4 py-3 text-start">{t.action}</th><th className="px-4 py-3 text-start">{t.entity}</th><th className="px-4 py-3 text-start">{t.details}</th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-4 py-3 whitespace-nowrap text-xs text-[#747780]">{adminDateTime(r.createdAt,l)}</td><td className="px-4 py-3"><b className="block text-[#001736]">{r.actorName}</b><span dir="ltr" className="text-xs text-[#747780]">{r.actorEmail}</span></td><td className="px-4 py-3 font-black text-[#002b5b]">{labels[r.action as keyof typeof labels]||r.action}</td><td className="px-4 py-3"><span className="font-bold">{r.entity}</span>{r.entityId?<div dir="ltr" className="mt-1 max-w-[220px] truncate font-mono text-[10px] text-[#8a8e96]">{r.entityId}</div>:null}</td><td className="px-4 py-3"><pre dir="ltr" className="max-w-[420px] whitespace-pre-wrap break-words rounded-lg bg-[#f7fafd] p-2 text-[10px] text-[#5f6570]">{JSON.stringify(r.details)}</pre></td></tr>)}{rows.length===0?<tr><td colSpan={5} className="p-10 text-center text-[#747780]">{t.empty}</td></tr>:null}</tbody></table></div></section></div>;
}
