import { getLocale, getTranslations } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { Activity, ArrowLeft, ArrowRight, BedDouble, HeartPulse, Home, Moon, PhoneCall, Stethoscope, Wind, Wrench } from "lucide-react";
import { Container } from "@/components/ui/container";
import { ProductCard } from "@/components/site/product-card";
import { HomeCollections } from "@/components/site/home-collections";
import { getCategories, getFeaturedProducts, getServices } from "@/lib/queries";
import { localizedName } from "@/lib/i18n-content";

function l(locale:string,fa:string,en:string,tr:string,ar:string){if(locale==="en")return en;if(locale==="tr")return tr;if(locale==="ar")return ar;return fa;}
const equipmentIcons=[Activity,HeartPulse,Wind,Home,BedDouble,Stethoscope];
const serviceIcons=[Moon,Wind,Wrench,PhoneCall];

export default async function HomePage(){
 const locale=await getLocale(); const t=await getTranslations("home"); const Arrow=locale==="fa"||locale==="ar"?ArrowLeft:ArrowRight;
 const [categories,featured,services]=await Promise.all([getCategories(),getFeaturedProducts(),getServices()]);
 return <main className="stitch-page-shell flex-1 pb-16"><Container className="pt-5 sm:pt-8">
  <section className="stitch-dark-feature relative mb-14 overflow-hidden p-7 sm:mb-20 sm:p-12 lg:p-16" aria-labelledby="home-hero-title">
   <div className="pointer-events-none absolute -end-24 -top-28 h-72 w-72 rounded-full bg-[#009dd8]/20 blur-3xl"/><div className="pointer-events-none absolute -bottom-32 -start-16 h-72 w-72 rounded-full bg-[#ba0036]/15 blur-3xl"/>
   <div className="relative z-10 max-w-3xl"><span className="inline-flex rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-bold text-[#82cfff]">VITALIS • HYPER DOCTOR</span><h1 id="home-hero-title" className="mt-5 text-3xl font-black leading-[1.35] text-white sm:text-5xl">{l(locale,"تجهیزات پزشکی و خدمات تخصصی سلامت","Medical equipment & specialist health services","Medikal ekipman ve uzman sağlık hizmetleri","المعدات الطبية والخدمات الصحية المتخصصة")}</h1><p className="mt-5 max-w-2xl text-sm leading-8 text-white/75 sm:text-base">{l(locale,"مسیر یکپارچه برای انتخاب تجهیزات، خدمات تنفسی و خواب، رزرو و پشتیبانی تخصصی.","One connected path for equipment selection, respiratory and sleep services, booking and specialist support.","Ekipman seçimi, solunum ve uyku hizmetleri, rezervasyon ve uzman destek için bütünleşik bir deneyim.","مسار متكامل لاختيار المعدات وخدمات التنفس والنوم والحجز والدعم المتخصص.")}</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/shop" className="stitch-button stitch-button-primary">{t("heroCtaShop")}<Arrow className="h-4 w-4" aria-hidden="true"/></Link><Link href="/services" className="stitch-button stitch-button-ghost">{t("heroCtaServices")}</Link></div></div>
  </section>
  <section className="mb-16 sm:mb-20"><div className="flex items-end justify-between gap-4"><h2 className="stitch-section-title text-start">{l(locale,"تجهیزات پزشکی","Medical Equipment","Medikal Ekipman","المعدات الطبية")}</h2><Link href="/shop" className="vitalis-focus rounded-lg text-sm font-bold text-[#002b5b]">{t("heroCtaShop")}</Link></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{categories.map((category,index)=>{const Icon=equipmentIcons[index%equipmentIcons.length];return <Link key={category.id} href={`/shop/${category.slug}`} className="stitch-soft-card vitalis-focus group flex min-h-32 flex-col items-center justify-center gap-3 p-4 text-center"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#d6e3ff] text-[#001736] transition group-hover:bg-[#001736] group-hover:text-white"><Icon className="h-5 w-5" aria-hidden="true"/></span><span className="text-xs font-bold leading-6 text-[#181c1e] sm:text-sm">{localizedName(locale,category)}</span></Link>})}</div></section>
  <HomeCollections locale={locale}/>
  <section className="mb-16 sm:mb-20" id="services"><div className="flex items-end justify-between gap-4"><h2 className="stitch-section-title text-start">{l(locale,"خدمات تخصصی","Specialist Services","Uzman Hizmetler","الخدمات المتخصصة")}</h2><Link href="/services" className="vitalis-focus rounded-lg text-sm font-bold text-[#002b5b]">{l(locale,"مشاهده همه","View all","Tümünü gör","عرض الكل")}</Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.slice(0,4).map((service,index)=>{const Icon=serviceIcons[index%serviceIcons.length];return <Link key={service.id} href={`/services/${service.slug}`} className="stitch-soft-card vitalis-focus overflow-hidden"><div className="flex h-32 items-center justify-center bg-gradient-to-br from-[#d6e3ff] via-[#f1f4f7] to-[#c6e7ff]"><Icon className="h-11 w-11 text-[#002b5b]" aria-hidden="true"/></div><div className="p-5"><h3 className="font-black text-[#181c1e]">{localizedName(locale,service)}</h3><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#002b5b]">{l(locale,"جزئیات بیشتر","Learn more","Detaylar","المزيد")}<Arrow className="h-3.5 w-3.5" aria-hidden="true"/></span></div></Link>})}</div></section>
  {featured.length>0?<section className="mb-16 sm:mb-20"><div className="flex items-end justify-between gap-4"><h2 className="stitch-section-title text-start">{t("featuredTitle")}</h2><Link href="/shop" className="vitalis-focus rounded-lg text-sm font-bold text-[#002b5b]">{t("heroCtaShop")}</Link></div><div className="mt-7 grid grid-cols-2 gap-4 lg:grid-cols-4">{featured.map(product=><ProductCard key={product.id} product={product}/>)}</div></section>:null}
  <section className="stitch-dark-feature mb-16 grid overflow-hidden p-7 sm:mb-20 sm:p-10 lg:grid-cols-[1fr_auto] lg:items-center lg:gap-12 lg:p-14"><div><span className="inline-flex rounded-full bg-[#e80346] px-3 py-1 text-xs font-bold text-white">{l(locale,"درباره هایپر دکتر","About Hyper Doctor","Hyper Doctor hakkında","عن هايبر دكتور")}</span><h2 className="mt-5 text-2xl font-black text-white sm:text-3xl">{l(locale,"تکنولوژی پزشکی و مراقبت حرفه‌ای","Medical technology and professional care","Medikal teknoloji ve profesyonel bakım","التقنية الطبية والرعاية الاحترافية")}</h2><p className="mt-5 max-w-2xl text-sm leading-8 text-white/75">{l(locale,"هایپر دکتر تجهیزات پزشکی، مراقبت تنفسی و خدمات تخصصی را از انتخاب تا پشتیبانی در یک تجربه یکپارچه ارائه می‌کند.","Hyper Doctor connects medical equipment, respiratory care and specialist services from selection through support.","Hyper Doctor medikal ekipman, solunum bakımı ve uzman hizmetleri seçimden desteğe tek deneyimde birleştirir.","يجمع هايبر دكتور المعدات الطبية والرعاية التنفسية والخدمات المتخصصة من الاختيار حتى الدعم.")}</p></div><Link href="/about" className="stitch-button stitch-button-ghost mt-6 shrink-0 lg:mt-0">{l(locale,"آشنایی بیشتر","Learn more","Daha fazla bilgi","اعرف المزيد")}<Arrow className="h-4 w-4" aria-hidden="true"/></Link></section>
  <section className="stitch-glass-card mb-4 rounded-3xl p-7 text-center sm:p-10"><span className="text-xs font-bold text-[#ba0036]">VITALIS • HYPER DOCTOR</span><h2 className="mt-3 text-2xl font-black text-[#001736]">{l(locale,"دانش و راهنمای تخصصی","Knowledge & specialist guidance","Bilgi ve uzman rehberliği","المعرفة والإرشاد المتخصص")}</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-[#747780]">{l(locale,"مطالبی که از بخش مدیریت منتشر شوند، در کتابخانه مقالات در دسترس قرار می‌گیرند.","Content published through Admin becomes available in the article library.","Yönetim panelinden yayımlanan içerikler makale kütüphanesinde yer alır.","يظهر المحتوى المنشور من لوحة الإدارة في مكتبة المقالات.")}</p><Link href="/articles" className="stitch-button stitch-button-primary mt-6">{l(locale,"مشاهده مقالات","View articles","Makaleleri gör","عرض المقالات")}<Arrow className="h-4 w-4" aria-hidden="true"/></Link></section>
 </Container></main>;
}
