import { NextResponse } from "next/server";
import { adminRpc } from "@/lib/admin-data";

export const runtime="nodejs";

type Row={line:number;sku:string;price:string;compareAtPrice:string;onHand:string};
function parseCsv(input:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<input.length;i++){const ch=input[i],next=input[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(ch===","&&!quoted){row.push(cell.trim());cell="";continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell.trim());cell="";if(row.some(Boolean))rows.push(row);row=[];continue}cell+=ch}row.push(cell.trim());if(row.some(Boolean))rows.push(row);const[headers,...body]=rows;if(!headers)return[];const normalized=headers.map(x=>x.replace(/^\uFEFF/,"").trim().toLowerCase());const idx=(key:string)=>normalized.indexOf(key.toLowerCase());return body.map((values,i)=>({line:i+2,sku:(values[idx("sku")]??"").trim(),price:(values[idx("price")]??"").replace(/[,_\s]/g,""),compareAtPrice:(values[idx("compareAtPrice")]??"").replace(/[,_\s]/g,""),onHand:(values[idx("onHand")]??"").replace(/[,_\s]/g,"")})).filter(r=>r.sku||r.price||r.compareAtPrice||r.onHand)}
function excelValue(value:unknown){if(value==null)return"";if(value instanceof Date)return value.toISOString().slice(0,10);if(typeof value==="object"){const v=value as {text?:string;result?:unknown;richText?:Array<{text:string}>};if(v.text!=null)return String(v.text);if(v.result!=null)return String(v.result);if(Array.isArray(v.richText))return v.richText.map(x=>x.text).join("")}return String(value)}
async function parseXlsx(file:File):Promise<Row[]>{const ExcelJS=(await import("exceljs")).default;const workbook=new ExcelJS.Workbook();const data=Buffer.from(await file.arrayBuffer()) as unknown as Parameters<typeof workbook.xlsx.load>[0];await workbook.xlsx.load(data);if(workbook.worksheets.length>10)throw new Error("Workbook sheet limit is 10");const sheet=workbook.worksheets[0];if(!sheet)return[];if(sheet.rowCount>2001)throw new Error("Row limit is 2000 plus header");const headers=(sheet.getRow(1).values as unknown[]).slice(1).map(v=>excelValue(v).trim().toLowerCase()),idx=(key:string)=>headers.indexOf(key.toLowerCase());const out:Row[]=[];for(let i=2;i<=sheet.rowCount;i++){const values=(sheet.getRow(i).values as unknown[]).slice(1),get=(key:string)=>idx(key)>=0?excelValue(values[idx(key)]).trim():"";const r={line:i,sku:get("sku"),price:get("price").replace(/[,_\s]/g,""),compareAtPrice:get("compareAtPrice").replace(/[,_\s]/g,""),onHand:get("onHand").replace(/[,_\s]/g,"")};if(r.sku||r.price||r.compareAtPrice||r.onHand)out.push(r)}return out}
async function readRows(file:File){const name=file.name.toLowerCase(),type=file.type.toLowerCase();if(name.endsWith(".csv")||type.includes("csv"))return parseCsv((await file.text()).replace(/^\uFEFF/,""));if(name.endsWith(".xlsx"))return parseXlsx(file);throw new Error("Only CSV and XLSX files are supported")}

export async function POST(request:Request){
 const form=await request.formData().catch(()=>null);if(!form)return NextResponse.json({error:"Invalid multipart payload"},{status:400});const file=form.get("file");if(!(file instanceof File))return NextResponse.json({error:"CSV or XLSX file is required"},{status:400});if(file.size>5*1024*1024)return NextResponse.json({error:"Import file is too large (5MB max)"},{status:400});
 const mode=String(form.get("mode")||"preview")==="apply"?"apply":"preview",branchId=String(form.get("branchId")||"").trim(),warehouseId=String(form.get("warehouseId")||"").trim(),sourceType=String(form.get("sourceType")||"CURRENT_COMMERCE_SNAPSHOT").trim().toUpperCase(),sourceTitle=String(form.get("sourceTitle")||"").trim(),sourceDate=String(form.get("sourceDate")||"").trim(),sourceReference=String(form.get("sourceReference")||"").trim();if(!branchId||!warehouseId)return NextResponse.json({error:"Branch and warehouse are required"},{status:400});if(!sourceTitle)return NextResponse.json({error:"Source title is required"},{status:400});if(!["CURRENT_COMMERCE_SNAPSHOT","CURRENT_PRICE_SNAPSHOT","CURRENT_INVENTORY_SNAPSHOT","MANUAL_ADMIN"].includes(sourceType))return NextResponse.json({error:"Invalid source type"},{status:400});
 let rows:Row[];try{rows=await readRows(file)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to read file"},{status:400})}if(!rows.length)return NextResponse.json({error:"No commerce rows found"},{status:400});if(rows.length>2000)return NextResponse.json({error:"Row limit is 2000"},{status:400});
 let preflight:Record<string,unknown>;try{preflight=await adminRpc("admin_commerce_import_preflight",{p_branch_id:branchId,p_warehouse_id:warehouseId,p_rows:rows})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Preflight failed"},{status:400})}
 if(mode==="preview")return NextResponse.json({mode,preflight});if(preflight.canApply!==true)return NextResponse.json({error:"Preflight contains blocking errors",mode,preflight},{status:409});
 try{const result=await adminRpc("admin_commerce_import_apply",{p_branch_id:branchId,p_warehouse_id:warehouseId,p_source:{sourceType,title:sourceTitle,sourceDate:sourceDate||null,reference:sourceReference,notes:"Current Hyper Doctor commerce data imported only after preview and explicit confirmation."},p_rows:rows});return NextResponse.json({mode,result})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Commerce import failed",mode,preflight},{status:400})}
}
