import { getLocale } from "next-intl/server";
import { Clock3, MapPin, PackageCheck, RadioTower, ShieldCheck, Truck } from "lucide-react";
import { OrderTrackingPanel } from "@/components/site/order-tracking-panel";

const pick=(locale:string,fa:string,en:string,tr:string,ar:string)=>locale==="en"?en:locale==="tr"?tr:locale==="ar"?ar:fa;
export default async function OrderTrackingPage(){const locale=await getLocale();return <main className="bg-[#f5f8fb] py-8 sm:py-12"><div className="mx-auto max-w-6xl px-4 sm:px-6">
 <section className="overflow-hidden rounded-[2rem] border border-[#dfe4ea] bg-white shadow-[0_20px_60px_rgba(0,23,54,.07)]"><div className="bg-[#001736] px-6 py-8 text-white sm:px-9"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><div className="flex items-center gap-2 text-[#82cfff]"><Truck className="h-5 w-5"/><span className="text-xs font-black uppercase tracking-[.16em]">Hyper Doctor Logistics</span></div><h1 className="mt-4 text-3xl font-black sm:text-4xl">{pick(locale,"رهگیری سفارش هایپر دکتر","Hyper Doctor order tracking","Hyper Doctor sipariş takibi","تتبع طلب Hyper Doctor")}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/68">{pick(locale,"شماره سفارش و موبایل ثبت‌شده را وارد کنید تا وضعیت واقعی پردازش، خروج از انبار و اطلاعات رهگیری مرسوله نمایش داده شود.","Enter your order number and registered mobile to view real processing, dispatch and tracking information.","Gerçek işlem, sevk ve takip bilgilerini görmek için sipariş numarası ve kayıtlı telefonu girin.","أدخل رقم الطلب والهاتف المسجل لعرض معلومات المعالجة والشحن والتتبع الفعلية.")}</p></div><span className="inline-flex items-center gap-2 self-start rounded-xl border border-white/12 bg-white/8 px-4 py-3 text-xs font-bold text-white/75"><RadioTower className="h-4 w-4 text-[#82cfff]"/>{pick(locale,"اطلاعات از سفارش واقعی","Live order data","Gerçek sipariş verisi","بيانات الطلب الفعلية")}</span></div></div>
  <div className="grid gap-3 border-b border-[#e0e3e6] bg-[#f9fbfd] p-5 sm:grid-cols-4 sm:p-6">{[[PackageCheck,pick(locale,"ثبت و پردازش","Processing","İşleniyor","المعالجة")],[Truck,pick(locale,"خروج از انبار","Dispatched","Sevk edildi","خرج من المستودع")],[MapPin,pick(locale,"رهگیری مرسوله","Shipment tracking","Gönderi takibi","تتبع الشحنة")],[Clock3,pick(locale,"تحویل","Delivery","Teslimat","التسليم")]].map(([Icon,label])=>{const I=Icon as typeof Truck;return <div key={String(label)} className="flex items-center gap-3 rounded-xl border border-[#dfe4ea] bg-white px-4 py-3 text-xs font-black text-[#43474f]"><I className="h-4 w-4 shrink-0 text-[#002b5b]"/>{label as string}</div>})}</div>
  <div className="p-5 sm:p-8"><OrderTrackingPanel/></div>
 </section><div className="mt-5 flex items-center justify-center gap-2 text-xs text-[#747780]"><ShieldCheck className="h-4 w-4 text-[#009dd8]"/>{pick(locale,"اطلاعات سفارش فقط پس از تطبیق شماره سفارش و موبایل نمایش داده می‌شود.","Order details are shown only after matching the order number and mobile.","Sipariş bilgileri yalnızca numara ve telefon eşleştiğinde gösterilir.","تظهر تفاصيل الطلب فقط بعد مطابقة رقم الطلب والهاتف.")}</div>
 </div></main>}
