import Link from "next/link";
import Image from "next/image";
import { Archive, ImageOff, PackageSearch, Pencil, Plus, Search } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { formatPrice } from "@/lib/utils";
import { deleteProduct } from "./actions";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminNumber, type AdminLocale } from "@/lib/admin-i18n";

type P={id:string;slug:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;sku:string;brand:string;price:number;stock:number;lowStockThreshold:number;isPublished:boolean;isFeatured:boolean;isNewArrival:boolean;categoryId:string;categoryNameFa:string;categoryNameTr:string;categoryNameEn:string;categoryNameAr:string;image?:string|null};
type Category={id:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string};
type B={products:P[];categories:Category[]};
const C:Record<AdminLocale,Record<string,string>>={
  fa:{eyebrow:"مدیریت کاتالوگ",title:"مدیریت محصولات",desc:"کاتالوگ، قیمت، موجودی، تصاویر و انتشار چهارزبانه",new:"محصول جدید",placeholder:"جستجوی نام در ۴ زبان، SKU، برند یا دسته...",search:"جستجو",product:"محصول",products:"محصول",category:"دسته‌بندی",catbrand:"دسته / برند",price:"قیمت",stock:"موجودی",status:"وضعیت",actions:"عملیات",published:"منتشرشده",draft:"پیش‌نویس",featured:"ویژه",newtag:"جدید",edit:"ویرایش",archive:"خروج از انتشار",empty:"هنوز محصولی ثبت نشده است.",emptySub:"از دکمه «محصول جدید» اولین کالای واقعی را اضافه کنید.",noMatch:"محصولی مطابق جست‌وجو پیدا نشد."},
  ar:{eyebrow:"إدارة الكتالوج",title:"إدارة المنتجات",desc:"الكتالوج والأسعار والمخزون والصور والنشر بأربع لغات",new:"منتج جديد",placeholder:"ابحث بالاسم بأربع لغات أو SKU أو العلامة أو التصنيف...",search:"بحث",product:"منتج",products:"منتجات",category:"تصنيف",catbrand:"التصنيف / العلامة",price:"السعر",stock:"المخزون",status:"الحالة",actions:"الإجراءات",published:"منشور",draft:"مسودة",featured:"مميز",newtag:"جديد",edit:"تعديل",archive:"إلغاء النشر",empty:"لا توجد منتجات بعد.",emptySub:"أضف أول منتج حقيقي من زر «منتج جديد».",noMatch:"لم يتم العثور على منتج مطابق للبحث."},
  en:{eyebrow:"Catalog management",title:"Product management",desc:"Catalog, pricing, inventory, images and four-language publishing",new:"New product",placeholder:"Search four-language names, SKU, brand or category...",search:"Search",product:"Product",products:"products",category:"categories",catbrand:"Category / brand",price:"Price",stock:"Stock",status:"Status",actions:"Actions",published:"Published",draft:"Draft",featured:"Featured",newtag:"New",edit:"Edit",archive:"Unpublish",empty:"No products have been added yet.",emptySub:"Use “New product” to add the first real item.",noMatch:"No product matched your search."},
  tr:{eyebrow:"Katalog yönetimi",title:"Ürün yönetimi",desc:"Katalog, fiyat, stok, görseller ve dört dilde yayınlama",new:"Yeni ürün",placeholder:"Dört dilde ad, SKU, marka veya kategori ara...",search:"Ara",product:"Ürün",products:"ürün",category:"kategori",catbrand:"Kategori / marka",price:"Fiyat",stock:"Stok",status:"Durum",actions:"İşlemler",published:"Yayında",draft:"Taslak",featured:"Öne çıkan",newtag:"Yeni",edit:"Düzenle",archive:"Yayından kaldır",empty:"Henüz ürün eklenmedi.",emptySub:"İlk gerçek ürünü “Yeni ürün” düğmesiyle ekleyin.",noMatch:"Aramanızla eşleşen ürün bulunamadı."}
};
function localizedName(x:{nameFa:string;nameTr:string;nameEn:string;nameAr:string},l:AdminLocale){const primary=l==="fa"?x.nameFa:l==="tr"?x.nameTr:l==="ar"?x.nameAr:x.nameEn;return primary||x.nameFa||x.nameEn||x.nameTr||x.nameAr||"—"}
export default async function Page({searchParams}:{searchParams:Promise<{q?:string}>}){
  const {q=""}=await searchParams;
  const [b,l]=await Promise.all([adminRpc<B>("admin_products_bundle",{p_search:q}),currentAdminLocale()]);
  const t=C[l];
  return <div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase text-[#009dd8]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.desc}</p></div><Link href="/admin/products/new" className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-[#ba0036] px-5 text-sm font-black text-white"><Plus className="h-4 w-4"/>{t.new}</Link></div><form className="mt-7 flex gap-3 rounded-3xl border bg-white p-4"><label className="relative flex-1"><Search className="absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2"/><input name="q" defaultValue={q} placeholder={t.placeholder} className="h-12 w-full rounded-2xl border ps-11 pe-4"/></label><button className="rounded-2xl bg-[#002b5b] px-5 text-xs font-black text-white">{t.search}</button></form><section className="mt-6 overflow-hidden rounded-3xl border bg-white"><div className="flex justify-between border-b px-5 py-4"><b>{adminNumber(b.products.length,l)} {t.products}</b><span>{adminNumber(b.categories.length,l)} {t.category}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr>{[t.product,t.catbrand,t.price,t.stock,t.status,t.actions].map(x=><th key={x} className="px-5 py-3 text-start">{x}</th>)}</tr></thead><tbody>{b.products.map(p=><tr key={p.id} className="border-t"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="relative h-12 w-12">{p.image?<Image src={p.image} alt={localizedName(p,l)} fill className="object-contain" sizes="48px"/>:<ImageOff/>}</div><div><b>{localizedName(p,l)}</b><p dir="ltr">{p.sku}</p></div></div></td><td className="px-5 py-4">{localizedName({nameFa:p.categoryNameFa,nameTr:p.categoryNameTr,nameEn:p.categoryNameEn,nameAr:p.categoryNameAr},l)}<br/>{p.brand||"—"}</td><td className="px-5 py-4">{formatPrice(p.price,l)}</td><td className="px-5 py-4">{adminNumber(p.stock,l)}</td><td className="px-5 py-4">{p.isPublished?t.published:t.draft}{p.isFeatured?` · ${t.featured}`:""}{p.isNewArrival?` · ${t.newtag}`:""}</td><td className="px-5 py-4"><div className="flex gap-2"><Link href={`/admin/products/${p.id}`} title={t.edit}><Pencil/></Link><form action={deleteProduct.bind(null,p.id)}><button title={t.archive}><Archive/></button></form></div></td></tr>)}{!b.products.length?<tr><td colSpan={6} className="px-6 py-14 text-center"><PackageSearch className="mx-auto"/><p className="mt-4 font-black">{q?t.noMatch:t.empty}</p>{!q?<p className="mt-2 text-xs">{t.emptySub}</p>:null}</td></tr>:null}</tbody></table></div></section></div>
}
