create table if not exists public."Branch" (
  id text primary key default gen_random_uuid()::text,
  code text not null unique,
  "nameFa" text not null default '',"nameTr" text not null default '',"nameEn" text not null default '',"nameAr" text not null default '',
  "countryCode" text not null default 'IR',currency text not null default 'IRT',timezone text not null default 'Asia/Tehran',
  "isDefault" boolean not null default false,"isPublished" boolean not null default true,
  "createdAt" timestamptz not null default now(),"updatedAt" timestamptz not null default now(),
  check (char_length(code) between 2 and 32),check (char_length("countryCode")=2),check (char_length(currency) between 2 and 12)
);
create unique index if not exists "Branch_single_default_idx" on public."Branch" (("isDefault")) where "isDefault"=true;
create table if not exists public."Warehouse" (
 id text primary key default gen_random_uuid()::text,"branchId" text not null references public."Branch"(id) on delete restrict,code text not null,
 "nameFa" text not null default '',"nameTr" text not null default '',"nameEn" text not null default '',"nameAr" text not null default '',"isActive" boolean not null default true,
 "createdAt" timestamptz not null default now(),"updatedAt" timestamptz not null default now(),unique("branchId",code)
);
create index if not exists "Warehouse_branchId_idx" on public."Warehouse"("branchId");
create table if not exists public."WarehouseInventory" (
 "warehouseId" text not null references public."Warehouse"(id) on delete cascade,"productId" text not null references public."Product"(id) on delete cascade,
 "onHand" integer not null default 0 check ("onHand">=0),reserved integer not null default 0 check (reserved>=0),"rentalUnits" integer not null default 0 check ("rentalUnits">=0),
 "updatedAt" timestamptz not null default now(),primary key("warehouseId","productId"),check (reserved <= "onHand"),check ("rentalUnits" <= "onHand")
);
create index if not exists "WarehouseInventory_productId_idx" on public."WarehouseInventory"("productId");
alter table public."Branch" enable row level security;alter table public."Warehouse" enable row level security;alter table public."WarehouseInventory" enable row level security;
revoke all on public."Branch",public."Warehouse",public."WarehouseInventory" from anon,authenticated;

create or replace function public.admin_locations_bundle(p_token text) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_admin public."AdminUser"%rowtype;v_result jsonb;begin v_admin:=public._admin_session_user(p_token);if v_admin.role not in ('SUPER_ADMIN'::"AdminRole",'EDITOR'::"AdminRole",'SALES'::"AdminRole") then raise exception 'forbidden';end if;select jsonb_build_object('branches',coalesce((select jsonb_agg(to_jsonb(b) order by b."isDefault" desc,b.code) from public."Branch" b),'[]'::jsonb),'warehouses',coalesce((select jsonb_agg(to_jsonb(w) order by w."branchId",w.code) from public."Warehouse" w),'[]'::jsonb)) into v_result;return v_result;end $$;
revoke all on function public.admin_locations_bundle(text) from public;grant execute on function public.admin_locations_bundle(text) to anon,authenticated;

create or replace function public.admin_upsert_branch(p_token text,p_id text default null,p_code text default null,p_name_fa text default '',p_name_tr text default '',p_name_en text default '',p_name_ar text default '',p_country_code text default 'IR',p_currency text default 'IRT',p_timezone text default 'Asia/Tehran',p_is_default boolean default false,p_is_published boolean default true) returns text language plpgsql security definer set search_path=public as $$
declare v_admin public."AdminUser"%rowtype;v_id text;begin v_admin:=public._admin_session_user(p_token);if v_admin.role <> 'SUPER_ADMIN'::"AdminRole" then raise exception 'forbidden';end if;if length(trim(coalesce(p_code,'')))<2 or length(trim(p_code))>32 then raise exception 'invalid branch code';end if;if length(trim(coalesce(p_name_en,'')))<2 and length(trim(coalesce(p_name_fa,'')))<2 then raise exception 'branch name required';end if;if p_is_default then update public."Branch" set "isDefault"=false,"updatedAt"=now() where "isDefault"=true and (p_id is null or id<>p_id);end if;if p_id is null or p_id='' then insert into public."Branch"(code,"nameFa","nameTr","nameEn","nameAr","countryCode",currency,timezone,"isDefault","isPublished") values(upper(trim(p_code)),trim(coalesce(p_name_fa,'')),trim(coalesce(p_name_tr,'')),trim(coalesce(p_name_en,'')),trim(coalesce(p_name_ar,'')),upper(trim(p_country_code)),upper(trim(p_currency)),trim(p_timezone),p_is_default,p_is_published) returning id into v_id;else update public."Branch" set code=upper(trim(p_code)),"nameFa"=trim(coalesce(p_name_fa,'')),"nameTr"=trim(coalesce(p_name_tr,'')),"nameEn"=trim(coalesce(p_name_en,'')),"nameAr"=trim(coalesce(p_name_ar,'')),"countryCode"=upper(trim(p_country_code)),currency=upper(trim(p_currency)),timezone=trim(p_timezone),"isDefault"=p_is_default,"isPublished"=p_is_published,"updatedAt"=now() where id=p_id returning id into v_id;if v_id is null then raise exception 'branch not found';end if;end if;return v_id;end $$;
revoke all on function public.admin_upsert_branch(text,text,text,text,text,text,text,text,text,text,boolean,boolean) from public;grant execute on function public.admin_upsert_branch(text,text,text,text,text,text,text,text,text,text,boolean,boolean) to anon,authenticated;

create or replace function public.admin_upsert_warehouse(p_token text,p_id text default null,p_branch_id text default null,p_code text default null,p_name_fa text default '',p_name_tr text default '',p_name_en text default '',p_name_ar text default '',p_is_active boolean default true) returns text language plpgsql security definer set search_path=public as $$
declare v_admin public."AdminUser"%rowtype;v_id text;begin v_admin:=public._admin_session_user(p_token);if v_admin.role <> 'SUPER_ADMIN'::"AdminRole" then raise exception 'forbidden';end if;if not exists(select 1 from public."Branch" where id=p_branch_id) then raise exception 'branch not found';end if;if length(trim(coalesce(p_code,'')))<1 or length(trim(p_code))>32 then raise exception 'invalid warehouse code';end if;if p_id is null or p_id='' then insert into public."Warehouse"("branchId",code,"nameFa","nameTr","nameEn","nameAr","isActive") values(p_branch_id,upper(trim(p_code)),trim(coalesce(p_name_fa,'')),trim(coalesce(p_name_tr,'')),trim(coalesce(p_name_en,'')),trim(coalesce(p_name_ar,'')),p_is_active) returning id into v_id;else update public."Warehouse" set "branchId"=p_branch_id,code=upper(trim(p_code)),"nameFa"=trim(coalesce(p_name_fa,'')),"nameTr"=trim(coalesce(p_name_tr,'')),"nameEn"=trim(coalesce(p_name_en,'')),"nameAr"=trim(coalesce(p_name_ar,'')),"isActive"=p_is_active,"updatedAt"=now() where id=p_id returning id into v_id;if v_id is null then raise exception 'warehouse not found';end if;end if;return v_id;end $$;
revoke all on function public.admin_upsert_warehouse(text,text,text,text,text,text,text,text,boolean) from public;grant execute on function public.admin_upsert_warehouse(text,text,text,text,text,text,text,text,boolean) to anon,authenticated;

create or replace function public.admin_warehouse_inventory(p_token text,p_warehouse_id text,p_search text default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_admin public."AdminUser"%rowtype;v_result jsonb;begin v_admin:=public._admin_session_user(p_token);if v_admin.role not in ('SUPER_ADMIN'::"AdminRole",'EDITOR'::"AdminRole",'SALES'::"AdminRole") then raise exception 'forbidden';end if;if not exists(select 1 from public."Warehouse" where id=p_warehouse_id) then raise exception 'warehouse not found';end if;select coalesce(jsonb_agg(to_jsonb(x) order by x."nameEn",x.sku),'[]'::jsonb) into v_result from (select p.id as "productId",p.sku,p."nameFa",p."nameTr",p."nameEn",p."nameAr",p.stock as "legacyStock",coalesce(i."onHand",0) as "onHand",coalesce(i.reserved,0) as reserved,coalesce(i."rentalUnits",0) as "rentalUnits",greatest(coalesce(i."onHand",0)-coalesce(i.reserved,0),0) as available from public."Product" p left join public."WarehouseInventory" i on i."productId"=p.id and i."warehouseId"=p_warehouse_id where (p_search is null or trim(p_search)='' or concat_ws(' ',p.sku,p."nameFa",p."nameTr",p."nameEn",p."nameAr") ilike '%'||trim(p_search)||'%') order by p."nameEn",p.sku limit 500)x;return v_result;end $$;
revoke all on function public.admin_warehouse_inventory(text,text,text) from public;grant execute on function public.admin_warehouse_inventory(text,text,text) to anon,authenticated;

create or replace function public.admin_set_warehouse_inventory(p_token text,p_warehouse_id text,p_product_id text,p_on_hand integer,p_reserved integer default 0,p_rental_units integer default 0) returns boolean language plpgsql security definer set search_path=public as $$
declare v_admin public."AdminUser"%rowtype;v_total integer;begin v_admin:=public._admin_session_user(p_token);if v_admin.role not in ('SUPER_ADMIN'::"AdminRole",'EDITOR'::"AdminRole",'SALES'::"AdminRole") then raise exception 'forbidden';end if;if p_on_hand<0 or p_reserved<0 or p_rental_units<0 or p_reserved>p_on_hand or p_rental_units>p_on_hand then raise exception 'invalid inventory values';end if;if not exists(select 1 from public."Warehouse" where id=p_warehouse_id and "isActive"=true) then raise exception 'active warehouse not found';end if;if not exists(select 1 from public."Product" where id=p_product_id) then raise exception 'product not found';end if;insert into public."WarehouseInventory"("warehouseId","productId","onHand",reserved,"rentalUnits","updatedAt") values(p_warehouse_id,p_product_id,p_on_hand,p_reserved,p_rental_units,now()) on conflict("warehouseId","productId") do update set "onHand"=excluded."onHand",reserved=excluded.reserved,"rentalUnits"=excluded."rentalUnits","updatedAt"=now();select coalesce(sum(greatest(i."onHand"-i.reserved,0)),0)::integer into v_total from public."WarehouseInventory" i join public."Warehouse" w on w.id=i."warehouseId" and w."isActive"=true where i."productId"=p_product_id;update public."Product" set stock=v_total,"updatedAt"=now() where id=p_product_id;return true;end $$;
revoke all on function public.admin_set_warehouse_inventory(text,text,text,integer,integer,integer) from public;grant execute on function public.admin_set_warehouse_inventory(text,text,text,integer,integer,integer) to anon,authenticated;
