-- Version 285 — Catalog Enrichment & Launch Readiness
-- Closes 23 B.Well four-language description gaps and 117 verified-media gaps
-- using only source-backed content/crops from cited catalogues.
-- No price, inventory, publication, order, or blocked-Hooshmand resolution is performed.

do $$
declare v_products integer; v_targets integer; v_desc_gaps integer; v_blocked integer;
begin
  select count(*) into v_products from public."Product";
  if v_products <> 170 then raise exception 'Version 285 requires exactly 170 Product Master rows; found %', v_products; end if;

  select count(*) into v_targets
  from public."Product" p left join public."Brand" b on b.id=p."brandId"
  where coalesce(b.name,p.brand) in ('B.Well','Hooshmand','EGT');
  if v_targets <> 117 then raise exception 'Version 285 expected exactly 117 B.Well/Hooshmand/EGT Product Master rows; found %', v_targets; end if;

  select count(*) into v_desc_gaps from public."Product"
  where sku in ('BW-MED-111','BW-MED-120','BW-MED-130','BW-MED-3000','BW-MED-320','BW-MED-325','BW-MED-55','BW-MED-56','BW-MED-58','BW-MED-59','BW-PRO-03','BW-PRO-04','BW-PRO-06','BW-PRO-100','BW-PRO-110','BW-PRO-118','BW-PRO-22','BW-PRO-25','BW-PRO-26','BW-PRO-29','BW-PRO-310','BW-WF-1000','BW-WF-4000')
    and (btrim("descriptionFa")='' or btrim("descriptionTr")='' or btrim("descriptionEn")='' or btrim("descriptionAr")='');
  if v_desc_gaps <> 23 then raise exception 'Version 285 expected exactly 23 B.Well description gaps before enrichment; found %', v_desc_gaps; end if;

  if exists (
    select 1 from public."Product" p left join public."Brand" b on b.id=p."brandId"
    where coalesce(b.name,p.brand) in ('B.Well','Hooshmand','EGT')
      and (p."isPublished" or coalesce(p.price,0)<>0 or coalesce(p.stock,0)<>0)
  ) then raise exception 'Version 285 refuses published/nonzero legacy price-stock state for target brands'; end if;

  if exists (select 1 from public."BranchProductPrice") then raise exception 'Version 285 refuses existing current BranchProductPrice rows'; end if;
  if exists (select 1 from public."WarehouseInventory") then raise exception 'Version 285 refuses existing current WarehouseInventory rows'; end if;

  select count(*) into v_blocked from public."CatalogStagingItem"
  where status='NEEDS_REVIEW' and "productId" is null
    and "siteSku" in ('HOO-COOLER-CLASSIC','HOO-COOLER-WAVE-L','HOO-COOLER-WAVE-XL','HOO-SLEEP-NECK','HOO-WAVE-MASSAGER');
  if v_blocked <> 5 then raise exception 'Version 285 requires the exact five Hooshmand fail-closed staging rows to remain unresolved; found %', v_blocked; end if;
end $$;

with descriptions(sku,"descriptionFa","descriptionTr","descriptionEn","descriptionAr") as (
 values
 ('BW-MED-111','نبولایزر کمپرسوری اطفال B.Well MED-111 با نرخ نبولایزیشن قابل تنظیم ۰٫۲ تا ۰٫۴ میلی‌لیتر در دقیقه و MMAD حدود ۲٫۱ میکرومتر.','B.Well MED-111 pediatrik kompresörlü nebülizatör; 0,2–0,4 ml/dk ayarlanabilir nebülizasyon hızı ve yaklaşık 2,1 µm MMAD değerine sahiptir.','B.Well MED-111 pediatric compressor nebulizer with an adjustable nebulization rate of 0.2–0.4 ml/min and an MMAD of approximately 2.1 µm.','جهاز الرذاذ الضاغط للأطفال B.Well MED-111 بمعدل رذاذ قابل للتعديل من 0.2 إلى 0.4 مل/دقيقة وMMAD يبلغ نحو 2.1 ميكرومتر.'),
 ('BW-MED-120','نبولایزر کمپرسوری جمع‌وجور B.Well MED-120 با MMAD حداکثر ۲٫۹ میکرومتر، FPD حداقل ۷۱٪، نرخ نبولایزیشن ۰٫۳ میلی‌لیتر در دقیقه و سطح صدا حدود ۴۴ دسی‌بل.','B.Well MED-120 kompakt kompresörlü nebülizatör; ≤2,9 µm MMAD, ≥%71 FPD, 0,3 ml/dk nebülizasyon hızı ve yaklaşık 44 dB ses seviyesi sunar.','B.Well MED-120 compact compressor nebulizer with MMAD ≤2.9 µm, FPD ≥71%, a nebulization rate of 0.3 ml/min, and a noise level of approximately 44 dB.','جهاز الرذاذ الضاغط المدمج B.Well MED-120 مع MMAD ≤2.9 ميكرومتر وFPD ≥71% ومعدل رذاذ 0.3 مل/دقيقة ومستوى ضوضاء يقارب 44 ديسيبل.'),
 ('BW-MED-130','نبولایزر کمپرسوری B.Well MED-130 با نرخ نبولایزیشن قابل تنظیم ۰٫۲ تا ۰٫۴ میلی‌لیتر در دقیقه، MMAD حدود ۲٫۱ میکرومتر و FPD حدود ۸۵٪.','B.Well MED-130 kompresörlü nebülizatör; 0,2–0,4 ml/dk ayarlanabilir nebülizasyon hızı, yaklaşık 2,1 µm MMAD ve yaklaşık %85 FPD değerlerine sahiptir.','B.Well MED-130 compressor nebulizer with an adjustable nebulization rate of 0.2–0.4 ml/min, an MMAD of approximately 2.1 µm, and FPD of approximately 85%.','جهاز الرذاذ الضاغط B.Well MED-130 بمعدل رذاذ قابل للتعديل من 0.2 إلى 0.4 مل/دقيقة وMMAD يقارب 2.1 ميكرومتر وFPD يقارب 85%.'),
 ('BW-MED-3000','تب‌سنج مادون قرمز غیرتماسی B.Well MED-3000 با محدوده اندازه‌گیری ۰ تا ۱۰۰ درجه سانتی‌گراد و زمان اندازه‌گیری از ۱ ثانیه.','B.Well MED-3000 temassız kızılötesi termometre; 0–100 °C ölçüm aralığı ve 1 saniyeden başlayan ölçüm süresi sunar.','B.Well MED-3000 non-contact infrared thermometer with a 0–100 °C measurement range and measurement from 1 second.','ميزان الحرارة بالأشعة تحت الحمراء دون تلامس B.Well MED-3000 بمدى قياس من 0 إلى 100 درجة مئوية وقياس يبدأ من ثانية واحدة.'),
 ('BW-MED-320','پالس اکسیمتر انگشتی B.Well MED-320 برای نمایش SpO₂، شاخص پرفیوژن و شکل موج نبض.','B.Well MED-320 parmak tipi pulse oksimetre; SpO₂, Perfüzyon İndeksi ve nabız dalga formunu gösterir.','B.Well MED-320 fingertip pulse oximeter displaying SpO₂, Perfusion Index, and pulse waveform.','مقياس التأكسج النبضي الإصبعي B.Well MED-320 لعرض SpO₂ ومؤشر التروية وشكل موجة النبض.'),
 ('BW-MED-325','پالس اکسیمتر پیشرفته B.Well MED-325 با فناوری ضدلرزش، پشتیبانی از اندازه‌گیری در پرفیوژن پایین و هشدار صوتی.','B.Well MED-325 gelişmiş pulse oksimetre; sarsıntı önleme teknolojisi, düşük perfüzyonda ölçüm desteği ve sesli alarm özelliklerine sahiptir.','B.Well MED-325 advanced pulse oximeter with anti-shake technology, low-perfusion measurement support, and a sound alarm.','مقياس التأكسج النبضي المتقدم B.Well MED-325 مع تقنية مقاومة الاهتزاز ودعم القياس عند انخفاض التروية وإنذار صوتي.'),
 ('BW-MED-55','فشارسنج بازویی نسل چهارم B.Well MED-55 با میانگین ۷ روزه صبح و عصر، فناوری 3CHECK، نور پس‌زمینه رنگی و کاف M–L با محدوده ۲۲ تا ۴۲ سانتی‌متر.','B.Well MED-55 4. nesil üst kol tansiyon aleti; sabah ve akşam 7 günlük ortalama, 3CHECK, renkli arka aydınlatma ve 22–42 cm M–L manşet sunar.','B.Well MED-55 Generation IV upper-arm blood pressure monitor with morning and evening 7-day averages, 3CHECK, color backlight, and an M–L cuff for 22–42 cm arms.','جهاز قياس ضغط الدم للذراع B.Well MED-55 من الجيل الرابع مع متوسط 7 أيام صباحًا ومساءً وتقنية 3CHECK وإضاءة خلفية ملونة وكفة M–L لمحيط 22–42 سم.'),
 ('BW-MED-56','فشارسنج B.Well MED-56 با راهنمای صوتی، دکمه‌های بزرگ و کاف M–L با محدوده ۲۲ تا ۴۲ سانتی‌متر.','B.Well MED-56 tansiyon aleti; sesli yönlendirme, büyük kontroller ve 22–42 cm M–L manşet ile sunulur.','B.Well MED-56 blood pressure monitor with voice guidance, large controls, and an M–L cuff for 22–42 cm arms.','جهاز قياس الضغط B.Well MED-56 مع إرشاد صوتي وأزرار كبيرة وكفة M–L لمحيط 22–42 سم.'),
 ('BW-MED-58','فشارسنج بازویی B.Well MED-58 با کاف Comfort360، فناوری‌های 3CHECK و 3AVG و حافظه ۱۵۰×۲.','B.Well MED-58 üst kol tansiyon aleti; Comfort360 manşet, 3CHECK ve 3AVG teknolojileri ile 150×2 hafıza sunar.','B.Well MED-58 upper-arm blood pressure monitor with a Comfort360 cuff, 3CHECK and 3AVG technologies, and 150×2 memory.','جهاز قياس ضغط الدم للذراع B.Well MED-58 مع كفة Comfort360 وتقنيتي 3CHECK و3AVG وذاكرة 150×2.'),
 ('BW-MED-59','فشارسنج مچی B.Well MED-59 با راهنمای موقعیت دست و قلب، فناوری 3AVG و حافظه ۱۵۰×۲.','B.Well MED-59 bilekten tansiyon aleti; el-kalp konumlandırma rehberi, 3AVG ve 150×2 hafıza sunar.','B.Well MED-59 wrist blood pressure monitor with hand-and-heart positioning guidance, 3AVG, and 150×2 memory.','جهاز قياس ضغط الدم للمعصم B.Well MED-59 مع إرشاد لوضع اليد والقلب وتقنية 3AVG وذاكرة 150×2.'),
 ('BW-PRO-03','تب‌سنج دیجیتال ضدآب B.Well PRO-03 با محدوده اندازه‌گیری ۳۲ تا ۴۲٫۹ درجه سانتی‌گراد و زمان اندازه‌گیری حدود ۶۰ ثانیه.','B.Well PRO-03 su geçirmez dijital termometre; 32–42,9 °C ölçüm aralığı ve yaklaşık 60 saniyelik ölçüm süresine sahiptir.','B.Well PRO-03 waterproof digital thermometer with a 32–42.9 °C measurement range and an approximate measurement time of 60 seconds.','ميزان الحرارة الرقمي المقاوم للماء B.Well PRO-03 بمدى 32–42.9 درجة مئوية وزمن قياس يقارب 60 ثانية.'),
 ('BW-PRO-04','تب‌سنج دیجیتال ضدآب B.Well PRO-04 با محدوده اندازه‌گیری ۳۲ تا ۴۲٫۹ درجه سانتی‌گراد و زمان اندازه‌گیری حدود ۳۰ ثانیه.','B.Well PRO-04 su geçirmez dijital termometre; 32–42,9 °C ölçüm aralığı ve yaklaşık 30 saniyelik ölçüm süresine sahiptir.','B.Well PRO-04 waterproof digital thermometer with a 32–42.9 °C measurement range and an approximate measurement time of 30 seconds.','ميزان الحرارة الرقمي المقاوم للماء B.Well PRO-04 بمدى 32–42.9 درجة مئوية وزمن قياس يقارب 30 ثانية.'),
 ('BW-PRO-06','تب‌سنج دیجیتال کودک B.Well PRO-06 با محدوده اندازه‌گیری ۳۲ تا ۴۲٫۹ درجه سانتی‌گراد، زمان اندازه‌گیری حدود ۱۰ ثانیه و بدنه ضدآب.','B.Well PRO-06 çocuk dijital termometresi; 32–42,9 °C ölçüm aralığı, yaklaşık 10 saniyelik ölçüm ve su geçirmez yapı sunar.','B.Well PRO-06 pediatric digital thermometer with a 32–42.9 °C measurement range, an approximate 10-second measurement time, and waterproof construction.','ميزان الحرارة الرقمي للأطفال B.Well PRO-06 بمدى 32–42.9 درجة مئوية وزمن قياس يقارب 10 ثوانٍ وبنية مقاومة للماء.'),
 ('BW-PRO-100','نبولایزر کمپرسوری B.Well PRO-100 با MMAD حدود ۲٫۱ میکرومتر، FPD برابر ۷۲٪ و نرخ نبولایزیشن ۰٫۳ میلی‌لیتر در دقیقه.','B.Well PRO-100 kompresörlü nebülizatör; yaklaşık 2,1 µm MMAD, %72 FPD ve 0,3 ml/dk nebülizasyon hızı sunar.','B.Well PRO-100 compressor nebulizer with an MMAD of approximately 2.1 µm, FPD of 72%, and a nebulization rate of 0.3 ml/min.','جهاز الرذاذ الضاغط B.Well PRO-100 مع MMAD يقارب 2.1 ميكرومتر وFPD بنسبة 72% ومعدل رذاذ 0.3 مل/دقيقة.'),
 ('BW-PRO-110','نبولایزر کمپرسوری B.Well PRO-110 با MMAD حدود ۳٫۱۶ میکرومتر، FPD حداقل ۷۰٪ و نرخ نبولایزیشن ۰٫۴ میلی‌لیتر در دقیقه.','B.Well PRO-110 kompresörlü nebülizatör; yaklaşık 3,16 µm MMAD, ≥%70 FPD ve 0,4 ml/dk nebülizasyon hızı sunar.','B.Well PRO-110 compressor nebulizer with an MMAD of approximately 3.16 µm, FPD ≥70%, and a nebulization rate of 0.4 ml/min.','جهاز الرذاذ الضاغط B.Well PRO-110 مع MMAD يقارب 3.16 ميكرومتر وFPD ≥70% ومعدل رذاذ 0.4 مل/دقيقة.'),
 ('BW-PRO-118','دستگاه استنشاق بخار B.Well PRO-118 با ابعاد ۲۳۵×۹۰×۲۶۰ میلی‌متر، وزن حدود ۰٫۵۶ کیلوگرم، ظرفیت ۸۰ میلی‌لیتر و نرخ حدود ۱۰٫۶ میلی‌لیتر در دقیقه.','B.Well PRO-118 buhar inhalatörü; 235×90×260 mm boyut, yaklaşık 0,56 kg ağırlık, 80 ml kapasite ve yaklaşık 10,6 ml/dk hız değerlerine sahiptir.','B.Well PRO-118 steam inhaler with dimensions of 235×90×260 mm, a weight of approximately 0.56 kg, an 80 ml capacity, and a rate of approximately 10.6 ml/min.','جهاز استنشاق البخار B.Well PRO-118 بأبعاد 235×90×260 مم ووزن يقارب 0.56 كغ وسعة 80 مل ومعدل يقارب 10.6 مل/دقيقة.'),
 ('BW-PRO-22','B.Well PRO-22 یک فشارسنج بازویی از مجموعه رسمی محصولات B.Well در کاتالوگ ۲۰۲۵–۲۰۲۶ است.','B.Well PRO-22, B.Well''in 2025–2026 resmi ürün kataloğunda yer alan bir üst kol tansiyon aletidir.','B.Well PRO-22 is an upper-arm blood pressure monitor listed in B.Well''s official 2025–2026 product catalogue.','B.Well PRO-22 هو جهاز قياس ضغط الدم للذراع مدرج في كتالوج منتجات B.Well الرسمي 2025–2026.'),
 ('BW-PRO-25','فشارسنج بازویی B.Well PRO-25 با فناوری 3AVG و حافظه ۹۹×۲.','B.Well PRO-25 üst kol tansiyon aleti; 3AVG teknolojisi ve 99×2 hafıza sunar.','B.Well PRO-25 upper-arm blood pressure monitor with 3AVG technology and 99×2 memory.','جهاز قياس ضغط الدم للذراع B.Well PRO-25 مع تقنية 3AVG وذاكرة 99×2.'),
 ('BW-PRO-26','فشارسنج B.Well PRO-26 با راهنمای صوتی، تشخیص آریتمی نبض و طبقه‌بندی فشار خون.','B.Well PRO-26 tansiyon aleti; sesli yönlendirme, nabız aritmisi algılama ve kan basıncı sınıflandırması sunar.','B.Well PRO-26 blood pressure monitor with voice guidance, pulse arrhythmia detection, and blood pressure classification.','جهاز قياس الضغط B.Well PRO-26 مع إرشاد صوتي وكشف اضطراب نظم النبض وتصنيف ضغط الدم.'),
 ('BW-PRO-29','فشارسنج مچی B.Well PRO-29 با فناوری 3AVG و حافظه ۹۹×۲.','B.Well PRO-29 bilekten tansiyon aleti; 3AVG teknolojisi ve 99×2 hafıza sunar.','B.Well PRO-29 wrist blood pressure monitor with 3AVG technology and 99×2 memory.','جهاز قياس ضغط الدم للمعصم B.Well PRO-29 مع تقنية 3AVG وذاكرة 99×2.'),
 ('BW-PRO-310','پالس اکسیمتر انگشتی B.Well PRO-310 برای نمایش SpO₂، تعداد نبض و هیستوگرام نبض.','B.Well PRO-310 parmak tipi pulse oksimetre; SpO₂, nabız hızı ve nabız histogramını gösterir.','B.Well PRO-310 fingertip pulse oximeter displaying SpO₂, pulse rate, and pulse histogram.','مقياس التأكسج النبضي الإصبعي B.Well PRO-310 لعرض SpO₂ ومعدل النبض ومخطط النبض.'),
 ('BW-WF-1000','تب‌سنج مادون قرمز گوش و پیشانی B.Well WF-1000 با محدوده اندازه‌گیری حدود ۱۰ تا ۵۰ درجه سانتی‌گراد، اندازه‌گیری از ۱ ثانیه و حالت‌های بدن، جسم و محیط.','B.Well WF-1000 kulak/alın kızılötesi termometre; yaklaşık 10–50 °C ölçüm aralığı, 1 saniyeden başlayan ölçüm ve Vücut, Nesne, Ortam modları sunar.','B.Well WF-1000 infrared ear/forehead thermometer with an approximately 10–50 °C measurement range, measurement from 1 second, and Body, Object, and Ambient modes.','ميزان الحرارة بالأشعة تحت الحمراء للأذن والجبهة B.Well WF-1000 بمدى قياس يقارب 10–50 درجة مئوية وقياس يبدأ من ثانية واحدة وأوضاع الجسم والجسم الخارجي والبيئة.'),
 ('BW-WF-4000','تب‌سنج مادون قرمز غیرتماسی B.Well WF-4000 با محدوده اندازه‌گیری ۰ تا ۱۱۰ درجه سانتی‌گراد و زمان اندازه‌گیری از ۱ ثانیه.','B.Well WF-4000 temassız kızılötesi termometre; 0–110 °C ölçüm aralığı ve 1 saniyeden başlayan ölçüm sunar.','B.Well WF-4000 non-contact infrared thermometer with a 0–110 °C measurement range and measurement from 1 second.','ميزان الحرارة بالأشعة تحت الحمراء دون تلامس B.Well WF-4000 بمدى قياس من 0 إلى 110 درجات مئوية وقياس يبدأ من ثانية واحدة.')
)
update public."Product" p
set "descriptionFa"=d."descriptionFa","descriptionTr"=d."descriptionTr","descriptionEn"=d."descriptionEn","descriptionAr"=d."descriptionAr","updatedAt"=current_timestamp
from descriptions d where p.sku=d.sku;
