import Link from "next/link";
import { redirect } from "next/navigation";
import { LockKeyhole, Mail, Phone, ShieldCheck, UserRound } from "lucide-react";
import { getCustomerSession } from "@/lib/customer-auth";
import { registerAction } from "../actions";

const BG="https://lh3.googleusercontent.com/aida/AEtjO1XsKXqpr5yRiWfVB-d1KkBSurcii3IusZ5vZkc9D6KJcRR2SW3LlkVb-kaVx_yZRT4vSqEEXeoUFzdyWN1mHWFmDkkjV0keIXfXF5byYE9NeKt9mmkYsTvRI_72rpslADLitqr6hLFZbB00yBCLxSbIuFZH0nRc_vYfHwwI8A90SQDK_1CQZEkrKVxZxSq7dDRJdxfuXX2drvm5TWsE7CK0UMYZrEKP-RBsNaS2WC7uZ_nDW4mmGG21XSWG";
const copy={fa:{title:"ایجاد حساب کاربری",first:"نام",last:"نام خانوادگی",email:"ایمیل",phone:"شماره موبایل",pass:"رمز عبور",confirm:"تکرار رمز عبور",submit:"ایجاد حساب",have:"قبلاً ثبت‌نام کرده‌اید؟",login:"وارد شوید",hint:"حداقل یکی از ایمیل یا شماره موبایل لازم است."},tr:{title:"Hesap oluştur",first:"Ad",last:"Soyad",email:"E-posta",phone:"Telefon",pass:"Şifre",confirm:"Şifre tekrar",submit:"Hesap oluştur",have:"Zaten kayıtlı mısınız?",login:"Giriş yap",hint:"E-posta veya telefon bilgilerinden en az biri gereklidir."},en:{title:"Create account",first:"First name",last:"Last name",email:"Email",phone:"Mobile number",pass:"Password",confirm:"Confirm password",submit:"Create account",have:"Already registered?",login:"Sign in",hint:"At least an email or mobile number is required."},ar:{title:"إنشاء حساب",first:"الاسم",last:"اسم العائلة",email:"البريد الإلكتروني",phone:"رقم الهاتف",pass:"كلمة المرور",confirm:"تأكيد كلمة المرور",submit:"إنشاء الحساب",have:"لديك حساب بالفعل؟",login:"تسجيل الدخول",hint:"يلزم بريد إلكتروني أو رقم هاتف واحد على الأقل."}} as const;

export default async function RegisterPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{error?:string}>}){
 const {locale}=await params; const q=await searchParams; if(await getCustomerSession())redirect(`/${locale}/account`); const t=copy[locale as keyof typeof copy]??copy.fa; const action=registerAction.bind(null,locale);
 const error=q.error==="exists"?"این ایمیل یا شماره قبلاً ثبت شده است.":q.error==="short"?"رمز عبور باید حداقل ۸ کاراکتر باشد.":q.error==="password_mismatch"?"رمز عبور و تکرار آن یکسان نیست.":q.error==="contact_required"?"ایمیل یا شماره موبایل را وارد کنید.":q.error?"ثبت‌نام انجام نشد؛ اطلاعات را بررسی کنید.":null;
 return <main className="relative min-h-[calc(100vh-5rem)] overflow-hidden bg-[#f7fafd] py-10 sm:py-16" style={{backgroundImage:`linear-gradient(rgba(247,250,253,.9),rgba(247,250,253,.96)),url(${BG})`,backgroundSize:"520px"}}><div className="mx-auto max-w-2xl px-4">
  <div className="mb-7 text-center"><h1 className="text-4xl font-black tracking-tight text-[#001736] sm:text-5xl">Hyper Doctor</h1><p className="mt-4 text-lg text-[#43474f]">{t.title}</p></div>
  <section className="rounded-[2rem] border border-white/80 bg-white/90 p-6 shadow-[0_28px_80px_rgba(0,23,54,.11)] backdrop-blur-xl sm:p-9">{error?<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-center text-xs font-bold text-red-700">{error}</div>:null}<form action={action} className="space-y-5">
   <div className="grid gap-4 sm:grid-cols-2"><Field name="firstName" label={t.first} icon={UserRound} required/><Field name="lastName" label={t.last} icon={UserRound} required/></div>
   <Field name="email" label={t.email} type="email" icon={Mail} dir="ltr"/><Field name="phone" label={t.phone} icon={Phone} dir="ltr"/>
   <div className="grid gap-4 sm:grid-cols-2"><Field name="password" label={t.pass} type="password" icon={LockKeyhole} dir="ltr" required minLength={8}/><Field name="confirmPassword" label={t.confirm} type="password" icon={LockKeyhole} dir="ltr" required minLength={8}/></div>
   <p className="rounded-xl bg-[#f5f8fb] px-4 py-3 text-xs leading-6 text-[#5f6570]">{t.hint}</p><button className="min-h-14 w-full rounded-xl bg-[#001736] px-5 text-sm font-black text-white shadow-[0_14px_28px_rgba(0,23,54,.18)] hover:bg-[#002b5b]">{t.submit}</button>
  </form><div className="mt-6 flex items-center justify-center gap-2 text-[11px] text-[#747780]"><ShieldCheck className="h-4 w-4"/>SSL / HttpOnly Session</div></section>
  <p className="mt-7 text-center text-sm text-[#43474f]">{t.have} <Link href={`/${locale}/account/login`} className="font-black text-[#001736] underline underline-offset-4">{t.login}</Link></p>
 </div></main>;
}
function Field({name,label,type="text",icon:Icon,required,dir,minLength}:{name:string;label:string;type?:string;icon:typeof UserRound;required?:boolean;dir?:"ltr"|"rtl";minLength?:number}){return <label className="block"><span className="mb-2 block text-sm font-bold text-[#181c1e]">{label}</span><div className="flex h-14 items-center gap-3 rounded-xl border border-[#c4c6d0] bg-white px-4 focus-within:border-[#001736]"><Icon className="h-5 w-5 shrink-0 text-[#747780]"/><input name={name} type={type} required={required} minLength={minLength} autoComplete={type==="password"?"new-password":name==="email"?"email":name==="phone"?"tel":"name"} dir={dir} className="h-full w-full bg-transparent text-sm outline-none"/></div></label>}
