import Link from "next/link";
import { redirect } from "next/navigation";
import { UserPlus, ShieldCheck, PackageCheck } from "lucide-react";
import { getCustomerSession } from "@/lib/customer-auth";
import { registerAction } from "../actions";

const copy={fa:{title:"ساخت حساب کاربری",sub:"برای پیگیری سفارش، گارانتی، خدمات و پشتیبانی یک حساب امن بسازید.",name:"نام و نام خانوادگی",email:"ایمیل",phone:"شماره موبایل",pass:"رمز عبور",confirm:"تکرار رمز عبور",submit:"ایجاد حساب",have:"قبلاً ثبت‌نام کرده‌اید؟",login:"ورود"},tr:{title:"Hesap oluşturun",sub:"Sipariş, garanti, hizmet ve destek takibi için güvenli bir hesap oluşturun.",name:"Ad soyad",email:"E-posta",phone:"Telefon",pass:"Şifre",confirm:"Şifre tekrar",submit:"Hesap oluştur",have:"Zaten hesabınız var mı?",login:"Giriş"},en:{title:"Create your account",sub:"Create a secure account to track orders, warranty, services and support.",name:"Full name",email:"Email",phone:"Mobile number",pass:"Password",confirm:"Confirm password",submit:"Create account",have:"Already registered?",login:"Sign in"},ar:{title:"إنشاء حساب",sub:"أنشئ حساباً آمناً لمتابعة الطلبات والضمان والخدمات والدعم.",name:"الاسم الكامل",email:"البريد الإلكتروني",phone:"رقم الهاتف",pass:"كلمة المرور",confirm:"تأكيد كلمة المرور",submit:"إنشاء الحساب",have:"لديك حساب بالفعل؟",login:"تسجيل الدخول"}} as const;

export default async function RegisterPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{error?:string}>}){
  const {locale}=await params; const q=await searchParams; if(await getCustomerSession()) redirect(`/${locale}/account`); const t=copy[locale as keyof typeof copy]??copy.fa; const action=registerAction.bind(null,locale);
  const error=q.error==="exists"?"این ایمیل یا شماره قبلاً ثبت شده است.":q.error==="short"?"رمز عبور باید حداقل ۸ کاراکتر باشد.":q.error==="password_mismatch"?"رمز عبور و تکرار آن یکسان نیست.":q.error?"ثبت‌نام انجام نشد؛ اطلاعات را بررسی کنید.":null;
  return <main className="relative overflow-hidden py-12 sm:py-20"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_80%_10%,rgba(0,157,216,.18),transparent_28%),radial-gradient(circle_at_10%_85%,rgba(0,43,91,.16),transparent_35%)]"/><div className="relative mx-auto grid max-w-5xl gap-8 px-4 lg:grid-cols-[.9fr_1.1fr]">
    <section className="rounded-[2rem] bg-[#001736] p-8 text-white shadow-2xl sm:p-10"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10"><UserPlus className="h-7 w-7 text-[#33c8ff]"/></div><h1 className="mt-8 text-4xl font-black leading-tight">VITALIS ×<br/><span className="text-[#33c8ff]">Hyper Doctor</span></h1><p className="mt-5 max-w-md text-sm leading-7 text-white/70">{t.sub}</p><div className="mt-10 space-y-3 text-xs"><div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4"><ShieldCheck className="h-5 w-5 text-[#33c8ff]"/>Session امن و HttpOnly</div><div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4"><PackageCheck className="h-5 w-5 text-[#33c8ff]"/>پیگیری خرید، گارانتی و خدمات</div></div></section>
    <section className="vitalis-glass rounded-[2rem] border border-white/70 p-6 shadow-xl sm:p-9"><h2 className="text-2xl font-black text-foreground">{t.title}</h2><p className="mt-2 text-sm leading-7 text-muted">{t.sub}</p>{error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>:null}<form action={action} className="mt-6 space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{t.name}</span><input name="fullName" required minLength={2} autoComplete="name" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{t.email}</span><input name="email" type="email" autoComplete="email" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{t.phone}</span><input name="phone" autoComplete="tel" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{t.pass}</span><input name="password" type="password" required minLength={8} autoComplete="new-password" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label><label className="block"><span className="mb-1.5 block text-xs font-bold text-muted">{t.confirm}</span><input name="confirmPassword" type="password" required minLength={8} autoComplete="new-password" className="h-12 w-full rounded-xl border border-border bg-white px-3 text-sm outline-none focus:border-primary" dir="ltr"/></label></div><p className="text-xs leading-6 text-muted">حداقل یکی از ایمیل یا شماره موبایل لازم است. برای بازیابی خودکار رمز، ثبت ایمیل توصیه می‌شود.</p><button className="min-h-12 w-full rounded-xl bg-primary px-5 text-sm font-black text-white shadow-lg">{t.submit}</button></form><p className="mt-6 text-center text-sm text-muted">{t.have} <Link href={`/${locale}/account/login`} className="font-black text-primary">{t.login}</Link></p></section>
  </div></main>;
}
