import { CheckCircle2, MessageSquareText, Search, Star, XCircle } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { updateReview } from "./actions";

type Review={id:string;authorName:string;rating:number;title:string;body:string;status:"PENDING"|"APPROVED"|"REJECTED";isVerified:boolean;createdAt:string;productNameFa:string;productNameEn:string;sku:string};
const STATUS={PENDING:"در انتظار",APPROVED:"تأیید شده",REJECTED:"رد شده"} as const;

export default async function AdminReviewsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){
  const [{q="",status=""},all]=await Promise.all([searchParams,adminRpc<Review[]>("admin_reviews")]);
  const reviews=all.filter(r=>(!q||r.authorName.toLowerCase().includes(q.toLowerCase())||r.productNameFa.toLowerCase().includes(q.toLowerCase())||r.productNameEn.toLowerCase().includes(q.toLowerCase())||r.sku.toLowerCase().includes(q.toLowerCase()))&&(!status||r.status===status));
  const pending=all.filter(r=>r.status==="PENDING").length, approved=all.filter(r=>r.status==="APPROVED").length;
  const avg=all.length?(all.reduce((a,r)=>a+r.rating,0)/all.length).toFixed(1):"0.0";
  return <div className="mx-auto max-w-[1450px] space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">Review Moderation</p><h1 className="mt-2 text-3xl font-black text-[#001736]">مدیریت نظرات و بازخوردها</h1><p className="mt-2 text-sm text-[#747780]">بررسی، تأیید و رد بازخوردهای کاربران بر اساس داده واقعی</p></div></div>
    <div className="grid gap-4 md:grid-cols-3"><Metric label="میانگین امتیاز" value={avg} icon={Star}/><Metric label="در انتظار بررسی" value={new Intl.NumberFormat("fa-IR").format(pending)} icon={MessageSquareText}/><Metric label="تأییدشده" value={new Intl.NumberFormat("fa-IR").format(approved)} icon={CheckCircle2}/></div>
    <form className="grid gap-3 rounded-[1.5rem] border border-[#e2e6eb] bg-white p-4 shadow-sm md:grid-cols-[1fr_190px_auto]"><label className="relative"><Search className="pointer-events-none absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9a9da5]"/><input name="q" defaultValue={q} placeholder="جستجو در نام کاربر، محصول یا SKU..." className="h-11 w-full rounded-xl border border-[#dfe4ea] bg-[#f7fafd] ps-11 pe-4 text-sm outline-none focus:border-[#009dd8]"/></label><select name="status" defaultValue={status} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"><option value="">همه وضعیت‌ها</option>{Object.entries(STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="rounded-xl bg-[#001736] px-5 text-xs font-black text-white">اعمال فیلتر</button></form>
    <div className="grid gap-4 xl:grid-cols-2">{reviews.map(r=>{const action=updateReview.bind(null,r.id);return <article key={r.id} className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-1 text-amber-500">{Array.from({length:5}).map((_,i)=><Star key={i} className={`h-4 w-4 ${i<r.rating?"fill-current":""}`}/>)}</div><h2 className="mt-2 font-black text-[#001736]">{r.productNameFa||r.productNameEn}</h2><p className="mt-1 text-xs text-[#747780]">{r.authorName} · <span dir="ltr">{r.sku}</span> · {new Date(r.createdAt).toLocaleDateString("fa-IR")}</p></div><span className={`self-start rounded-full px-3 py-1.5 text-[10px] font-black ${r.status==="APPROVED"?"bg-emerald-50 text-emerald-700":r.status==="REJECTED"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{STATUS[r.status]}</span></div>{r.title?<h3 className="mt-4 text-sm font-black text-[#001736]">{r.title}</h3>:null}<p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-[#5f6570]">{r.body||"بدون متن"}</p><form action={action} className="mt-5 grid gap-3 rounded-2xl border border-[#edf0f2] bg-[#fafcff] p-4 sm:grid-cols-[180px_1fr_auto]"><select name="status" defaultValue={r.status} className="h-10 rounded-xl border border-[#dfe4ea] bg-white px-3 text-xs font-bold">{Object.entries(STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="flex items-center gap-2 text-xs font-bold text-[#5f6570]"><input type="checkbox" name="isVerified" defaultChecked={r.isVerified}/> خرید تأییدشده</label><button className="h-10 rounded-xl bg-[#e80346] px-4 text-xs font-black text-white">ذخیره</button></form></article>})}{reviews.length===0?<div className="xl:col-span-2 rounded-[1.6rem] border border-dashed border-[#cfd5dc] bg-white p-12 text-center text-sm text-[#8a8e96]"><XCircle className="mx-auto mb-3 h-6 w-6"/>نظری با این معیار پیدا نشد.</div>:null}</div>
  </div>;
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof Star}){return <article className="rounded-[1.5rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf4ff] text-[#002b5b]"><Icon className="h-5 w-5"/></span><p className="mt-4 text-xs font-black text-[#747780]">{label}</p><p className="mt-1 text-2xl font-black text-[#001736]">{value}</p></article>}
