import { CheckCircle2, MessageSquareText, Search, Star, XCircle } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminDate, adminNumber, type AdminLocale } from "@/lib/admin-i18n";
import { updateReview } from "./actions";

type Review={id:string;authorName:string;rating:number;title:string;body:string;status:"PENDING"|"APPROVED"|"REJECTED";isVerified:boolean;createdAt:string;productNameFa:string;productNameEn:string;sku:string};
const c:Record<AdminLocale,Record<string,string>>={
  fa:{eyebrow:"مدیریت نظرات",title:"مدیریت نظرات و بازخوردها",subtitle:"بررسی، تأیید و رد بازخوردهای کاربران بر اساس داده واقعی",average:"میانگین امتیاز",pendingCount:"در انتظار بررسی",approvedCount:"تأییدشده",searchPlaceholder:"جستجو در نام کاربر، محصول یا SKU...",allStatuses:"همه وضعیت‌ها",filter:"اعمال فیلتر",PENDING:"در انتظار",APPROVED:"تأیید شده",REJECTED:"رد شده",noText:"بدون متن",verified:"خرید تأییدشده",save:"ذخیره",empty:"نظری با این معیار پیدا نشد."},
  ar:{eyebrow:"إدارة المراجعات",title:"إدارة التقييمات والملاحظات",subtitle:"مراجعة واعتماد ورفض ملاحظات المستخدمين اعتماداً على البيانات الفعلية",average:"متوسط التقييم",pendingCount:"بانتظار المراجعة",approvedCount:"معتمد",searchPlaceholder:"ابحث باسم المستخدم أو المنتج أو SKU...",allStatuses:"كل الحالات",filter:"تطبيق الفلتر",PENDING:"قيد الانتظار",APPROVED:"معتمد",REJECTED:"مرفوض",noText:"بدون نص",verified:"شراء موثّق",save:"حفظ",empty:"لم يتم العثور على مراجعات مطابقة."},
  en:{eyebrow:"Review Moderation",title:"Reviews & feedback",subtitle:"Review, approve and reject customer feedback using live data",average:"Average rating",pendingCount:"Pending review",approvedCount:"Approved",searchPlaceholder:"Search by customer, product or SKU...",allStatuses:"All statuses",filter:"Apply filter",PENDING:"Pending",APPROVED:"Approved",REJECTED:"Rejected",noText:"No text",verified:"Verified purchase",save:"Save",empty:"No review matched these criteria."},
  tr:{eyebrow:"Yorum Moderasyonu",title:"Yorum ve geri bildirim yönetimi",subtitle:"Gerçek verilerle kullanıcı geri bildirimlerini inceleyin, onaylayın veya reddedin",average:"Ortalama puan",pendingCount:"İnceleme bekliyor",approvedCount:"Onaylandı",searchPlaceholder:"Kullanıcı, ürün veya SKU ile ara...",allStatuses:"Tüm durumlar",filter:"Filtrele",PENDING:"Bekliyor",APPROVED:"Onaylandı",REJECTED:"Reddedildi",noText:"Metin yok",verified:"Doğrulanmış satın alma",save:"Kaydet",empty:"Bu kriterlere uyan yorum bulunamadı."}
};

export default async function AdminReviewsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){
  const [{q="",status=""},all,l]=await Promise.all([searchParams,adminRpc<Review[]>("admin_reviews"),currentAdminLocale()]);
  const t=c[l];
  const reviews=all.filter(r=>(!q||r.authorName.toLowerCase().includes(q.toLowerCase())||r.productNameFa.toLowerCase().includes(q.toLowerCase())||r.productNameEn.toLowerCase().includes(q.toLowerCase())||r.sku.toLowerCase().includes(q.toLowerCase()))&&(!status||r.status===status));
  const pending=all.filter(r=>r.status==="PENDING").length, approved=all.filter(r=>r.status==="APPROVED").length;
  const avg=all.length?(all.reduce((a,r)=>a+r.rating,0)/all.length):0;
  const statuses:[Review["status"],string][]= [["PENDING",t.PENDING],["APPROVED",t.APPROVED],["REJECTED",t.REJECTED]];
  return <div className="mx-auto max-w-[1450px] space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.subtitle}</p></div></div>
    <div className="grid gap-4 md:grid-cols-3"><Metric label={t.average} value={avg.toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1})} icon={Star}/><Metric label={t.pendingCount} value={adminNumber(pending,l)} icon={MessageSquareText}/><Metric label={t.approvedCount} value={adminNumber(approved,l)} icon={CheckCircle2}/></div>
    <form className="grid gap-3 rounded-[1.5rem] border border-[#e2e6eb] bg-white p-4 shadow-sm md:grid-cols-[1fr_190px_auto]"><label className="relative"><Search className="pointer-events-none absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9a9da5]"/><input name="q" defaultValue={q} placeholder={t.searchPlaceholder} className="h-11 w-full rounded-xl border border-[#dfe4ea] bg-[#f7fafd] ps-11 pe-4 text-sm outline-none focus:border-[#009dd8]"/></label><select name="status" defaultValue={status} className="h-11 rounded-xl border border-[#dfe4ea] bg-[#f7fafd] px-3 text-sm"><option value="">{t.allStatuses}</option>{statuses.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select><button className="rounded-xl bg-[#001736] px-5 text-xs font-black text-white">{t.filter}</button></form>
    <div className="grid gap-4 xl:grid-cols-2">{reviews.map(r=>{const action=updateReview.bind(null,r.id);return <article key={r.id} className="rounded-[1.6rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-1 text-amber-500">{Array.from({length:5}).map((_,i)=><Star key={i} className={`h-4 w-4 ${i<r.rating?"fill-current":""}`}/>)}</div><h2 className="mt-2 font-black text-[#001736]">{r.productNameFa||r.productNameEn}</h2><p className="mt-1 text-xs text-[#747780]">{r.authorName} · <span dir="ltr">{r.sku}</span> · {adminDate(r.createdAt,l)}</p></div><span className={`self-start rounded-full px-3 py-1.5 text-[10px] font-black ${r.status==="APPROVED"?"bg-emerald-50 text-emerald-700":r.status==="REJECTED"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{t[r.status]}</span></div>{r.title?<h3 className="mt-4 text-sm font-black text-[#001736]">{r.title}</h3>:null}<p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-[#5f6570]">{r.body||t.noText}</p><form action={action} className="mt-5 grid gap-3 rounded-2xl border border-[#edf0f2] bg-[#fafcff] p-4 sm:grid-cols-[180px_1fr_auto]"><select name="status" defaultValue={r.status} className="h-10 rounded-xl border border-[#dfe4ea] bg-white px-3 text-xs font-bold">{statuses.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select><label className="flex items-center gap-2 text-xs font-bold text-[#5f6570]"><input type="checkbox" name="isVerified" defaultChecked={r.isVerified}/> {t.verified}</label><button className="h-10 rounded-xl bg-[#e80346] px-4 text-xs font-black text-white">{t.save}</button></form></article>})}{reviews.length===0?<div className="xl:col-span-2 rounded-[1.6rem] border border-dashed border-[#cfd5dc] bg-white p-12 text-center text-sm text-[#8a8e96]"><XCircle className="mx-auto mb-3 h-6 w-6"/>{t.empty}</div>:null}</div>
  </div>;
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof Star}){return <article className="rounded-[1.5rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf4ff] text-[#002b5b]"><Icon className="h-5 w-5"/></span><p className="mt-4 text-xs font-black text-[#747780]">{label}</p><p className="mt-1 text-2xl font-black text-[#001736]">{value}</p></article>}
