import Link from "next/link";
import { Banknote, CircleDollarSign, CreditCard, ReceiptText, Search } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import { adminCurrency, adminDate, adminNumber, adminStatusText, type AdminLocale } from "@/lib/admin-i18n";

type TransactionRow={id:string;orderNumber:string;customerName:string;total:number;status:string;gateway:string;paymentRefId?:string|null;createdAt:string};
type ReportBundle = {
  summary: { orders: number; paidOrders: number; failedOrders:number; revenue: number; discounts: number; shipping: number; customers: number; products: number; lowStock: number };
  recent: TransactionRow[];
  daily: Array<{ dateKey:string; orderCount:number; revenue:number }>;
};
const c:Record<AdminLocale,Record<string,string>>={
  fa:{eyebrow:"عملیات مالی",title:"مدیریت تراکنش‌های مالی",subtitle:"کنترل مرجع پرداخت، درگاه، وضعیت و مبلغ سفارش‌های واقعی",back:"بازگشت به گزارش فروش",successAmount:"کل مبلغ موفق",successPayments:"پرداخت‌های موفق",failedPayments:"پرداخت ناموفق",shipping:"هزینه ارسال",searchPlaceholder:"جستجو با شماره سفارش، مشتری، مرجع پرداخت، درگاه یا وضعیت...",search:"جستجو",history:"سوابق تراکنش‌ها",records:"رکورد در نمای فعلی",badge:"داده واقعی پرداخت",date:"تاریخ",order:"سفارش",customer:"مشتری",gateway:"درگاه",reference:"مرجع",amount:"مبلغ",status:"وضعیت",empty:"تراکنشی با این معیار پیدا نشد.",ZARINPAL:"زرین‌پال",IDPAY:"آیدی‌پی",MANUAL:"پرداخت دستی"},
  ar:{eyebrow:"العمليات المالية",title:"إدارة المعاملات المالية",subtitle:"متابعة مرجع الدفع والبوابة والحالة ومبالغ الطلبات الفعلية",back:"العودة إلى تقرير المبيعات",successAmount:"إجمالي المبلغ الناجح",successPayments:"المدفوعات الناجحة",failedPayments:"المدفوعات الفاشلة",shipping:"تكلفة الشحن",searchPlaceholder:"ابحث برقم الطلب أو العميل أو مرجع الدفع أو البوابة أو الحالة...",search:"بحث",history:"سجل المعاملات",records:"سجل في العرض الحالي",badge:"بيانات دفع فعلية",date:"التاريخ",order:"الطلب",customer:"العميل",gateway:"بوابة الدفع",reference:"المرجع",amount:"المبلغ",status:"الحالة",empty:"لم يتم العثور على معاملة مطابقة.",ZARINPAL:"زرين بال",IDPAY:"آي دي باي",MANUAL:"دفع يدوي"},
  en:{eyebrow:"Finance Operations",title:"Financial transaction management",subtitle:"Track payment reference, gateway, status and real order amounts",back:"Back to sales report",successAmount:"Successful amount",successPayments:"Successful payments",failedPayments:"Failed payments",shipping:"Shipping cost",searchPlaceholder:"Search order, customer, payment reference, gateway or status...",search:"Search",history:"Transaction history",records:"records in current view",badge:"Real payment data",date:"Date",order:"Order",customer:"Customer",gateway:"Gateway",reference:"Reference",amount:"Amount",status:"Status",empty:"No transaction matched these criteria.",ZARINPAL:"ZarinPal",IDPAY:"IDPay",MANUAL:"Manual payment"},
  tr:{eyebrow:"Finans Operasyonları",title:"Finansal işlem yönetimi",subtitle:"Gerçek siparişlerde ödeme referansı, ağ, durum ve tutarı yönetin",back:"Satış raporuna dön",successAmount:"Başarılı toplam tutar",successPayments:"Başarılı ödemeler",failedPayments:"Başarısız ödemeler",shipping:"Kargo maliyeti",searchPlaceholder:"Sipariş, müşteri, ödeme referansı, ağ veya durum ile ara...",search:"Ara",history:"İşlem geçmişi",records:"mevcut görünümde kayıt",badge:"Gerçek ödeme verisi",date:"Tarih",order:"Sipariş",customer:"Müşteri",gateway:"Ödeme ağı",reference:"Referans",amount:"Tutar",status:"Durum",empty:"Bu kriterlere uyan işlem bulunamadı.",ZARINPAL:"ZarinPal",IDPAY:"IDPay",MANUAL:"Manuel ödeme"}
};

export default async function AdminTransactionsPage({searchParams}:{searchParams:Promise<{q?:string}>}){
  const {q=""}=await searchParams;
  const [data,rows,l]=await Promise.all([adminRpc<ReportBundle>("admin_reports_bundle"),adminRpc<TransactionRow[]>("admin_transactions",{p_search:q}),currentAdminLocale()]);
  const t=c[l];
  const cards=[
    {label:t.successAmount,value:`${adminNumber(data.summary.revenue,l)} ${adminCurrency[l]}`,icon:CircleDollarSign,tone:"bg-[#edf4ff] text-[#002b5b]"},
    {label:t.successPayments,value:adminNumber(data.summary.paidOrders,l),icon:CreditCard,tone:"bg-emerald-50 text-emerald-700"},
    {label:t.failedPayments,value:adminNumber(data.summary.failedOrders,l),icon:ReceiptText,tone:"bg-red-50 text-red-700"},
    {label:t.shipping,value:`${adminNumber(data.summary.shipping,l)} ${adminCurrency[l]}`,icon:Banknote,tone:"bg-amber-50 text-amber-700"},
  ];
  return <div className="mx-auto max-w-[1450px]">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e80346]">{t.eyebrow}</p><h1 className="mt-2 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 text-sm text-[#747780]">{t.subtitle}</p></div><Link href="/admin/reports" className="rounded-xl border border-[#dfe4ea] bg-white px-4 py-3 text-xs font-black text-[#001736]">{t.back}</Link></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,icon:Icon,tone})=><article key={label} className="rounded-[1.5rem] border border-[#e2e6eb] bg-white p-5 shadow-sm"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5"/></span><p className="mt-4 text-xs font-black text-[#747780]">{label}</p><p className="mt-1 text-xl font-black tabular-nums text-[#001736]">{value}</p></article>)}</div>
    <form className="mt-6 flex gap-3 rounded-[1.5rem] border border-[#e2e6eb] bg-white p-4 shadow-sm"><label className="relative flex-1"><Search className="pointer-events-none absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9a9da5]"/><input name="q" defaultValue={q} placeholder={t.searchPlaceholder} className="h-11 w-full rounded-xl border border-[#dfe4ea] bg-[#f7fafd] ps-11 pe-4 text-sm outline-none focus:border-[#009dd8]"/></label><button className="rounded-xl bg-[#001736] px-5 text-xs font-black text-white">{t.search}</button></form>
    <section className="mt-6 overflow-hidden rounded-[1.6rem] border border-[#e2e6eb] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#edf0f2] px-5 py-4"><div><h2 className="font-black text-[#001736]">{t.history}</h2><p className="mt-1 text-[11px] text-[#8a8e96]">{adminNumber(rows.length,l)} {t.records}</p></div><span className="rounded-full bg-[#f1f4f7] px-3 py-1 text-[10px] font-black text-[#747780]">{t.badge}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead className="bg-[#f7fafd] text-[11px] font-black text-[#747780]"><tr><th className="px-5 py-3 text-start">{t.date}</th><th className="px-5 py-3 text-start">{t.order}</th><th className="px-5 py-3 text-start">{t.customer}</th><th className="px-5 py-3 text-start">{t.gateway}</th><th className="px-5 py-3 text-start">{t.reference}</th><th className="px-5 py-3 text-start">{t.amount}</th><th className="px-5 py-3 text-start">{t.status}</th></tr></thead><tbody className="divide-y divide-[#edf0f2]">{rows.map(r=><tr key={r.id} className="hover:bg-[#fafcff]"><td className="px-5 py-4 text-xs text-[#747780]">{adminDate(r.createdAt,l)}</td><td className="px-5 py-4"><Link href={`/admin/orders/${r.id}`} dir="ltr" className="font-mono text-xs font-black text-[#002b5b]">{r.orderNumber}</Link></td><td className="px-5 py-4 font-bold text-[#43474f]">{r.customerName}</td><td className="px-5 py-4 text-xs text-[#747780]">{t[r.gateway]||r.gateway||"—"}</td><td className="px-5 py-4 font-mono text-xs text-[#747780]" dir="ltr">{r.paymentRefId||"—"}</td><td className="px-5 py-4 font-black tabular-nums text-[#001736]">{adminNumber(r.total,l)} {adminCurrency[l]}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${r.status==="PAID"?"bg-emerald-50 text-emerald-700":r.status==="FAILED"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{adminStatusText(r.status,l)}</span></td></tr>)}{rows.length===0?<tr><td colSpan={7} className="px-5 py-14 text-center text-[#8a8e96]">{t.empty}</td></tr>:null}</tbody></table></div></section>
  </div>;
}
