import { adminRpc } from "@/lib/admin-data";
import { ImageUploadField } from "@/components/admin/image-upload-field";
import { TextField, CheckboxField } from "@/components/admin/form-field";
import { DeleteButton } from "@/components/admin/delete-button";
import { upsertBanner, deleteBanner } from "./actions";

type Banner={id:string;key:string;titleFa:string;titleTr:string;titleEn:string;titleAr:string;subtitleFa:string;subtitleTr:string;subtitleEn:string;subtitleAr:string;imageUrl:string;mobileImageUrl:string;linkUrl:string;isPublished:boolean;order:number;startsAt?:string|null;endsAt?:string|null};

function BannerForm({b}:{b?:Banner}){return <form action={upsertBanner} className="rounded-2xl border border-border bg-card p-5 shadow-sm">{b?.id?<input type="hidden" name="id" value={b.id}/>:null}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><TextField label="کلید" name="key" defaultValue={b?.key??"hero"} dir="ltr"/><TextField label="ترتیب" name="order" type="number" defaultValue={b?.order??0}/><TextField label="شروع" name="startsAt" type="datetime-local" defaultValue={b?.startsAt?new Date(b.startsAt).toISOString().slice(0,16):undefined}/><TextField label="پایان" name="endsAt" type="datetime-local" defaultValue={b?.endsAt?new Date(b.endsAt).toISOString().slice(0,16):undefined}/></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><TextField label="عنوان فارسی" name="titleFa" defaultValue={b?.titleFa}/><TextField label="Türkçe başlık" name="titleTr" defaultValue={b?.titleTr} dir="ltr"/><TextField label="English title" name="titleEn" defaultValue={b?.titleEn} dir="ltr"/><TextField label="العنوان العربي" name="titleAr" defaultValue={b?.titleAr}/></div><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><TextField label="زیرعنوان فارسی" name="subtitleFa" defaultValue={b?.subtitleFa}/><TextField label="Türkçe alt başlık" name="subtitleTr" defaultValue={b?.subtitleTr} dir="ltr"/><TextField label="English subtitle" name="subtitleEn" defaultValue={b?.subtitleEn} dir="ltr"/><TextField label="العنوان الفرعي" name="subtitleAr" defaultValue={b?.subtitleAr}/></div><div className="mt-4 grid gap-4 md:grid-cols-2"><ImageUploadField label="تصویر دسکتاپ" name="imageUrl" defaultValue={b?.imageUrl}/><ImageUploadField label="تصویر موبایل" name="mobileImageUrl" defaultValue={b?.mobileImageUrl}/></div><div className="mt-4 grid gap-4 md:grid-cols-[1fr_auto]"><TextField label="لینک مقصد" name="linkUrl" defaultValue={b?.linkUrl} dir="ltr"/><div className="pt-7"><CheckboxField label="منتشر شده" name="isPublished" defaultChecked={b?.isPublished??true}/></div></div><div className="mt-5 flex justify-end gap-2"><button className="min-h-10 rounded-xl bg-primary px-5 text-sm font-black text-white">{b?"ذخیره تغییرات":"افزودن بنر"}</button>{b?<DeleteButton action={deleteBanner.bind(null,b.id)} confirmMessage="این بنر حذف شود؟"/>:null}</div></form>}

export default async function AdminBannersPage(){const banners=await adminRpc<Banner[]>("admin_banners_bundle");return <div className="space-y-6"><div><p className="text-xs font-black uppercase tracking-[.16em] text-muted">Homepage Content</p><h1 className="mt-2 text-2xl font-black text-foreground">مدیریت بنرها و اسلایدها</h1></div><BannerForm/>{banners.map(b=><BannerForm key={b.id} b={b}/>)}</div>}
