import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, BadgeCheck, ImagePlus, Search, ShieldCheck, Trash2 } from "lucide-react";
import { adminRpc } from "@/lib/admin-data";
import { currentAdminLocale } from "@/lib/admin-locale-server";
import type { AdminLocale } from "@/lib/admin-i18n";
import { MediaUploader } from "@/components/admin/media-uploader";
import { attachVerifiedProductMedia, detachVerifiedProductMedia } from "./actions";

type Evidence={id:string;sourceType:string;sourceReference:string;sourceModel:string;notes:string;verificationStatus:string;createdAt:string};
type Media={id:string;url:string;altFa:string;altTr:string;altEn:string;altAr:string;sortOrder?:number;createdAt?:string;evidence?:Evidence|null};
type Product={id:string;sku:string;modelNumber:string;nameFa:string;nameTr:string;nameEn:string;nameAr:string;isPublished:boolean};
type Workspace={product:Product;attached:Media[];available:Media[];verifiedCount:number};
const copy:Record<AdminLocale,Record<string,string>>={
 fa:{title:"رسانه تأییدشده محصول",desc:"فقط تصویری را به محصول وصل کن که مدل آن با منبع واقعی تطبیق داده شده باشد. تصویر بدون Evidence برای لانچ معتبر نیست.",back:"بازگشت به محصول",verified:"تصاویر تأییدشده",attached:"تصاویر متصل",library:"رسانه‌های آزاد",search:"جستجو در کتابخانه",sourceType:"نوع منبع",sourceRef:"مرجع منبع",sourceModel:"مدل درج‌شده در منبع",notes:"یادداشت بررسی",attach:"تأیید و اتصال",detach:"جدا کردن",none:"هنوز تصویر تأییدشده‌ای برای این محصول ثبت نشده است.",empty:"رسانه آزاد پیدا نشد.",upload:"ابتدا تصویر واقعی را در کتابخانه آپلود کن، سپس مرجع و مدل منبع را ثبت و اتصال را تأیید کن.",published:"منتشرشده",draft:"پیش‌نویس"},
 en:{title:"Verified product media",desc:"Attach only media whose model has been matched to a real source. Media without evidence does not satisfy the launch gate.",back:"Back to product",verified:"Verified images",attached:"Attached media",library:"Unassigned media",search:"Search media library",sourceType:"Source type",sourceRef:"Source reference",sourceModel:"Model shown by source",notes:"Verification note",attach:"Verify & attach",detach:"Detach",none:"No verified media is attached to this product yet.",empty:"No unassigned media matched.",upload:"Upload the real image to the media library first, then record its source and model before attaching it.",published:"Published",draft:"Draft"},
 tr:{title:"Doğrulanmış ürün medyası",desc:"Yalnız gerçek kaynakla model eşleşmesi doğrulanmış görselleri bağlayın. Kanıtsız medya lansman kontrolünü geçmez.",back:"Ürüne dön",verified:"Doğrulanmış görseller",attached:"Bağlı medya",library:"Boşta medya",search:"Medya kitaplığında ara",sourceType:"Kaynak türü",sourceRef:"Kaynak referansı",sourceModel:"Kaynakta görünen model",notes:"Doğrulama notu",attach:"Doğrula ve bağla",detach:"Ayır",none:"Bu ürün için henüz doğrulanmış medya yok.",empty:"Eşleşen boşta medya yok.",upload:"Önce gerçek görseli medya kitaplığına yükleyin, ardından kaynağı ve modeli kaydedip bağlayın.",published:"Yayında",draft:"Taslak"},
 ar:{title:"وسائط المنتج الموثقة",desc:"اربط فقط الصور التي تمت مطابقة موديلها مع مصدر حقيقي. الوسائط بلا دليل لا تجتاز بوابة الإطلاق.",back:"العودة إلى المنتج",verified:"صور موثقة",attached:"الوسائط المرتبطة",library:"وسائط غير مرتبطة",search:"بحث في مكتبة الوسائط",sourceType:"نوع المصدر",sourceRef:"مرجع المصدر",sourceModel:"الموديل في المصدر",notes:"ملاحظة التحقق",attach:"تحقق واربط",detach:"فصل",none:"لا توجد وسائط موثقة لهذا المنتج بعد.",empty:"لا توجد وسائط غير مرتبطة مطابقة.",upload:"ارفع الصورة الحقيقية أولاً ثم سجل المصدر والموديل قبل ربطها.",published:"منشور",draft:"مسودة"}
};
function name(p:Product,l:AdminLocale){return l==="fa"?p.nameFa:l==="tr"?p.nameTr:l==="ar"?p.nameAr:p.nameEn}
function alt(m:Media,l:AdminLocale){return l==="fa"?m.altFa:l==="tr"?m.altTr:l==="ar"?m.altAr:m.altEn}
export default async function ProductMediaPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{q?:string}>}){
 const [{id},{q=""},l]=await Promise.all([params,searchParams,currentAdminLocale()]);
 const data=await adminRpc<Workspace>("admin_product_media_workspace",{p_product_id:id,p_search:q});const t=copy[l],model=data.product.modelNumber||data.product.sku;
 return <div className="mx-auto max-w-7xl space-y-6">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><Link href={`/admin/products/${id}`} className="inline-flex items-center gap-2 text-xs font-black text-[#002b5b]"><ArrowLeft className="h-4 w-4"/>{t.back}</Link><h1 className="mt-4 text-3xl font-black text-[#001736]">{t.title}</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-[#747780]">{t.desc}</p><p className="mt-2 text-xs font-bold" dir="ltr">{data.product.sku} · {data.product.modelNumber||"—"}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1.5 text-xs font-black ${data.product.isPublished?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-700"}`}>{data.product.isPublished?t.published:t.draft}</span><span className="inline-flex items-center gap-2 rounded-full bg-sky-100 px-3 py-1.5 text-xs font-black text-sky-800"><BadgeCheck className="h-4 w-4"/>{t.verified}: {data.verifiedCount}</span></div></header>
  <section className="rounded-3xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black text-[#001736]">{t.attached}</h2><p className="mt-1 text-xs text-[#747780]">{name(data.product,l)}</p></div><MediaUploader/></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{data.attached.map(m=><article key={m.id} className="overflow-hidden rounded-2xl border"><div className="relative aspect-square bg-[#f7fafd]"><Image src={m.url} alt={alt(m,l)||name(data.product,l)} fill className="object-contain p-3" sizes="(max-width:768px) 50vw, 25vw"/></div><div className="space-y-2 p-4"><div className="flex items-center justify-between gap-2"><b className="truncate text-xs">{m.evidence?.sourceType||"UNVERIFIED"}</b>{m.evidence?.verificationStatus==="VERIFIED"?<ShieldCheck className="h-4 w-4 text-emerald-600"/>:null}</div><p className="break-all text-[10px] text-[#747780]">{m.evidence?.sourceReference||"Evidence missing"}</p><p className="text-[10px] font-bold" dir="ltr">{m.evidence?.sourceModel||"—"}</p><form action={detachVerifiedProductMedia.bind(null,id,m.id)}><button className="inline-flex min-h-9 w-full items-center justify-center gap-2 rounded-xl border text-xs font-black text-red-700"><Trash2 className="h-4 w-4"/>{t.detach}</button></form></div></article>)}{!data.attached.length?<p className="col-span-full rounded-2xl border border-dashed p-10 text-center text-sm text-[#747780]">{t.none}</p>:null}</div></section>
  <section className="rounded-3xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-black text-[#001736]">{t.library}</h2><p className="mt-1 text-xs text-[#747780]">{t.upload}</p></div><form className="flex gap-2"><label className="relative"><Search className="absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#9aa0aa]"/><input name="q" defaultValue={q} placeholder={t.search} className="h-10 rounded-xl border ps-9 pe-3 text-xs"/></label><button className="rounded-xl bg-[#001736] px-4 text-xs font-black text-white">{t.search}</button></form></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{data.available.map(m=><article key={m.id} className="grid gap-4 rounded-2xl border p-4 sm:grid-cols-[150px_1fr]"><div className="relative aspect-square overflow-hidden rounded-xl bg-[#f7fafd]"><Image src={m.url} alt={alt(m,l)||"media"} fill className="object-contain p-2" sizes="150px"/></div><form action={attachVerifiedProductMedia.bind(null,id)} className="grid gap-3"><input type="hidden" name="mediaId" value={m.id}/><label className="text-[11px] font-bold">{t.sourceType}<select name="sourceType" defaultValue="CATALOG" className="mt-1 h-10 w-full rounded-xl border px-2"><option>CATALOG</option><option>BRAND_SITE</option><option>SUPPLIER_FILE</option><option>ADMIN_UPLOAD</option><option>OTHER</option></select></label><label className="text-[11px] font-bold">{t.sourceRef}<input name="sourceReference" required className="mt-1 h-10 w-full rounded-xl border px-3" placeholder="Catalogue page / URL / supplier document"/></label><label className="text-[11px] font-bold">{t.sourceModel}<input name="sourceModel" required defaultValue={model} className="mt-1 h-10 w-full rounded-xl border px-3" dir="ltr"/></label><label className="text-[11px] font-bold">{t.notes}<input name="notes" className="mt-1 h-10 w-full rounded-xl border px-3"/></label><button className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-[#002b5b] text-xs font-black text-white"><ImagePlus className="h-4 w-4"/>{t.attach}</button></form></article>)}{!data.available.length?<p className="col-span-full rounded-2xl border border-dashed p-10 text-center text-sm text-[#747780]">{t.empty}</p>:null}</div></section>
 </div>;
}
