import Link from "next/link";
import { ArrowLeft, KeyRound, MailCheck, RotateCcwKey, ShieldCheck } from "lucide-react";
import { forgotPasswordAction } from "../actions";

const BG="https://lh3.googleusercontent.com/aida/AEtjO1XsKXqpr5yRiWfVB-d1KkBSurcii3IusZ5vZkc9D6KJcRR2SW3LlkVb-kaVx_yZRT4vSqEEXeoUFzdyWN1mHWFmDkkjV0keIXfXF5byYE9NeKt9mmkYsTvRI_72rpslADLitqr6hLFZbB00yBCLxSbIuFZH0nRc_vYfHwwI8A90SQDK_1CQZEkrKVxZxSq7dDRJdxfuXX2drvm5TWsE7CK0UMYZrEKP-RBsNaS2WC7uZ_nDW4mmGG21XSWG";
const copy={
 fa:{title:"بازیابی رمز عبور",body:"ایمیل یا شماره موبایل حساب خود را وارد کنید. اگر بازیابی خودکار برای حساب فعال باشد، راهنمای امن برای شما ارسال می‌شود.",field:"ایمیل یا شماره موبایل",submit:"ارسال درخواست بازیابی",back:"بازگشت به ورود",support:"مرکز پشتیبانی",secure:"اتصال امن و پروتکل SSL",sent:"اگر حسابی با این اطلاعات وجود داشته باشد، راهنمای بازیابی برای آن ارسال شده است.",manual:"بازیابی خودکار ایمیلی هنوز روی سرور فعال نشده است. برای حفظ امنیت، Reset Token خام نمایش داده نمی‌شود؛ لطفاً از مرکز پشتیبانی درخواست بازیابی حساب ثبت کنید."},
 tr:{title:"Şifre kurtarma",body:"Hesabınıza ait e-posta veya telefon numarasını girin. Otomatik kurtarma etkinse güvenli yönergeler gönderilir.",field:"E-posta veya telefon",submit:"Kurtarma isteği gönder",back:"Girişe dön",support:"Destek merkezi",secure:"Güvenli SSL bağlantısı",sent:"Bu bilgilerle eşleşen bir hesap varsa kurtarma yönergeleri gönderildi.",manual:"Otomatik e-posta kurtarma henüz sunucuda etkin değil. Güvenlik nedeniyle ham sıfırlama belirteci gösterilmez; lütfen destek merkezinden hesap kurtarma talebi oluşturun."},
 en:{title:"Password recovery",body:"Enter the email or mobile number for your account. If automated recovery is enabled, secure instructions will be sent.",field:"Email or phone",submit:"Send recovery request",back:"Back to sign in",support:"Support center",secure:"Secure SSL connection",sent:"If an account matches this information, recovery instructions have been sent.",manual:"Automated email recovery is not enabled on the server yet. For security, the raw reset token is never displayed; please submit an account recovery request through the support center."},
 ar:{title:"استعادة كلمة المرور",body:"أدخل البريد الإلكتروني أو رقم الهاتف المرتبط بحسابك. إذا كانت الاستعادة التلقائية مفعّلة فسيتم إرسال إرشادات آمنة.",field:"البريد الإلكتروني أو الهاتف",submit:"إرسال طلب الاستعادة",back:"العودة إلى تسجيل الدخول",support:"مركز الدعم",secure:"اتصال SSL آمن",sent:"إذا وُجد حساب يطابق هذه البيانات، فقد تم إرسال تعليمات الاستعادة.",manual:"الاستعادة التلقائية عبر البريد الإلكتروني غير مفعّلة على الخادم بعد. ولأسباب أمنية لا يتم عرض رمز إعادة التعيين الخام؛ يرجى إرسال طلب استعادة الحساب عبر مركز الدعم."}
} as const;

export default async function ForgotPasswordPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{status?:string}>}){
 const {locale}=await params; const q=await searchParams; const t=copy[locale as keyof typeof copy]??copy.fa; const action=forgotPasswordAction.bind(null,locale); const rtl=locale==="fa"||locale==="ar";
 return <main className="relative min-h-[calc(100vh-5rem)] overflow-hidden bg-[#f7fafd] py-10 sm:py-16" style={{backgroundImage:`linear-gradient(rgba(247,250,253,.91),rgba(247,250,253,.97)),url(${BG})`,backgroundSize:"520px"}}><div className="mx-auto max-w-xl px-4">
  <div className="mb-8 flex items-center justify-between"><Link href={`/${locale}/account/login`} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/75 text-[#001736] shadow-sm"><ArrowLeft className={`h-5 w-5 ${rtl?"rotate-180":""}`}/></Link><div className="text-3xl font-black text-[#001736]">Hyper Doctor</div><span className="h-11 w-11"/></div>
  <section className="rounded-[2rem] border border-white/80 bg-white/88 p-7 shadow-[0_28px_80px_rgba(0,23,54,.11)] backdrop-blur-xl sm:p-10"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-[#d6e3ff] bg-[#edf4ff] text-[#001736]">{q.status?<MailCheck className="h-9 w-9"/>:<RotateCcwKey className="h-9 w-9"/>}</div><h1 className="mt-7 text-center text-3xl font-black text-[#001736]">{t.title}</h1><p className="mx-auto mt-4 max-w-md text-center text-sm leading-8 text-[#5f6570]">{t.body}</p>
   {q.status==="sent"?<div className="mt-7 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm leading-7 text-emerald-800">{t.sent}</div>:q.status==="support"?<div className="mt-7 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-7 text-amber-800">{t.manual}</div>:<form action={action} className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold text-[#5f6570]">{t.field}</span><div className="flex h-14 items-center gap-3 rounded-xl border border-[#c4c6d0] bg-white px-4 focus-within:border-[#001736]"><KeyRound className="h-5 w-5 shrink-0 text-[#747780]"/><input name="identifier" required dir="ltr" className="h-full w-full bg-transparent text-sm outline-none"/></div></label><button className="flex min-h-14 w-full items-center justify-center gap-2 rounded-xl bg-[#001736] px-5 text-sm font-black text-white shadow-[0_14px_28px_rgba(0,23,54,.18)]"><span>{t.submit}</span><span aria-hidden>{rtl?"▷":"◁"}</span></button></form>}
   <div className="mt-7 grid gap-3 border-t border-[#e0e3e6] pt-6 sm:grid-cols-2"><Link href={`/${locale}/account/login`} className="text-center text-xs font-black text-[#001736]">{t.back}</Link><Link href={`/${locale}/support`} className="text-center text-xs font-black text-[#5f6570]">{t.support}</Link></div><div className="mt-6 flex items-center justify-center gap-2 text-[11px] text-[#747780]"><ShieldCheck className="h-4 w-4"/>{t.secure}</div>
  </section>
 </div></main>;
}
